### ISSUE TITLE
Pod通过ovn.kubernetes.io/logical_switch配置子网，但是Pod没有在被创建到指定的子网中

### ISSUE THREAD

**Issue by kunandrui** [kubeovn/kube-ovn#1049]
我的目标是将Pod绑定到子网 Subnet-1，结果是Pod的ovn.kubernetes.io/logical_switch的属性没有生效，Pod被分配到了默认子网ovn-default。

配置如下：
# Vpc配置
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc-1
spec:
  namespaces:
    - ns1
  
# Subnet配置
# subnet-1
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: subnet-1
spec:
  vpc: vpc-1
  namespaces:
    - ns1
  cidrBlock: 10.0.1.0/24

# subnet-2
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: subnet-2
spec:
  vpc: vpc-1
  namespaces:
    - ns1
  cidrBlock: 10.0.2.0/24

# Pod配置
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-1
  namespace: ns1
  name: subnet-1-pod-1
spec:
  containers:
    - name: nginx
      image: nginx

**Comment by oilbeater** [comment]
@kunandrui 我这边没有能复现你的问题，能否看下用的是哪个版本的 kube-ovn 以及 kube-ovn-controller 日志内有没有什么错误信息。

此外 subnet-2 的 yaml 里 name 和 subnet-1 重复，需要先将原有的 subnet 删除在创建新的 subnet，可能会对你的问题有影响

**Comment by kunandrui** [comment]
抱歉！我重新试了，创建普通pod是没问题的。
我用的是1.8版本的kube-ovn。

新的问题是，我安装了kubevirt，创建VirtualMachine类型Pod，ovn.kubernetes.io/logical_switch属性没有生效，是因为kubevirt不支持ovn.kubernetes.io/logical_switch这个属性吗？

yaml配置如下：
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-2
  name: test-vm-1
  namespace: ns1

**Comment by oilbeater** [comment]
@kunandrui kube-ovn 的机制是最终通过读取 pod annotation 来配置 pod 网络，所以这个 annotation 应该加在 template 里，不应该加载 VirtualMachine 的 annotation 里

**Comment by kunandrui** [comment]
谢谢你的解答！
