### ISSUE TITLE
vpc场景下的bug

### ISSUE THREAD

**Issue by hugo345816** [kubeovn/kube-ovn#1087]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. 在创建vpc网络时，如果subnet与vpc同名，就会导致相应的vpc-nat-gw pod无法创建。只要修改subnet或vpc中其中一个名字就行了。
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
1.8.1
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
"CentOS Stream 8"
  ```

**Comment by oilbeater** [comment]
目前看是 ovn 本身的限制，两个datapath 不能使用相同的名字
