### ISSUE TITLE
multus bug from v1.8.1-x86

### ISSUE THREAD

**Issue by hugo345816** [kubeovn/kube-ovn#1106]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. 在1.8.1-x86版本中，attachnet.default.ovn.kubernetes.io/logical_switch这个注解不会生效，总是分配到默认的subnet中。
2. 在1.7.1-x86版本中则没有这个问题。
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by oilbeater** [comment]
resolved in https://github.com/kubeovn/kube-ovn/pull/1078/files
