### ISSUE TITLE
question abouot the annotation "ovn.kubernetes.io/port_security"

### ISSUE THREAD

**Issue by A-Zee029** [kubeovn/kube-ovn#1143]
I want to know if I have to set the annotation "ovn.kubernetes.io/port_security" to "true" on the pod **when it is created**?
I tried to add the same annotation on the **existing pod**, but it doesn't change the port_security value in the **Logical_Switch_Port** table.
I am not sure if this is a bug, can anyone conclude that?

**Comment by hongzhen-ma** [comment]
For more detail information about security-group, the document link is

[security-group](https://github.com/fanriming/kube-ovn/wiki/%E5%AE%89%E5%85%A8%E7%BB%84)

**Comment by A-Zee029** [comment]
现在是发现在已经存在的pod上加ovn.kubernetes.io/port_security: 'true'注解后，controller并没有把pod对应的ip4和ip6的地址填充到Logical_Switch_Port表的port_security里面。
所以想知道这个当时是设计成就只能在创建pod的时候开启port_security吗

**Comment by oilbeater** [comment]
> 现在是发现在已经存在的pod上加ovn.kubernetes.io/port_security: 'true'注解后，controller并没有把pod对应的ip4和ip6的地址填充到Logical_Switch_Port表的port_security里面。 所以想知道这个当时是设计成就只能在创建pod的时候开启port_security吗

目前是这样，感兴趣的话可以提个动态设置 port_security 的 pr

**Comment by A-Zee029** [comment]
> 目前是这样，感兴趣的话可以提个动态设置 port_security 的 pr

ok
