### ISSUE TITLE
gcCustomLogicalRouter() deletes lrs created by Neutron

### ISSUE THREAD

**Issue by ruijzhan** [kubeovn/kube-ovn#1145]
# Expected Behavior
gcCustomLogicalRouter does not delete lrs created by Neutron
# Actual Behavior
In environment where kube-ovn and Neutron shares one ovn, when starting kube-ovn-controller, kube-ovn runs gc, gc calls gcCustomLogicalRouter. It lists vpcs defined in cluster and all lrs from ovn. Then it deletes lrs which does not exist in vpc CRs, those including ones created by Neutron.

Although gcCustomLogicalRouter() has needVendorFilter bool as a parameter, seems it does not make use of it.
```go
// ListLogicalRouter list logical router names
func (c Client) ListLogicalRouter(needVendorFilter bool, args ...string) ([]string, error) {
	return c.ListLogicalEntity("logical_router", args...)
}
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by lut777** [comment]
looks like a careless omission in the use of this parameter.
Now fixed.
