### ISSUE TITLE
Use go to reimplement kube-ovn-controller-healthcheck.sh

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1153]
[kube-ovn-controller-healthcheck.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/kube-ovn-controller-healthcheck.sh) now use shell to check ovn-nb, apiserver and self httpserver alive. It can be reimplemented in kube-ovn-controller binary, which can be more clear and remove the dependency of kubectl binary

**Comment by A-Zee029** [comment]
Hello, I tried to reimplement the healtheck.sh but i can't unstand why it need to exec the command `kubectl version` in the [kube-ovn-controller-healthcheck.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/kube-ovn-controller-healthcheck.sh), could you explain the necessary of this command?

**Comment by zhangzujian** [comment]
@A-Zee029 Can you create a PR and add this issue to the linked issue so that we can know you are working on it?

Tips: If the PR is still in progress and not ready for review, you can convert it into a draft one.
