### ISSUE TITLE
pods from subnetA with mask /n can't access pods from subnetB with mask /m, if n>m

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#1216]
# Steps to Reproduce the Problem
1. default vpc，pod1 with subnetA 192.168.100.0/24, subnetA is centralized and gateway ovn0 IP is 100.64.0.10， pod2 with subnetB 10.16.0./16
2. lr-route-list ovn-cluster  
```
IPv4 Routes
               100.17.0.2                100.64.0.6 src-ip
               100.17.0.3                100.64.0.6 src-ip
         192.168.100.0/24               100.64.0.10 src-ip
             10.16.0.0/16               100.64.0.10 src-ip
             10.18.0.0/16               100.64.0.10 src-ip ecmp
             10.18.0.0/16               100.64.0.14 src-ip ecmp
             10.18.0.0/16               100.64.0.15 src-ip ecmp
```
3. route rule on subnetA gateway node(100.64.0.10)
```
[root@node-1 ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
...
10.16.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
10.18.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
192.168.100.0   100.64.0.1      255.255.255.0   UG    0      0        0 ovn0
```
4. pod1 192.168.100.5  ping   pod2 10.16.0.8
```
192.168.100.5 ---> 192.168.100.1 ---> 100.64.0.10 ---> 100.64.0.1 ---> 100.64.0.10 ---> 100.64.0.1 ...
```

# Expected Behavior
with one same vpc,  pods from one subnet are able to access pods from other subnets

# Actual Behavior
```
()[root@kata-ovn-busybox-net192 /]# ping 10.16.0.8
PING 10.16.0.8 (10.16.0.8) 56(84) bytes of data.
From 100.64.0.10 icmp_seq=1 Time to live exceeded
From 100.64.0.10 icmp_seq=2 Time to live exceeded
```

# Additional Info

tcpdump -i ovn0(100.64.0.10) -nne icmp
```
21:40:24.723058 00:00:00:43:4c:3e > 00:00:00:ec:a6:29, ethertype IPv4 (0x0800), length 98: 192.168.100.5 > 10.16.0.8: ICMP echo request, id 58, seq 2, length 64
21:40:24.723060 00:00:00:ec:a6:29 > 00:00:00:43:4c:3e, ethertype IPv4 (0x0800), length 98: 192.168.100.5 > 10.16.0.8: ICMP echo request, id 58, seq 2, length 64
21:40:24.723062 00:00:00:43:4c:3e > 00:00:00:ec:a6:29, ethertype IPv4 (0x0800), length 98: 192.168.100.5 > 10.16.0.8: ICMP echo request, id 58, seq 2, length 64
21:40:24.723065 00:00:00:ec:a6:29 > 00:00:00:43:4c:3e, ethertype IPv4 (0x0800), length 98: 192.168.100.5 > 10.16.0.8: ICMP echo request, id 58, seq 2, length 64
```
00:00:00:43:4c:3e is mac of 100.64.0.1
00:00:00:ec:a6:29 is mac of 100.64.0.10

I think the reason is route rules on ovn-cluster
```192.168.100.0/24               100.64.0.10 src-ip``` has high priority than ```10.16.0.0/16               dst-ip```

ovn-sbctl dump-flows  ovn-cluster
```
 table=10(lr_in_ip_routing   ), **priority=48**   , match=(ip4.src == 192.168.100.0/24), action=(ip.ttl--; reg8[0..15] = 0; reg0 = 100.64.0.10; reg1 = 100.64.0.1; eth.src = 00:00:00:43:4c:3e; outport = "ovn-cluster-join"; flags.loopback = 1; next;)
  table=10(lr_in_ip_routing   ), **priority=33**   , match=(ip4.dst == 10.16.0.0/16), action=(ip.ttl--; reg8[0..15] = 0; reg0 = ip4.dst; reg1 = 10.16.0.1; eth.src = 00:00:00:c1:27:99; outport = "ovn-cluster-ovn-default"; flags.loopback = 1; next;)
  table=10(lr_in_ip_routing   ), priority=33   , match=(ip4.dst == 10.18.0.0/16), action=(ip.ttl--; reg8[0..15] = 0; reg0 = ip4.dst; reg1 = 10.18.0.1; eth.src = 00:00:00:83:53:ad; outport = "ovn-cluster-net9"; flags.loopback = 1; next;)
  table=10(lr_in_ip_routing   ), priority=33   , match=(ip4.dst == 100.17.0.0/16), action=(ip.ttl--; reg8[0..15] = 0; reg0 = ip4.dst; reg1 = 100.17.0.1; eth.src = 00:00:00:8b:d1:d8; outport = "ovn-cluster-net-distributed"; flags.loopback = 1; next;)
  table=10(lr_in_ip_routing   ), priority=33   , match=(ip4.dst == 100.64.0.0/16), action=(ip.ttl--; reg8[0..15] = 0; reg0 = ip4.dst; reg1 = 100.64.0.1; eth.src = 00:00:00:43:4c:3e; outport = "ovn-cluster-join"; flags.loopback = 1; next;)
  table=10(lr_in_ip_routing   ), priority=32   , match=(ip4.src == 10.16.0.0/16), act
```

**Comment by chestack** [comment]
同样的问题，如果subnet是 distributed gateway，route ```100.17.0.2                100.64.0.6 src-ip``` priority是32*2=64 > 10.16.0.0/16 dst 的 priority 33，导致 distributed gateway subnet的Pod 无法访问其他子网Pod

**Comment by zhangzujian** [comment]
The issue has been fixed by this patch #447 .

What version are you using? Or are you using the official OVN?

**Comment by chestack** [comment]
@zhangzujian  thanks for your info.

I use official ovn version  21.06.0 [(https://github.com/ovn-org/ovn/blob/branch-21.06/northd/ovn-northd.c)] without commit [https://github.com/kubeovn/ovn/commit/b75eb1f231da55d1b8a29f386dc56234e2eb9d35] from kubeovn/ovn

**Comment by chestack** [comment]
@zhangzujian  clould you help answer what in https://github.com/kubeovn/kube-ovn/issues/1216#issuecomment-1003294735

**Comment by zhangzujian** [comment]
> I am curious that [kubeovn/ovn@b75eb1f](https://github.com/kubeovn/ovn/commit/b75eb1f231da55d1b8a29f386dc56234e2eb9d35) looks like a private patch only in kubeovn/ovn but not ovn-org/ovn. why we keep this different priority logic using in kube-ovn

We need the patch to implement distrbuted/centralized gateway since we are using LR routes. We will use logical router policy and address set instead later.

**Comment by oilbeater** [comment]
@chestack It's a historical reason. OVN at that time didn't support policy route, and we need a way to route packet by 32bit src-ip with lowest priority so that any packet that not designated to container network will be redirect to distributed/centralized gateway . The origin OVN routes will set priority automatically by mask length which will give the highest priority, that's not what we expected. We customized the src-ip route priority to meet our requirement but it's not what upstream ovn  expected behavior, so we keep it in kubeovn/ovn.

As @zhangzujian said we will migrate to policy route later and this patch will no longer needed in the future

**Comment by chestack** [comment]
@zhangzujian @oilbeater thanks for your response. 

We use ovn for both containers and neutron in our env, so we can't cherry-pick this patch. Maybe it's not a common case just for your information.
