### ISSUE TITLE
Support CNI VESION command

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1228]
CNI has new spec for `VERSION` command and we should support it

https://github.com/containernetworking/cni/blob/master/SPEC.md#version-probe-plugin-version-support

**Comment by sober-wang** [comment]
can you give us some example cni's and how to run the CNI VERSION command ?

**Comment by sober-wang** [comment]
I think add a version command in ko kubectl plugin. Is good? 
```shell
kubectl ko version 
# cat /etc/cni/net.d/01-kube-ovn.conflist
```

I maked a daemon.
```shell
[root@opstest ~]# kubectl ko version
kubectl ko {subcommand} [option...]
Available Subcommands:
  [nb|sb] [status|kick|backup]     ovn-db operations show cluster status, kick stale server or backup database
  nbctl [ovn-nbctl options ...]    invoke ovn-nbctl
  sbctl [ovn-sbctl options ...]    invoke ovn-sbctl
  vsctl {nodeName} [ovs-vsctl options ...]   invoke ovs-vsctl on the specified node
  ofctl {nodeName} [ovs-ofctl options ...]   invoke ovs-ofctl on the specified node
  dpctl {nodeName} [ovs-dpctl options ...]   invoke ovs-dpctl on the specified node
  appctl {nodeName} [ovs-appctl options ...]   invoke ovs-appctl on the specified node
  tcpdump {namespace/podname} [tcpdump options ...]     capture pod traffic
  trace {namespace/podname} {target ip address} {icmp|tcp|udp} [target tcp or udp port]    trace ovn microflow of specific packet
  diagnose {all|node} [nodename]    diagnose connectivity of all nodes or a specific node
[root@opstest ~]# vim /usr/local/bin/kubectl-ko 
[root@opstest ~]# kubectl ko version
{
    "name":"kube-ovn",
    "cniVersion":"0.3.1",
    "plugins":[
        {
            "type":"kube-ovn",
            "server_socket":"/run/openvswitch/kube-ovn-daemon.sock"
        },
        {
            "type":"portmap",
            "capabilities":{
                "portMappings":true
            }
        }
    ]
}
[root@opstest ~]# 
```

**Comment by zhangzujian** [comment]
> can you give us some example cni's and how to run the CNI VERSION command ?

Here is an example of how the `ADD` command works:

https://github.com/kubeovn/kube-ovn/blob/master/cmd/cni/cni.go#L32
https://github.com/kubeovn/kube-ovn/blob/master/pkg/daemon/handler.go#L57

As to the `VERSION` command, modification only to `cmd/cni/cni.go` is needed.

**Comment by sober-wang** [comment]
> 

oh right. Your mean's  add the version number into kube-ovn source code . But how to visit the version interface with command? 
Maybe, we can create a version api at webhook , next run `kubectl ko version`  visit the version api  and print version number to stdout.

**Comment by zhangzujian** [comment]
@sober-wang  Here is an introduction about `VERSION` result: https://github.com/containernetworking/cni/blob/master/SPEC.md#version-1

Maybe we need only the CNI version and supported CNI versions but I'm not sure.

As to the Kube-OVN version, it's defined in the `VERSION` file and injected into the `versions` package in compile time.

**Comment by sober-wang** [comment]
I understand your mean's.
But I don't know of the relation  `/opt/cni/bin/kube-ovn` and `kube-ovn-daemon` and `kubelet` 

Maybe add the `VESION` in `/opt/cni/bin/kube-ovn` subcommand. 
**run**
```shell
/opt/cni/bin/kube-ovn version
```

**output**
```json
{
    "cniVersion": "1.0.0",
    "supportedVersions": [ "0.1.0", "0.2.0", "0.3.0", "0.3.1", "0.4.0", "1.0.0" ]
}
```

And , Are you know CNI VERSION command from  another CNI plugin ?

**Comment by xujunjie-cover** [comment]
maybe we can't update cni version to v1.0.1 now；
multus is needed by kube-ovn controller, but cni v0.8.1 is used by multus still now;
if only support version command based on v0.8.1?
