### ISSUE TITLE
Upgrade CNI to v1.0.1

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1229]
CNI has a new spec, we should check if we can upgrade to it and if it is compatible with old version kubernetes

**Comment by sober-wang** [comment]
How to check CNI version from a k8s cluster?

And How to modify the CNI version  at my k8s cluster?

**Comment by 826167518** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
