### ISSUE TITLE
failed to get cm ExternalGatewayConfig which is not under "kube-system" ns

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#1236]
# Steps to Reproduce the Problem

kube-ovn-controller pods run under some ns but not "kube-system".  It's an obvious issue that could be improved

- [c.configMapsLister.ConfigMaps(c.config.PodNamespace).Get(util.ExternalGatewayConfig)](https://github.com/kubeovn/kube-ovn/blob/839c27750ace889fbc03ca39361e95fbf824fb53/pkg/controller/external-gw.go#L25)
- [c.config.KubeClient.CoreV1().ConfigMaps("kube-system").Get(context.Background(), util.ExternalGatewayConfig)](https://github.com/kubeovn/kube-ovn/blob/e8ddfa5bcd9069be7b2416276e0b8366745734bd/pkg/daemon/gateway.go#L623)
- [ConfigMaps("kube-system").Get(context.Background(), util.ExternalGatewayConfig)](https://github.com/kubeovn/kube-ovn/blob/f6b0d369cad5828e2f5e8740c061f429683764c7/pkg/controller/pod.go#L735)

**Comment by oilbeater** [comment]
@chestack can you help to improve it?
