### ISSUE TITLE
port ln-ovn-external could be configurable

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#1237]
### Feature request

properties of port ln-ovn-external could be configurable according to the physical network, such as:
- vlanid,  for the case that underlay network has vlanid configured
- network_name of port options, for the case that connects ln-ovn-external to existing ovn bridge instead of creating br-external

**Comment by oilbeater** [comment]
@chestack thanks for your advice, do you have any interest to contribute this feature?
