### ISSUE TITLE
Support DHCP

### ISSUE THREAD

**Issue by fanriming** [kubeovn/kube-ovn#1248]
#### Configure IPv6 address for the Kubevirt virtual machine
Currently, Kubevirt provides a built-in DHCP server for IPv4, but does not provide DHCP capability for IPv6. In IPv6 or dual-stack scenarios, only cloud-init can inject static configuration.
In addition, the DCHP server provided by Kubevirt is relatively limited. It only provides IP address and gateway configuration, but does not provide configurations like DNS-server/FTP-server.
Hopefully kubeovn can provide a centralized and complete DHCP server management.

**Comment by oilbeater** [comment]
resolved in #1319
