### ISSUE TITLE
the pod can't get ip from kube-ovn cni when pod is in creating (新建的pod无法从cni获取IP，创建失败)

### ISSUE THREAD

**Issue by luzxiang** [kubeovn/kube-ovn#1272]
kube-ovn环境：

- 3个master节点

- 2个node节点

- kube-ovn启用了高可用

发布工作负载后，pod正常运行，停止这个pod所在节点的kubelet一段时间后，再次创建pod一直失败，无法分配到ip，一直处于ContainerCreating状态，describe这个pod的信息如下
Events:
Type          Reason          From            Message
warning CreateOVNportFailed 3m22S ovn-controller 2022-01 -19T01 :18:11Z 100001 Ifatal_ signal IWARNIterminating with signal 15 (Terminated),  signal terminated
warning CreateOVNPortFailed 3m22s ovn-controller ovn-nbct1: unix:/van /run/ ovn/ovnnb_ db. sock: database connection failed (NO such file or directory)

kube-ovn-controller 里的日志也是报这个错。

**Comment by oilbeater** [comment]
Close stale issues.
