### ISSUE TITLE
使用eip的pod无法进行service对应dns的解析

### ISSUE THREAD

**Issue by hackeren** [kubeovn/kube-ovn#1277]
# Expected Behavior
使用eip的pod仍然可以解析service对应的dns
# Actual Behavior
无法解析。原因是改pod发往nodelocaldns的数据包的目的IP为169.254.25.10，该数据包进入虚拟路由器（ovn-cluster-router）后将被转到eip对应的虚拟交换机上，而不是到ovn0对应的交换机上。
# Steps to Reproduce the Problem
1. 给pod配置eip
2. 该pod在initContainer中配置等待其他pod提供service ready的逻辑
3. 该pod处于Init状态，进入initContainer中，无法ping通nodelocaldns的IP

# Additional Info

- Kubernetes version: v1.17.9

  **Output of `kubectl version`:**

  ```
  v1.17.9
  ```

- kube-ovn version:
  
  ```
  v1.9.0
  ```

**Comment by hackeren** [comment]
通过排查，发现Kube-OVN为使用eip的Pod自动添加了基于源IP的路由，该路由将从该Pod发送的报文全部转到网关上，导致无法连通nodelocaldns。通过手动删除该默认路由，添加基于目的地址的路由到ovn0上，可以完成dns解析。
后续是否考虑支持路由优先级或者长度匹配？ @oilbeater

**Comment by hackeren** [comment]
@oilbeater 请问这个自定义路由有版本规划么？大致在哪个版本会上？

**Comment by oilbeater** [comment]
@hackeren 还没有具体排期，可以先手动在 ovn 里加对应路由来临时解决

**Comment by hackeren** [comment]
> @hackeren 还没有具体排期，可以先手动在 ovn 里加对应路由来临时解决

默认的基于源IP的路由的优先级似乎是最高的？我之前单独为nodelocaldns添加基于目的地址的路由好像优先级比较低。

**Comment by oilbeater** [comment]
@hackeren kube-ovn 里的 ovn 修改了源 ip 路由的优先级，把源 ip 路由优先级调整到了最低，应该可以适应这种情况

**Comment by hackeren** [comment]
> @hackeren kube-ovn 里的 ovn 修改了源 ip 路由的优先级，把源 ip 路由优先级调整到了最低，应该可以适应这种情况

具体在哪里修改源IP路由优先级呢？我目前对kube-ovn的代码不是很熟悉，谢谢！

**Comment by hackeren** [comment]
> @hackeren kube-ovn 里的 ovn 修改了源 ip 路由的优先级，把源 ip 路由优先级调整到了最低，应该可以适应这种情况

https://github.com/kubeovn/ovn/commit/e24734913d25c0bffdf1cfd79e14ef43d01e1019.patch 是这个patch的修订么？ 如果移除这个patch后，会有其他的影响么？

**Comment by oilbeater** [comment]
对分布式网关会有影响，为了保证出网的路由流量优先级最低把源 ip 路由的优先级调到了最低，不然默认按照 mask 计算优先级，32位匹配的优先级会最高

**Comment by oilbeater** [comment]
https://github.com/kubeovn/kube-ovn/pull/2733 fix this issue
