### ISSUE TITLE
Submariner integration

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1291]
### Feature request

Kube-OVN already has the ability to connect multi-cluster Pods by Pod IP. However users prefer to use cluster ip or dns name to connect a service in remote clusters. [Submariner](https://github.com/submariner-io/submariner)  has an all in one solution to enables direct networking between Pods and Services, we should check if it works for Kube-OVN

**Comment by lut777** [comment]
The following problems currently exist:
1, when the submariner operator joins a broker, it can not correctly read the CNI svcCIDR and podCIDR.
2, manually specify the correct PodCIDR will lead the gateway to error during the initialization of gateway. A wrong PodCIDR(e.g., use joinCIDR) may pass the gateway check but will inevitable lead to an invalid dataplane.

So before we move on, there are some features need to be fixed.
