### ISSUE TITLE
vpc-nat-gateway，网关和浮动 IP 添加问题

### ISSUE THREAD

**Issue by xujunjie-cover** [kubeovn/kube-ovn#1300]
# Expected Behavior
添加网关后，pod 连到外部网络，外部网络访问浮动 IP 没有延迟。

# Actual Behavior
subnet 创建后有网关，也是 pod 的默认网关，pod 记录了该网关的 mac 地址；创建的 vpc-nat-gw 中 lanIp 写 subnet 的网关后，会新建一个 网关 port；需要等待 pod 中 arp 老化后才会更新默认网关的 mac 为 vpc-nat-gw 创建的网关；导致网关创建后不立即生效。

# Additional Info

- Kubernetes version:

  v1.22.3

- kube-ovn version:
  
v1.9.0

**Comment by hongzhen-ma** [comment]
https://github.com/kubeovn/kube-ovn/wiki/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89-VPC

lanip 是vpc-nat-gw pod使用的ip地址，不是写的所在子网的网关地址

**Comment by xujunjie-cover** [comment]
> https://github.com/kubeovn/kube-ovn/wiki/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89-VPC
> 
> lanip 是 vpc-nat-gw pod使用的ip地址，不是写的所在子网的网关地址

我做了测试，vpc-nat-gw 设置与 subnet 网关不同的地址，且 vpc 加静态路由 解决了我的问题，谢谢。
