### ISSUE TITLE
How to visit peer vpc service?

### ISSUE THREAD

**Issue by xujunjie-cover** [kubeovn/kube-ovn#1355]
已知：
通过 vpc Peerings，可以访问对端 vpc 的 pod；
且 vpc 里的 service 是由 ovn logicalswitch 的 lb 来实现的；
lb vip 地址同步自 k8s service 的 ip；

请问：
是否可以访问对端 vpc 的 service 呢？我尝试加静态路由 svc 的 ip 到对端 vpc 的 ConnectIP，是不通的。有什么实现方式吗？

**Comment by oilbeater** [comment]
ovn 的 lb 是在客户端进行的 nat，需要把对端 svc ip 和 endpoint 加到本端 ls 下的 lb 才可以

**Comment by xujunjie-cover** [comment]
> ovn 的 lb 是在客户端进行的 nat，需要把对端 svc ip 和 endpoint 加到本端 ls 下的 lb 才可以

加到本端 lb 的方式我试过，确实可以，但是考虑如果 需要访问此 vpc 的svc 过多的情况下，需要 每个 vpc 全同步一遍；
如果还是通过静态路由的方式，可以通过加 lb 到 logicalRouter 来解决这个问题吗？

**Comment by xujunjie-cover** [comment]
> ovn 的 lb 是在客户端进行的 nat，需要把对端 svc ip 和 endpoint 加到本端 ls 下的 lb 才可以

加到本端 lb 的方式我试过，确实可以；
如果还是通过静态路由的方式，可以通过加 lb 到 logicalRouter 来解决这个问题吗？lb 加到 logicalRouter 可以实现代理的形式吗？

**Comment by oilbeater** [comment]
> 可以通过加 lb 到 logicalRouter 来解决这个问题吗？

这个会有局限性，ovn lr 上的 lb 不是分布式的需要在 lr 上配置 chassis-gateway 固定到某个节点去执行 lb 相关能力，kube-ovn 目前不会默认配置chassis-gateway。

**Comment by xujunjie-cover** [comment]
@oilbeater 谢谢，我去试一下，我们以后有计划兼容这种 lb 模式吗？
