### ISSUE TITLE
[kube-ovn-monitor] OOM occurred in large-scale clusters

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#1381]
It seems that OVN client used in `kube-ovn-monitor` synchronizes all data from the OVN databases. In large-scale clusters, this behavior results in Pod OOM.

**Comment by hongzhen-ma** [comment]
containers:
  - command:
    - /kube-ovn/start-ovn-monitor.sh
    env:
    - name: ENABLE_SSL
      value: "false"
    - name: NODE_IPS
      value: 192.168.133.214,192.168.133.215,192.168.133.216,
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: registry.alauda.cn:60080/acp/kube-ovn:v1.8.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - cat
        - /var/run/ovn/ovn-nbctl.pid
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 45
    name: kube-ovn-monitor
    readinessProbe:
      exec:
        command:
        - cat
        - /var/run/ovn/ovnnb_db.pid
      failureThreshold: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 45


这个是staging环境上，使用的readiness的检查。还是使用的之前的nbctl的检查，这块最早是参考ovn-central添加的检查。

最近添加db自动恢复的功能，在 #1359 合入后，kube-ovn-monitor 现在打包不再包含daemon，监控中查询db数据是使用rpc接口查询的数据。

可以在staging环境更新镜像后，持续观察下是否还会出现问题。
