### ISSUE TITLE
Kubevirt vm pod support multus-cni 

### ISSUE THREAD

**Issue by hongzhen-ma** [kubeovn/kube-ovn#1385]
# Expected Behavior
after pr #1347 ，expect vm multus cni both keep ip stable

# Actual Behavior

the multus nic maybe can not keep ip statble

# Steps to Reproduce the Problem

1.   
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  v1.9.1
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by xujunjie-cover** [comment]
打扰，关于这个 issue，我想问一下：是在什么操作下 IP 会变呢？
我在使用中，未发现这个情况。

**Comment by hongzhen-ma** [comment]
> 打扰，关于这个 issue，我想问一下：是在什么操作下 IP 会变呢？ 我在使用中，未发现这个情况。谢谢

是社区的一个小伙伴反馈的说是有这个问题存在，说是多网卡情况下，IP没有固定。所以先提了个issue跟踪。
从代码上分析，应该是没有问题。
我们这虚拟机的环境比较难申请，目前还没有在本地验证。
