### ISSUE TITLE
kube-ovn pod snat-and-eip not work

### ISSUE THREAD

**Issue by wlooppy** [kubeovn/kube-ovn#1394]
您好，测试过 社区的 snat-and-eip
发现 pod snat-and-eip 并没有正常工作，下边是配置和问题分析：
**配置：**
cat ovn-external-gw-config.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  type: "centralized"
  external-gw-nodes: "k8s-worker1"
  external-gw-nic: "eth2"
  nic-ip: "1.0.10.254/24"           # The ip and mask of the underlay physical gateway
  nic-mac: "00:00:3e:e7:00:eb"          # The mac of the underlay physical gateway

cat eippod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: pod-gw
  annotations:
    ovn.kubernetes.io/eip: 1.0.10.199        #指定 pod 的 floating ip
spec:
  containers:
   -name: dnat-pod
    image: nginx:alpine

**问题分析：**
原生的配置 有误在 配置 租户路由时，会配置成默认 SNAT ip 而非 物理网络网关，导致 arp 错误
真是的 物理网关应为 1.0.10.1
kubectl ko nbctl lr-route-list ovn-cluster
IPv4 Routes
                10.16.0.16                1.0.10.254 src-ip

router 3ce127a0-d1c9-44cf-a360-062a93618857 (ovn-cluster)
    port ovn-cluster-ovn-default
        mac: "00:00:00:AC:5A:11"
        networks: ["10.16.0.1/16"]
    port ovn-cluster-join
        mac: "00:00:00:7B:8A:70"
        networks: ["100.64.0.1/16"]
    port ovn-cluster-ovn-external
        mac: "00:00:3e:e7:00:eb"
        networks: ["1.0.10.254/24"]

tcpdump -i eth2 -nnnnne
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
13:53:14.896015 00:00:3e:e7:00:eb > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Request who-has 1.0.10.254 tell 1.0.10.254, length 46

手动解决：
将路由指向 真正物理网关后，eip 生效，流量正常
kubectl ko nbctl lr-route-list ovn-cluster
IPv4 Routes
                10.16.0.16                1.0.10.1 src-ip

请问是否为 BUG ？谢谢

**Comment by oilbeater** [comment]
cm 里 nic-ip 的地方应该填物理网关的地址

**Comment by wlooppy** [comment]
您好，
cm nic-ip 填 物理网关地址的话， 会导致 arp 用物理网关的ip 去找 物理网关
tcpdump -i eth2 -nnnnne
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
13:53:14.896015 00:00:3e:e7:00:eb > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Request who-has 1.0.10.1 tell 1.0.10.1, length 46

因为 nic-ip 会配置在  router 的端口上 
router 3ce127a0-d1c9-44cf-a360-062a93618857 (ovn-cluster)
port ovn-cluster-ovn-default
mac: "00:00:00:AC:5A:11"
networks: ["10.16.0.1/16"]
port ovn-cluster-join
mac: "00:00:00:7B:8A:70"
networks: ["100.64.0.1/16"]
port ovn-cluster-ovn-external
mac: "00:00:3e:e7:00:eb"
networks: ["1.0.10.1/24"]

还请帮忙确认，谢谢

**Comment by oilbeater** [comment]
这块看上去确实是有问题，我们找环境验证一下
