### ISSUE TITLE
Investigate network break during kube-ovn upgrade

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1420]

**Comment by hongzhen-ma** [comment]
acp 版本的升级脚本，已经调整顺序，将kube-ovn-pinger的升级放在首位，可以实现在每个节点上提前拉取镜像

升级中断的情况，还需要再继续测试

**Comment by hongzhen-ma** [comment]
实际测试，在ovs-ovn pod删除重建的时候，从集群外访问ovs-ovn pod所在节点上的业务pod，会出现1s的访问中断。

**Comment by oilbeater** [comment]
flow-restore-wait option in ovs-vswitchd.conf.db(5) may help to decrease the upgrade down time

**Comment by oilbeater** [comment]
https://github.com/ovn-org/ovn-kubernetes/pull/2949 upstream ovn has a new patch to resolve upgrade downtime
