### ISSUE TITLE
error syncing 'master2': ovn-nbctl: Error on switch join: duplicate IPv4 address '100.64.0.4' found on logical switch port 'node-master3' , "exit status 1", requeuing

### ISSUE THREAD

**Issue by zhajun1990** [kubeovn/kube-ovn#1449]
I0417 14:14:47.704771       1 controller.go:355] wait node master2 annotation ready
I0417 14:14:48.448543       1 ipam.go:37] allocate 100.64.0.4 00:00:00:5F:E3:B0 for node-master2
I0417 14:14:48.448566       1 ipam.go:37] allocate 100.64.0.3 00:00:00:42:72:FB for node-master3
W0417 14:14:48.453580       1 ovn-nbctl.go:24] ovn-nbctl command error or took too long
W0417 14:14:48.453596       1 ovn-nbctl.go:25] ovn-nbctl --timeout=30 --may-exist lsp-add join node-master3 -- lsp-set-addresses node-master3 00:00:00:42:72:FB 100.64.0.3 in 4ms
E0417 14:14:48.453638       1 ovn-nbctl.go:114] create port node-master3 failed ovn-nbctl: Error on switch join: duplicate IPv4 address '100.64.0.3' found on logical switch port 'node-master2'
, "exit status 1"
E0417 14:14:48.453692       1 node.go:118] error syncing 'master3': ovn-nbctl: Error on switch join: duplicate IPv4 address '100.64.0.3' found on logical switch port 'node-master2'
, "exit status 1", requeuing
W0417 14:14:48.454409       1 ovn-nbctl.go:24] ovn-nbctl command error or took too long
W0417 14:14:48.454420       1 ovn-nbctl.go:25] ovn-nbctl --timeout=30 --may-exist lsp-add join node-master2 -- lsp-set-addresses node-master2 00:00:00:5F:E3:B0 100.64.0.4 in 5ms
E0417 14:14:48.454430       1 ovn-nbctl.go:114] create port node-master2 failed ovn-nbctl: Error on switch join: duplicate IPv4 address '100.64.0.4' found on logical switch port 'node-master3'
, "exit status 1"
E0417 14:14:48.454451       1 node.go:118] error syncing 'master2': ovn-nbctl: Error on switch join: duplicate IPv4 address '100.64.0.4' found on logical switch port 'node-master3'
, "exit status 1", requeuing
I0417 14:14:50.704941       1 controller.go:355] wait node master2 annotation ready
I0417 14:14:53.705177       1 controller.go:355] wait node master2 annotation ready
I0417 14:14:56.705369       1 controller.go:355] wait node master2 annotation ready
I0417 14:14:59.705458       1 controller.go:355] wait node master2 annotation ready
I0417 14:15:02.705758       1 controller.go:355] wait node master3 annotation ready
使用kubesphere集成你们的kube_ovn网络插件，查看kube-ovn-controller在被选举的pod中查看到这个错误信息，请问怎么解决知道吗？

**Comment by oilbeater** [comment]
Close stale issues.
