### ISSUE TITLE
用Jmeter做压测，总有1%的请求，响应时间过长

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#1458]
- ##  测试环境：

  -  k8s版本v1.18.6
  - kubesphere版本v3.0.0
  - kubeovn（1.8.1和1.8.4都测过，结果一样）
  - 千兆网
  - kube-proxy mode配置为ipvs

- ##  集群：

  1master+8worker 

  都是通过虚拟机创建

  另外一台压测机在集群外，不过和集群属于同一个局域网内

- ##  压测软件：

  Jmeter 版本5.4.3，安装在压测机上

- ##  压测方案：

  service的外网访问方式为nodeport

  一个n实例的工作负载provider和一个同为n实例的工作负载consumer

  - 方案1： 压测软件调用http空接口-->nodeport-->provider-->返回100k数据给压测软件
  - 方案2： 压测软件调用http空接口-->nodeport-->consumer-->consumer调用b2接口请求provider（请求的数据包也很小）-->provider返回100k数据给consumer-->consumer返回100k数据给压测软件

- ## 压测结果：

  以方案2为主

  - 当provider和consumer实例数为1时，Jmeter的结果是：（正常）

![image](https://user-images.githubusercontent.com/25982171/164201390-9ad3b873-d829-4bcb-b2ee-f11ac5c3c1fa.png)

  - 当provider和consumer实例数为2时，Jmeter的结果是：（正常）

    
![image](https://user-images.githubusercontent.com/25982171/164201433-b5922f82-dfff-4b1a-834f-b1d927fa8b11.png)

    流量截图：（图中Ubuntu-test-Server节点为压测机所在节点，可以忽略）

   ![image](https://user-images.githubusercontent.com/25982171/164201578-e5d1ae4a-12d8-4431-a987-1a9cfc528589.png)

  - 当provider和consumer实例数为19时，Jmeter的结果是：（正常）

    
![image](https://user-images.githubusercontent.com/25982171/164201765-98fbc867-6750-46e6-b840-0ffcd6776ca8.png)

    流量截图：

    
![image](https://user-images.githubusercontent.com/25982171/164202258-cc7da686-38ea-41d3-95ef-3755f2ae60fd.png)

    流量大概是1846/2

  -  当provider和consumer实例数为21时，Jmeter的结果是：（异常）

   
![image](https://user-images.githubusercontent.com/25982171/164202344-5de718bb-47f9-4a95-8b73-157de8e0951d.png)
 

    有1%的数据返回很慢，表格中目前最大值已经接近100秒，但是还有的数据没有返回，需要长时间等待，有的等待200秒以上还未回来，直接造成吞吐量下降。

    流量截图：

  
![image](https://user-images.githubusercontent.com/25982171/164202418-44ca280a-b015-4069-824d-2a04fe5ba4e9.png)

    流量大概是1925/2 

  - 此时如果实例数再增大，那么流量会更大，但是这时候还是有1%的数据需要等待长时间返回，而且等待时间会更长。

  如果这时候，测试方案1，也是21个及大于21个实例，结果也是一样的。

- ## 对比calico

  之前有做过测试，集群其他环境不变

  使用ipvs

  当provider和consumer实例数为24时

  使用方案2，压测

  结果为：

![image](https://user-images.githubusercontent.com/25982171/164202488-36e5063a-7e7b-47bf-a3c5-a93764ad678c.png)

   

​		流量截图为：

​		
![image](https://user-images.githubusercontent.com/25982171/164202539-7eebaa0d-dc60-4246-af8f-2d98c342ce56.png)

​		流量大约为2219/2
- ### 在满流量的情况下，calico并没有存在1%的数据会响应时间很长。
麻烦大佬们看看，谢谢！

**Comment by oilbeater** [comment]
看起来像 conntrack 相关资源被消耗尽的问题
如果是 overlay 网络可以再kube-ovn-controller 里设置 --enable-lb=false 看看减少相关使用

**Comment by geniusxiong** [comment]
> 看起来像 conntrack 相关资源被消耗尽的问题 如果是 overlay 网络可以再kube-ovn-controller 里设置 --enable-lb=false 看看减少相关使用

试了下，还是会有同样的情况发生

**Comment by oilbeater** [comment]
Close stale issues.
