### ISSUE TITLE
Mark node as NotReady when ovs-ovn failed

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1475]
### Feature request

When ovs-ovn on when node fails, scheduler will still puts pods into this node and leads further problems.

We need to mark the node as NotReady to prevent this, one simple way is that kube-ovn-cni prob check if ovs is not ready and remove the cni conf.

**Comment by sober-wang** [comment]
if the node status is notready, kube-controller-manager can't put pods into notready nodes. 

Can you draw a picture with descript your means?

maybe, we only use shell scripts in k8s prob check.

**Comment by oilbeater** [comment]
If node not ready eviction will be triggered which is not what we want.
