### ISSUE TITLE
 External network to access services in custom VPCs.

### ISSUE THREAD

**Issue by mkcetinkaya** [kubeovn/kube-ovn#1477]
Hello,

We are testing Custom VPC. We have tested isolation between two different VPCs and isolation was tested successfully.

After that, we have tried to expose service in custom VPC. As far as I understand correctly, we need to add static routes on our router for each service ip which is explained in below section. 

https://github.com/kubeovn/kube-ovn/blob/master/docs/vpc.md#vpc-loadbalancer 

ip route add <SVC_IP> via <VPC_LB_IP> and SVC_IP is internal IP of course. Why do we need to add route? Can LB do nat to SVC_IP and port like NodePort solution?

Or is there any possibilty to expose services via nodeport or loadbalancer in custom VPC solution without adding static routes to local router or host. Because this solution may not be working in public cloud providers

Many thanks for your support.

**Comment by zhangzujian** [comment]
You can refer to the VPC LB document [here](https://github.com/kubeovn/kube-ovn/blob/master/docs/vpc.md#vpc-loadbalancer). After adding the annotation to the VPC, a Pod will be created automatically in the kube-system namespace.

**Comment by mkcetinkaya** [comment]
Hello @zhangzujian, yes exactly after annotation vpc-lb pod automatically created. My quesion is that do we need to add following static routes to our local router for each service "ip route add <SVC_IP> via <VPC_LB_IP>" which is written in VPC LB document.

Instead of this, external network use VPC-LB IP in order to reach service and VPC-LB make nat to SVC_IP and port like NodePort solution? 

Thanks

**Comment by zhangzujian** [comment]
> Instead of this, external network use VPC-LB IP in order to reach service and VPC-LB can make nat to SVC_IP and port like NodePort solution?

We have not implemented a NodePort-like solution so it's the only way to access services currently.

Accessing services through node ports is a good idea, but it's not been our focus recently.

**Comment by mkcetinkaya** [comment]
Thanks again for quick reply. Yes this would be very helpful. Actually I thought initially OVS DNAT can easily be used for exposing service from external sources. So user can easily use this feature without adding routes to their underlying infrastructure like any other Kubernetes services.
