### ISSUE TITLE
使用vpc下的非默认子网创建虚拟机不支持keep-vm-ip功能

### ISSUE THREAD

**Issue by lynn901** [kubeovn/kube-ovn#1481]
**集群信息**
Kubernetes：v1.21.5
docker：v20.10.
Kube-ovn：v1.9.1
kubevirt：v0.52

默认子网中包含新建了一个自定义子网net2
\# kubectl get vpc
NAME          STANDBY   SUBNETS                         NAMESPACES
ovn-cluster   true      ["join","ovn-default","net2"]   

**现象描述：**
**使用自定义子网net2创建VM，虚拟机重启后IP地址没有保持固定**
虚拟机情况如下
\# kubectl get vm
NAME        AGE     STATUS    READY
vm-centos   34s     Running   True

\# kubectl get po -owide
NAME                            READY   STATUS    RESTARTS   AGE     IP              NODE     NOMINATED NODE   READINESS GATES
virt-launcher-vm-centos-tj8pm   1/1     Running   0          52s     **10.0.1.2**        k8s-15   <none>           1/1

重启虚拟机后情况如下：
\# kubectl get vm
NAME        AGE     STATUS    READY
vm-centos   2m54s   Running   True

\# kubectl get po -owide
NAME                            READY   STATUS    RESTARTS   AGE     IP              NODE     NOMINATED NODE   READINESS GATES
virt-launcher-vm-centos-wfd7v   1/1     Running   0          37s     **10.0.1.3**        k8s-15   <none>           1/1

kube-ovn-controller日志如下：
I0425 15:19:49.032591       1 pod.go:292] handle add pod default/virt-launcher-vm-centos-tj8pm
I0425 15:19:49.032738       1 ipam.go:50] allocate v4 10.0.1.2 v6  mac 00:00:00:C9:A1:70 for default/vm-centos
I0425 15:19:49.071763       1 pod.go:298] take 39 ms to handle add pod default/virt-launcher-vm-centos-tj8pm
I0425 15:19:49.088315       1 pod.go:756] update pod default/virt-launcher-vm-centos-tj8pm
I0425 15:19:49.168086       1 pod.go:756] update pod default/virt-launcher-vm-centos-tj8pm
I0425 15:19:51.653871       1 node.go:884] pod on node changed, new added port vm-centos.default should add to node port group node.k8s.15
I0425 15:22:12.534885       1 node.go:891] pod on node changed, can not find match pod for port a2ecb563-a64c-4cf3-8a46-0e5a9082a68e in node port group node.k8s.15
I0425 15:22:21.676546       1 pod.go:327] handle delete pod virt-launcher-vm-centos-tj8pm
**I0425 15:22:21.711679       1 pod.go:1331] ns default annotation subnet is ovn-default, which is inconstant with subnet for pod virt-launcher-vm-centos-tj8pm, delete pod**
I0425 15:22:21.758121       1 subnet.go:432] release v4 10.0.1.2 mac 00:00:00:C9:A1:70 for default/vm-centos, add ip to released list
I0425 15:22:21.758152       1 pod.go:334] take 81 ms to handle delete pod virt-launcher-vm-centos-tj8pm
I0425 15:22:22.798760       1 pod.go:292] handle add pod default/virt-launcher-vm-centos-wfd7v
I0425 15:22:22.798906       1 ipam.go:50] allocate v4 10.0.1.3 v6  mac 00:00:00:C3:88:00 for default/vm-centos
I0425 15:22:22.828794       1 pod.go:298] take 30 ms to handle add pod default/virt-launcher-vm-centos-wfd7v
I0425 15:22:22.836143       1 pod.go:756] update pod default/virt-launcher-vm-centos-wfd7v
I0425 15:22:22.885386       1 pod.go:756] update pod default/virt-launcher-vm-centos-wfd7v
I0425 15:22:32.666141       1 node.go:884] pod on node changed, new added port vm-centos.default should add to node port group node.k8s.15

**Comment by xujunjie-cover** [comment]
关于此 issue，具体问题应该是：

当创建 statefulset 或 vm 且使用  `ovn.kubernetes.io/logical_switch` 选择 subnet 的情况下；创建 statefulset 或 vm 选择的 namespace 不在 subnet 的 namespces 列表里时（即创建 subnet 时 namespaces 不包含使用的 ns）；会出现 @lynn901 看到的 ip 保持不住的问题；原因是下面红框代码中：

![image](https://user-images.githubusercontent.com/27765472/166971126-e82d8d91-0963-4992-bb66-b91328f20c25.png)

该检查必须要求 statefulset 或 vm 的 subnet 在 ns 的 `ovn.kubernetes.io/logical_switch` 中（即 subnet 的 namespaces 里要有该 namespace）；该检查适用于创建 statefulset 或 vm 时未指定 `ovn.kubernetes.io/logical_switch` 时，选择默认 subnet 的情况；不适用于指定 subnet 的情况；

是否删除红框内判断解决此 issue?
thanks！
@lynn901 @oilbeater @hongzhen-ma

**Comment by lynn901** [comment]
> 

是否可以在appendCheckPodToDel方法增加一个vm的bool型入参，用来判断是不是要对红框内逻辑进行检查，这样能规避对其他方法调用的影响

**Comment by xujunjie-cover** [comment]
> > 
> 
> 是否可以在appendCheckPodToDel方法增加一个vm的bool型入参，用来判断是不是要对红框内逻辑进行检查，这样能规避对其他方法调用的影响

因为 statefulset  和  vm 都有该问题，建议是解决此判断逻辑

**Comment by hongzhen-ma** [comment]
> 

@xujunjie-cover 直接删除，是不合适的。
这里补充的两种检查情况，第一种就是提到的，sts或者vm，在分配了IP地址之后，修改了所在namespace 使用的子网信息，那么重建之后，需要分配新子网的地址。这种情况是合理的。

对于确实影响了 指定子网的虚拟机使用 的情况，可以参考 @lynn901 的建议，利用 c.config.EnableKeepVmIP 参数加一个判断，如果设置了该参数，就跳过这里的删除逻辑。

**Comment by hongzhen-ma** [comment]
> 关于此 issue，具体问题应该是：
> 
> 当创建 statefulset 或 vm 且使用 `ovn.kubernetes.io/logical_switch` 选择 subnet 的情况下；创建 statefulset 或 vm 选择的 namespace 不在 subnet 的 namespces 列表里时（即创建 subnet 时 namespaces 不包含使用的 ns）；会出现 @lynn901 看到的 ip 保持不住的问题；原因是下面红框代码中：
> 
> ![image](https://user-images.githubusercontent.com/27765472/166971126-e82d8d91-0963-4992-bb66-b91328f20c25.png)
> 
> 该检查必须要求 statefulset 或 vm 的 subnet 在 ns 的 `ovn.kubernetes.io/logical_switch` 中（即 subnet 的 namespaces 里要有该 namespace）；该检查适用于创建 statefulset 或 vm 时未指定 `ovn.kubernetes.io/logical_switch` 时，选择默认 subnet 的情况；不适用于指定 subnet 的情况；
> 
> 是否删除红框内判断解决此 issue? thanks！ @lynn901 @oilbeater @hongzhen-ma

@xujunjie-cover 直接删除，是不合适的。
这里补充的两种检查情况，第一种就是提到的，sts或者vm，在分配了IP地址之后，修改了所在namespace 使用的子网信息，那么重建之后，需要分配新子网的地址。这种情况是合理的。

对于确实影响了 指定子网的虚拟机使用 的情况，可以参考 @lynn901 的建议，利用 c.config.EnableKeepVmIP 参数加一个判断，如果设置了该参数，就跳过这里的删除逻辑。

**Comment by hongzhen-ma** [comment]
@oilbeater 给了一个建议，就是在删除检查中增加一步，检查下pod的OwnerReferences，在spec.template.metadata 中是否有设置 指定子网的annotation，确实是指定子网的情况，就跳过删除。

@xujunjie-cover @lynn901 考虑修改下？

**Comment by xujunjie-cover** [comment]
> 



> @oilbeater 给了一个建议，就是在删除检查中增加一步，检查下pod的OwnerReferences，在spec.template.metadata 中是否有设置 指定子网的annotation，确实是指定子网的情况，就跳过删除。
> 
> @xujunjie-cover @lynn901 考虑修改下？

Good Idea！ sts 和 vm 都需要检查 pod 的 OwnerReferences；  我修改下，请问是提到 release-1.9 吗，因为最新 master 似乎没有 vm 这部分代码。https://github.com/kubeovn/kube-ovn/blob/79ad4fcf44066a8be2809bb6f3991fba84b972a1/pkg/controller/pod.go#L609

**Comment by hongzhen-ma** [comment]
> > 
> 
> > @oilbeater 给了一个建议，就是在删除检查中增加一步，检查下pod的OwnerReferences，在spec.template.metadata 中是否有设置 指定子网的annotation，确实是指定子网的情况，就跳过删除。
> > @xujunjie-cover @lynn901 考虑修改下？
> 
> Good Idea！ sts 和 vm 都需要检查 pod 的 OwnerReferences； 我修改下，请问是提到 release-1.9 吗，因为最新 master 似乎没有 vm 这部分代码。
> 
> https://github.com/kubeovn/kube-ovn/blob/79ad4fcf44066a8be2809bb6f3991fba84b972a1/pkg/controller/pod.go#L609

更新下代码看看呢，master分支应该也有vm固定IP的功能。
确实没有的话，可以提交到release-1.9 分支，后续可以再同步代码。

**Comment by lynn901** [comment]
> > > 
> > 
> > 
> > > @oilbeater 给了一个建议，就是在删除检查中增加一步，检查下pod的OwnerReferences，在spec.template.metadata 中是否有设置 指定子网的annotation，确实是指定子网的情况，就跳过删除。
> > > @xujunjie-cover @lynn901 考虑修改下？
> > 
> > 
> > Good Idea！ sts 和 vm 都需要检查 pod 的 OwnerReferences； 我修改下，请问是提到 release-1.9 吗，因为最新 master 似乎没有 vm 这部分代码。
> > https://github.com/kubeovn/kube-ovn/blob/79ad4fcf44066a8be2809bb6f3991fba84b972a1/pkg/controller/pod.go#L609
> 
> @xujunjie-cover master 应该也有appendCheckPodToDel 这个，应该可以在这里加检查。 确实没有的话，可以提交到release-1.9 分支，后续可以再同步代码。
这样就完美解决了~
master分支中是有appendCheckPodToDel 方法的
