### ISSUE TITLE
kube-ovn-controller容器中ovn-nbctl进程被pkill后不能正常回收

### ISSUE THREAD

**Issue by hwjiangkai** [kubeovn/kube-ovn#1497]
# Expected Behavior
底层ovn故障导致kube-ovn-controller中CheckAlive失败，重启ovn-nbctl，通过pkill -f ovn-nbctl杀掉进程后，进程正常回收。

# Actual Behavior
底层ovn故障导致kube-ovn-controller中CheckAlive失败，重启ovn-nbctl，通过pkill -f ovn-nbctl杀掉进程后，其父进程不能正常回收进程，导致进程残留，现象如下：
```
root@node-10:/kube-ovn# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  1 14:22 ?        00:00:00 ./kube-ovn-controller --ovn-nb-addr=tcp:[ovn-ovsdb-nb.openstack.svc.cluster.local]:6641 --ovn-sb-addr=tcp:[ovn-ovsdb-sb
root        10     1  0 14:22 ?        00:00:00 ovn-nbctl --db=tcp:[ovn-ovsdb-nb.openstack.svc.cluster.local]:6641 --pidfile --detach --overwrite-pidfile
root       240     0  0 14:23 pts/0    00:00:00 bash
root       318   240  0 14:23 pts/0    00:00:00 ps -ef
root@node-10:/kube-ovn# pkill -9 ovn-nbctl
root@node-10:/kube-ovn# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 14:22 ?        00:00:00 ./kube-ovn-controller --ovn-nb-addr=tcp:[ovn-ovsdb-nb.openstack.svc.cluster.local]:6641 --ovn-sb-addr=tcp:[ovn-ovsdb-sb
root        10     1  0 14:22 ?        00:00:00 [ovn-nbctl] <defunct>
root       240     0  0 14:23 pts/0    00:00:00 bash
root       367     1  0 14:24 ?        00:00:00 ovn-nbctl --db=tcp:[ovn-ovsdb-nb.openstack.svc.cluster.local]:6641 --pidfile --detach --overwrite-pidfile
root       387   240  0 14:24 pts/0    00:00:00 ps -ef
root@node-10:/kube-ovn# 
```
即：
root        10     1  0 14:22 ?        00:00:00 [ovn-nbctl] <defunct>

# Steps to Reproduce the Problem

1. exec kube-ovn-controller
2. pkill -f ovn-nbctl
3.

# Additional Info

- Kubernetes version:
v1.20.14
  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  v1.9.0
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

可以考虑修改start-controller.sh，通过dumb_init来回收子进程。
同时需要kube-ovn-controller镜像预装dumb_init

**Comment by zhangzujian** [comment]
Observed the same issue:

![image](https://user-images.githubusercontent.com/13048299/168040256-259bb7fa-5ea9-4cf7-9c1d-d59edf755045.png)
