### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mkcetinkaya** [kubeovn/kube-ovn#1499]
Hi,

We would like to use ACL feature and so we are deploying master branch. Monday we deployed and tested succesfully but today could not deploy master branch.  So we planned to deploy Monday version and tried to create build related Monday commit and tried development guide. However we got many error related to "stack smashing detected". one of them as below.

  > [line 0 : column 0] - loading files from package "cmd": err: signal: aborted (core dumped): stderr: *** stack smashing detected ***: <unknown> terminated

Could you please make a recommendation to overcome this issue?

Thanks and regards.

**Comment by zhangzujian** [comment]
> [line 0 : column 0] - loading files from package "cmd": err: signal: aborted (core dumped): stderr: *** stack smashing detected ***: terminated

Where did you see this error?

**Comment by mkcetinkaya** [comment]
after "make release" command

**Comment by zhangzujian** [comment]
You can try `make build-go` to check whether it's a compile problem. If you're using the original source code, it's okay to skip the `lint` target.

**Comment by oilbeater** [comment]
@mkcetinkaya can you tell us the problem of the master deploy?

**Comment by mkcetinkaya** [comment]
@oilbeater Step 2 gives a timeou.  When I check dameonset and deployment ovn-central and ovs-ovn in CrashLoopBackoff state. 

1) ovs-ovn pod logs : 
 * ovsdb-server is not running
Illegal instruction (core dumped)
 * /etc/openvswitch/conf.db does not exist
 * Creating empty database /etc/openvswitch/conf.db
Illegal instruction (core dumped)
 * ovn-controller is not running
 * ovs-vswitchd is not running
 * ovsdb-server is not running

2)ovn-central pod logs:
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
timeout: the monitored command dumped core
Illegal instruction (core dumped)
 * Creating cluster database /etc/ovn/ovnnb_db.db
Illegal instruction (core dumped)
Illegal instruction (core dumped)
 * Starting ovsdb-nb
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
 * Waiting for  to come up
Illegal instruction (core dumped)
Illegal instruction (core dumped)
 * Creating cluster database /etc/ovn/ovnsb_db.db
 * Starting ovsdb-sb
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
 * Waiting for  to come up
 * OVN Northbound DB is not running
/kube-ovn/start-db.sh: line 264:   170 Illegal instruction     (core dumped) ovn-nbctl --no-leader-only set-connection ptcp:"${DB_NB_PORT}":[::]
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running

**Comment by mkcetinkaya** [comment]
@oilbeater could you find a chance to check this error for the master branch?

**Comment by oilbeater** [comment]
@mkcetinkaya we can not reproduce it in my cluster, did you run it on arm64 arch? Or can you paste your kernel version?

**Comment by mkcetinkaya** [comment]
@oilbeater 5.4.0-109-generic our kernel version

**Comment by oilbeater** [comment]
@mkcetinkaya Can you check the log in /var/log/ovn and /var/log/openvswitch if there is anything wrong

**Comment by oilbeater** [comment]
please check the dmesg if it's oom issues

**Comment by xujunjie-cover** [comment]
@oilbeater，dmesg like this

```
[592032.716203] traps: ovsdb-tool[1845098] trap invalid opcode ip:7f4673fceb48 sp:7fff32271de0 error:0 in libopenvswitch-2.17.so.0.0.2[7f4673fcb000+17e000]
[592033.376477] traps: ovsdb-client[1845152] trap invalid opcode ip:7f0c0975db48 sp:7fff67d6b950 error:0 in libopenvswitch-2.17.so.0.0.2[7f0c0975a000+17e000]
[592035.050944] traps: ovsdb-tool[1845216] trap invalid opcode ip:7fd7209acb48 sp:7ffe48fd58b0 error:0 in libopenvswitch-2.17.so.0.0.2[7fd7209a9000+17e000]
[592038.782054] traps: ovsdb-client[1845364] trap invalid opcode ip:7fa1132d2b48 sp:7fff576cb7b0 error:0 in libopenvswitch-2.17.so.0.0.2[7fa1132cf000+17e000]
[592039.934594] traps: ovsdb-server[1845442] trap invalid opcode ip:7fa036cc1b48 sp:7ffc189a8220 error:0 in libopenvswitch-2.17.so.0.0.2[7fa036cbe000+17e000]
[592041.460641] traps: ovsdb-client[1845567] trap invalid opcode ip:7f3f6821fb48 sp:7fffe3300180 error:0 in libopenvswitch-2.17.so.0.0.2[7f3f6821c000+17e000]
```

I have solve this issue in my env;
the reason why  `Monday we deployed and tested succesfully but today could not deploy master branch`,  I think image `kubeovn/kube-ovn-base:v1.10.0` in Dockerfile had changed between your twice tests, it rebuild because of change ovs version(#1495)
new image kubeovn/kube-ovn-base:v1.10.0 build in hosts that has cpu with `AVX2` and `AVX512`, but not unsuited with your hosts.

maybe you need to build ovs and rebuild image kubeovn/kube-ovn-base:v1.10.0 in your host, 
please check your host's cpuinfo if has avx2 or avx512. @mkcetinkaya

**Comment by zhangzujian** [comment]
@mkcetinkaya  Please try the new built images `kubeovn/kube-ovn:v1.10.0-no-avx512` for v1.10 and `kubeovn/kube-ovn:v1.11.0-no-avx512` for the master branch.
