### ISSUE TITLE
ipam init and gc issues

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1502]
<img width="1269" alt="wecom-temp-53b8c1548e76614aaee78758e5e46c1d" src="https://user-images.githubusercontent.com/1189736/166869862-df9d4b28-52ef-45d5-9453-e738a6d5bf91.png">

**Comment by zhangzujian** [comment]
This issue should have been fixed.

**Comment by hongzhen-ma** [comment]
ipam 初始化之后，如果 isPodAlive(pod) 判断Pod 处于非alive状态的话，在初始化的gc中，会间隔3s，两次调用markAndCleanLSP。这种情况下，应该能出现截图中描述的问题，在ipam刚初始化完短时间内又调用到gc lsp的情况。
