### ISSUE TITLE
failed to import package github.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned

### ISSUE THREAD

**Issue by hdf15804299051** [kubeovn/kube-ovn#1535]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.import this problem failed ,(import ""github.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned"")
2.failed message is 
mytest/main imports
        github.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned: module githu
b.com/kubeovn/kube-ovn@latest found (v1.10.0), but does not contain package gith
ub.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned
3.reference to another problem :https://github.com/tensorflow/tensorflow/issues/44539

4.help me pelase 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)

  ```

- kube-ovn version:v1.10.0
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
     mytest/main imports
            github.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned: module githu
    b.com/kubeovn/kube-ovn@latest found (v1.10.0), but does not contain package gith
    ub.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned

  ```

**Comment by hdf15804299051** [comment]
another program inport this problem failed ,message is mytest/main imports
github.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned: module githu
b.com/kubeovn/kube-ovn@latest found (v1.10.0), but does not contain package gith
ub.com/kubeovn/kube-ovn/pkg/client/clinetset/versioned

**Comment by zhangzujian** [comment]
Add the following content to you go.mod may fix it:

```go
replace (
	github.com/alauda/felix => github.com/kubeovn/felix v0.0.0-20220325073257-c8a0f705d139
	github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
	github.com/greenpau/ovsdb => github.com/alauda/ovsdb v0.0.0-20210113100339-040cf3e76c28
	github.com/openshift/api => github.com/openshift/api v0.0.0-20210428205234-a8389931bee7
	github.com/openshift/client-go => github.com/openshift/client-go v0.0.0-20210112165513-ebc401615f47
	github.com/openshift/library-go => github.com/mhenriks/library-go v0.0.0-20210511195009-51ba86622560
	gopkg.in/k8snetworkplumbingwg/multus-cni.v3 => github.com/k8snetworkplumbingwg/multus-cni v0.0.0-20220308162416-497ddfe315a9
	k8s.io/api => k8s.io/api v0.23.1
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.23.1
	k8s.io/apimachinery => k8s.io/apimachinery v0.23.1
	k8s.io/apiserver => k8s.io/apiserver v0.23.1
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.23.1
	k8s.io/client-go => k8s.io/client-go v0.23.1
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.23.1
	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.23.1
	k8s.io/code-generator => k8s.io/code-generator v0.23.1
	k8s.io/component-base => k8s.io/component-base v0.23.1
	k8s.io/component-helpers => k8s.io/component-helpers v0.23.1
	k8s.io/controller-manager => k8s.io/controller-manager v0.23.1
	k8s.io/cri-api => k8s.io/cri-api v0.23.1
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.23.1
	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.23.1
	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.23.1
	k8s.io/kube-proxy => k8s.io/kube-proxy v0.23.1
	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.23.1
	k8s.io/kubectl => k8s.io/kubectl v0.23.1
	k8s.io/kubelet => k8s.io/kubelet v0.23.1
	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.23.1
	k8s.io/metrics => k8s.io/metrics v0.23.1
	k8s.io/mount-utils => k8s.io/mount-utils v0.23.1
	k8s.io/pod-security-admission => k8s.io/pod-security-admission v0.23.1
	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.23.1
	kubevirt.io/api => kubevirt.io/api v0.50.0
	kubevirt.io/client-go => kubevirt.io/client-go v0.50.0
	kubevirt.io/containerized-data-importer => kubevirt.io/kubevirt-containerized-data-importer v1.42.1
)
```

**Comment by hdf15804299051** [comment]
> Add the following content to you go.mod may fix it:
> 
> ```go
> replace (
> 	github.com/alauda/felix => github.com/kubeovn/felix v0.0.0-20220325073257-c8a0f705d139
> 	github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
> 	github.com/greenpau/ovsdb => github.com/alauda/ovsdb v0.0.0-20210113100339-040cf3e76c28
> 	github.com/openshift/api => github.com/openshift/api v0.0.0-20210428205234-a8389931bee7
> 	github.com/openshift/client-go => github.com/openshift/client-go v0.0.0-20210112165513-ebc401615f47
> 	github.com/openshift/library-go => github.com/mhenriks/library-go v0.0.0-20210511195009-51ba86622560
> 	gopkg.in/k8snetworkplumbingwg/multus-cni.v3 => github.com/k8snetworkplumbingwg/multus-cni v0.0.0-20220308162416-497ddfe315a9
> 	k8s.io/api => k8s.io/api v0.23.1
> 	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.23.1
> 	k8s.io/apimachinery => k8s.io/apimachinery v0.23.1
> 	k8s.io/apiserver => k8s.io/apiserver v0.23.1
> 	k8s.io/cli-runtime => k8s.io/cli-runtime v0.23.1
> 	k8s.io/client-go => k8s.io/client-go v0.23.1
> 	k8s.io/cloud-provider => k8s.io/cloud-provider v0.23.1
> 	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.23.1
> 	k8s.io/code-generator => k8s.io/code-generator v0.23.1
> 	k8s.io/component-base => k8s.io/component-base v0.23.1
> 	k8s.io/component-helpers => k8s.io/component-helpers v0.23.1
> 	k8s.io/controller-manager => k8s.io/controller-manager v0.23.1
> 	k8s.io/cri-api => k8s.io/cri-api v0.23.1
> 	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.23.1
> 	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.23.1
> 	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.23.1
> 	k8s.io/kube-proxy => k8s.io/kube-proxy v0.23.1
> 	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.23.1
> 	k8s.io/kubectl => k8s.io/kubectl v0.23.1
> 	k8s.io/kubelet => k8s.io/kubelet v0.23.1
> 	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.23.1
> 	k8s.io/metrics => k8s.io/metrics v0.23.1
> 	k8s.io/mount-utils => k8s.io/mount-utils v0.23.1
> 	k8s.io/pod-security-admission => k8s.io/pod-security-admission v0.23.1
> 	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.23.1
> 	kubevirt.io/api => kubevirt.io/api v0.50.0
> 	kubevirt.io/client-go => kubevirt.io/client-go v0.50.0
> 	kubevirt.io/containerized-data-importer => kubevirt.io/kubevirt-containerized-data-importer v1.42.1
> )
> ```

I tried this method last week, but it doesn't seem to work. and I try again,it failed again

**Comment by hdf15804299051** [comment]
I tried this method last week, but it doesn't seem to work. and I try again,it failed again

**Comment by hdf15804299051** [comment]
the same error

**Comment by hdf15804299051** [comment]
I change the kubeovn version to 1.8.0 to fix this problem
