### ISSUE TITLE
kubevirt & multus-cni net1无法ping通

### ISSUE THREAD

**Issue by AyaSenri** [kubeovn/kube-ovn#1546]
## 1. 发布我的vm

![image](https://user-images.githubusercontent.com/46734911/169227913-8c6fc827-e611-49fd-91fd-166003070e25.png)

 ```python
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net1-nad
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net1-nad.default.ovn"
    }'
 ```

 ```python
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: my-subnet
spec:
  protocol: IPv4
  cidrBlock: 172.17.0.0/16
  gateway: 172.17.0.1
 ```

 ```python
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    metadata:
      creationTimestamp:
      labels:
        kubevirt.io/domain: testvm
        kubevirt.io/size: small
      annotations:
        net1-nad.default.ovn.kubernetes.io/logical_switch: my-subnet
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          - name: net1-interface
            bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      - name: net1-interface
        multus:
          networkName: default/net1-nad
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo:latest
          imagePullPolicy: IfNotPresent
        name: containerdisk
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitdisk
 ```

##  2.检查launcher POD和 vm的网络配置
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "compute" out of: compute, volumecontainerdisk, container-disk-binary (init), volumecontainerdisk-init (init)
bash-4.4# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 02:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.1/24 brd 10.0.2.255 scope global k6t-eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
3: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc fq_codel master k6t-eth0 state UP group default qlen 1000
    link/ether ce:b9:f8:06:e6:18 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ccb9:f8ff:fe06:e618/64 scope link 
       valid_lft forever preferred_lft forever
4: net1: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 8a:eb:a7:88:e2:85 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.6/16 brd 172.17.255.255 scope global net1
       valid_lft forever preferred_lft forever
5: k6t-net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 02:00:00:de:8f:cf brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.11/32 scope global k6t-net1
       valid_lft forever preferred_lft forever
    inet6 fe80::ff:fede:8fcf/64 scope link 
       valid_lft forever preferred_lft forever
6: tap1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc fq_codel master k6t-net1 state UP group default qlen 1000
    link/ether 5e:f3:d5:dc:25:75 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5cf3:d5ff:fedc:2575/64 scope link 
       valid_lft forever preferred_lft forever
443: eth0@if444: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:00:07:6a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.22.0.40/14 brd 10.23.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe00:76a/64 scope link 
       valid_lft forever preferred_lft forever
445: net1-nic@if446: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master k6t-net1 state UP group default 
    link/ether 02:00:00:de:8f:cf brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ff:fede:8fcf/64 scope link 
       valid_lft forever preferred_lft forever
bash-4.4# ip route
default via 10.22.0.1 dev eth0 
10.0.2.0/24 dev k6t-eth0 proto kernel scope link src 10.0.2.1 
10.20.0.0/14 dev eth0 proto kernel scope link src 10.22.0.40 

Successfully connected to testvm console. The escape sequence is ^]

login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
testvm login: cirros
Password: 
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast qlen 1000
    link/ether 52:54:00:b9:ce:e9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feb9:cee9/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 00:00:00:b7:5a:7c brd ff:ff:ff:ff:ff:ff
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast qlen 1000
    link/ether 52:54:00:b9:ce:e9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feb9:cee9/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 00:00:00:b7:5a:7c brd ff:ff:ff:ff:ff:ff
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.0.2.1        0.0.0.0         UG    0      0        0 eth0
10.0.2.0        *               255.255.255.0   U     0      0        0 eth0

## 3. 使用sample pod测试网络，发现eth0可ping通， net1无法ping通
kubectl exec -it samplepod sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # ping 10.22.0.40
PING 10.22.0.40 (10.22.0.40): 56 data bytes
64 bytes from 10.22.0.40: seq=0 ttl=42 time=1.272 ms
64 bytes from 10.22.0.40: seq=1 ttl=42 time=0.419 ms
64 bytes from 10.22.0.40: seq=2 ttl=42 time=0.326 ms
^Z[1]+  Stopped                    ping 10.22.0.40
/ # ping 172.17.0.6
PING 172.17.0.6 (172.17.0.6): 56 data bytes
^Z[2]+  Stopped                    ping 172.17.0.6

- kube-ovn version:
v1.9.1

**Comment by xujunjie-cover** [comment]
vm 内的 eth1 没起来啊，没有 IP 啊，改一下 /etc/interfaces ，改成 eth1 dhcp，重启 vm 网络；应该就可以了。

cirros 是有这个问题的，默认配置文件里只有一个 网卡，需要自己加

**Comment by KillMaster9** [comment]
> 这个eth1网卡采用的是kube-ovn的ipam吧，还需要开启dhcp吗？

**Comment by xujunjie-cover** [comment]
> > 这个eth1网卡采用的是kube-ovn的ipam吧，还需要开启dhcp吗？

不是这个意思，是虚机内部网卡需要开启；
```
/etc/network/interfaces 
# Configure Loopback
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
```

你看 cissos 里只管了 eth0，你需要把另一张网卡也加上

**Comment by AyaSenri** [comment]
#### kube-ovn-cni logs
I0519 06:16:24.841192    8258 server.go:71] [2022-05-19T06:16:24Z] Outgoing response POST /api/v1/del with 204 status code in 158ms
I0519 06:16:54.869270    8258 server.go:63] [2022-05-19T06:16:54Z] Incoming HTTP/1.1 POST /api/v1/add request
I0519 06:16:54.869326    8258 handler.go:77] add port request {kube-ovn virt-launcher-testvm-jzvr4 default 817d7ed8146858363dd97f3f6d1adb09a8650de40cebccc88ed1fd0a4af0e063 /var/run/netns/2d55610a-8465-4d58-b35a-c34cf971d804 eth0 ovn []  }
I0519 06:16:54.881000    8258 handler.go:216] create container interface eth0 mac 00:00:00:00:07:6A, ip 10.22.0.40/14, cidr 10.20.0.0/14, gw 10.22.0.1, custom routes []
I0519 06:16:55.160511    8258 ovs.go:339] 10.22.0.40 network ready after 1 ping, gw 10.22.0.1
I0519 06:16:55.197626    8258 server.go:71] [2022-05-19T06:16:55Z] Outgoing response POST /api/v1/add with 200 status code in 328ms
I0519 06:16:55.275484    8258 server.go:63] [2022-05-19T06:16:55Z] Incoming HTTP/1.1 POST /api/v1/add request
I0519 06:16:55.275548    8258 handler.go:77] add port request {kube-ovn virt-launcher-testvm-jzvr4 default 817d7ed8146858363dd97f3f6d1adb09a8650de40cebccc88ed1fd0a4af0e063 /var/run/netns/2d55610a-8465-4d58-b35a-c34cf971d804 net1 net1-nad.default.ovn []  }

**Comment by xujunjie-cover** [comment]
cirros 内 /etc/network/interfaces 改成
```
# Configure Loopback
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto net1
iface net1 inet dhcp
```

重启网络或者 reboot 
@AyaSenri

**Comment by AyaSenri** [comment]
it works！谢谢~ cirros镜像的问题
