### ISSUE TITLE
plugin type="kube-ovn" failed (add): request ip return 500 no address allocated to pod 

### ISSUE THREAD

**Issue by pdo2013** [kubeovn/kube-ovn#1557]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem
1.创建一个test.yaml
2.创建kubevirt 虚拟机，ip无法正常分配。普通的pod却可以正常分配

~#kubectl get pods -n ls1  -o wide
NAME                                  READY   STATUS     RESTARTS      AGE     IP           NODE                     NOMINATED NODE   READINESS GATES
busybox                               1/1     Running    2 (54m ago)   172m    10.66.0.14   compute172.localdomain   <none>           <none>
busybox-staticip                      1/1     Running    2 (29m ago)   147m    10.66.0.10   compute172.localdomain   <none>           <none>
nginx-8f458dc5b-chb6f                 1/1     Running    0             142m    10.66.0.16   k8s102                   <none>           <none>
nginx-8f458dc5b-w4s4g                 1/1     Running    0             3h27m   10.66.0.11   compute172.localdomain   <none>           <none>
virt-launcher-testvmi-nocloud-hhskv   0/2     Init:0/2   0             159m    <none>       compute172.localdomain   <none>           1/1

~#cat test.yaml 
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
  namespace: ls1
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }

~#kubectl describe -n ls1 pods virt-launcher-testvmi-nocloud-hhskv
Events:
  Type     Reason                  Age                    From     Message
  ----     ------                  ----                   ----     -------
  Warning  FailedCreatePodSandBox  3m8s (x434 over 155m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "206adb1363e874ed8a0f25c1ecbf39b6f6806e6a8be19e6088a47e9c6a08fa5f": plugin type="kube-ovn" failed (add): request ip return 500 no address allocated to pod ls1/virt-launcher-testvmi-nocloud-hhskv provider ovn, please see kube-ovn-controller logs to find errors

~#kubectl -n kube-system logs kube-ovn-controller-86d8cf9969-5dfr9 |grep hhskv
I0524 15:46:42.050793       7 pod.go:314] handle add pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.050989       7 ipam.go:51] allocate v4 10.66.0.15 v6  mac 00:00:00:C6:FC:6F for ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.058127       7 pod.go:349] handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.082180       7 pod.go:320] take 31 ms to handle add pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.082922       7 pod.go:349] handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.084434       7 pod.go:349] handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.119926       7 subnet.go:453] release v4 10.66.0.15 mac 00:00:00:C6:FC:6F for ls1/virt-launcher-testvmi-nocloud-hhskv, add ip to released list
I0524 15:46:42.119971       7 pod.go:356] take 61 ms to handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.119985       7 pod.go:349] handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.135078       7 pod.go:356] take 52 ms to handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.195147       7 pod.go:356] take 110 ms to handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:42.210296       7 pod.go:356] take 90 ms to handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:54.465495       7 pod.go:314] handle add pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:54.474134       7 pod.go:349] handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:54.476572       7 pod.go:320] take 11 ms to handle add pod ls1/virt-launcher-testvmi-nocloud-hhskv
I0524 15:46:54.492487       7 pod.go:356] take 18 ms to handle delete pod ls1/virt-launcher-testvmi-nocloud-hhskv

- Kubernetes version:

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0

- kube-ovn version:
 
1.10

- operation-system/kernel version:
  
  5.4.195-1.el8.elrepo.x86_64

**Comment by oilbeater** [comment]
please paste the cni config in `/etc/cni/net.d` and the full describe information of the pod ls1/virt-launcher-testvmi-nocloud-hhskv

**Comment by pdo2013** [comment]
there is only one  01-kube-ovn.conflist  in /etc/cni/net.d

 ![image](https://user-images.githubusercontent.com/7898547/170157669-29113b7f-c436-4eb0-b193-5aa792aff29c.png
[virt-launcher-testvmi-nocloud-hhskv.log](https://github.com/kubeovn/kube-ovn/files/8767173/virt-launcher-testvmi-nocloud-hhskv.log)
)

**Comment by lrh3321** [comment]
I'm also having this issue

**Comment by pdo2013** [comment]
这是一个yaml问题，已解决

**Comment by lrh3321** [comment]
> 这是一个yaml问题，通过kind: VirtualMachine 能成功创建，通过kind: VirtualMachineInstance 则会失败。

https://github.com/kubeovn/kube-ovn/blob/fb1f59b107b43ab5583f4c7cfa453ff2d17459e3/pkg/controller/pod.go#L1448-L1458

**Comment by zhangzujian** [comment]
> > 这是一个yaml问题，通过kind: VirtualMachine 能成功创建，通过kind: VirtualMachineInstance 则会失败。
> 
> https://github.com/kubeovn/kube-ovn/blob/fb1f59b107b43ab5583f4c7cfa453ff2d17459e3/pkg/controller/pod.go#L1448-L1458
> 
> should relace `VirtualMachine` to `VirtualMachineInstance`

Thanks for the information! Could you please submit a PR to fix it? : )
