### ISSUE TITLE
kube-ovn-cni 启动失败

### ISSUE THREAD

**Issue by huangleilz** [kubeovn/kube-ovn#1591]
启动ovn后出现kube-ovn-cni部分pod启动失败日志如下：

deployment "kube-ovn-controller" successfully rolled out
I0608 16:47:51.234506   40123 cniserver.go:24] 
-------------------------------------------------------------------------------
Kube-OVN: 
  Version:       v1.6.0
  Build:         2021-01-15_13:35:33
  Commit:        git-449185b62226c5cd7e35838bbc8edac8c640bed5
  Go Version:    go1.15.6
  Arch:          amd64
-------------------------------------------------------------------------------
I0608 16:47:51.246703   40123 config.go:199] no --kubeconfig, use in-cluster kubernetes config
I0608 16:47:51.249474   40123 config.go:118] daemon config: &{ 1400 1360 true mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0xc0001571e0 0xc0006348f0 134.130.235.8 10.68.0.0/16  true 10665 geneve provider }
E0608 16:48:04.379704   40123 ovs.go:282] ovn0 failed to ping gw 100.64.0.1, exit status 1
F0608 16:48:04.379742   40123 cniserver.go:36] init node gateway failed exit status 1

查看主机路由并没有生成100.64.0.1相关的网关路由信息。

**Comment by zhangzujian** [comment]
Please check status of `ovs-cnetral`, `ovs-ovn` and `kube-ovn-controller`.

**Comment by huangleilz** [comment]
> Please check status of `ovs-cnetral`, `ovs-ovn` and `kube-ovn-controller`.

ovs-cnetral, ovs-ovn  kube-ovn-controller 的状态都是正常的。并不是所有的ube-ovn-cni异常，只有个别节点

**Comment by oilbeater** [comment]
建议更换到新版本 1.6 已经是比较老的版本了很多问题可能在新版本已经修复了
