### ISSUE TITLE
kube-ovn-controller 在大量 POD 场景下的内存占用异常问题

### ISSUE THREAD

**Issue by gugulee** [kubeovn/kube-ovn#1602]
# Expected Behavior
当存在大量 POD 时，占用内存 18G 左右，不知道占用是否正常。
删除 POD 后，占用的内存应该释放。

# Actual Behavior

kube-ovn-controller 在大量 POD （1W）场景，占用内存 18G 左右，删除 POD 后，内存未释放。

# Steps to Reproduce the Problem

1. 使用 kubemark 创建大量 POD（1W），kubectl top pod 查看你内存如下
![image](https://user-images.githubusercontent.com/37604165/173042164-f3d9181d-d8da-4e8e-a40b-00c3db678637.png)

2. 删除 POD 后，kubectl top pod 查看你内存如下
![image](https://user-images.githubusercontent.com/37604165/173042381-f00f9caf-c167-40c7-aa77-672dfcca06a6.png)

3. 删除 POD 后，用 go pprof 分析 heap（IP:PORT/debug/pprof/heap）使用情况，看着好像 POD 缓存已经释放，如下
![image](https://user-images.githubusercontent.com/37604165/173043577-c8f47e5b-0385-4db7-92d7-68c4a261d1eb.png)

4. 但是 kubectl top pod 查看内存并没有释放，具体见如下
![image](https://user-images.githubusercontent.com/37604165/173043771-260fc5ba-eb75-4cb5-917c-2ee38f9a9f91.png)

5. 使用 top 查看 kube-ovn-controller 的内存是正常的
![image](https://user-images.githubusercontent.com/37604165/173044326-93c926ef-d7a7-4d7e-9122-2001da70acbf.png)

6. 查看 kube-ovn-controller 查看 crgoup 里面 memory.usage_in_bytes 内存异常。理论上 memory.stat 里面的 total_inactive_anon 应该会被自动释放（但是未释放）。
![image](https://user-images.githubusercontent.com/37604165/173270583-5bb5e0d1-8c39-4d17-a27f-9bebb637bad7.png)

7. memory.usage_in_bytes 和 oom 有关，可能导致 kube-ovn-controller  被 oom，从而影响集群的稳定性。

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
  1.9.2
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  "Rocky Linux 8.5 (Green Obsidian)"
  4.18.0-348.el8.0.2.x86_64
  ```

**Comment by gugulee** [comment]
十分抱歉，在 “Steps to Reproduce the Problem” 步骤 6 中我写错了。
正确的是只能通过 `echo 2 > /proc/sys/vm/drop_caches `释放内存而非` echo 1 > /proc/sys/vm/drop_caches`。

----------------------------------------------------------------------------------------------------------------------
我看了下 https://github.com/kubernetes/kubernetes/issues/43916，  应该和这个无关，这个 issue 中讨论的好像关于的是 page cache 的问题。

而我遇到的问题，是 inactive_anon 内存占用异常的问题。

**Comment by oilbeater** [comment]
目前看起来是操作系统相关的问题，并未在其他用户那里复现
