### ISSUE TITLE
Networkpolicy should disable log by default to avoid ddos

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1603]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by hongzhen-ma** [comment]
ACL 创建的时候，携带的 --log 参数，会在ovn-controller 中生成ACL匹配的log，影响性能。
考虑增加annotation或者其他参数，来控制是否开启ACL的log功能
