### ISSUE TITLE
VPC NAT 网关镜像中arping 执行结果异常

### ISSUE THREAD

**Issue by lynn901** [kubeovn/kube-ovn#1613]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

通过nsenter进到容器的namespace中，执行arping 命令，返回执行结果为成功
![image](https://user-images.githubusercontent.com/11764870/173996060-3dc68eae-dd6b-4cd8-a87a-081834403cb8.png)
而直接进入容器，执行arping命令，返回执行结果为失败
![5c77f9f34ee1ed5bb2e368a7f951e62](https://user-images.githubusercontent.com/11764870/173996146-9af21522-db11-4dfb-957b-2fba0f915017.png)

这导致无法成功创建EIP，ovn-controller报错如下：
![image](https://user-images.githubusercontent.com/11764870/173996309-5f0a9e0d-20f2-44b7-9404-7d405125b29c.png)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  
  ```
 1.10
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
 CentOS Linux 7 (Core) 3.10.0-1127.el7.x86_64

  ```

**Comment by lynn901** [comment]
镜像中脚本与社区代码不一致
![349de12f21abb43134e294c602941e1](https://user-images.githubusercontent.com/11764870/174006338-cc5be856-7990-4522-9a03-86520e139998.png)
镜像中的arping的版本为arping from iputils v20220328-1499-gc662f01584

**Comment by zhangzujian** [comment]
> 镜像中脚本与社区代码不一致 ![349de12f21abb43134e294c602941e1](https://user-images.githubusercontent.com/11764870/174006338-cc5be856-7990-4522-9a03-86520e139998.png) 社区的 ![image](https://user-images.githubusercontent.com/11764870/174007227-b09bb5c9-d7d3-4f73-9df6-ec5a9d6a1b58.png)
> 
> 镜像中的arping的版本为arping from iputils v20220328-1499-gc662f01584

新版本修复了脚本中的 `exit $1`。VPC NAT 脚本失败的原因还是 arping 退出码非零。

**Comment by bobz965** [comment]
should fixed
