### ISSUE TITLE
VIP lost after k8s service update 

### ISSUE THREAD

**Issue by ShaPoHun** [kubeovn/kube-ovn#1632]
# Expected Behavior
service更新功能正常
# Actual Behavior
service更新后，vip丢失
# Steps to Reproduce the Problem

1.当前环境
```
[root@hci-dev-mst-1 home]# kubectl get svc
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
demo                ClusterIP   10.105.42.178   <none>        80/TCP                   5d18h
```
```
NAME                ENDPOINTS                                                AGE
demo                10.16.0.31:80                                            5d18h
```
```
[root@hci-dev-mst-1 home]# kubectl ko nbctl lb-list
UUID                                    LB                  PROTO      VIP                     IPs
84200011-4c15-4815-9a34-0e245bf10208    cluster-tcp-load    tcp       10.105.42.178:80        10.16.0.31:80
```

2.更新service
```
[root@hci-dev-mst-1 home]# kubectl edit svc demo 
```
3.再次查看lb-list，vip消失

# Additional Info

- kube-ovn version: 1.10
  
代码这里，会对当前的vip进行删除：
https://github.com/kubeovn/kube-ovn/blob/16d28f755b22704427c297918c01119955ed6e6d/pkg/controller/service.go#L280

**Comment by oilbeater** [comment]
@ShaPoHun 感谢发现问题，可不可以提交个 pr 来修复这个问题？

**Comment by hongzhen-ma** [comment]
@ShaPoHun 能贴一下详细的service信息，以及更新的字段信息吗？

从代码上分析，在 svc.Spec.SessionAffinity 字段取值变更后，280行是删除原来的 oTcpLb 的vip信息，在更新endpoints的时候，会给新的LB添加vip信息

自验证更新SessionAffinity 字段，lb的vip信息更新是正常的，没有复现出来issue描述的问题

**Comment by hongzhen-ma** [comment]
更新前
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/67130442/177682940-f8e41f8d-14a8-436f-b853-52f05ea39f1a.png">

更新后
<img width="1603" alt="image" src="https://user-images.githubusercontent.com/67130442/177683000-014b11a4-86fb-4fe8-a39e-ac72f0e1893b.png">

**Comment by ShaPoHun** [comment]
没有再出现问题描述
