### ISSUE TITLE
nat gw pod snat rule apply failed when subnet is dualstack

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#1657]
# Expected Behavior
nat gw pod snat rule should apply completely  when subnet is dualstack

# Actual Behavior

repeat log err
![image](https://user-images.githubusercontent.com/7981158/176396773-11ad4742-f240-4e3f-923f-6ac28b1fd3aa.png)

ps： ipv4 works well

# Steps to Reproduce the Problem

1. nat gw pod create snat with dualstack subnet

# Additional Info

- kube-ovn version:
  
  ```
1.10.0
  ```

**Comment by hongzhen-ma** [comment]
vpc-nat-gw 目前只支持IPv4的iptables命令，不支持 ip6tables 命令，无法做 IPv6 的 SNAT 处理。 eip.Spec.V6ip 字段暂时用不上。
在vpc 内部子网 为双栈的情况下，验证 子网 cidr 进行 snat 配置
![image](https://user-images.githubusercontent.com/67130442/180914193-9d1bfa68-8d13-4892-903b-d6f9dbe695d0.png)
![image](https://user-images.githubusercontent.com/67130442/180914209-0939058a-be92-4408-a129-94bfa9802fc4.png)

snat 处理的时候，是以 逗号隔开的rules，取 rules[1] 作为snat的 cidr，在内部双栈子网cidr格式为 IPv4,IPv6 时，rules[1]解析的cidr 碰巧是 v4的cidr，这种情况能正常处理。

反过来，当双栈cidr格式为 IPv6,IPv4 格式时，会将 IPv6 cidr 映射到 IPv4的EIP地址上，这个时候就会出现问题中的报错。
<img width="416" alt="企业微信截图_bef7f6ad-93d0-4ebc-abc1-af29aaa9b5c5" src="https://user-images.githubusercontent.com/67130442/180914496-6b8d6cd7-36f0-4aa2-8f52-3b094879cb90.png">
<img width="1169" alt="企业微信截图_da98da61-9d34-4b69-8b23-12b4aa1a9507" src="https://user-images.githubusercontent.com/67130442/180914501-d3a7e15c-8c0a-4b88-875f-117c3730def1.png">

针对这种情况做了修改。
