### ISSUE TITLE
nat gw pod net1 lack of route

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#1658]
# Expected Behavior

net1 route should be exist

# Actual Behavior
## 重建之前
![image](https://user-images.githubusercontent.com/7981158/176409759-8e9a25b0-3b0f-4604-b94d-0f27b4b67bad.png)

## 重建之后
![image](https://user-images.githubusercontent.com/7981158/176411124-51b0deae-2814-4592-8537-7eba9b7b81d8.png)

![image](https://user-images.githubusercontent.com/7981158/176409843-b284eacc-b2b4-4c03-a05b-afd9848ff1da.png)

偶现问题，也许路由设置完毕后需确认存在，或者路由即使未设置成功也未报错，未触发重试

# Steps to Reproduce the Problem

1. create nat gw pod

2. just create a snat rule

3. delete nat gw pod and wait to see routes for net1

**Comment by bobz965** [comment]
kube-ovn version
1.10 

不断重试，重建nat gw pod

**Comment by hongzhen-ma** [comment]
沟通了下，反馈的问题，是说 route table100 中，net1 网卡的路由，应该有两条。一条是默认路由，另外一条是 外部子网经net1 转发的路由。
在部分情况下，缺少外部子网的那条路由，这种情况是添加 vpc内部路由时，将外部子网也添加到vpc下，一起做了处理，出现覆盖情况导致的。这个问题在https://github.com/kubeovn/kube-ovn/pull/1735 中修复了。

测试遇到的情况
<img width="546" alt="企业微信截图_b77b0540-b6aa-480f-b02e-9db01241df8f" src="https://user-images.githubusercontent.com/67130442/180694825-bf73ed44-b8c0-445e-aa03-dfe0be933b92.png">

**Comment by bobz965** [comment]
这个issue 在并发10-20的时候，应该是可以概率性复现 internal route 和 external route 未添加的情况，
目前已在eip里面添回了eip对应net1的公网默认网关的逻辑，所以只要使用eip，extrenal route的路由应该存在，访问公网是正常的
关于内部的路由，感觉每一个子网还是对应一个nat gw pod 比较好，这样直连路由都是稳定存在，应该没有问题。
当然，如果是一个vpc粒度对应的nat gw pod ，可能在并发情况较大的情况下，会出现内部路由缺失的情况。感觉对nat gw pod 的创建做一下限速能够有效解决该问题。 
或许存在更好的根本解决方式，后续可以再研究下。
