### ISSUE TITLE
Installation failed in k8s v1.24

### ISSUE THREAD

**Issue by jichenjc** [kubeovn/kube-ovn#1659]
# Expected Behavior

https://github.com/kubeovn/kube-ovn/blob/master/dist/images/install.sh#L58

still default to LABEL="node-role.kubernetes.io/master"
with new 1.24 k8s, it's "node-role.kubernetes.io/control-plane now"

or run the install.sh got following which is not a good user experience
```
No resources found
ERROR: No node with label node-role.kubernetes.io/master
```

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
We are working on this in PR #1553.
