### ISSUE TITLE
大量 POD 场景下 logical_switch_port 等资源查询，创建和删除操作性能优化

### ISSUE THREAD

**Issue by gugulee** [kubeovn/kube-ovn#1675]
### Feature request

用 libovsdb 替换 ovn-nbctl daemon，优化大量 POD 场景下 logical_switch_port 等资源查询，创建和删除操作性能

### Use case

在大量 POD 场景下，logical_switch_port 等资源查询，创建和删除操作性能不好。

使用 kubemark 创建 110 个 hollow-node，10000 个 POD。经测试，在分支 1.10.1 上， logical_switch_port  创建和删除时间大约需要 15~17 分钟。

用 libovsdb 替换 ovn-nbctl daemon，希望能提升相关资源的 CRUD 性能

**Comment by sober-wang** [comment]
可是 libovsdb 也是对 ovs/ovn 命令行的封装。

**Comment by zhangzujian** [comment]
> 可是 libovsdb 也是对 ovs/ovn 命令行的封装。

https://github.com/ovn-org/libovsdb
