### ISSUE TITLE
K3s安装1.10.2版本kube-ovn问题

### ISSUE THREAD

**Issue by wangxg422** [kubeovn/kube-ovn#1680]
k3s有一个svclb-traefik，会添加一条主机80 443端口的流量DNAT到svclb-traefik Pod的iptables规则：
![image](https://user-images.githubusercontent.com/35413234/178389366-ad9579e5-0a0b-4662-b4d2-1b56ab72e5cb.png)

1.10.2版本未生成该iptables规则：
![image](https://user-images.githubusercontent.com/35413234/178388555-44fd09d1-b4f4-4f58-809b-6ed39bdb1ff7.png)
导致双网络接口一个可以通，一个不通：
![image](https://user-images.githubusercontent.com/35413234/178388711-a74113e4-8c81-4480-987f-e609966d6191.png)

而1.9.5版本没有该问题：
![image](https://user-images.githubusercontent.com/35413234/178389178-040ffb3f-d75b-4602-9921-96da6d5a2838.png)

此外，1.10.2版本中ovn-central组件一直报错：
![image](https://user-images.githubusercontent.com/35413234/178389570-d7e3ab83-742b-481a-9042-a7e7c8d72d8a.png)
1.9.5版本无此问题。
感谢。

**Comment by zhangzujian** [comment]
缺少的 iptables 规则应该不是 Kube-OVN 负责创建的，建议排查一下 svclb-traefik 的相关配置，比如是否开启了 hostPort。

compactDataBase 的问题可以排查一下 ovnn-central 所在节点的 /var/log/ovn 的日志。

**Comment by Ubbo-Sathla** [comment]
![image](https://user-images.githubusercontent.com/64345457/179167862-00111c82-efbb-4360-9a79-211bb093e1a2.png)

![image](https://user-images.githubusercontent.com/64345457/179168846-3ea29919-7ff6-4734-aa11-1cc38fd8d997.png)

**Comment by zhangzujian** [comment]
@wangxg422  @Ubbo-Sathla  compactDataBase 的问题已经修复：#1691。
