### ISSUE TITLE
failed to create subnet join

### ISSUE THREAD

**Issue by yuexian1234** [kubeovn/kube-ovn#1749]
# Expected Behavior
success init join subnet when kubectl apply -f kube-ovn.yaml
# Actual Behavior
<img width="820" alt="image" src="https://user-images.githubusercontent.com/14341344/180979530-0fcfb6e0-caa5-48ff-aba1-4626b7298561.png">
the kube-ovn-controller container start fail on init join subnet
logs: 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/14341344/180979796-69d6813d-98c5-40dc-96cf-f0b0edb14e3e.png">

# Steps to Reproduce the Problem

1.  kubectl apply -f  crd.yaml  && kubectl apply -f ovn.yaml 
2. kubectl apply -f kube-ovn.yaml
3. kubectl get pod -n kube-system | grep kube-ovn-controller
4.  then  will see pod status is ERROR

# Additional Info

- Kubernetes version:
  ```
  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}  

  Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.10-",GitCommit:"eab7d504b1d17586cb6e79d36a4350b647a61483", GitTreeState:"dirty", BuildDate:"2022-06-28T08:04:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  ```
     release-1.10
  ```

- operation-system/kernel version:
  ```
    CentOS Linux 7 (Core)
    5.10.1

  ```

in subnet spec struct . some fields do not have omitempty tag,so when json marshal,this field will marshal to null,and the crd will not reject the create request with null string。
<img width="545" alt="image" src="https://user-images.githubusercontent.com/14341344/180980995-d250e58e-8fca-4506-b867-ccb1b5b6cd62.png">

**Comment by yuexian1234** [comment]
anybody  has some problem?

**Comment by oilbeater** [comment]
Do you run any webhook in the cluster? @yuexian1234
