### ISSUE TITLE
The VpcNatGateway CR missed status information

### ISSUE THREAD

**Issue by larryliuqing** [kubeovn/kube-ovn#1767]
### Feature request
```
apiVersion: kubeovn.io/v1
kind: VpcNatGateway
metadata:
  name: vpc1-gw
  resourceVersion: "146539490"
  uid: 2fff3d6b-6cb5-47a6-951e-9bdca581c300
spec:
  lanIp: 172.16.100.254
  selector:
  - pn.kubesphere.io:eip-subnet-provider-network
  subnet: vpc1-net0
  vpc: vpc1

```
when i created VpcNatGateway, it don't provider status infomations, the vpc-nat-gateway pod is very import container for communication with external network, then it's status is necessary as following:

```
vpc-name: vpc1
ovn-vpc-external-network-ip: 192.168.100.108
vpc-nat-gw-condition:
 - type: Ready
eips:
 - eip1
 - eip2

```

**Comment by bobz965** [comment]
# 1. vpc-name: vpc1 
this section, maybe you can use `kubectl  get vpc-nat-gateways| grep <gw name>`  you can see gw pod with vpc

# 2. this section may be necessary, in consideration
ovn-vpc-external-network-ip: 192.168.100.108

# 3. this section may be necessary, in consideration
vpc-nat-gw-condition:
 - type: Ready
 
Ready should means: init(nat table) and route resources create successfully

# 4. eips: 
this section, maybe you can use `kubectl get eip | grep <gw name > ` to list all eips ralated to this nat gw pod
eips:
 - eip1
 - eip2

**Comment by bobz965** [comment]
use crd should be enough for now
