### ISSUE TITLE
Pods randomly killed because of failed health check

### ISSUE THREAD

**Issue by icebear74** [kubeovn/kube-ovn#1768]
# Expected Behavior
Pods Health Check working
# Actual Behavior
Pods restarting randomly because of failed health check
# Steps to Reproduce the Problem

1. Install Kubeovn
2. 
3.

# Additional Info
it's a fresh install of Kube-OVN with Installer Script

- Kubernetes version:

  **Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

  (paste your output here)
  ```

- kube-ovn version:
  kubeovn/kube-ovn:v1.10.1-no-avx512
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
"Debian GNU/Linux 11 (bullseye)"
5.10.0-16-amd64

Pods Checked: 
Longhorn
Neuvector
Grafana Monitoring

**Comment by oilbeater** [comment]
can you give a more detailed reproduce steps and the log about failed health check
