### ISSUE TITLE
Native Prometheus config without ServiceExporter

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1772]

**Comment by hongzhen-ma** [comment]
https://confluence.alauda.cn/pages/viewpage.action?pageId=120124474

**Comment by hongzhen-ma** [comment]
prometheus 官方文档
配置文件
https://prometheus.io/docs/introduction/first_steps/
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

安装
https://prometheus.io/docs/prometheus/latest/installation/

**Comment by hongzhen-ma** [comment]
prometheus 动态查询监控指标，配置参考
https://yunlzheng.gitbook.io/prometheus-book/part-iii-prometheus-shi-zhan/readmd/deploy-prometheus-in-kubernetes

**Comment by oilbeater** [comment]
need document

**Comment by hongzhen-ma** [comment]
https://github.com/kubeovn/docs/pull/19
