### ISSUE TITLE
v1.11.0-no-avx512版本使用自建subnet创建的pod无法访问外部网络

### ISSUE THREAD

**Issue by hejiahang929** [kubeovn/kube-ovn#1774]
# Expected Behavior
v1.11.0-no-avx512版本使用自建subnet创建的pod，通过设置natOutgoing: true,访问集群外部网络

# Actual Behavior
v1.11.0-no-avx512版本使用自建subnet创建的pod，通过设置natOutgoing: true, 无法访问集群外部网络，只能抓到veth端的icmp的请求包，抓不到其它网卡的icmp包，退回到1.10.4-no-avx512版本没有问题

# Steps to Reproduce the Problem

1. 创建一个subnet资源，natOutgoing设置为true， namespaces: test
2. 在 test命名空间下创建pod, 所创建的pod会使用第一步subnet里面的ip
3. 在pod里面ping外部ip，无法ping通

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.5-sn.1", GitCommit:"7bcf6d6c4f067f95f62095a1e5d3673977ab8e87", GitTreeState:"archive", BuildDate:"2020-09-25T03:11:26Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
 v1.11.0-no-avx512
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
 CentOS Linux 7 (Core)
 4.18.0-80.11.1.el7.centos.x86_64
  ```

**Comment by oilbeater** [comment]
暂时没有复现出这个问题，可以用 `kubectl ko trace` 看一下逻辑流表是否有问题 @hejiahang929
