### ISSUE TITLE
Restore OVN DB from apiserver resources

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1805]
### Feature request

When the majority of ovn db crash, we should have a way to rescue the cluster from apiserver with no data loss. 

If it can be achieved, we can just remove the data and restart ovn-central to recover from an incident, and we no longer need the ha of ovn db.

**Comment by hongzhen-ma** [comment]
测试的时候，发现同步完OVN NB DB的数据后，nbctl 可以查询到数据，sbctl 查询不出来数据


![Image](https://user-images.githubusercontent.com/67130442/193199620-7985727c-d0a0-49f2-a9ec-7ff7181a9c01.png)


这个需要解决

**Comment by hongzhen-ma** [comment]
如果只删除 ovnnb_db.db 文件，保留 ovnsb_db.db 文件，在重建 ovn-central pod之后，在完成 NB DB的恢复之后，SB DB数据也能恢复正常。

**Comment by hongzhen-ma** [comment]
查看ovn-controller的文档，如果是同时删除NB SB DB之后，可以在每个 ovs-ovn 中执行命令 
ovs-appctl -t /var/run/ovn/ovn-controller.3721.ctl  sb-cluster-state-reset
用于恢复 ovn-controller 的本地索引

<img width="690" alt="企业微信截图_15f2de3d-164f-4fed-a9a4-dfc7cd7dfb19" src="https://user-images.githubusercontent.com/67130442/197473006-22ade2e2-83a8-43d9-8b7a-bb2b8fefbd0b.png">

**Comment by hongzhen-ma** [comment]
在 ovs 健康检查中，加入 ovn-controller 对 OVN SB DB 写入的检查，不能正常写入时，就执行 sb-cluster-state-reset 命令，恢复写入控制。
这样就只需要关注 NB DB的内容恢复，SB DB的内容，会由 ovn-controller 恢复写入。

**Comment by hongzhen-ma** [comment]
<img width="1142" alt="企业微信截图_afc36816-3ca6-4781-a152-53e56f05d13d" src="https://user-images.githubusercontent.com/67130442/197973457-bc696f43-88d8-45f9-8d47-51e1874da165.png">

从测试的ovs-ovn pod log 上看，在执行 sb-cluster-state-reset 命令后，会重新注册一遍 port 信息，这个过程可能会影响 应用访问的连续性

**Comment by hongzhen-ma** [comment]
https://confluence.alauda.cn/pages/viewpage.action?pageId=130548145

经过讨论，确认 OVN SB DB的恢复，由 ovs-ovn的健康检查，自动执行 sb-cluster-state-reset 命令实现。
NB DB 的恢复，在重启 ovn-central pod 之后，通过删除 kube-ovn-controller pod 重建，利用 kube-ovn-controller 的初始化来恢复。
