### ISSUE TITLE
OVS-DPDK: Can not create vhostuesr port

### ISSUE THREAD

**Issue by carezkh** [kubeovn/kube-ovn#1837]
# Expected Behavior

Hi ! I want to create VMs and connect them to vhost-user ports respectively provided by OVS/DPDK, as shown below
```
             +----+----------+          +-------------+-----------+-------------+          +----------+----+
             |    |          |          |             |           |             |          |          |    |
             |    |vhost-user|----------| vhost-user  |   ovs     | vhost-user  |----------|vhost-user|    |
             |    |net device|          | port 1      |           | port 2      |          |net device|    |
             |    |          |          |             |           |             |          |          |    |
             |    +----------+          +-------------+-----------+-------------+          +----------+    |
             |               |          |                                       |          |               |
             |vm1            |          |                  dpdk                 |          |           vm2 |
             |               |          |                                       |          |               |
          +--+---------------------------------------------------------------------------------------------+--+
          |  |                                       hugepages                                             |  |
          |  +---------------------------------------------------------------------------------------------+  |
          |                                                                                                   |
          |                                              host                                                 |
          |                                                                                                   |
          +---------------------------------------------------------------------------------------------------+
```

Follow  [Kube-OVN with OVS-DPDK](https://github.com/kubeovn/kube-ovn/blob/master/docs/dpdk.md) document, I expect VMs and Pods can communicate with each other.

# Actual Behavior

After making some configurations different with the document that I don't think will affect the results, I can not create the vhostuser port as expect.

The ovs-ovn pod output shows `cannot create port '<port-name>' because it has unsupported type 'dpdkvhostuser'`. 

# Steps to Reproduce the Problem

Follow [Kube-OVN with OVS-DPDK](https://github.com/kubeovn/kube-ovn/blob/master/docs/dpdk.md) document, and make some different configurations.

1. Use kube-ovn v1.8.0 installation script: `wget https://raw.githubusercontent.com/kubeovn/kube-ovn/v1.8.0/dist/images/install.sh`
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- kube-ovn version:
```
  v.1.8.0
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
```
"Ubuntu 18.04.3 LTS"
4.15.0-191-generic
```

After running command `ovs-vsctl set Bridge br-int datapath_type=netdev`, the vhost-user port can be created, but this will affect the pod network connections.

BTW, the lasted version of kubeovn/kube-ovn-dpdk is `19.11-v1.8.0`, means that OVS-DPDK cannot be used later than kube-ovn 1.8.0 ? 

Thanks!

**Comment by oilbeater** [comment]
The previous dpdk mode is not support anymore, please check https://kubeovn.github.io/docs/v1.10.x/advance/dpdk/ for the recent usage

**Comment by carezkh** [comment]
Can kube-ovn  provide multiple DPDK-type network interfaces when there is only one NIC for DPDK driver to run on the node?

**Comment by oilbeater** [comment]
> Can kube-ovn provide multiple DPDK-type network interfaces when there is only one NIC for DPDK driver to run on the node?
I haven't tested before but it should works as the usual multiple kube-ovn type nic  https://kubeovn.github.io/docs/v1.10.x/advance/multi-nic/#kube-ovn

**Comment by carezkh** [comment]
Thanks a lot! I will give it a try.

**Comment by carezkh** [comment]
The image `kubeovn/kube-ovn:v1.10.6-dpdk` is not found, the script `install.sh` use it in DaemonSet `ovs-ovn-dpdk`.

**Comment by oilbeater** [comment]
@carezkh the image has been pushed. Thanks for informing us.

**Comment by carezkh** [comment]
@oilbeater  I found some issues when setting up OVS-DPDK.

1. The command `driverctl set-override xxx` in [start-ovs-dpdk-v2.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/start-ovs-dpdk-v2.sh#L19) will write `/sys/bus/pci/xxx`, so we should make the `/sys` directory in `ovs-ovn-dpdk` pod writable. I fix it #1899
2. The command `driverctl set-override ${DPDK_DEV} vfio-pci` in [start-ovs-dpdk-v2.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/start-ovs-dpdk-v2.sh#L19) failed with error message `failed to bind device 0000:00:0b.0 to driver vfio-pci`, change the driver to `uio_pci_generic` will work. I'm sure that the IOMMU was enabled and vfio-pci kernel module was loaded (my host is ubuntu22.04, the module vfio-pci was already built into the kernel).
3. What are the requirements for `ENCAP_IP` mentioned in the document [dpdk-support](https://kubeovn.github.io/docs/v1.10.x/advance/dpdk/#_2)? I set  IP addresses `100.65.0.2/16` and `100.65.0.3/16` to two hosts (hostA and hostB), the pod on hostA can not communicate with pod on hostB.
4. After enable OVS-DPDK, The performance of the ovs bridge was greatly degraded! With OVS-DPDK (ovs datapath_type is netdev), pod-to-pod network latency: 1.5ms, bandwidth: 211 Mib/s. Without OVS-DPDK (ovs datapath_type is system), pod-to-pod network latency: 0.2ms, bandwidth: 35Gib/s. I'm not sure the reason.

**Comment by oilbeater** [comment]
@luoyunhe can you take a look at this?

**Comment by luoyunhe** [comment]
2、Different network cards may be different, maybe you can refer to this [document](https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html#binding-and-unbinding-network-ports-to-from-the-kernel-modules)

**Comment by watermelon-brother** [comment]
What is the ENCAP_IP? It`s the physhic nic address to use for the dpdk? @carezkh @oilbeater @luoyunhe
