### ISSUE TITLE
some issues when I run `make release`, How to bypass these issue?

### ISSUE THREAD

**Issue by sober-wang** [kubeovn/kube-ovn#1859]
### Feature request

```
Results:


[kube-ovn/cmd/speaker/speaker.go:29] - G114 (CWE): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    28:                 http.Handle("/metrics", promhttp.Handler())
  > 29:                 klog.Fatal(http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", config.PprofPort), nil))
    30:         }()



[kube-ovn/cmd/pinger/pinger.go:29] - G114 (CWE): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    28:                 go func() {
  > 29:                         klog.Fatal(http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", config.Port), nil))
    30:                 }()



[kube-ovn/cmd/ovn_monitor/ovn_monitor.go:31] - G114 (CWE): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    30:         klog.Infoln("Listening on", config.ListenAddress)
  > 31:         klog.Fatal(http.ListenAndServe(config.ListenAddress, nil))
    32: }



[kube-ovn/cmd/daemon/cniserver.go:97] - G114 (CWE): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    96:         }
  > 97:         klog.Fatal(http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", config.PprofPort), mux))
    98: }



[kube-ovn/cmd/controller/controller.go:52] - G114 (CWE): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    51:                 }
  > 52:                 klog.Fatal(http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", config.PprofPort), mux))
    53:         }()

```

<img width="305" alt="图片" src="https://user-images.githubusercontent.com/35804630/186855574-2e1cba24-e36f-40e0-85de-f1e82703651e.png">

### Use case

I want create a development and jump these gosec issue. 

--------------------------

Maybe, we should this wrote go code:

```golang
...
server := &http.Server{
      Addr:        fmt.Sprintf("0.0.0.0:%d", config.PprofPort),
     ReadTimeout: 3 * time.Second,
}
klog.Fatal(server.ListenAndServe())
.....
````

**Comment by zhangzujian** [comment]
You can remove `lint` from dependencies of target `release`:


.PHONY: release
release: ~~lint~~ image-kube-ovn image-vpc-nat-gateway image-centos-compile

**Comment by zhangzujian** [comment]
Could you please create a patch to fix this issue?

**Comment by sober-wang** [comment]
I try.

**Comment by sober-wang** [comment]
the Makefile e2e tag miss `-ginkgo.time` when used `ginkgo` v2.x 

```shell
ginkgo version                                                                                                                                  git:master*
# Ginkgo Version 2.1.4
```

```
kube-ovn-e2e
docker run -d --name kube-ovn-e2e --network kind --cap-add=NET_ADMIN kubeovn/kube-ovn:v1.11.0 sleep infinity
5ee8619004ef668d50750920053b3ab7c43805b960eec40dc56cef797363dcbf
kind load docker-image --name kube-ovn kubeovn/pause:3.2
Image: "kubeovn/pause:3.2" with ID "sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c" found to be already present on all nodes.
ginkgo -mod=mod -progress -r -timeout=1m --always-emit-ginkgo-writer -slow-spec-threshold=60s test/e2e
flag provided but not defined: -ginkgo.timeout
Usage of /Users/wangshen/Documents/code/github-code/kube-ovn/test/e2e/e2e.test:
  -ginkgo.debug
    	If set, ginkgo will emit node output to files when running in parallel.
  -ginkgo.dryRun
    	If set, ginkgo will walk the test hierarchy without actually running anything.  Best paired with -v.
  -ginkgo.failFast
    	If set, ginkgo will stop running a test suite after a failure occurs.
  -ginkgo.failOnPending
    	If set, ginkgo will mark the test suite as failed if any specs are pending.
  -ginkgo.flakeAttempts int
    	Make up to this many attempts to run each spec. Please note that if any of the attempts succeed, the suite will not be failed. But any failures will still be recorded. (default 1)
  -ginkgo.focus value
    	If set, ginkgo will only run specs that match this regular expression. Can be specified multiple times, values are ORed.
  -ginkgo.noColor
    	If set, suppress color output in default reporter.
  -ginkgo.noisyPendings
    	If set, default reporter will shout about pending tests. (default true)
  -ginkgo.noisySkippings
    	If set, default reporter will shout about skipping tests. (default true)
  -ginkgo.parallel.node int
    	This worker node's (one-indexed) node number.  For running specs in parallel. (default 1)
  -ginkgo.parallel.streamhost string
...
```

**Comment by zhangzujian** [comment]
> the Makefile e2e tag miss `-ginkgo.timeout` when used `ginkgo` v2.x
> 
> ```shell
> ginkgo version                                                                                                                                  git:master*
> # Ginkgo Version 2.1.4
> ```
> 
> ```
> kube-ovn-e2e
> docker run -d --name kube-ovn-e2e --network kind --cap-add=NET_ADMIN kubeovn/kube-ovn:v1.11.0 sleep infinity
> 5ee8619004ef668d50750920053b3ab7c43805b960eec40dc56cef797363dcbf
> kind load docker-image --name kube-ovn kubeovn/pause:3.2
> Image: "kubeovn/pause:3.2" with ID "sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c" found to be already present on all nodes.
> ginkgo -mod=mod -progress -r -timeout=1m --always-emit-ginkgo-writer -slow-spec-threshold=60s test/e2e
> flag provided but not defined: -ginkgo.timeout
> Usage of kube-ovn/test/e2e/e2e.test:
>   -ginkgo.debug
>     	If set, ginkgo will emit node output to files when running in parallel.
>   -ginkgo.dryRun
>     	If set, ginkgo will walk the test hierarchy without actually running anything.  Best paired with -v.
>   -ginkgo.failFast
>     	If set, ginkgo will stop running a test suite after a failure occurs.
>   -ginkgo.failOnPending
>     	If set, ginkgo will mark the test suite as failed if any specs are pending.
>   -ginkgo.flakeAttempts int
>     	Make up to this many attempts to run each spec. Please note that if any of the attempts succeed, the suite will not be failed. But any failures will still be recorded. (default 1)
>   -ginkgo.focus value
>     	If set, ginkgo will only run specs that match this regular expression. Can be specified multiple times, values are ORed.
>   -ginkgo.noColor
>     	If set, suppress color output in default reporter.
>   -ginkgo.noisyPendings
>     	If set, default reporter will shout about pending tests. (default true)
>   -ginkgo.noisySkippings
>     	If set, default reporter will shout about skipping tests. (default true)
>   -ginkgo.parallel.node int
>     	This worker node's (one-indexed) node number.  For running specs in parallel. (default 1)
>   -ginkgo.parallel.streamhost string
> ...
> ```

I will fix it ASAP.
