### ISSUE TITLE
Question: Value or nic-mac if ovn-external-gw-config in distributed type

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#1876]
Hi,

in `ovn-external-gw-config` config map, we have option `centrailized` or `distributed` for `type` directive. If I use `distributed` option, then what value should I put for `nic-mac`. In my understand this value should be unique related to NIC for each node.

thanks in advance

**Comment by oilbeater** [comment]
The name is misleading, it should be any mac that not in use

**Comment by ikandars** [comment]
@oilbeater what if the node is down where the mac address attached to it. how we mitigate with this situation?
