### ISSUE TITLE
Docs for release 1.11 new features

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1882]

**Comment by sober-wang** [comment]
oh, When add new version id in VERSION file ,we should modify these file.

example: 
[k8s_yml_image_tag](https://github.com/kubeovn/kube-ovn/blob/master/yamls/kube-ovn.yaml#L44)

or,we'll create a new kube-ovn.yaml.j2 file , next used [j2cli](https://github.com/kolypto/j2cli) to render templates
