### ISSUE TITLE
dpdk的测试虚机无法进入

### ISSUE THREAD

**Issue by htz2507** [kubeovn/kube-ovn#1889]
# Expected Behavior
能够进入虚机
# Actual Behavior
不能进入虚机
# Steps to Reproduce the Problem

1. 按时教程https://kubeovn.github.io/docs/v1.10.x/advance/dpdk/ ，  完成了dpdk环境搭建
2. 执行到最后一步本配置虚机登陆名密码 virsh set-user-password vm root 12345

3. ![image](https://github.com/htz2507/mytest/blob/master/22.jpg?raw=true)

# Additional Info

- Kubernetes version:
```
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"52a2fd9", GitTreeState:"clean", BuildDate:"2022-02-08T01:26:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-1839+b93fd35dd03051-dirty", GitCommit:"b93fd35dd030519c24dd02f8bc2a7f873d2928cd", GitTreeState:"dirty", BuildDate:"2022-02-11T06:14:59Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.22) exceeds the supported minor version skew of +/-1
```

- kube-ovn version:  
 ```
kube-ovn-v1.10.1
kube-ovn-v1.10.5-dpdk
```
- operation-system/kernel version:
```
"Fedora CoreOS 34"
5.14.14-200.fc34.x86_64
```

**Comment by oilbeater** [comment]
@luoyunhe 有时间帮忙看下这个问题

**Comment by luoyunhe** [comment]
@htz2507  可以通过virsh list查看虚拟机是否正常启动，如果没有正常启动，可以通过virsh start vm来查看启动异常的原因

**Comment by htz2507** [comment]
- virsh list
![image](https://github.com/htz2507/mytest/blob/master/33.jpg?raw=true)
- oc logs pod 
![image](https://github.com/htz2507/mytest/blob/master/44.jpg?raw=true)

**Comment by luoyunhe** [comment]
看起来虚拟机已经正常启动了。
是否是还未启动完成就执行了 set-user-password。
通过virsh dumpxml vm |grep agent -C 10

**Comment by htz2507** [comment]
- virsh dumpxml vm |grep agent
![image](https://github.com/htz2507/mytest/blob/master/55.jpg?raw=true)
三个小时了，还是disconnected.

**Comment by luoyunhe** [comment]
最近比较忙，没有及时回复，kube-ovn部分应该没有多大问题，也许你应该可以通过阅读https://libvirt.org/的帮助文档，或者到https://github.com/libvirt/libvirt寻求帮助。
