### ISSUE TITLE
双栈模式目前只有geneve模式吗

### ISSUE THREAD

**Issue by mzzgaopeng** [kubeovn/kube-ovn#1893]
双栈模式目前只有geneve模式吗，社区文档yaml配置仅有geneve
vxlan隧道模式支持双栈吗

**Comment by zhangzujian** [comment]
支持

**Comment by mzzgaopeng** [comment]
> 



> 支持
 建议补充下社区文档吧，在双栈介绍只有yaml文件说明，多谢

**Comment by zhangzujian** [comment]
> 社区文档yaml配置仅有geneve

你说的 yaml 配置是 Pod 的 annotations 吗？这里并不是配置，而是 Pod 信息。

**Comment by zhangzujian** [comment]
配置隧道模式请参考 [隧道类型设置](https://kubeovn.github.io/docs/v1.10.x/guide/setup-options/#_4)。
