### ISSUE TITLE
VPC NAT网关和SNAT/FIP池分配重复问题

### ISSUE THREAD

**Issue by flyfish002** [kubeovn/kube-ovn#1900]
创建VPC网关自身使用 IP和分配 SNAT IP 和 FIP 出现重复现象，172.16.33.105，172.16.33.107作为VPC NAT网关本身使用IP, 可以分配给另一个vpc网关 vpc-nat-gw-subnet-o8qwjg8tceezezcykaqyn-d4ddf6dbb-vf5bw   作为SNAT 和FIP使用

root@node1:~# kubectl  get pod  -A    -o wide  |  grep nat

kube-system                    vpc-nat-gw-subnet-22fmlmq4ceezecekabjak-5fc758dfd-7j7bz           1/1     Running            0                  28m     192.168.11.1    node1   <none>           <none>
kube-system                    vpc-nat-gw-subnet-o8qwjg8tceezezcykaqyn-d4ddf6dbb-vf5bw           1/1     Running            0                  20m     192.168.100.1   node1   <none>           <none>
kube-system                    vpc-nat-gw-subnet-q2kvsq5fceezezzzqzbnn-6897898cb5-27v52          1/1     Running            0                  18m     192.168.0.1     node1   <none>           <none>

vpc-nat-gw-subnet-22fmlmq4ceezecekabjak-5fc758dfd-7j7bz.kube-system.ovn-vpc-external-network.kube-system    172.16.33.105          00:00:00:E0:F9:B2   node1   ovn-vpc-external-network
vpc-nat-gw-subnet-o8qwjg8tceezezcykaqyn-d4ddf6dbb-vf5bw.kube-system                                         192.168.100.1          00:00:00:30:70:97   node1   subnet-o8qwjg8tceezezcykaqyn
vpc-nat-gw-subnet-o8qwjg8tceezezcykaqyn-d4ddf6dbb-vf5bw.kube-system.ovn-vpc-external-network.kube-system    172.16.33.106          00:00:00:C3:F1:B6   node1   ovn-vpc-external-network
vpc-nat-gw-subnet-q2kvsq5fceezezzzqzbnn-6897898cb5-27v52.kube-system                                        192.168.0.1            00:00:00:34:74:76   node1   subnet-q2kvsq5fceezezzzqzbnn
vpc-nat-gw-subnet-q2kvsq5fceezezzzqzbnn-6897898cb5-27v52.kube-system.ovn-vpc-external-network.kube-system   172.16.33.107          00:00:00:5B:04:F9   node1   ovn-vpc-external-network

root@node1:~# kubectl  exec  -it      vpc-nat-gw-subnet-o8qwjg8tceezezcykaqyn-d4ddf6dbb-vf5bw     -n  kube-system     ip addr
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] [COMMAND] instead.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 2e:11:b5:39:56:75 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.33.106/24 brd 172.16.33.255 scope global net1
       valid_lft forever preferred_lft forever
    inet 172.16.33.105/24 scope global secondary net1
       valid_lft forever preferred_lft forever
    inet 172.16.33.107/24 scope global secondary net1
       valid_lft forever preferred_lft forever
    inet 172.16.33.108/24 scope global secondary net1
       valid_lft forever preferred_lft forever
189: eth0@if190: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:30:70:97 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.100.1/24 brd 192.168.100.255 scope global eth0
       valid_lft forever preferred_lft forever

**Comment by bobz965** [comment]
您好，您使用的版本是？ 可以尝试下1.10.6，1.10.6 之后该问题应该已经修复了

**Comment by flyfish002** [comment]
版本为 v1.10.0

**Comment by bobz965** [comment]
fixed after 1.10.6
