### ISSUE TITLE
When delete pod with sriov nic, vf not return to the original condition.

### ISSUE THREAD

**Issue by xujunjie-cover** [kubeovn/kube-ovn#1903]
# Expected Behavior
when pod is deleted, set vf mac 00:00:00:00:00:00

# Actual Behavior
do nothing

# Steps to Reproduce the Problem

1. create a pod with mellanox cx-6 vf
2. delete this pod

# Q
What is the effect?
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/handler.go#L426-L431

After change deviceID from `00:af:0x.x` to `mellanox.com/cx5_sriov_switchdev:`
will do nothing when delete pod with sriov nic
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/ovs_linux.go#L152-L174

Should we delete this part code, when I use kata with kube-ovn sriov, always get old mac if don't set mac to 00:00:00:00:00:00

**Comment by oilbeater** [comment]
@fanriming can you take a look at this?

**Comment by fanriming** [comment]
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/handler.go#L426-L431
上面这段代码应该是为了防止 deviceID 为空时 netlink 被删除的问题，但我觉得 deviceID 为空应该不需要做任何处理，所以下面的代码应该也是可以删除的
https://github.com/kubeovn/kube-ovn/blob/dbe4ebb31496d959768dd6d451939b11f831856a/pkg/daemon/ovs_linux.go#L152-L163

@oilbeater @xujunjie-cover

**Comment by xujunjie-cover** [comment]
OK，那上面那段进行删除，然后下面这个修改如下如何。
``` go
	if deviceID == "" {
		hostLink, err := netlink.LinkByName(nicName)
		if err != nil {
			// If link already not exists, return quietly
			if _, ok := err.(netlink.LinkNotFoundError); ok {
				return nil
			}
			return fmt.Errorf("find host link %s failed %v", nicName, err)
		}
		if err = netlink.LinkDel(hostLink); err != nil {
			return fmt.Errorf("delete host link %s failed %v", hostLink, err)
		}
	} else if pciAddrRegexp.MatchString(deviceID) {
		// Ret VF index from PCI
		vfIndex, err := sriovnet.GetVfIndexByPciAddress(deviceID)
		if err != nil {
			klog.Errorf("failed to get vf %s index, %v", deviceID, err)
			return err
		}
		if err = setVfMac(deviceID, vfIndex, "00:00:00:00:00:00"); err != nil {
			return err
		}
	}
```
改为
``` go
	if deviceID != "" && pciAddrRegexp.MatchString(deviceID) {
		// Ret VF index from PCI
		vfIndex, err := sriovnet.GetVfIndexByPciAddress(deviceID)
		if err != nil {
			klog.Errorf("failed to get vf %s index, %v", deviceID, err)
			return err
		}
		if err = setVfMac(deviceID, vfIndex, "00:00:00:00:00:00"); err != nil {
			return err
		}
	} 
```

**Comment by fanriming** [comment]
想了下，我之前的回复还是欠考虑了一些情况：
某些条件下，容器确实使用了 vf，但 delete pod 时 cni 没有将 deviceID 传入，当deviceID为空，后续逻辑会当成是 veth 或 internal 类型的 port 执行删除，这会导致 vf 误删。所以这个判断条件还是要保留的，但可以优化为更优雅的方式而不是给 DeviceID 强行赋值：

```go
 // check if it's a sriov device 
 for _, container := range pod.Spec.Containers { 
 	if _, ok := container.Resources.Requests[util.SRIOVResourceName]; ok { 
 		podRequest.DeviceID = util.SRIOVResourceName 
 	} 
 }
```

可以修改为
```go
nicType := pod.Annotations[util.PodNicAnnotation]
for _, container := range pod.Spec.Containers { 
 	if _, ok := container.Resources.Requests[util.SRIOVResourceName]; ok { 
 		nicType = util.OffloadType
                break
 	} 
}
```
deleteNic 方法中可以修改为使用 nicType 作为判断条件，对资源进行合理的回收动作：
```go
if nicType == util.OffloadType {
...
}else if deviceID != "" && pciAddrRegexp.MatchString(deviceID) {
...
}
```

**Comment by xujunjie-cover** [comment]
@fanriming 好的，明白了，需要考虑不存在 deviceID 的情况。最后想问一下，这种情况通常什么时候会出现呢？使用 dockershim 吗？

**Comment by xujunjie-cover** [comment]
@fanriming CNI 删除网卡应该是依次进行删除，多个网卡时多次调用 CNI 在 NetNS 内删除网卡。如果通过 SRIOVResourceName 来进行判断本次删除的网卡是否是 Sriov 网卡，当 pod 普通网卡和 Sriov 网卡同时存在时，处理普通网卡时也会按照 SRIOV 网卡进行处理。
所以我认为还是最好通过 deviceID 来进行判断本次删除是否是 Sriov 网卡，那本次提交删除那段应该就可以了。
谢谢

**Comment by oilbeater** [comment]
我记得早些时候在多次 del pod 时可能没有带 deviceID，不能完全依赖 multus 传进来你的 deviceID，最好可以通过容器内网卡类型判断是否需要删除，我这边看 veth 类型的 netlink.type 是 veth，sriov 我这里没有环境不清楚会是什么，可以看下能否通过这个值进行判断

**Comment by xujunjie-cover** [comment]
> 我记得早些时候在多次 del pod 时可能没有带 deviceID，不能完全依赖 multus 传进来你的 deviceID，最好可以通过容器内网卡类型判断是否需要删除，我这边看 veth 类型的 netlink.type 是 veth，sriov 我这里没有环境不清楚会是什么，可以看下能否通过这个值进行判断

好主意，我看了一下，是 vf 的 driver，确实可以通过 driver 来判断，可以操作非 veth or internal 的网卡不删除。
```
# ip netns exec  cni-0e596300-80f5-d046-cbd7-bdeb15d04788  ethtool -i net1 
driver: mlx5_core
version: 5.7-1.0.2
firmware-version: 22.34.1002 (MT_0000000536)
expansion-rom-version: 
bus-info: 0000:af:00.6
```

**Comment by xujunjie-cover** [comment]
@fanriming @oilbeater  updated. help review. Thanks
https://github.com/kubeovn/kube-ovn/pull/1904
