### ISSUE TITLE
fip解绑后，之前关于此fip的nat session 仍然处于保活状态，会有未知流量鲁莽地尝试传输强制保持风险

### ISSUE THREAD

**Issue by flyfish002** [kubeovn/kube-ovn#1919]
问题 
[1]   绑定fip
<1-1> 查看绑定fip
kubectl   get  fip
NAME                                   EIP                                                             V4IP            INTERNALIP        V6IP   READY   NATGWDP
eiprule-856rx2h3ceebnkyqjbnjb          eip-3u7330j1ceebnnqkbcnkc                                       172.16.32.168   172.16.0.3               true    subnet-1xf7a8i2ceebnnqejzjak
<1-2>   测试映射生效
<1-3>  fip 内网ip 为 linux vm, 开放 22 端口，进入登录建连，使会话保活
<1-4>   解绑fip
<1-5>   之前登录建连的会话会一直生效

[2]本人解决方法
<2-1>进入 vpc-nat-gw pod, 安装 contrack 
apk   add   conntrack-tools
<2-2>解绑ip后强行删除对指定弹性ip的session条目
conntrack  -D     -t tcp    --dst  弹性ip
<2-3>执行后之前保持会话立即断连

[3]问题反馈
希望新版本的 vpc-nat-gw 解决这个问题并合入主代码

**Comment by oilbeater** [comment]
感谢发现问题，能不能提个 pr 帮忙修一下这个问题

**Comment by shane965** [comment]
> 感谢发现问题，能不能提个 pr 帮忙修一下这个问题

可以，等我们测试通过后再提交pr
