### ISSUE TITLE
kubevirt 场景下，vm获得分配ip又立即释放

### ISSUE THREAD

**Issue by flyfish002** [kubeovn/kube-ovn#1931]
版本:  v.1.10.0 
正常在部署完的  kubevirt 场景下分配一个 192.168.0.3 ip 给虚拟机又立即释放，新创建一台虚机，随机获取 192.168.0.5 又表现正常

异常虚机获得ip日志
` kubectl  logs  kube-ovn-controller-68d46cc55f-rddnk  -n  kube-system  |  tac |  more  |  grep   192.168.0.3`
I0923 14:26:29.533918       7 ipam.go:79] allocate v4 192.168.0.3 mac 00:00:00:35:d7:52 for project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4
I0923 14:26:29.438909       7 subnet.go:453] release v4 192.168.0.3 mac 00:00:00:35:d7:52 for project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-b9rvz, add ip to released list
I0923 14:22:54.890047       7 ipam.go:79] allocate v4 192.168.0.3 mac 00:00:00:35:d7:52 for project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-b9rvz
I0923 14:22:54.815403       7 subnet.go:453] release v4 192.168.0.3 mac 00:00:00:35:D7:52 for project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-ht55s, add ip to released list

正常虚机获得ip情况
` kubectl  logs  kube-ovn-controller-68d46cc55f-rddnk  -n  kube-system  |  tac |  more  |  grep   192.168.0.5`
I0923 14:48:05.618127       7 ipam.go:51] allocate v4 192.168.0.5 v6  mac 00:00:00:3F:DD:2D for project-4/virt-launcher-vm-ves7dsa0ceebycneeannb-v759f

异常的包含pod的vm启动过程日志
`kubectl  describe  pod  virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4     -n   project-4`
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hotplug-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                 From               Message
  Normal   Scheduled               55m                 default-scheduler  Successfully assigned project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4 to kcp02
  Normal   SuccessfulMountVolume   55m                 kubelet            MapVolume.MapPodDevice succeeded for volume "pvc-2bb18b33-7afc-444c-b5a6-d249fd5296e7" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-2bb18b33-7afc-444c-b5a6-d249fd5296e7/dev"
  Normal   SuccessfulMountVolume   55m                 kubelet            MapVolume.MapPodDevice succeeded for volume "pvc-2bb18b33-7afc-444c-b5a6-d249fd5296e7" volumeMapPath "/var/lib/kubelet/pods/2ac83538-3f53-40b1-9196-ff371e0457ba/volumeDevices/kubernetes.io~csi"
  Warning  FailedCreatePodSandBox  51m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ecea34beeffb4c3d516e311cc3b77ef32bc0594c8ab221eb9fe9845d47b914be" network for pod "virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4": networkPlugin cni failed to set up pod "virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4_project-4" network: [project-4/virt-launcher-vm-26k5hxsbceebqajkayykq-5cfd4/:kube-ovn]: error adding container to network "kube-ovn": request ip return 500 configure nic failed 192.168.0.3 network not ready after 200 ping 192.168.0.1

想请问下官方，触发分配ip 又立即释放的触发机制是什么？ 方便后期定位问题

**Comment by oilbeater** [comment]
一般是有 delete 事件或者 pod 进入 terminating 状态会触发释放流程，需要看一下这个 pod 其他相关的日志来判断过程中发生了什么

**Comment by hongzhen-ma** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/67130442/209602074-6b06e8e6-caf5-42f4-8b9c-543fa31166ee.png">

这个可能删除 vm的时候，上一个删除的vm 影响了新创建的vm lsp

这个问题跟 https://github.com/kubeovn/kube-ovn/issues/2162 类似，应该在以下PR修改了
https://github.com/kubeovn/kube-ovn/pull/2190
