### ISSUE TITLE
分配EIP后pod无法解析dns

### ISSUE THREAD

**Issue by foxiyu** [kubeovn/kube-ovn#1934]
# Expected Behavior
分配EIP后pod也可以解析dns

# Actual Behavior
分配EIP后pod无法解析dns

# Steps to Reproduce the Problem

1.如图一 创建两个pod 一个不分配eip 另一个分配eip
2.分别在pod中检查网络情况 发现第二个pod无法解析dns 如图二

图一：
![image](http://imgsrc.baidu.com/super/pic/item/7e3e6709c93d70cf3604f2d2bddcd100bba12b76.jpg)
图二：
![image](http://imgsrc.baidu.com/super/pic/item/b3b7d0a20cf431ad0b501be60e36acaf2fdd986b.jpg)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (1.24.2)
  ```

- kube-ovn version:
  
  ```
  (1.10.6)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (Ubuntu 22.04.1 LTS 5.15.0-48-generic)
  ```

**Comment by oilbeater** [comment]
需要检查一下 kube-ovn-controller 的参数 enable-lb 是否设置成了 false，false 情况下目前 eip 会和 service 功能冲突

**Comment by foxiyu** [comment]
值是true(--enable-lb=true)  我也尝试过false 问题是一样的

**Comment by oilbeater** [comment]
kubectl ko trace 看下访问 dns 的路径是不是有问题

**Comment by foxiyu** [comment]
执行完报错
root@xxxxx:~/kubeadm_init# kubectl ko trace
/usr/local/bin/kubectl-ko: line 171: $1: unbound variable

删除/usr/local/bin/kubectl-ko 我重新下载了一下安装脚本 安装后也还是这样

**Comment by bobz965** [comment]
> 执行完报错 root@xxxxx:~/kubeadm_init# kubectl ko trace /usr/local/bin/kubectl-ko: line 171: $1: unbound variable
> 
> 删除/usr/local/bin/kubectl-ko 我重新下载了一下安装脚本 安装后也还是这样

如果enable-lb=false，
估计跟pod 启用eip后不在port-group 有关系， 导致该pod 不会被策略路由匹配到，进而不会被转发到node上，最后没办法访问svc。 

enable-lb=true，感觉应该可以通过switch 的lb 前端vip访问svc吧。

**Comment by oilbeater** [comment]
https://github.com/kubeovn/kube-ovn/pull/2733 修复了这个问题
