### ISSUE TITLE
Failed to established vpc peering connection by IPv6 address

### ISSUE THREAD

**Issue by fatcha14** [kubeovn/kube-ovn#1961]
Failed to established vpc peering connection by IPv6 address, thought I was using an incorrect IPv6 address. But after checking the log, it looks like that the IPv6 address cannot be paresed as an argument by ovn-nbctl without any quotes. 

log: 

failed to create peer router port for vpc vpc-2, ovn-nbctl: 2001:db8:0:0:34f4:0:0:121/64: unexpected ":" parsing set of 1 or more strings

I have tested the following command with quotes surrounding the IPv6 address which successfully added the logical router port:
ovn-nbctl --timeout=60 --no-wait unset logical_router_port vpc-2-vpc-1 networks='"2001:db8:0:0:34f4:0:0:121/64"'

**Comment by oilbeater** [comment]
@fatcha14 Thanks for report, we will look at it soon

**Comment by hongzhen-ma** [comment]
已回合 release-1.10 和 release-1.9 分支

**Comment by lynn901** [comment]
基于1.11分支测试了一下vpc peer双栈的场景，这部分代码还是有点问题，已修改自测，
