### ISSUE TITLE
使用EIP或SNAT 功能可能会导致Tomcat容器 自动关闭

### ISSUE THREAD

**Issue by foxiyu** [kubeovn/kube-ovn#1966]
使用Tomcat容器部署一个多线程项目 大概每五分钟会出现这个问题
尝试过调整tomcat启动内存 并没有解决这个问题
停止使用EIP或SNAT 容器稳定运行

错误日志：
Oct 15, 2022 11:50:04 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-apr-8080"]
Oct 15, 2022 11:50:04 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Catalina]
[localhost-startStop-2] INFO com.alibaba.druid.pool.DruidDataSource - {dataSource-6} closed
[localhost-startStop-2] INFO com.alibaba.druid.pool.DruidDataSource - {dataSource-2} closed
[localhost-startStop-2] INFO com.alibaba.druid.pool.DruidDataSource - {dataSource-5} closed
.......
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.sqlite.JDBC] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Thread-2] but has failed to stop it. This is very likely to create a memory leak.
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
Oct 15, 2022 11:50:04 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Thread-22] but has failed to stop it. This is very likely to create a memory leak.
......
Oct 15, 2022 11:50:04 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-apr-8080"]
Oct 15, 2022 11:50:04 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-apr-8080"]

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (v1.24.2)
  ```

- kube-ovn version:
  
  ```
  (v1.10.6)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (ubuntu22.04 LTS)
  ```

**Comment by oilbeater** [comment]
看上去像连接没有响应了，请问这个是不是长连接出现的问题，此外是否可以调整相关连接超时时间来避免这个问题

**Comment by foxiyu** [comment]
已找到问题 因为添加livenessProbe端口检测导致的问题 可能是因为配置了EIP后 原podIP不能使用导致触发了重启
