### ISSUE TITLE
kube-ovn deployment failed

### ISSUE THREAD

**Issue by zcola** [kubeovn/kube-ovn#1982]
kubernetes 1.23.13
cri-o 1.25
# Steps to Reproduce the Problem
```
daemonset.apps/kube-ovn-pinger created
deployment.apps/kube-ovn-monitor created
service/kube-ovn-monitor created
service/kube-ovn-pinger created
service/kube-ovn-controller created
service/kube-ovn-cni created
+ kubectl rollout status deployment/kube-ovn-controller -n kube-system --timeout 300s
Waiting for deployment "kube-ovn-controller" rollout to finish: 0 of 2 updated replicas are available...
```

ovn-central
```
W1021 15:30:08.663624     170 ovn.go:394] no available northd leader, try to release the lock
E1021 15:30:08.666397     170 ovn.go:279] stealLock err exit status 1
E1021 15:30:23.714213     170 ovn.go:163] CheckNbIsLeader execute err exit status 1 error msg ovsdb-client: failed to connect to "tcp:127.0.0.1:6641" (Connection refused)
E1021 15:30:23.716391     170 ovn.go:201] CheckSbIsLeader execute err exit status 1 error msg ovsdb-client: failed to connect to "tcp:127.0.0.1:6642" (Connection refused)
W1021 15:30:23.725440     170 ovn.go:394] no available northd leader, try to release the lock
E1021 15:30:23.727549     170 ovn.go:279] stealLock err exit status 1
E1021 15:30:38.784875     170 ovn.go:163] CheckNbIsLeader execute err exit status 1 error msg ovsdb-client: failed to connect to "tcp:127.0.0.1:6641" (Connection refused)
E1021 15:30:38.786918     170 ovn.go:201] CheckSbIsLeader execute err exit status 1 error msg ovsdb-client: failed to connect to "tcp:127.0.0.1:6642" (Connection refused)
W1021 15:30:38.796653     170 ovn.go:394] no available northd leader, try to release the lock
E1021 15:30:38.798727     170 ovn.go:279] stealLock err exit status 1
~# kubectl logs  -n kube-system ovn-central-58ddc4dc7b-jpwht
```

 kube-ovn-controller not output log

Enter the container to run `/kube-ovn/kube-ovn-controller-healthcheck` There is no detailed log in the error output
```
Warning  Unhealthy  45m                   kubelet            Readiness probe failed:
  Warning  Unhealthy  45m (x2 over 45m)     kubelet            Readiness probe errored: rpc error: code = NotFound desc = container is not created or running: checking if PID of 88ec0c264c66ded9806a0457e436d296656d1314597b4650246ddfee35d87be2 is running failed: open /proc/10947/stat: no such file or directory: container process not found
  Normal   Killing    45m                   kubelet            Container kube-ovn-controller failed liveness probe, will be restarted
  Normal   Started    45m (x2 over 54m)     kubelet            Started container kube-ovn-controller
  Normal   Pulled     45m (x2 over 54m)     kubelet            Container image "ndsda_docker.io/kubeovn/kube-ovn:v1.10.6" already present on machine
  Normal   Created    45m (x2 over 54m)     kubelet            Created container kube-ovn-controller
  Warning  Unhealthy  8m36s (x57 over 53m)  kubelet            Readiness probe failed: command timed out
  Warning  Unhealthy  4m15s (x26 over 48m)  kubelet            Liveness probe failed: command timed out
```

**Comment by dmd17** [comment]
I have the same issue now, using Kube-OVN 1.12 on Ubuntu 20.04.
OVN central is having the same problem.

Was there a resolution?

**Comment by zhangzujian** [comment]
@dmd17 It seems that OVN NB/SB are down. Please check the following log files on the node:

/var/log/ovn/ovsdb-server-nb.log
/var/log/ovn/ovsdb-server-sb.log

**Comment by dmd17** [comment]
[ovn-controller.log](https://github.com/kubeovn/kube-ovn/files/10780588/ovn-controller.log)
[ovn-northd.log](https://github.com/kubeovn/kube-ovn/files/10780590/ovn-northd.log)
[ovsdb-server-nb.log](https://github.com/kubeovn/kube-ovn/files/10780592/ovsdb-server-nb.log)
[ovsdb-server-sb.log](https://github.com/kubeovn/kube-ovn/files/10780594/ovsdb-server-sb.log)

I don't see anything unusual, except that the OVN-central pod keeps restarting. Here is the log of the pod.

root@sens0:/var/log/ovn# kubectl -n kube-system logs ovn-central-7c99c9c64d-lkgxc
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
 * Starting ovsdb-nb
 * Starting ovsdb-sb
 * Starting ovn-northd
I0220 07:33:40.488757      66 ovn.go:93] no --kubeconfig, use in-cluster kubernetes config
W0220 07:33:40.574621      66 ovn.go:355] no available northd leader, try to release the lock
E0220 07:33:41.578828      66 ovn.go:237] stealLock err signal: alarm clock
W0220 07:33:56.710624      66 ovn.go:355] no available northd leader, try to release the lock
E0220 07:33:57.715106      66 ovn.go:237] stealLock err signal: alarm clock

**Comment by dmd17** [comment]
Looks like ovn-healthcheck.sh script is failing

When I try to execute these commands from inside ovn-central pod...

root@sens0:/kube-ovn# ovn-appctl -t /var/run/ovn/ovnsb_db.ctl cluster/status OVN_Southbound
"cluster/status" is not a valid command (use "list-commands" to see a list of valid commands)
ovn-appctl: /var/run/ovn/ovnsb_db.ctl: server returned an error

root@sens0:/kube-ovn# ovn-appctl -t /var/run/ovn/ovnsb_db.ctl list-commands                
The available commands are:
  coverage/read-counter   COUNTER
  coverage/show           
  exit                    
  list-commands           
  memory/show             
  ovsdb-server/add-db     DB
  ovsdb-server/add-remote REMOTE
  ovsdb-server/compact    
  ovsdb-server/connect-active-ovsdb-server 
  ovsdb-server/disable-monitor-cond 
  ovsdb-server/disconnect-active-ovsdb-server 
  ovsdb-server/get-active-ovsdb-server 
  ovsdb-server/get-db-storage-status DB
  ovsdb-server/get-sync-exclude-tables 
  ovsdb-server/list-dbs   
  ovsdb-server/list-remotes 
  ovsdb-server/memory-trim-on-compaction on|off
  ovsdb-server/perf-counters-clear 
  ovsdb-server/perf-counters-show 
  ovsdb-server/reconnect  
  ovsdb-server/remove-db  DB
  ovsdb-server/remove-remote REMOTE
  ovsdb-server/set-active-ovsdb-server 
  ovsdb-server/set-active-ovsdb-server-probe-interval 
  ovsdb-server/set-sync-exclude-tables 
  ovsdb-server/sync-status 
  ovsdb-server/tlog-list  
  ovsdb-server/tlog-set   DB:TABLE on|off
  version                 
  vlog/close              
  vlog/disable-rate-limit [module]...
  vlog/enable-rate-limit  [module]...
  vlog/list               
  vlog/list-pattern       
  vlog/reopen             
  vlog/set                {spec | PATTERN:destination:pattern}

**Comment by dmd17** [comment]
I edited the Deployment of ovn-central to not run start-db.sh on start and went into the container and ran it manually.

root@sens0:/kube-ovn# ./start-db.sh 
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
ovsdb-tool: ovsdb error: /etc/ovn/ovnnb_db.db: cannot identify file type
detected database corruption for file /etc/ovn/ovnnb_db.db, rebuild it.
ovsdb-tool: /etc/ovn/ovnnb_db.db: not a clustered database
failed to get sid from nb db file /etc/ovn/ovnnb_db.db
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
 
 
then i deleted /etc/ovn/ovnnb_db.db and ran start-db.sh again

root@sens0:/kube-ovn# ./start-db.sh 
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
[{"uuid":["uuid","c4cadb3d-ff38-45ca-8d99-2e0d088d446e"]},{"uuid":["uuid","19e0bfa3-d561-4866-a691-bd2950bce3b3"]}]
[{"uuid":["uuid","8cb3e475-ba2e-42e3-8ee8-fe13faa1d041"]},{"uuid":["uuid","571d02ff-cdc1-4bb1-bd39-41357dcae958"]}]
ovsdb-client: failed to connect to "tcp:[128.178.116.221]:6641" (Connection refused)
 * Creating cluster database /etc/ovn/ovnnb_db.db
 * Starting ovsdb-nb
2023-02-20T12:42:00Z|00001|reconnect|INFO|unix:/var/run/ovn/ovnnb_db.sock: connecting...
2023-02-20T12:42:00Z|00002|reconnect|INFO|unix:/var/run/ovn/ovnnb_db.sock: connected
 * Waiting for OVN_Northbound to come up
 * Creating cluster database /etc/ovn/ovnsb_db.db
 * Starting ovsdb-sb
2023-02-20T12:42:00Z|00001|reconnect|INFO|unix:/var/run/ovn/ovnsb_db.sock: connecting...
2023-02-20T12:42:00Z|00002|reconnect|INFO|unix:/var/run/ovn/ovnsb_db.sock: connected
 * Waiting for OVN_Southbound to come up
 * Starting ovn-northd


now it worked fine and all the other pods (kube-ovn-controller and kube-ovn-cni) are also healthy.

what happened...?

i think there was bad/corrupt image of kube-ovn:v1.12.0 and it was cached locally. i deleted it with `crictl rmi image_id` and then redeployed the Helm chart.

**Comment by zhangzujian** [comment]
@dmd17 Thanks for the information! Version 1.12.0 is in development at the moment. Stable releases (v1.11/v1.10) are suggested.
