### ISSUE TITLE
There is something missing for DPDK Mellanox PMD

### ISSUE THREAD

**Issue by carezkh** [kubeovn/kube-ovn#1995]
# Expected Behavior
Mellanox NICs can be used for DPDK tunnel interface.

# Actual Behavior

- There are some libs missing for Mellanox PMD when compiling DPDK source code in Kube-OVN 1.10.6
- The dirver `vfio-pci` is fixed in script `start-ovs-dpdk-v2.sh`, but for Mellanox, mlx*-pci and MLNX-OFED driver are required.

# Steps to Reproduce the Problem
1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
 
 ```
 Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
  v1.10.6
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

```
"Ubuntu 22.04 LTS"
5.15.0-52-generic
```

I have a [patch](https://github.com/carezkh/kube-ovn/commit/a541a12a8ef2a3dd3e158c0aab3b56dc00e06886) to add libs required by DPDK Mellanox PMD.

In this patch:
- I removed the fixed `vfio-pci` driver in script `start-ovs-dpdk-v2.sh`. The driver can be configured by users, and for a Mellanox interface, [MLNX-OFED](https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/) driver is required!
- I added libs `libibverbs1`, `libibverbs-dev` and `ibverbs-providers` for DPDK Mellanox PMD, the driver `mlx*-pci` will be configured automatically when running `meson build`.
- I updated OVS 2.16, from commit `c50a0f080d95e9027b7ba3a70150b02c2377c721` to `1570924c3f83851f39f56e3363050b70ba1aafb0`. Because the function [inet_parse_active](https://github.com/openvswitch/ovs/blob/c50a0f080d95e9027b7ba3a70150b02c2377c721/lib/socket-util.h#L51-L52) definition in `c50a...` is not compatible with [OVN branch-21.06](https://github.com/kubeovn/ovn/blob/8146578592200c7b732bca8ab43be05a84e34269/utilities/ovn-nbctl.c#L2733-L2737).

I built a container image `carezkh/kube-ovn:v1.10.6-dpdk` from the patch, and it worked for Mellanox NICs.

**Comment by oilbeater** [comment]
@carezkh Thanks for the detailed analysis! Can you make a pr about this fix?

**Comment by carezkh** [comment]
I'm glad to do this! And feel free to comment :)
