### ISSUE TITLE
Connect Multiple Cluster with Submariner: Destination host unreachable

### ISSUE THREAD

**Issue by s-mansouri** [kubeovn/kube-ovn#2000]
I connect two different clusters with submariner based on [this](https://github.com/kubeovn/kube-ovn/blob/master/docs/cluster-submariner.md) document but when I ping the IP pod of another cluster from the local cluster, it gives Destination Host Unreachable 
```
root:~# ping 12.16.0.7
PING 12.16.0.7 (12.16.0.7) 56(84) bytes of data.
From 241.231.182.235 icmp_seq=1 Destination Host Unreachable
From 241.231.182.235 icmp_seq=2 Destination Host Unreachable
From 241.231.182.235 icmp_seq=3 Destination Host Unreachable
```
# Additional Info

- Kubernetes version: 1.25.2

- kube-ovn version: 1.10.6

- operation-system/kernel version:
```
Debian GNU/Linux 11 (bullseye)
5.10.0-14-amd64
```

**Comment by oilbeater** [comment]
Please follow the latest docs and check if it works. https://kubeovn.github.io/docs/v1.12.x/en/advance/with-submariner/
