### ISSUE TITLE
Set socket priority and vlan_qos

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2009]
In TSN(Time-Sensitive Networking) scenario, application, os and hardware work together to achieve very low transmission latency and high availability. 

The traditional workflow may look like this:
1. Application use `SO_PRIORITY` argument in `setsockopt` to set socket priority which will set the `priority` field in `sk_buff` structure.
2. Use `vconfig set_egress_map` command to map skb-priority to vlan-qos, which is the `pcp` field in vlan 802.1Q header.
3. Underlay switch will use the `pcp` value to QoS packets.

In Kube-OVN, we need to implement the Step 2 above to achieve same function that map skb-priority to vlan-qos.
From [ovs-fields.7](http://www.openvswitch.org/support/dist-docs/ovs-fields.7.txt) there is `skb_priority` to match however the doc said it's not supported. We need to try if it can work.

From [ovs-ofctl.8](https://www.openvswitch.org/support/dist-docs-2.5/ovs-ofctl.8.html) the `mod_vlan_pcp` action can be used to modify vlan priority.

**Comment by hongzhen-ma** [comment]
https://confluence.alauda.cn/pages/viewpage.action?pageId=130575555
