### ISSUE TITLE
集群外部无法访问集群内部分配的vip

### ISSUE THREAD

**Issue by hejiahang929** [kubeovn/kube-ovn#2022]
### k8s环境：
k8s version: v1.22.7
kube-ovn version: v1.10.4-no-avx512

### 操作：
使用kubevirt在集群里面创建了KVM虚拟机，同时使用vips.kubeovn.io资源分配了一个vip(KVM ip和vip属于同一个subnet) ，  在KVM虚拟机里面通过部署keepalive给KVM虚拟机配置了vip(eth0有两个ip，一个原来的ip，一个vip)， 集群外部通过路由方式打通和集群内部Overlay网络的通信;

### 问题描述:
集群里面可以访问KVM的ip以及vip， 集群外部只能访问到KVM的ip，却访问不了vip，抓包查看集群外部访问vip的时候，请求可以到kvm，响应的包从veth出来后就抓不到了，是kube-ovn这个版本不支持集群外部访问vip还是缺少其它什么配置吗？ 有什么办法可以满足集群外部访问集群内部vip的需求吗？ 谢谢

**Comment by hejiahang929** [comment]
目前发现使用分布式网关会有以上问题，因为是分布式网关，所以策略路由里面是根据不同的源ip走不同的宿主机流量出去，vip不在源ip列表里面。
更换为集中式网关就可以，因为集中式网关所有的源ip段都从集中式网关出去，不区分实际的ip

**Comment by bobz965** [comment]
默认vpc 比较特别一点，有port-group对应的策略路由。 自定义vpc 无该限制。 基于自定义vpc 无法满足场景需求么？
