### ISSUE TITLE
ipset KUBE-NODE-PORT-LOCAL-TCP does not exist

### ISSUE THREAD

**Issue by NoahLovesLife** [kubeovn/kube-ovn#2027]
I check `/var/log/kube-ovn/kube-ovn-cni.log` file and find these logs. What does this mean? Should I care about it?
![image](https://user-images.githubusercontent.com/84314029/200759112-ac812674-f3e2-49c1-9e37-c7496590902f.png)

**Comment by zhangzujian** [comment]
Which version are you using?

**Comment by NoahLovesLife** [comment]
```
kube-ovn: v1.10.6
kubernetes: v1.25.0
containerd: v1.6.9
```

**Comment by zhangzujian** [comment]
> ```
> kube-ovn: v1.10.6
> kubernetes: v1.25.0
> containerd: v1.6.9
> ```

Thanks for the information. One more thing, are you using iptables mode for kube-proxy?

**Comment by NoahLovesLife** [comment]
Yeah, I'm using iptables by default.
```
root @ k8smaster01 <~> [15:20:18] # curl localhost:10249/proxyMode; echo
iptables
```

**Comment by zhangzujian** [comment]
> Yeah, I'm using iptables by default.
> 
> ```
> root @ k8smaster01 <~> [15:20:18] # curl localhost:10249/proxyMode; echo
> iptables
> ```

The warning is for NodePort services with external traffic policy set to Local. Kube-OVN depends on the ipsets to keep the source IP address, while the ipsets only exist in IPVS mode.

Generally, the only thing you need to care about is that the log file (/var/log/kube-ovn/kube-ovn-cni.log) will take up more disk space. I have created a PR to fix the logging issue.

**Comment by NoahLovesLife** [comment]
Got it. Thanks!👍
