### ISSUE TITLE
Can we support OVS-DPDK on underlay network?

### ISSUE THREAD

**Issue by carezkh** [kubeovn/kube-ovn#2056]
### Feature request

I have tested the performance of Kube-OVN OVS-DPDK network with [Cloud Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor), and noticed that the TCP bandwidth between two CH VMs on the same host increased by nearly 4 times by enabling [TSO](https://docs.openvswitch.org/en/latest/topics/userspace-tso/#userspace-datapath-tso)!

Unfortunately, as the doc's [limitations](https://docs.openvswitch.org/en/latest/topics/userspace-tso/#limitations) said "_The current OvS userspace TSO implementation supports flat and VLAN networks only (i.e. no support for TSO over tunneled connection [VxLAN, GRE, IPinIP, etc.])_". And i have not seen any plan in OVS community to support userspace TSO over tunnel.

So, can we make some changes to adapt userspace TSO on Kube-OVN OVS-DPDK network? For example, using physical network just like [underlay network](https://kubeovn.github.io/docs/v1.10.x/en/start/underlay/) in Kube-OVN.

**Comment by oilbeater** [comment]
@carezkh Thanks for the analysis. It should be great to use OVS-DPDK for flat network. But for the ovn flat network implementation, it uses a separated ovs bridge to connect physical network and then use a pair of patch ports to connect this bridge with br-int. I am not sure if ovs-dpdk still work all in userspace if these two bridges are connected by patch ports

**Comment by carezkh** [comment]
@oilbeater  Thanks, and i'll give it a try!

Any suggestion or even patch would be appreciated!

**Comment by carezkh** [comment]
I followed the doc [Connecting VMs Using Tunnels (Userspace)](https://docs.openvswitch.org/en/latest/howto/userspace-tunneling/) to create ovs bridges `br-phy` and `br-int`. In order to enable TSO, i connected two bridges with patch ports instead of using VxLAN tunnel. The TCP segments between two vhost-user VMs on different host can be transmitted normally!

But i'm not familiar with OpenFlow, i have no idea on how to make changes in Kube-OVN.
