### ISSUE TITLE
Cilium/Tetragon 功能在KubeOVN下不可用，是否可以提供支持呢？

### ISSUE THREAD

**Issue by CraneRZz** [kubeovn/kube-ovn#2062]
### Feature request

Cilium Tetragon 是一个来自 Cilium 制造商的开源安全可观察性和运行时强制工具，它通过用户提供的配置来捕获不同的进程和网络事件类型 ，以启用内核中任意钩子点上的安全可观察性。

Tetragon可以独立运行，不依靠Cilium。经测试，在calico:v3.24.1和cilium:v1.12.1环境下可用，在kubeOVN:v1.10.6环境下不可用，捕获不到进程执行的事件。另外，我参照了KubeOVN集成Cilium的文档，完成了集成操作，但依然捕获不到进程执行的事件，无法复现Tetragon的demo操作。

可能是kubeOVN没有做相应的支持，我非常希望能够同时使用kubeOVN和Tetragon，所以恳请KubeOVN的开发大佬们能给我一些帮助或者建议！谢谢！

**Comment by oilbeater** [comment]
具体的复现步骤和详细的报错信息请发一下
