### ISSUE TITLE
Can not attach VF with driver mode vfio-pci

### ISSUE THREAD

**Issue by AyaSenri** [kubeovn/kube-ovn#2081]
# Expected Behavior
容器/虚拟机可以正常卸载运行在vfio-pci驱动的vf网卡上
# Actual Behavior
CNI获取VF设备时报错，并未走到vfio-pci驱动分支
# Steps to Reproduce the Problem
1. CX5网卡环境安装了卸载模式，且mlx5_core驱动的VF可以正常运行POD和卸载流量
2. 修改VF驱动为vfio-pci
3.创建POD和虚拟机，均无法创建，异常提示找不到VF设备

# Additional Info
kube-ovn-cni logs
```logs
I1125 07:24:21.015039 1108170 handler.go:77] add port request: {kube-ovn ovs-offload-pod-1 default ad806616c44569428f2323901b15842161c7c1a96588447a08a28325be96a97b /var/run/netns/1137c205-e593-4a18-90c5-869fc92135d2 eth0 default.default.ovn [] {[]  [] []}  0000:ca:00.6  }
I1125 07:24:21.021476 1108170 handler.go:248] create container interface eth0 mac 00:00:00:44:CA:D2, ip 10.128.0.26/16, cidr 10.128.0.0/16, gw 10.128.0.1, custom routes []
E1125 07:24:21.021530 1108170 ovs_linux.go:765] failed to get vf netdevice 0000:ca:00.6, cannot get a network device with pci address 0000:ca:00.6 stat /sys/bus/pci/devices/0000:ca:00.6/net: no such file or directory
E1125 07:24:21.021536 1108170 ovs_linux.go:70] failed to create sriov interfaces cannot get a network device with pci address 0000:ca:00.6 stat /sys/bus/pci/devices/0000:ca:00.6/net: no such file or directory
E1125 07:24:21.021545 1108170 handler.go:259] configure nic failed cannot get a network device with pci address 0000:ca:00.6 stat /sys/bus/pci/devices/0000:ca:00.6/net: no such file or directory

```
bind vfio-pci cmd
```logs
echo 0000:ca:00.6 > /sys/bus/pci/drivers/mlx5_core/unbind
echo 0000:ca:00.7 > /sys/bus/pci/drivers/mlx5_core/unbind
echo "15b3 1018" > /sys/bus/pci/drivers/vfio-pci/new_id
```

sriovdp
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [{
          "resourcePrefix": "mellanox.com",
          "resourceName": "cx5_sriov_switchdev",
          "selectors": {
                  "vendors": ["15b3"],
                  "devices": ["1018"],
                  "drivers": ["vfio-pci"]
              }
      },{
          "resourcePrefix": "mellanox.com",
          "resourceName": "cx5_sriov_pod",
          "selectors": {
                  "vendors": ["15b3"],
                  "devices": ["1018"],
                  "drivers": ["mlx5_core"]
              }
      }
      ]
    }
```

- kube-ovn version:
  v1.10.1

**Comment by oilbeater** [comment]
@fanriming 帮忙看下这个问题

**Comment by fanriming** [comment]
@AyaSenri pod 或者 vm 的 yaml 定义也发出来看看呢？

**Comment by AyaSenri** [comment]
@fanriming 
看代码是没走vfio的分支
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    v1.multus-cni.io/default-network: default/default
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        mellanox.com/cx5_sriov_switchdev: '1'
      limits:
        mellanox.com/cx5_sriov_switchdev: '1'
```

**Comment by fanriming** [comment]
> @fanriming 看代码是kube-ovn-cni中没走vfio的分支
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: nginx
>   annotations:
>     v1.multus-cni.io/default-network: default/default
> spec:
>   containers:
>   - name: nginx
>     image: nginx:alpine
>     resources:
>       requests:
>         mellanox.com/cx5_sriov_switchdev: '1'
>       limits:
>         mellanox.com/cx5_sriov_switchdev: '1'
> ```

主机对应目录 “/sys/bus/pci/drivers/vfio-pci” 有没有对应的deviceID (0000:ca:00.6)，如果没有的话尝试执行下面的命令进行绑定：
```
echo "vfio-pci" > /sys/bus/pci/devices/0000:ca:00.6/driver_override
echo 0000:ca:00.6 > /sys/bus/pci/drivers/vfio-pci/bind
```

**Comment by AyaSenri** [comment]
> > @fanriming 看代码是kube-ovn-cni中没走vfio的分支
> > ```yaml
> > apiVersion: v1
> > kind: Pod
> > metadata:
> >   name: nginx
> >   annotations:
> >     v1.multus-cni.io/default-network: default/default
> > spec:
> >   containers:
> >   - name: nginx
> >     image: nginx:alpine
> >     resources:
> >       requests:
> >         mellanox.com/cx5_sriov_switchdev: '1'
> >       limits:
> >         mellanox.com/cx5_sriov_switchdev: '1'
> > ```
> 
> 主机对应目录 “/sys/bus/pci/drivers/vfio-pci” 有没有对应的deviceID (0000:ca:00.6)，如果没有的话尝试执行下面的命令进行绑定：
> 
> ```
> echo "vfio-pci" > /sys/bus/pci/devices/0000:ca:00.6/driver_override
> echo 0000:ca:00.6 > /sys/bus/pci/drivers/vfio-pci/bind
> ```

vfio-pci目录下是有这个设备的，日志里是查询的net目录，我打过debug，函数setupSriovInterface的入参vfDriver传进来的driver是一个空值

**Comment by fanriming** [comment]
NetworkAttachmentDefinition

> > > @fanriming 看代码是kube-ovn-cni中没走vfio的分支
> > > ```yaml
> > > apiVersion: v1
> > > kind: Pod
> > > metadata:
> > >   name: nginx
> > >   annotations:
> > >     v1.multus-cni.io/default-network: default/default
> > > spec:
> > >   containers:
> > >   - name: nginx
> > >     image: nginx:alpine
> > >     resources:
> > >       requests:
> > >         mellanox.com/cx5_sriov_switchdev: '1'
> > >       limits:
> > >         mellanox.com/cx5_sriov_switchdev: '1'
> > > ```
> > 
> > 
> > 主机对应目录 “/sys/bus/pci/drivers/vfio-pci” 有没有对应的deviceID (0000:ca:00.6)，如果没有的话尝试执行下面的命令进行绑定：
> > ```
> > echo "vfio-pci" > /sys/bus/pci/devices/0000:ca:00.6/driver_override
> > echo 0000:ca:00.6 > /sys/bus/pci/drivers/vfio-pci/bind
> > ```
> 
> vfio-pci目录下是有这个设备的，报错日志里是查询的net目录，这个目录是走netdev分支 我打过debug，函数setupSriovInterface的入参vfDriver传进来的driver是一个空值

关联的 NetworkAttachmentDefinition 也发出来看看呢？
