### ISSUE TITLE
use kube-ovn on k3s

### ISSUE THREAD

**Issue by wangxg422** [kubeovn/kube-ovn#2082]
在k3s中使用kube-ovn作为CNI，当主机有两个网络接口时（10.30.0.0/16，192.168.1.0/24），当k3s安装时指定--node-ip为10.30.0.0/16网段的，安装kube-ovn后，10.30.0.0/16网口的80、443端口正常访问，192.168.1.0/24网口不能访问80、443端口。其他CNI无此问题。
![image](https://user-images.githubusercontent.com/35413234/203944889-260edfbe-df8b-4198-954a-bd316cc51f72.png)

**Comment by oilbeater** [comment]
kube-ovn 不会对主机网络进行额外操作，请检查是否存在地址冲突或监听相关问题。
