### ISSUE TITLE
ovn-cluster vpc eip(dnat_and_snat) can not access after restart kube-ovn-controller

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2090]
# Expected Behavior
ovn-cluster eip should work always well even if  kube-ovn-controller restart

# Actual Behavior
ovn-cluster eip ping failed after  kube-ovn-controller restart

# Steps to Reproduce the Problem
1. enable eip snat and create a pod with eip
``` bash
router faf4af20-49f3-4eed-9024-3267e6445c5a (ovn-cluster)
    port ovn-cluster-default-ecmp-subnet
        mac: "00:00:00:81:DF:C7"
        networks: ["192.168.0.1/24"]
    port ovn-cluster-ovn-default
        mac: "00:00:00:48:4E:37"
        networks: ["10.16.0.1/16"]
    port ovn-cluster-external204
        mac: "00:00:00:D9:91:AD"
        networks: ["10.5.204.101/24"]
        gateway chassis: [346243a1-cc27-4f16-a1e4-29569c50322b 826155af-a380-4099-be8f-f77df50da1e0 e7e9e036-32a2-4206-9a01-767b03e9f127]
    port ovn-cluster-join
        mac: "00:00:00:13:32:4F"
        networks: ["100.64.0.1/16"]
    nat 7fe2222d-716f-4afe-af37-77503a095e10
        external ip: "10.5.204.201"
        logical ip: "10.16.0.3"
        type: "dnat_and_snat"

# keep ping 10.5.204.201 from outside
```

2. restart kube-ovn-controller
3. you will see ping failed 

# Additional Info

- Kubernetes version:
  ```

# k get node -o wide
NAME        STATUS   ROLES                  AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION                CONTAINER-RUNTIME
pc-node-1   Ready    control-plane,master   108d   v1.23.7   10.5.32.51    <none>        CentOS Stream 8   5.4.207-1.el8.elrepo.x86_64   containerd://1.6.4
pc-node-2   Ready    control-plane,master   108d   v1.23.7   10.5.32.52    <none>        CentOS Stream 8   5.4.207-1.el8.elrepo.x86_64   containerd://1.6.4
pc-node-3   Ready    control-plane,master   108d   v1.23.7   10.5.32.53    <none>        CentOS Stream 8   5.4.207-1.el8.elrepo.x86_64   containerd://1.6.4
  ```

- kube-ovn version:
  
  ```
  master 
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  
"CentOS Stream 8"
5.4.207-1.el8.elrepo.x86_64
  ```

**Comment by bobz965** [comment]
only default vpc ovn-cluster has issue now，after this pr:  https://github.com/kubeovn/kube-ovn/pull/2083, i test restart kube-ovn-controller, make make sure that all policy routes (route id ) ralated to ovn-cluster not changed.  all policy route id not changed.  so the issue may  not  ralated with policy route.

**Comment by bobz965** [comment]
类似地情况，如果删掉了公网网桥。那么重新加回公网网桥后，所有vpc的面向公网连接的的lrp，lsp资源都需要重建才能恢复fip snat资源。

现在应该已经基本排除了重启kube-ovn-controller，动到默认vpc lrp的情况，可能是单独动到了lsp。 

自定义vpc eip snat资源目前无影响。

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/7c76aecb-bb34-402a-9414-d355afe6907e)


seems fixed

**Comment by bobz965** [comment]
> ![image](https://private-user-images.githubusercontent.com/7981158/250493249-7c76aecb-bb34-402a-9414-d355afe6907e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTQ4OTEsIm5iZiI6MTcwNjU5NDU5MSwicGF0aCI6Ii83OTgxMTU4LzI1MDQ5MzI0OS03Yzc2YWVjYi1iYjM0LTQwMmEtOTQxNC1kMzU1YWZlNjkwN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDYwMzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk3NjA2M2EwNjlmY2YyZGNlMTE2OTQ2MjA1MGI2NWU3Yzk2MjIxMGUyMjBiNjMzNDIzYmU1Yjg2NmYxMWFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0826E5x4-s0fx0b78o_Tj1yGoBP2NPTWyKYWvACcrEk)
> 
> seems fixed

当时测试 ovn-default 的 pod 配置 eip 以及 自定义 vpc 配置 eip 在 node 上 ping eip 都是可以用的，这个时候 1.12 还没发布 1.12.1.  

这个测试环境是一个 all in one 的 ubuntu pc。

也就是说 1.12.0 和 1.12.1 之间应该是可用的。

**Comment by bobz965** [comment]
默认 vpc 支持自定义添加路由，应该可以通过配置一下路由来保证 ovn eip snat fip 流量优先

``` bash



#### 默认vpc ovn eip 参考配置路由


kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: ovn-cluster
spec:
  namespaces:
  - default
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: <公网网关>
    policy: policyDst
  policyRoutes:
  - action: reroute
    match: ip4.src==10.16.0.0/16 && ip4.dst!=169.254.25.10 && ip4.dst!=10.96.0.0/12 && ip4.dst!=100.64.0.0/16
    nextHopIP: <公网网关>
    priority: 30001




过滤掉到 localdns ip， svc cidr ip, join ip,  
ip4.src==10.16.0.0/16 && ip4.dst!=169.254.25.10 && ip4.dst!=10.96.0.0/12 && ip4.dst!=100.64.0.0/16 && <k8s node ip>


priority: 30001 优先于 


root@empty:~/feat/kube-ovn# k ko nbctl lr-policy-list ovn-cluster
Routing Policies
     31000                            ip4.dst == 10.16.0.0/16           allow
     31000                           ip4.dst == 100.64.0.0/16           allow
     30000                              ip4.dst == 172.18.0.2         reroute                100.64.0.2
     30000                              ip4.dst == 172.18.0.3         reroute                100.64.0.3
     29000 ip4.src == $ovn.default.kube.ovn.control.plane_ip4         reroute                100.64.0.3
     29000        ip4.src == $ovn.default.kube.ovn.worker_ip4         reroute                100.64.0.2

以下路由

```

**Comment by a180285** [comment]
@bobz965 了解，看上去是把代码中的逻辑部分写成可额外配置的了，看上去应该问题不大
