### ISSUE TITLE
Link to download windows package

### ISSUE THREAD

**Issue by Rama-Krishna-P** [kubeovn/kube-ovn#2091]
Hi,

In the windows-support.md file there is a step to download Kube-OVN windows packages but there is no mention of any link from where I can download. Can anyone please help me to find the location from where I can download the windows packages

**Comment by zhangzujian** [comment]
The file has been uploaded to the release assets:
https://github.com/kubeovn/kube-ovn/releases/download/v1.10.7/kube-ovn-win64.zip

**Comment by Rama-Krishna-P** [comment]
Thank you very much for your support
