### ISSUE TITLE
ProviderNetwork 资源不停的被ovn-Controller和ovn-cni  patch

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#2115]
# Expected Behavior

ovn-cni和ovn-controller 不再patch  ProviderNetwork资源

# Actual Behavior

# Steps to Reproduce the Problem

Ovn-controller和ovn-cni 都会监听ProviderNetwork资源，
正常情况下，Ovn-controller  主要是会patch  ProviderNetwork 的status下的ready状态值，
node 节点的加入或者离开，该node上的ovn-cni 会patch  ProviderNetwork 资源下的整个status，包括其下ready值

不幸的是，某次加节点的时候不知道发生了什么，产生了下面的现象，Ovn-controller 一直patch status 下ready字段的值true，但是ovn-cni 却拿到ProviderNetwork里面status下的ready的值是false，然后把ProviderNetwork下status的ready字段值又patch成false，这样就会导致 read状态的值一直在true和false之前切换，不停的产生ProviderNetwork的事件，传递到集群所有node下的ovn-cni，这样导致apiserver的cpu压力飙升很高

# Additional Info

- Kubernetes version:

  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"
  ```

- kube-ovn version:
  
  ```
  v1.8.2
  ```

- operation-system/kernel version:
  
  ```
  "CentOS Linux 7 (Core)"
  ```

**Comment by wolgod** [comment]
如果我想临时解决这个问题有什么办法，应该怎么操作@zhangzujian

**Comment by zhangzujian** [comment]
> 如果我想临时解决这个问题有什么办法，应该怎么操作@zhangzujian

通过配置 kube-ovn-cni 的 node selector 或 node affinity，将 kube-ovn-cni 停掉后逐个启动。

kube-ovn-cni 停止期间，无法正常处理 pod 创建/删除。

**Comment by wolgod** [comment]
> > 如果我想临时解决这个问题有什么办法，应该怎么操作@zhangzujian
> 
> 通过配置 kube-ovn-cni 的 node selector 或 node affinity，将 kube-ovn-cni 停掉后逐个启动。
> 
> kube-ovn-cni 停止期间，无法正常处理 pod 创建/删除。

非常感谢您的答复，如果我把ovn-controller的副本缩为0，等一会再起来，不知道能否解决这个问题，如果能的话，停的期间会影响什么呢？
非常期待能得到那您的答复！
