### ISSUE TITLE
dockerhub 中 v1.8.2的镜像拉下来，启动之后内容却是v1.8.3的

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#2128]
# Expected Behavior
v1.8.2 镜像使用v1.8.2的tag
# Actual Behavior
<img width="734" alt="image" src="https://user-images.githubusercontent.com/4132442/205592302-b30778e6-c776-4e67-ab8a-fd0daed28105.png">

# Steps to Reproduce the Problem
  新的节点加入后拉下来的镜像tag是v1.8.2,但是内容却是v1.8.3的 
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/4132442/205592899-692301a0-a5ce-4449-ba46-eba894f33527.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4132442/205592946-759cdc4c-d141-4a3b-8a0c-6da929805565.png">

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:v1.20.1

 

- kube-ovn version: v1.8.2
  
 

- operation-system/kernel version: "CentOS Linux 7 (Core)"

**Comment by oilbeater** [comment]
1.8 早期版本已经不再维护，请使用 1.8 分支的最新版本
