### ISSUE TITLE
[install] does kube-ovn install script will install ovs in vm

### ISSUE THREAD

**Issue by Shoothzj** [kubeovn/kube-ovn#2149]
Hello, I want to know if `kube-ovn install script` will install ovs in vm using `apt-get` or `dnf`? Thanks in advance.
:)

**Comment by hongzhen-ma** [comment]
All the things about ovn/ovs is  build into image, which can be found in dist/image/Dockerfile.base
The install script for install ovn is  start-db.sh, script for ovs is start-ovs.sh. The script is in the same directory with install.sh.
