### ISSUE TITLE
Missing Documentation for Upgrade Version

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#2174]
### Feature request

As far as I search, I couldn't find any docs that explain step by step to doing upgrade version without interrupt existing workloads.  Did I missed somethings?

Thanks for any help

**Comment by oilbeater** [comment]
There is no official upgrade document now. We are still trying to find a way to standardize the upgrade process, maybe helm in later version. 

At the moment we usually do upgrade by diff the `install.sh` script between two versions and manually apply these diff in yamls and kubectl-ko. The order is the crds first, then ovn-central deployment, then ovs-ovn  daemonset (which will bring a short time of network brreak), then kube-ovn-controller and other component that not really impact the datapath like pinger, monitor and so.

**Comment by ikandars** [comment]
thanks @oilbeater
