### ISSUE TITLE
Support krew for the kubectl ko addon

### ISSUE THREAD

**Issue by JochenFriedrich** [kubeovn/kube-ovn#2179]
### Feature request

Support krew for the kubectl ko addon.
https://krew.sigs.k8s.io/

This would make installation of the addon easier, in particular if kubectl is used on a node different from the control plane.

**Comment by sober-wang** [comment]
I want to try. Can you assignees me?

**Comment by sober-wang** [comment]
https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/

maybe , we should open a github release package download page for  krw package manager.
At other issue  #2354  can also reuse this release download page 
<img width="920" alt="image" src="https://user-images.githubusercontent.com/35804630/223932372-dba3abb4-cdc5-49bd-90c8-074040c2d1f7.png">

**Comment by sober-wang** [comment]
this release tar package should incloud [dist/images/kubectl-ko](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/kubectl-ko) and [LICENSE](https://github.com/kubeovn/kube-ovn/blob/master/LICENSE) 

```shell
[root@localhost dir]# tar tf kubectl-ko.tar.gz
kubectl-ko
LICENSE
```

I'll create a index file in [krew.git](https://github.com/kubernetes-sigs/krew-index.git). it's `ko.yaml`
