### ISSUE TITLE
pod绑定eip导致当前网络不可用

### ISSUE THREAD

**Issue by llhed** [kubeovn/kube-ovn#2184]
使用POD绑定EIP功能，参照相关章节配置

![image](https://user-images.githubusercontent.com/6269589/209032384-647a890c-5899-402e-9b85-f75cc39ad9d5.png)

执行这个cm，当前的会话都会中断。。而且连不上去

只能换管理网网段登上去，把这个cm撤回才能重新登录。

该功能官网有这么一段说明：

![image](https://user-images.githubusercontent.com/6269589/209032696-7280d869-bb08-4bb6-962c-736edf4810f9.png)

节点的VirtualNetworkSwitch，必须是Open vSwitch吗？
而且需要把一个网卡bridged into the br-external bridge吗？

**Comment by bobz965** [comment]
你圈定的文字部分表示，如果要使用ovn L3 gw的功能，比如fip，snat，必须准备一张独立专用的的网卡用于构造运营商网桥，该网桥就是ovs网桥，对应的underlay 公网网段需要提前规划好，且和真实物理交换机上的配置保持一致。

该网桥也属于kube-ovn provider-network，vlan，（underlay）subnet 的业务覆盖范围。可以再参考下这些资源的准备和使用。

另外麻烦贴下在用的kube-ovn的版本。

**Comment by llhed** [comment]
1.10.6

**Comment by llhed** [comment]
![image](https://user-images.githubusercontent.com/6269589/209073655-270dfa12-06f5-4a16-8096-34e6c5c2ec03.png)
比如说，我物理网网卡是eno1，这样还得找一个独立的物理网卡eno2，然后bridged into the br-external，是这意思吧

**Comment by llhed** [comment]
还有一个问题，就是这个配置
![image](https://user-images.githubusercontent.com/6269589/209074092-10eb3bff-e136-4117-8e77-49318a70d9eb.png)
上面配置里，哪个地方会体现这个独立专用的网卡呢

**Comment by llhed** [comment]
external-gw-nic 这个配置项，应该就是所说的独立专用网卡的，无不是物理网的那张吧
