### ISSUE TITLE
配置 vpc-dns 的 Configmap 报错

### ISSUE THREAD

**Issue by WaterAndBread** [kubeovn/kube-ovn#2193]
直接使用文档内容 报错
![image](https://user-images.githubusercontent.com/27998792/209546046-7b46b88a-8095-4c18-afb3-460f49b4f110.png)

Error from server (BadRequest): error when creating "cn.yml": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found t, error found in #10 byte of ...|vpc-dns":true,"nad-n|..., bigger context ...|ata":{"coredns-vip":"10.96.0.3","enable-vpc-dns":true,"nad-name":"ovn-nad","nad-provider":"ovn-nad.d|...

- kube-ovn version:
  1.11.0
  ```

**Comment by WaterAndBread** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-config
  namespace: kube-system
data:
  coredns-vip: "10.233.0.3"
  enable-vpc-dns: "true"
  nad-name: "ovn-nad"
  nad-provider: "ovn-nad.default.ovn"
  coredns-template: "http://192.168.50.61:8097/coredns-template.yaml"

coredns-template.yaml  会有因为网络问题，无法下载。
正确方式如上，可以创建成功

**Comment by oilbeater** [comment]
@WaterAndBread 文档已修改，十分感谢
