### ISSUE TITLE
Cyclonus network policy e2e fail

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#2217]
# Expected Behavior

# Actual Behavior

The following e2e test cases fail:

```
2: should support a 'default-deny-all' policy
13: should stop enforcing policies after they are deleted    
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
 ```
 v1.8/v1.10
 ```

Not observed in master/v1.9.

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by changluyi** [comment]
2: should support a 'default-deny-all' policy
13: should stop enforcing policies after they are deleted    
出错是一个问题

怀疑是脚本本身的问题。
规则如下
![image](https://user-images.githubusercontent.com/47097611/211951131-e10c6e95-9609-45a7-bee4-b71b56ddd59c.png)

很明显应该是x namespace的pod 访问别的pod和被访问不通。

但脚本预期结果是X namespace的pod 访问别的pod和被访问不通。
![image](https://user-images.githubusercontent.com/47097611/211951323-a8637f36-ab36-49af-aaa1-9f1d285459c2.png)

**Comment by changluyi** [comment]
重新跑测试没问题。
![image](https://user-images.githubusercontent.com/47097611/213344108-1b958c64-4516-4992-aee7-9c6a7ae6837b.png)
![image](https://user-images.githubusercontent.com/47097611/213344131-ef5cac0d-69a2-4f60-a61c-012f7f9b7a12.png)

**Comment by zhangzujian** [comment]
Test case 12 timed out:

```txt
starting test case #12
time="2023-01-28T03:16:18Z" level=info msg="cluster state reset"
time="2023-01-28T03:16:21Z" level=info msg="cluster state verified"
time="2023-01-28T03:16:21Z" level=info msg="step 1: waiting 5 seconds for perturbation to take effect"
time="2023-01-28T03:16:26Z" level=info msg="running probe &{AllAvailable:true PortProtocol:<nil> Mode:service-name}"
time="2023-01-28T03:16:26Z" level=info msg="running kube probe on try 1"
time="2023-01-28T03:17:45Z" level=info msg="running kube probe on try 2"
```
