### ISSUE TITLE
不同vpc 使用相同ip地址段的subnet ，snat 功能无法使用

### ISSUE THREAD

**Issue by WaterAndBread** [kubeovn/kube-ovn#2219]
# Expected Behavior
创建了2个vpc  vpc2 vpc3 ,使用 相同地址段的subnet ，使用snat 后，发现 pod 无法ping 通外网
eip snat gw 等信息如下
![image](https://user-images.githubusercontent.com/27998792/210492865-4e5d7267-b1c9-41ea-b62b-5f64bba730b1.png)

![image](https://user-images.githubusercontent.com/27998792/210493280-a57cbf86-f542-4f81-a096-a2ed103b6fbd.png)

iptables 规则，在gw pod 里面确实有看到，但实际无效果。 有劳开发者验证一下。
**vpc2 相关yml 文件**
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc2-subnet2
spec:
  vpc: vpc2
  cidrBlock: 13.168.0.0/24
  gateway: 13.168.0.1
  default: false
  gatewayType: distributed
  natOutgoing: false
  protocol: IPv4
  namespaces:
    - vpc2
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc2
spec:
  namespaces:
  - vpc2
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: 13.168.0.254
    policy: policyDst
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw2
spec:
  vpc: vpc2
  subnet: vpc2-subnet2
  lanIp: 13.168.0.254
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: vpc2-eip
spec:
  natGwDp: gw2
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: vpc2-snat01
spec:
  eip: vpc2-eip
  internalCIDR: 13.168.0.0/24

---
apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: vpc2
  labels:
    name: busybox
spec:
  containers:
  - image:  mynet-tool:1.0
    name: busybox
    command:
      - sleep
      - "3600"
---
**vpc3 相关yml**
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc3-subnet3
spec:
  vpc: vpc3
  cidrBlock: 13.168.0.0/24
  gateway: 13.168.0.1
  default: false
  gatewayType: distributed
  natOutgoing: false
  protocol: IPv4
  namespaces:
    - vpc3
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc3
spec:
  namespaces:
  - vpc3
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: 13.168.0.254
    policy: policyDst
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw3
spec:
  vpc: vpc3
  subnet: vpc3-subnet3
  lanIp: 13.168.0.254
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: vpc3-eip
spec:
  natGwDp: gw3
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: vpc3-snat01
spec:
  eip: vpc3-eip
  internalCIDR: 13.168.0.0/24
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: vpc3
  labels:
    name: busybox
spec:
  containers:
  - image:  mynet-tool:1.0
    name: busybox
    command:
      - sleep
      - "3600"

# Additional Info

- Kubernetes version:
  v1.22.9
  **Output of `kubectl version`:**
  ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  1.10.6 / 1.11
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
CentOS Linux 7 (Core)"
3.10.0-1160.el7.x86_64
  ```

**Comment by bobz965** [comment]
把所有nat gw pod中的 ip a， route -n，iptables-save 截图下看看

**Comment by WaterAndBread** [comment]
![gw2-ip](https://user-images.githubusercontent.com/27998792/210496733-20faabea-9b64-4c2e-9ab7-ed50c0d44c85.png)
![gw2-table](https://user-images.githubusercontent.com/27998792/210496737-abd068ea-faab-45cc-b58c-b132ece5ec2c.png)
![gw3-ip](https://user-images.githubusercontent.com/27998792/210496739-77aaa5d7-b3a2-44e0-9a26-2b3b16d41e3b.png)
![gw3-iptable](https://user-images.githubusercontent.com/27998792/210496741-2965a0b8-bb9b-4902-9b8f-4cfce8087f25.png)

**Comment by bobz965** [comment]
看起来没有问题，到网关192.168.50.2 都能通么？

**Comment by WaterAndBread** [comment]
en ,都可以通的
![image](https://user-images.githubusercontent.com/27998792/210497686-fd538c33-85ff-447c-a406-b10b7e5498e7.png)

**Comment by bobz965** [comment]
tracepath -n 114.114.114.114 看下

**Comment by WaterAndBread** [comment]
![image](https://user-images.githubusercontent.com/27998792/210501116-c4b1ebf0-bbe5-410f-9b97-ba7cc3575db4.png)
看了一下，这两个pod 也是在同一个node 下的
![image](https://user-images.githubusercontent.com/27998792/210501268-6d82acdb-d407-4a95-8e76-e2280867023d.png)

**Comment by bobz965** [comment]
加下 -n， 这些都是不能通的结果，不是还有pod可以通外网的么？

**Comment by WaterAndBread** [comment]
vpc2 是可以ping 通外网，vpc3 不可以ping通 外网。 看tracepath 返回的内容用都是一样的
![image](https://user-images.githubusercontent.com/27998792/210502100-d02e0562-06ef-4c58-bd03-1875260cd2d9.png)

**Comment by bobz965** [comment]
直接ping 114看下

**Comment by WaterAndBread** [comment]
![image](https://user-images.githubusercontent.com/27998792/210503748-4725b3de-32ac-4a87-bbce-137fc0273e56.png)
很奇怪 ping 114 都是通的

**Comment by bobz965** [comment]
你这只是dns解析有问题吧，你自己再看下呗

**Comment by WaterAndBread** [comment]
对您说的是没有问题，是dns 的问题。
