### ISSUE TITLE
More metrics and events about gateway status

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2233]
Metrics:
- [ ] Gateway packet count/size
- [ ] Gateway packet retransmission

Events:
- [ ] Subnet gateway type changes
- [ ] Subnet gateway node changes
- [ ] Gateway status changes to not ready

**Comment by changluyi** [comment]
Gateway packet count/size
 Gateway packet retransmission

我理解这个需求应该是去抓网关的包，并且上报给metrics报文信息吧。
这里有个问题， 网关一般流量很大，去网关抓包，还分析报文上报metrics，感觉负载会很高

**Comment by changluyi** [comment]
node上的tcp重传计数 ，在node exporter有收集。

```
node_netstat_Tcp_RetransSegs 714
```
