### ISSUE TITLE
Expose ipam freeList and usedList to Subnet status

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2239]

**Comment by changluyi** [comment]
usingip实现 有两种方法，我想应该是第二种去实现。
1. ipam维护一个usingIp的 IPRangelist, 每次创建删除pod都去对这个list修改。但有个坏处，之前在测试ipam的性能的时候在30000~40000个pod的时候会性能明显下降，原因估计和这个rangelist因为不断merge splite生成的碎片有关系。
2. 每次get subnet根据ipam里面的数据重新算一次
