### ISSUE TITLE
E2E test for submariner integration

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2293]

**Comment by changluyi** [comment]
1. submariner 默认使用nf_tables（它根据当前系统nf_tables和legacy_tables，谁规则多来选用谁） kube-ovn使用legacy的，所以导致网关那里规则串不起来。submariner 没提供什么办法去切换它的iptables，后来我尝试删除.ko，使用update-alternative命令都没成功，最后我在workflow使用ubuntu20.04才解决的，估计以后可能碰到类似的问题。
2. submariner 没提供参数去skip掉某个case，所以那个错误的case我skip不掉 subctl只提供了--only，这个只能skip掉某一组case。
