### ISSUE TITLE
kube-ovn-controller CrashLoopBackOff

### ISSUE THREAD

**Issue by LinuxSuRen** [kubeovn/kube-ovn#2314]
# Expected Behavior
All pods of Kube-OVN could run well.

# Actual Behavior
```
│ kube-system  kube-ovn-cni-cfjpr                                           ●  0/1          5 CrashLoopBackOff  10.121.218.242  localhost.locald ││ kube-system  kube-ovn-controller-7c646cb68c-fhz6k                         ●  0/1          5 CrashLoopBackOff
```

# Steps to Reproduce the Problem

1. Install containerd
1. Install K8S v1.23.0
1. Install ovn via https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.10/dist/images/install.sh
1. See errors

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
v1.23.0
  ```

- kube-ovn version:
  
  ```
v1.10.8
  ```

- containerd
```
containerd github.com/containerd/containerd v1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc1
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
CentOS Linux 7 (Core)
3.10.0-1160.el7.x86_64
  ```

```
│ -------------------------------------------------------------------------------                                                                ││ Kube-OVN:                                                                                                                                      ││   Version:       v1.10.8                                                                                                                       ││   Build:         2023-01-03_03:23:13                                                                                                           ││   Commit:        git-d009416                                                                                                                   ││   Go Version:    go1.18.9                                                                                                                      ││   Arch:          amd64                                                                                                                         ││ -------------------------------------------------------------------------------                                                                ││ unknown flag: --default-u2o-interconnection                                                                                                    ││ Usage of ./kube-ovn-controller:                                                                                                                ││ unknown flag: --default-u2o-interconnection                                        
```

```
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:15:11Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by changluyi** [comment]
> # Expected Behavior
> All pods of Kube-OVN could run well.
> 
> # Actual Behavior
> ```
> │ kube-system  kube-ovn-cni-cfjpr                                           ●  0/1          5 CrashLoopBackOff  10.121.218.242  localhost.locald ││ kube-system  kube-ovn-controller-7c646cb68c-fhz6k                         ●  0/1          5 CrashLoopBackOff
> ```
> 
> # Steps to Reproduce the Problem
> 1. Install containerd
> 2. Install K8S v1.23.0
> 3. Install ovn via https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.10/dist/images/install.sh
> 4. See errors
> 
> # Additional Info
> * Kubernetes version:
>   **Output of `kubectl version`:**
> 
> v1.23.0
> 
> ```
> 
> - kube-ovn version:
> ```
> 
> v1.10.8
> 
> ```
> 
> - containerd
> ```
> 
> containerd github.com/containerd/containerd v1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc1
> 
> ```
> 
> - operation-system/kernel version:
>   
>   **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
>   **Output of `uname -r`:**
> ```
> 
> CentOS Linux 7 (Core) 3.10.0-1160.el7.x86_64
> 
> ```
> 
> ```
> 
> │ ------------------------------------------------------------------------------- ││ Kube-OVN: ││ Version: v1.10.8 ││ Build: 2023-01-03_03:23:13 ││ Commit: git-d009416 ││ Go Version: go1.18.9 ││ Arch: amd64 ││ ------------------------------------------------------------------------------- ││ unknown flag: --default-u2o-interconnection ││ Usage of ./kube-ovn-controller: ││ unknown flag: --default-u2o-interconnection
> 
> ```
> 
> ```
> 
> kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:15:11Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

you may need pull the latest image of kubeovn/kube-ovn:v1.10.8
my image is created as below time
![image](https://user-images.githubusercontent.com/47097611/217810907-491ba57d-1df5-461d-9bef-8ae67c5f6008.png)

**Comment by LinuxSuRen** [comment]
> you may need pull the latest image

Considering I installed it from the official script, I'm wondering if that is a potential issue?

**Comment by changluyi** [comment]
> > you may need pull the latest image
> 
> Considering I installed it from the official script, I'm wondering if that is a potential issue?

if you get the latest image and solve this problem , please give an reply

If this proves to be the problem, it may be a  potential issue, I will think of a method to avoid this problem, while the source code has a new parameter but the image does not have.
