### ISSUE TITLE
underlay  route replace should use the correct ip of interface

### ISSUE THREAD

**Issue by hongzhen-ma** [kubeovn/kube-ovn#2333]
# Expected Behavior
pinger pod 可以正常访问其他节点的pinger pod
# Actual Behavior
pinger pod 无法正常访问其他节点的pinger pod

# Steps to Reproduce the Problem
1. 创建集群，3 master 1worker节点，overlay 网络
1. 集群创建成功后，添加underlay 配置，underlay 网卡使用管理网卡 eth0，eth0 网卡上配置有2个IP地址
1. 关机master节点，重启。出现某个节点上的pinger pod 访问别的节点上pod 不通。实际测试 异常节点上访问别的节点的 ovn0 网卡地址也不通

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
v1.9.1
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by hongzhen-ma** [comment]
网卡地址信息
![image](https://user-images.githubusercontent.com/67130442/218426590-edcfd092-60ea-4e32-915d-8d20d295f107.png)

异常节点pod报错信息
![image](https://user-images.githubusercontent.com/67130442/218427430-c4c3795d-aa2f-4f78-95a4-3df818279a98.png)

underlay provider-networks 信息
![image](https://user-images.githubusercontent.com/67130442/218427469-578e2c47-f76d-4c0f-b14b-ab2e7c0e21c2.png)

异常节点路由信息对比
master3为访问异常节点，master2 为访问正常节点
![image](https://user-images.githubusercontent.com/67130442/218427337-d7544832-b176-46cd-a8b2-6ebfaceefd21.png)

chassis 记录geneve ip 为 192.168.108 网段地址

**Comment by zhangzujian** [comment]
未能复现bug。OVS 转移 IP 时，只跳过 LinkLocal 的路由，普通 link 路由的 src 字段不会被修改。

**Comment by zhangzujian** [comment]
若 src IP 与 ovs encap ip 不一致，会导致跨节点隧道通信异常。
