### ISSUE TITLE
Investigate OVN remote mirror

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2404]
Related to #1472 and #1288.

OVN now support remote mirror in 22.12 we need to investigate if it can meet the requirement to mirror the traffic of one pod to another pod and how the traffic flow into underlay network.

**Comment by zhangzujian** [comment]
TCP_RR test result using netperf:

| Case | Latency (us) |
| --- | ---: |
| No Mirror | 154.440 |
| Remote Pod Running on the Same Node | 171.245 |
| Remote Pod Running on Different Node | 177.151 |

171.245 / 154.440 = 110.88%
177.151 / 154.440 = 114.71%
