### ISSUE TITLE
kube-ovn-controller memory optimization

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2407]
Information comes from #1602 

![image](https://user-images.githubusercontent.com/37604165/173043577-c8f47e5b-0385-4db7-92d7-68c4a261d1eb.png)

From the pprof memory call graph, the Pod takes up about 75% memory. However, most of the fields like `managedFields`, `containers`, `volumes` and so on are not used by kube-ovn-controller. We need to find a way to trim the objects stored in the cache to reduce memory usage.

The [SetTransform](https://github.com/kubernetes/client-go/blob/v0.26.1/tools/cache/shared_informer.go#L205) method in sharedInformer can trim fields before store objects. We also need to take care the extra CPU usage.

**Comment by ShaPoHun** [comment]
mark
