### ISSUE TITLE
If the value of enable-external-gw is false,  emcp route still exists

### ISSUE THREAD

**Issue by ShaPoHun** [kubeovn/kube-ovn#2446]
# Expected Behavior
The bfd emcp function can be disabled

# Actual Behavior
enable-external-gw is false， emcp route still exists
```
# k ko  nbctl lr-route-list vpc1
IPv4 Routes
Route Table <main>:
           192.168.0.0/24              10.5.204.103 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.104 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.105 src-ip ecmp ecmp-symmetric-reply bfd
                0.0.0.0/0             192.168.0.254 dst-ip

```

# Steps to Reproduce the Problem

1.`enableBfd: true` and `enableExternal: true` in subnet
2. `enable-external-gw: "true"` in cm ovn-external-gw-config
3.  `enable-external-gw: "false"` in cm ovn-external-gw-config

**Comment by ShaPoHun** [comment]
@bobz965

**Comment by bobz965** [comment]
enable-external-gw only control default vpc， and can not control any custom default vpc.  

enable-external-gw  will delete external logical switch. this will be a bug wile custom vpc is still use this external swith. i will fix this.
