### ISSUE TITLE
spec.updateStrategy.rollingUpdate.maxUnavailable  cannot be 0

### ISSUE THREAD

**Issue by lynn901** [kubeovn/kube-ovn#2459]
# Expected Behavior
no error report
# Actual Behavior
report The DaemonSet "ovs-ovn" is invalid: spec.updateStrategy.rollingUpdate.maxUnavailable: Invalid value: intstr.IntOrString{Type:0, IntVal:0, StrVal:""}: cannot be 0
# Steps to Reproduce the Problem

1. bash install.sh
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  
  ```
  (master release)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by lynn901** [comment]
assign to me pls

**Comment by zhangzujian** [comment]
Please attach the k8s version. The daemonset requires feature gate DaemonSetUpdateSurge, which is enabled by default since v1.22.

**Comment by lynn901** [comment]
> Please attach the k8s version. The daemonset requires feature gate DaemonSetUpdateSurge, which is enabled by default since v1.22.
v1.21.5

**Comment by zhangzujian** [comment]
> > DaemonSetUpdateSurge
> > we can get the k8s version than set the value?

We do not support this behavior.
