### ISSUE TITLE
Submariner with distributed gateway

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2493]

**Comment by changluyi** [comment]
![submariner分布式网关多一个hostnetwork 的case报错 drawio](https://user-images.githubusercontent.com/47097611/226275634-ecb495d1-64c4-4727-80a5-a80eb456aa2b.png)

**Comment by changluyi** [comment]
![submariner分布式网关多一个hostnetwork 的case](https://user-images.githubusercontent.com/47097611/226275860-06b9474f-ba57-431b-bb47-452bec751ed1.png)

**Comment by changluyi** [comment]
这个pr 把join网络加入进来，
![image](https://user-images.githubusercontent.com/47097611/226805710-fac9d8f0-b4a6-42f8-9276-13cc12a62c68.png)
比较巧合的让hostnetwork的 case跑通。
https://github.com/kubeovn/kube-ovn/pull/2519

原因是会在非gateway node上面生成这条snat的iptables
![image](https://user-images.githubusercontent.com/47097611/226805955-4b2e6649-ca23-4cda-82c1-687470965e7a.png)
这条规则，可以导致pod hostnetwork在从host出来后会被snat成ovn0的100.64段的ip , 从而导致集群回报能找到路由返回。

这条iptables的配置逻辑是在这里，
![image](https://user-images.githubusercontent.com/47097611/226806211-721f022d-bbfd-4acd-aa97-9a72918fbea1.png)
其中cniinterface初始化时在这里，可以看出routeagent在初始化的时候会选取第一个cluster network网段。然后根据网段在宿主机上找对应网段的网卡作为cniinterface.
![image](https://user-images.githubusercontent.com/47097611/226806269-db327914-ae87-4c91-a331-a9aaf69e9798.png)

那么如果subctl join 加入cluster network如果这么配置，把10.16网段放前面，就不会生成这条iptables，从而会导致case fail。
![image](https://user-images.githubusercontent.com/47097611/226806638-bac22291-e433-47b3-908c-f34c47c960cf.png)

**Comment by changluyi** [comment]
补充下流量图，distributegw，加join网段配置前的路径是这样。
![加join网段前的distributegateway](https://user-images.githubusercontent.com/47097611/227081715-d664d553-3fd5-49da-81c6-817d63cc4730.png)

加了join网段后的流量图是这样。
![submariner 加了join网关 drawio](https://user-images.githubusercontent.com/47097611/227082012-befa0eab-ed7a-41df-bfed-903071948de5.png)
