### ISSUE TITLE
Benchmark libovsdb performance

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2495]

**Comment by zhangzujian** [comment]
Time spent to create a deployment in a kind cluster with [kwok](https://github.com/kubernetes-sigs/kwok):

| Replicas | Version | Time | Performance Improvement |
| :--- | :--- | :--- | ---: |
| 0.5k | v1.11 | 25s | - |
| 0.5k | v1.12 | 24s | -4.00% |
| 1k | v1.11 | 52s | - |
| 1k | v1.12 | 53s | -1.89% |
| 1.5k | v1.11 | 88s | - |
| 1.5k | v1.12 | 76s | 15.79%
| 2k | v1.11 | 111s | - |
| 2k | v1.12 | 103s | 7.77% |

**Comment by zhangzujian** [comment]
> Do we have any detailed data available for comparison of the handleAdd and handleDelete functions?

The result does not include the time spent on Pod deletion.

**Comment by zhangzujian** [comment]
Workqueue metric `workqueue_work_duration_seconds_sum` result:

| Replicas | Version | Workqueue | Time | Improvement |
| :---: | :---: | :--- | ---: | ---: |
| 0.5k | v1.11 | AddPod+UpdatePod | 112.89s | - |
| 0.5k | v1.12 | AddOrUpdatePod | 48.56s | 132.48% |
| 0.5k | v1.11 | DeletePod | 45.11s | - |
| 0.5k | v1.12 | DeletePod | 27.04s | 66.83% |
| 1k | v1.11 | AddPod+UpdatePod | 241.96s | - |
| 1k | v1.12 | AddOrUpdatePod | 105.61s | 129.11% |
| 1k | v1.11 | DeletePod | 104.83s | - |
| 1k | v1.12 | DeletePod | 61.09s | 71.60% |
| 1.5k | v1.11 | AddPod+UpdatePod | 418.64s | - |
| 1.5k | v1.12 | AddOrUpdatePod | 176.17s | 137.63% |
| 1.5k | v1.11 | DeletePod | 179.30s | - |
| 1.5k | v1.12 | DeletePod | 107.74s | 66.42% |
| 2k | v1.11 | AddPod+UpdatePod | 579.66s | - |
| 2k | v1.12 | AddOrUpdatePod | 250.52 | 131.38% |
| 2k | v1.11 | DeletePod | 248.90s | - |
| 2k | v1.12 | DeletePod | 150.58s | 65.29% |
