### ISSUE TITLE
EIP Qos support

### ISSUE THREAD

**Issue by shane965** [kubeovn/kube-ovn#2496]
### Feature request

Add rate limit support for the EIP of custom VPC

### Use case

To limit the bandwidth of EIP similar to limit the bandwidth of floating IP in Neutron.

**Comment by shane965** [comment]
I did some testing using TC ,and the commands are as follows:
```
ingress
tc qdisc  add dev net1 root handle 1:0 htb
tc class  add dev net1  parent 1:0 classid 1:1 htb rate 10mbit ceil 10mbit
tc filter add dev net1 protocol ip parent 1:0 prio 1 u32 match ip src {eip} flowid 1:1

egress
tc qdisc add dev net1 ingress
tc filter add dev net1 parent ffff: protocol ip prio 1 u32 match ip dst {eip} police rate 10000Kbit burst 10Mb drop flowid :1
```
It seem to work.

I am planning to add rate limit to EIP. Please let me know if you have any suggestions before I start coding.

**Comment by bobz965** [comment]
我这边感觉没什么问题，可能我这边后续想把bfd下一跳网关的qos也这样做下，不知道他们那边有没qos相关的安排。 @shane965
