### ISSUE TITLE
Add more Helm charts template parameters.

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2497]

**Comment by hongzhen-ma** [comment]
已经完成部分：
1、参数对齐

仍然存在的问题：
1、helm repo 搭建遇到问题，还没解决
2、需要给节点添加label，设置master节点 untaint，在本地安装的时候，kind-install-chart 中有预先设置。
但是在直接使用 helm 安装时候，没有地方能预先设置这些参数。
使用 pre-install 的 job 设置的时候，遇到 default serviceaccount 没有权限获取node 列表，添加 label 的权限。
3、目前的helm 安装，还需要在命令行中指定参数 MASTER_NODES，取值为 master 节点 IP 地址，在 helm 中无法自动获取。
4、enableSSL 参数，生成 ovn、ovs 证书的处理，在 helm 中无法完成

**Comment by hongzhen-ma** [comment]
安装文档更新
https://github.com/kubeovn/docs/pull/61

github ci 添加流水线，由 https://github.com/kubeovn/kube-ovn/issues/2354 跟踪
