### ISSUE TITLE
安装kube-ovn失败？？？？急救

### ISSUE THREAD

**Issue by xinsir88** [kubeovn/kube-ovn#2528]
各位老师，大佬好：
我今天在本地全新安装了k8s集群，最后安装kube-ovn组件，失败。具体信息如下，求协助解决。
k8s版本：v1.23.15
Docker 版本：20.10.17
containerd 版本: 1.6.18
kube-ovn 版本：v1.10.6

`[root@k8s-Master ~]# kubectl  get ds -A
NAMESPACE     NAME              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   kube-ovn-cni      3         3         0       3            0           kubernetes.io/os=linux   7m31s
kube-system   kube-ovn-pinger   0         0         0       0            0           kubernetes.io/os=linux   7m31s
kube-system   kube-proxy        3         3         3       3            3           kubernetes.io/os=linux   21m
kube-system   ovs-ovn           3         3         3       3            3           kubernetes.io/os=linux   7m37s

[root@k8s-Master ~]# kubectl  get pod -A
NAMESPACE     NAME                                   READY   STATUS             RESTARTS       AGE
kube-system   coredns-6d8c4cb4d-5q457                0/1     Pending            0              21m
kube-system   coredns-6d8c4cb4d-9psqb                0/1     Pending            0              21m
kube-system   etcd-k8s-master                        1/1     Running            0              21m
kube-system   kube-apiserver-k8s-master              1/1     Running            0              21m
kube-system   kube-controller-manager-k8s-master     1/1     Running            1 (18m ago)    21m
kube-system   kube-ovn-cni-57sq9                     0/1     CrashLoopBackOff   6 (37s ago)    7m44s
kube-system   kube-ovn-cni-hmjwz                     0/1     CrashLoopBackOff   6 (30s ago)    7m44s
kube-system   kube-ovn-cni-xql7q                     0/1     CrashLoopBackOff   6 (23s ago)    7m44s
kube-system   kube-ovn-controller-77df6874b6-dm846   0/1     CrashLoopBackOff   6 (117s ago)   7m44s
kube-system   kube-ovn-monitor-58fbcc5788-dbjz7      1/1     Running            0              7m44s
kube-system   kube-proxy-k8bz7                       1/1     Running            0              21m
kube-system   kube-proxy-sbtsz                       1/1     Running            0              20m
kube-system   kube-proxy-zldbj                       1/1     Running            0              20m
kube-system   kube-scheduler-k8s-master              1/1     Running            1 (18m ago)    21m
kube-system   ovn-central-5d87469d7-rfcd7            1/1     Running            0              7m50s
kube-system   ovs-ovn-2vrc4                          1/1     Running            0              7m50s
kube-system   ovs-ovn-stkdp                          1/1     Running            0              7m49s
kube-system   ovs-ovn-z4dw5                          1/1     Running            0              7m49s

[root@k8s-Master kube-ovn]# cat kube-ovn-cni.log 
Log file created at: 2023/03/20 17:45:11
Running on machine: k8s-Master
Binary: Built with gc go1.18.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0320 17:45:11.801404   15559 cniserver.go:34] 
-------------------------------------------------------------------------------
Kube-OVN: 
  Version:       v1.10.6
  Build:         2022-08-30_08:58:37
  Commit:        git-1510905
  Go Version:    go1.18.5
  Arch:          amd64
-------------------------------------------------------------------------------
I0320 17:45:11.879020   15559 config.go:136] node name not specified in command line parameters, fall back to the environment variable
I0320 17:45:11.879060   15559 config.go:297] no --kubeconfig, use in-cluster kubernetes config
I0320 17:45:11.937939   15559 config.go:154] daemon config: &{ ens33 br-phy 1400 1360 false mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0xc0004e2600 0xc0001f6f20 k8s-master 10.96.0.0/12  true false 10665 geneve /etc/cni/net.d /kube-ovn/01-kube-ovn.conflist 01-kube-ovn.conflist provider  kube-system}
I0320 17:45:11.966377   15559 cniserver.go:155] finish adding chassis annotation
W0320 17:45:12.109087   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:15.114843   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:18.119982   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:21.130662   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:24.149621   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:27.155479   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:30.162291   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:33.168819   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:36.173854   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:39.186465   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:42.191637   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:45.196493   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:48.201502   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:51.207488   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs
W0320 17:45:54.211541   15559 init.go:66] no ovn0 address for node k8s-master, please check kube-ovn-controller logs

`

**Comment by zhangzujian** [comment]
> no ovn0 address for node k8s-master, please check kube-ovn-controller logs

检查一下 kube-ovn-controller 日志

**Comment by xinsir88** [comment]
> > 节点 k8s-master 没有 ovn0 地址，请检查 kube-ovn-controller 日志
> 
> 检查一下 kube-ovn-controller 日志

没有日志输出， pod起来后立刻停止。

**Comment by jimorsm** [comment]
> > > 节点 k8s-master 没有 ovn0 地址，请检查 kube-ovn-controller 日志
> > 
> > 
> > 检查一下 kube-ovn-controller 日志
> 
> 没有日志输出， pod起来后立刻停止。

怎么解决的？
