### ISSUE TITLE
kube-ovn-controller CrashLoopBackOff无法启动

### ISSUE THREAD

**Issue by xinsir88** [kubeovn/kube-ovn#2530]
本地安装了k8s 计划使用ovn网络组件，但是安装过程中失败，并且无日志输出，pod起来后立刻就CrashLoopBackOff
[root@k8s-Master log]# kubectl  get pod -A
NAMESPACE     NAME                                   READY   STATUS             RESTARTS   AGE
kube-system   coredns-7f89b7bc75-gxbr7               0/1     Pending            0          35m
kube-system   coredns-7f89b7bc75-pk298               0/1     Pending            0          35m
kube-system   etcd-k8s-master                        1/1     Running            1          35m
kube-system   kube-apiserver-k8s-master              1/1     Running            1          35m
kube-system   kube-controller-manager-k8s-master     1/1     Running            1          35m
kube-system   kube-ovn-cni-9sjw4                     0/1     Running            3          3m8s
kube-system   kube-ovn-cni-rmc4v                     0/1     Running            3          3m8s
kube-system   kube-ovn-cni-sggg8                     0/1     Running            3          3m8s
kube-system   kube-ovn-controller-795959bc8d-gcnnh   0/1     CrashLoopBackOff   5          3m9s
kube-system   kube-ovn-monitor-595f859fd8-v7pql      1/1     Running            0          3m8s
kube-system   kube-proxy-kdtqm                       1/1     Running            1          35m
kube-system   kube-proxy-p8q98                       1/1     Running            1          34m
kube-system   kube-proxy-vr9pj                       1/1     Running            1          34m
kube-system   kube-scheduler-k8s-master              1/1     Running            1          35m
kube-system   ovn-central-56db6bc5bc-4f25c           1/1     Running            0          3m19s
kube-system   ovs-ovn-2zxhv                          1/1     Running            0          3m19s
kube-system   ovs-ovn-78tl4                          1/1     Running            0          3m19s
kube-system   ovs-ovn-xc86d                          1/1     Running            0          3m19s
您在 /var/spool/mail/root 中有新邮件
[root@k8s-Master log]#

**Comment by oilbeater** [comment]
需要看一下 kube-ovn-controller pod 的日志和事件
