### ISSUE TITLE
是否（如何）提供一种方式类似neutron port 永久保留ip

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2532]
之前用vip提供了一种方式来帮助pod进行ip占位，但是vip设计之初是为了表示pod主网卡ip的附属ip，不太适合作为pod主网卡ip。

而且ip本来就是用于ip占位，只是目前一般跟随pod生命周期或者vm生命周期，不能持久化保存。 用vip代替ip占位并不直接。所以打算弃用该方式。 目前认为可以在ip上加一个属性，明确表示该ip是持久化的，不跟随pod或者vm生命周期。

在neutron中port也是有临时port（随vm生命周期），以及持久化port（人工手动管理）两种使用方式。

**Comment by xujunjie-cover** [comment]
当前 ip crd 是有名字的，且名字跟 lsp 的名字相同，当 ip 未绑定 pod 或 vm 时，就没有 lsp；如何命名该 ipcrd 的名字呢。

**Comment by bobz965** [comment]
> 当前 ip crd 是有名字的，且名字跟 lsp 的名字相同，当 ip 未绑定 pod 或 vm 时，就没有 lsp；如何命名该 ipcrd 的名字呢。

按照当前的情况来看，因为ip和lsp名字相同，而ip和pod（vm）的名字和ns有对应关系。基于这个原因，预留的ip和随后创建的pod和vm的名字需要能对应得上。

**Comment by oilbeater** [comment]
现在的 IP CRD 和 lsp 资源绑定的，并且已经有很多针对 statefulset 和 vm 的特殊处理逻辑，不太适合继续做保留 IP 的功能。可以考虑一个 IPPool 的 CRD 取代 vip 和现在的 subnet 里的 exclude ip 功能。用户可以指定一个 size 自动保留一段 IP，或者输入预期的保留范围进行保留。

**Comment by bobz965** [comment]
> 现在的 IP CRD 和 lsp 资源绑定的，并且已经有很多针对 statefulset 和 vm 的特殊处理逻辑，不太适合继续做保留 IP 的功能。可以考虑一个 IPPool 的 CRD 取代 vip 和现在的 subnet 里的 exclude ip 功能。用户可以指定一个 size 自动保留一段 IP，或者输入预期的保留范围进行保留。

可以，这个我跟 @ShaPoHun 把之前ip pool的设计文档再改改，后续发出来再看下

**Comment by oilbeater** [comment]
我又想了一下，可能有两类使用方式：
1. 保留一段 ip 按需分配，这个更多是从 ip 管理视角来的，这种 ipPool 的 CRD 会更合适
2. 弹性网卡，按需动态的创建一个网卡，再绑定到 vm 上，这种可能还是类似 vip 的这种 CRD 更合适

可以看下你们最终的目的是做什么，再考虑那种 CRD 更合适. @bobz965

**Comment by bobz965** [comment]
> 我又想了一下，可能有两类使用方式：
> 
> 1. 保留一段 ip 按需分配，这个更多是从 ip 管理视角来的，这种 ipPool 的 CRD 会更合适
> 2. 弹性网卡，按需动态的创建一个网卡，再绑定到 vm 上，这种可能还是类似 vip 的这种 CRD 更合适
> 
> 可以看下你们最终的目的是做什么，再考虑那种 CRD 更合适. @bobz965

1. ip pool 可以存一些ip用于sts deployment这种负载，用于绝对固定或者相对固定一个负载中的pod到指定一个ip 池，当sts|deployment删除的时候才会触发ip池，或者永久保留这部分ip池。
2. vip 之前设计上主要就是面向附属于pod主网卡的ip，也就是ovn中的type=virtual-port的 lsp，这种用途也确实比较广泛，neutron有一个数据模型叫做allowedAddressPairs来表示主网卡和依附ip的这种关系，比如虚拟机内部跑ipvlan|veth-pair模型。
3. 由于neutron的port可以永久保留用于固定ip，这个功能目前kube-ovn没有，感觉这个用法也比较常见。当然这个也可以用ip 池实现，一个ip 池中只有一个ip的情况。
