### ISSUE TITLE
Detect iptables version and use the same mode with kube-proxy

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#2533]
### Use case

Fix submariner integration in ubuntu 22.04.

https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/README.md

**Comment by Cynerva** [comment]
It looks like this should also fix an issue I've been having with BGP-routed requests to pods, where reply packets from pods don't hit the "early accept" rules from kube-ovn, and instead go through the KUBE-FORWARD chain where they get dropped.

Any idea when this fix might make it out to a stable release?

**Comment by oilbeater** [comment]
@Cynerva we have backport this patch to release-1.11 branch and will publish v1.11.5 next week
