### ISSUE TITLE
subnet的子网和namespace是否可以设置冲突检查？

### ISSUE THREAD

**Issue by peixuewu** [kubeovn/kube-ovn#2536]
# Expected Behavior
1、默认vpc下，不同subnet不能设置同样的子网CIDR 
2、默认vpc下，不同subnet不能设置相同的namespace

# Actual Behavior
1、默认vpc下，不同subnet可以设置同样的子网CIDR 
2、默认vpc下，不同subnet可以设置相同的namespace

# Steps to Reproduce the Problem

1.cat <<EOF | kubectl create -f -
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1
spec:
  protocol: IPv4
  cidrBlock: 10.66.0.0/16
  excludeIps:
  - 10.66.0.1..10.66.0.10
  - 10.66.0.101..10.66.0.151
  gateway: 10.66.0.1
  gatewayType: distributed
  natOutgoing: true
  namespaces:
  - ns1
EOF

2.cat <<EOF | kubectl create -f -
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet2
spec:
  protocol: IPv4
  cidrBlock: 10.66.0.0/16
  excludeIps:
  - 10.66.0.1..10.66.0.10
  - 10.66.0.101..10.66.0.151
  gateway: 10.66.0.1
  gatewayType: distributed
  natOutgoing: true
  namespaces:
  - ns1
EOF

3.
![1679472813417](https://user-images.githubusercontent.com/13651500/226839951-2e47ce94-ca27-4d13-bf58-36cfabf08212.png)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
v1.10.6
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
"CentOS Linux 7 (Core)"
3.10.0-1127.el7.x86_64
  ```

**Comment by hongzhen-ma** [comment]
1、默认vpc下，不同subnet不能设置同样的子网CIDR
这个检查在webhook中有做，如果安装了webhook pod，在创建subnet2 的时候，会给出报错提示，创建不成功
如果没有安装webhook pod，查看kube-ovn-controller pod 的log，应该也能看到 log 报错，实际上 subnet2 一直没有创建成功。

2、默认vpc下，不同subnet不能设置相同的namespace
最开始是支持一个ns 只能被一个 subnet 指定。
但是在 ns 支持多子网 功能添加进来之后，就支持在多个子网下设置相同的 ns，用于在某个子网的 IP 耗尽之后，ns 下的pod 可以分配另外一个子网的 IP 地址。

**Comment by peixuewu** [comment]
> 1、默认vpc下，不同subnet不能设置同样的子网CIDR 这个检查在webhook中有做，如果安装了webhook pod，在创建subnet2 的时候，会给出报错提示，创建不成功 如果没有安装webhook pod，查看kube-ovn-controller pod 的log，应该也能看到 log 报错，实际上 subnet2 一直没有创建成功。
> 
> 2、默认vpc下，不同subnet不能设置相同的namespace 最开始是支持一个ns 只能被一个 subnet 指定。 但是在 ns 支持多子网 功能添加进来之后，就支持在多个子网下设置相同的 ns，用于在某个子网的 IP 耗尽之后，ns 下的pod 可以分配另外一个子网的 IP 地址。

ok感谢！
