### ISSUE TITLE
when restart deployment ,the released ip sometimes can be used Immediately

### ISSUE THREAD

**Issue by changluyi** [kubeovn/kube-ovn#2547]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

https://github.com/kubeovn/kube-ovn/actions/runs/4507562970/jobs/7935511029?pr=2545

**Comment by zhangzujian** [comment]
https://onsi.github.io/ginkgo/#serial-specs
