### ISSUE TITLE
Handle delete pod log appear after create a pod.

### ISSUE THREAD

**Issue by xujunjie-cover** [kubeovn/kube-ovn#2555]
# Expected Behavior
Only have create or update pod log in kube-ovn-controller.log

# Actual Behavior
```
I0327 02:18:53.429992       7 pod.go:235] enqueue add pod default/pod1
I0327 02:18:53.430095       7 pod.go:407] handle add pod default/pod1
I0327 02:18:53.430422       7 ipam.go:51] allocate v4 10.16.0.3 v6  mac 00:00:00:57:73:69 for default/pod1 from subnet ovn-default
I0327 02:18:53.443027       7 ip.go:14] enqueue update status subnet ovn-default
I0327 02:18:53.450308       7 net.go:383] expand exclude ips [10.16.0.1]
I0327 02:18:53.470796       7 pod.go:413] take 40 ms to handle add pod default/pod1
I0327 02:18:53.470974       7 pod.go:349] enqueue update pod default/pod1
I0327 02:18:53.471074       7 pod.go:477] handle update pod default/pod1
I0327 02:18:53.471167       7 pod.go:928] update pod default/pod1
I0327 02:18:53.514696       7 pod.go:484] take 43 ms to handle update pod default/pod1
I0327 02:18:55.734159       7 ip.go:28] enqueue update status subnet ovn-default 
I0327 02:19:11.819096       7 pod.go:442] handle delete pod default/pod1
I0327 02:19:11.819231       7 pod.go:449] take 0 ms to handle delete pod default/pod1
I0327 02:19:14.785112       7 node.go:942] start to check node port-group status
I0327 02:19:14.807228       7 node.go:1004] pods on node node1 do not changed
I0327 02:19:14.807396       7 node.go:924] pod on node changed, new added port pod1.default should add to node port group node.node2
I0327 02:19:15.001472       7 pod.go:442] handle delete pod default/pod1
I0327 02:19:15.001793       7 pod.go:449] take 0 ms to handle delete pod default/pod1

```
no effect to this pod，but very strange.

# Steps to Reproduce the Problem

1. create a pod; then watch kube-ovn-controller log

# Additional Info

- kube-ovn version:
  
```
v1.12.0
```

**Comment by oilbeater** [comment]
I cannot reproduce it by simple `kubectl run nginx --image=nginx:alpine`.  Is there any special config in your pod spec?

**Comment by xujunjie-cover** [comment]
> I cannot reproduce it by simple `kubectl run nginx --image=nginx:alpine`. Is there any special config in your pod spec?

It happens when create more than twice with same pod name.
try  create name nginx --> del it --> create name nginx.

**Comment by oilbeater** [comment]
That's because when pod is updated with `DeletionTimestamp`, kube-ovn-controller will start a timer to wait the `TerminationGracePeriodSeconds` and then enqueue the pod to deletePodQueue. It focus to resolve sometimes the node is lost, then pods can not be deleted  and stuck in terminating status, we have a way to release the ip resources.

**Comment by oilbeater** [comment]
However I see 4 delete enqueue event, it's unnecessary we should further optimize it

**Comment by oilbeater** [comment]
We cannot release the ip when `DeletionTimestamp` is updated, the pod may still running and need network connection to do cleanup, that's why we have to wait. However when the Pod delete event arrive, at this time the pod is not exist any more, the kube-ovn-controller will also try to enqueue the deletePodQueue. That's why we will handle delete twice. 

The issue now is there are four deletion handle in the log and we should find why.

**Comment by oilbeater** [comment]
```
I0403 09:14:57.560645      13 pod.go:457] handle delete pod default/nginx
I0403 09:14:57.561886      13 pod.go:457] handle delete pod default/nginx
I0403 09:14:57.563683      13 pod.go:835] gc logical switch port nginx.default
I0403 09:14:57.567233      13 node.go:703] delete cr ip 'nginx.default' for pod default/nginx
I0403 09:14:57.569959      13 subnet.go:515] release v4 10.16.0.16 mac 00:00:00:A7:5F:09 for default/nginx, add ip to released list
I0403 09:14:57.570000      13 pod.go:464] take 9 ms to handle delete pod default/nginx
I0403 09:14:57.570068      13 node.go:703] delete cr ip 'nginx.default' for pod default/nginx
I0403 09:14:57.571613      13 pod.go:464] take 9 ms to handle delete pod default/nginx
I0403 09:15:26.884381      13 pod.go:457] handle delete pod default/nginx
I0403 09:15:26.884456      13 node.go:703] delete cr ip 'nginx.default' for pod default/nginx
I0403 09:15:26.886092      13 pod.go:464] take 1 ms to handle delete pod default/nginx
I0403 09:15:27.558906      13 pod.go:457] handle delete pod default/nginx
I0403 09:15:27.559013      13 node.go:703] delete cr ip 'nginx.default' for pod default/nginx
I0403 09:15:27.560711      13 pod.go:464] take 1 ms to handle delete pod default/nginx
```

**Comment by changluyi** [comment]
[clyi-146360277-090523-1443-160.pdf](https://github.com/kubeovn/kube-ovn/files/11428151/clyi-146360277-090523-1443-160.pdf)

**Comment by changluyi** [comment]
[handledeletepod_4_times.pdf](https://github.com/kubeovn/kube-ovn/files/11428154/handledeletepod_4_times.pdf)

The attachment describes the reason why handleeletePod triggers 4 times
