### ISSUE TITLE
请问kube-ovn是否支持namesp层级的流量限制？

### ISSUE THREAD

**Issue by xinsir88** [kubeovn/kube-ovn#2558]
请问kube-ovn是否支持namesp层级的流量限制？
比如，指定命名空间下的 所有pod的流入流出流量的限速呢？

**Comment by xinsir88** [comment]
望大神指点一二。。。。。

**Comment by bobz965** [comment]
最近有小伙伴提了一个eip相关的qos的特性，然后把neutron相关的qos的的用法大致看了一遍。
小伙伴提的这个PR，单独为qos搞了一个crd，参考neutron，qos具有很多种类型（后端实现）。 但是qos本身的定义内容是可以抽象（统一）表示的。


你这个namespace层级，我是这么理解的：
ns和vpc有对应关系，vpc可能对应多个subnet。ns的qos，可能是ns内所有pod使用资源的一种默认qos。

qos 可以直接绑定在ip上，ip可以对应到lsp，lrp，eip，vip。

当然也可以绑定在subnet，vpc上，甚至为ns绑定一个qos，默认创建的vpc或者subnet可以从ns上继承qos，从subnet中默认创建的ip也可以继承该qos。

大概实现思路上是这个样子，但是目前还没有实现。 有其他建议和想法可以一起讨论
