### ISSUE TITLE
Unable to add multiple external networks in EIP and SNAT configuration

### ISSUE THREAD

**Issue by nics90** [kubeovn/kube-ovn#2587]
It is common in production that one segment/network of IPs are used up soon and is there a workaround in the current version to assign additional external gateway.

**Comment by bobz965** [comment]
are you use iptables nat gw? or ovn eip snat?

**Comment by nics90** [comment]
We are using ovn eip snat

We are following the as per this documentation https://kubeovn.github.io/docs/v1.11.x/guide/eip-snat/  and assign a dedicated nic/vlan in "ovn-external-gw-config" configmap

**Comment by bobz965** [comment]
> It is common in production that one segment/network of IPs are used up soon and is there a workaround in the current version to assign additional external gateway.

in the case，will you add additional nic in the host（node）for this additional external gateway？

**Comment by nics90** [comment]
Yes  we have added additional NIC but that would be assigned to different VLAN/Subnet in the data center switch. How can we create EIPs from multiple Host VLANs/Subnets ?  Is there any way provided in the configuration ?

**Comment by bobz965** [comment]
> Yes we have added additional NIC but that would be assigned to different VLAN/Subnet in the data center switch. How can we create EIPs from multiple Host VLANs/Subnets ? Is there any way provided in the configuration ?

In openstack neutron, a network can have more than one subnet, but a subnet (cidr) always refer to a VLAN. 
for now,  in ovn eip snat case, subnet also refer to a vlan, a provider network.  

maybe neutron network|subnet could give us some ideas.

**Comment by akbarkn** [comment]
anyone has a workaround to this issue?

**Comment by bobz965** [comment]
> anyone has a workaround to this issue?

yeah， we are working on a PR for the case： multi external vlan subnets attached to a custom vpc。

you can use the feature with these steps

1. create an extra external subnet with （provider network，vlan subnet crd）
2. set the extra external subnets in the custom vpc spec extraExternalSubnets list
3. create ovn snat and ovn fip as you need

**Comment by akbarkn** [comment]
@bobz965 Will it also work on default vpc?

**Comment by bobz965** [comment]
> @bobz965 Will it also work on default vpc?

we will try, please wait

**Comment by akbarkn** [comment]
@bobz965 Thanks for the info. It would be a very cool feature.

**Comment by akbarkn** [comment]
> > @bobz965 Will it also work on default vpc?
> 
> we will try, please wait

@bobz965 any updates on this?

**Comment by bobz965** [comment]
> > > @bobz965 Will it also work on default vpc?
> > 
> > 
> > we will try, please wait
> 
> @bobz965 any updates on this?

yeah， already complete， please refer： https://kubeovn.github.io/docs/v1.13.x/en/advance/ovn-eip-fip-snat/

**Comment by bobz965** [comment]
> > > > @bobz965 Will it also work on default vpc?
> > > 
> > > 
> > > we will try, please wait
> > 
> > 
> > @bobz965 any updates on this?
> 
> yeah， already complete， please refer： https://kubeovn.github.io/docs/v1.13.x/en/advance/ovn-eip-fip-snat/

maybe you need to handle the default vpc route by yourself carefully. you can try custom vpc as an example.
