### ISSUE TITLE
DNS Resolution doesn't work post EIP allocation

### ISSUE THREAD

**Issue by nics90** [kubeovn/kube-ovn#2595]
In kubernetes cluster with Nodelocal DNS setup, whenever a POD is assigned an EIP using annotation, then DNS resolution stops working.

# Expected Behavior
DNS Resolution must work even after EIP allocation.

# Actual Behavior
DNS Resolution stops working.

# Steps to Reproduce the Problem

1. kubectl run test-eip --rm -i --tty --image ubuntu -- bash
2. root@test-eip:/# apt update
3. root@test-eip:/# apt install iputils-*
4. root@test-eip:/# ping google.com
PING google.com (209.85.144.100) 56(84) bytes of data.
64 bytes from qv-in-f100.1e100.net (209.85.144.100): icmp_seq=1 ttl=102 time=63.3 ms
5. In separate session, annotate the POD with EIP:
  kubectl annotate pod test-eip ovn.kubernetes.io/eip=141.x.x.x. --overwrite 
  kubectl annotate pod test-eip ovn.kubernetes.io/routed- 
6. Try to ping again, it stops working: 
   root@test-eip:/# ping google.com 
   root@test-eip:/# ping 169.254.25.10
PING 169.254.25.10 (169.254.25.10) 56(84) bytes of data.

# Additional Info

- Kubernetes version:

  *Output of `kubectl version`:*

  
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

  

- kube-ovn version:
  
  1.11.3
  
- operation-system/kernel version:
  
  *Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:*
  *Output of `uname -r`:*
  
  "Ubuntu 20.04.4 LTS"
  5.4.0-146-generic

**Comment by nics90** [comment]
Also we observed that after EIP allocation, connectivity to both core dns service and node local dns breaks.

**Comment by nics90** [comment]
Here attached are the kubectl ko trace output files.
[trace_before-EIP.txt](https://github.com/kubeovn/kube-ovn/files/11145279/trace_before-EIP.txt)
[trace_after-EIP.txt](https://github.com/kubeovn/kube-ovn/files/11145280/trace_after-EIP.txt)

**Comment by oilbeater** [comment]
Thanks, I think it’s related to how nodelocaldns work and how kube-ovn route traffic.

nodelocaldns will set up an dummy interface and an IP on the host, that’s 169.254.25.10  in your logs and assumes all the traffic that from the pods to this address will first come to the host.
If the EIP is not set on the Pod and the subnet use distributed gateway, this assumption is correct. The traffic will first comes to the ovn0 on the node and then connect to the `169.254.25.10`.

However when EIP is enabled, kube-ovn will treat 169.254.25.10 as an external address and send the traffic to the eip interface and it will directly go to the underlay network without hitting the dummy interface.

We didn’t test eip with nodelocaldns before, and it should be a bug on kube-ovn side.

**Comment by changluyi** [comment]
https://github.com/kubeovn/kube-ovn/pull/2733

this pr will fix this issue，when dst ip = 169.254.25.10 ，the packet will pass though ovn0 on local node
