### ISSUE TITLE
multiple route tables support

### ISSUE THREAD

**Issue by mingoooo** [kubeovn/kube-ovn#2637]
### Feature request

Shell we have multiple route tables in VPC level and can be associate/disassociate with Subnet.
I think this features is already in OVN (set static route with --route_table in lr and set option in lrp)

### Use case

- reuse routings and use different route table in each Subnet
- associate / disassociate routing table in Subnet easily

I think use policy-based route with src=<subnet_cidr> match can instead, but will be more flow entry and difficulty to switch route table

I can contribute to this feature If that make sense

**Comment by oilbeater** [comment]
@mingoooo I think is a good feature, you can go ahead for the crd design and we can discuss it further

**Comment by mingoooo** [comment]
Three options of the crd design I'm thinking -

1. New a crd named `RouteTable` to manage all the route tables in the cluster
2. Add a field named `RouteTable` in `StaticRoute` as `--route_table` option in ovn, that should be more compatible with current version of crd
3. Add a field named `RouteTables` in `Vpc` that cover route table name and routing entrys (`StaticRoute`) to manage the route tables in vpc level


Currently I will perfer `option 3`, because - 
- Store in vpc level is ok, no need to share with other vpc
- The structure clear than option 2 and should be more easliy to handle the default/system route with all the route tables
- I think we can keep the `StaticRoutes` and `RouteTables` in `Vpc` crd for the compatibility, we can copy the routes in `StaticRoutes` in main table of `RouteTables` (or just use `RouteTables` for custom without main table)

Here is the definition changes, please take a look and correct me -
https://github.com/mingoooo/kube-ovn/commit/e1ffde86638075d60412a2f5fce307f99bf72fbb

@oilbeater @zhangzujian
