### ISSUE TITLE
subnet excludeIps ignored in ipam allocation 

### ISSUE THREAD

**Issue by patrizio-bassi** [kubeovn/kube-ovn#2653]
# Expected Behavior
when a subnet is created with excludeIps list/range the user should not be able to use it

# Actual Behavior

specifying ip_address address will bypass ipam checks

# Steps to Reproduce the Problem

1. define a subnet 

`apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1-vpc
spec:
  cidrBlock: 10.0.6.0/24
  gateway: 10.0.6.1
  vlan: provvlan1
  vpc: test-vpc-1
  protocol: IPv4
  namespaces:
  - ns1
  excludeIps:
  - 10.0.6.1
  - 10.0.6.2
  - 10.0.6.20..10.0.6.255
  private: true
  gatewayType: distributed
  natOutgoing: false
  disableGatewayCheck: true`

3. create a Pod

`apiVersion: v1
kind: Pod
metadata:
  name: busybox-ovn-vpc2-noescape
  labels:
    app: busybox
  annotations:
    ovn.kubernetes.io/logical_switch: subnet1-vpc
    ovn.kubernetes.io/ip_address: 10.0.6.24
  namespace: ns2
spec:
  containers:
  - name: busybox
    image: busybox@sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]`

please notice that 10.0.6.24 is in the excludeIps range.

It should be denied, while it is not.

# Additional Info

another problem is that even if i add namespaces limitations, from another namespace i can use that ip address, bypassing multitenancy

- Kubernetes version:

1.26

- kube-ovn version:
  
v1.10.4

- operation-system/kernel version:
  
ubuntu/5.15.0-67-generic

**Comment by oilbeater** [comment]
@patrizio-bassi this behavior is by design. 

There are two origin requirements for the `exclude_ips`, one is in underlay subnet some addresses may already be used by other network devices, so we need a way to exclude these IPs. The second is that when specify ip_address by annotation, these address may have already been allocated by the random allocation, so we can reserve a range of IP for static allocation.

For you use case, I think a custom webhook might be more suitable.

**Comment by patrizio-bassi** [comment]
Thank you for explaination, but even in the case i would like to preallocate some static ips, shouldn’t the cni ensure that those addresses are unique? Otherwise we will end up breaking connectivity for existing pods.

Do you have an example of webhook? I tried the admission control described in the documentation but it fails in this scenario.

thank you

**Comment by stonejianbu** [comment]
附议将excludeIps添加到ipam管理

**Comment by AlexsJones** [comment]
> @patrizio-bassi this behavior is by design.
> 
> There are two origin requirements for the `exclude_ips`, one is in underlay subnet some addresses may already be used by other network devices, so we need a way to exclude these IPs. The second is that when specify ip_address by annotation, these address may have already been allocated by the random allocation, so we can reserve a range of IP for static allocation.
> 
> For you use case, I think a custom webhook might be more suitable.

Are you saying that if you set excludeIP's manually for underlay devices + reservation for static allocation then dynamic allocation will correctly not use these?

It seems in that case, unless specifically assigning an IP you know is in the excludeIP's list, it should obey the expected behaviour @patrizio-bassi ?

**Comment by patrizio-bassi** [comment]
Hi @AlexsJones,
sorry i didn't completely understand your question so i will try to rephrase my request.

Let me recap: i have a subnet, i want to restrict the usable addresses range, so i use the excludeIP feature in order to tell the IPAM scheduler not to pick the addresses our of the allowed range. This generally works if you do not put any particolar annotation and pods get the IPs in the desired range.

But using the ovn.kubernetes.io/ip_address annotation will let you pick up any ip you want, without obeying the excludeIPs directive.

So in the case i posted i have a subnet **10.0.6.0/24** and then i set as excludeIps:
**10.0.6.1
10.0.6.2
10.0.6.20..10.0.6.255**

This should result in allowed range of usable addresses from **10.0.6.3 to 10.0.6.19** only.

Unfortunately in a pod definition, using the annotation:
ovn.kubernetes.io/ip_address: **10.0.6.24** (which is our from 10.0.6.3 to 10.0.6.19 allowed range) 
works and the pod is created, while it should fail.

Why is this important? because i would like to assign the k8s cluster a big subnet, and than split it in several logical subnets each one with its own ranges assigned to separated namespaces, each one will use its own with no overlap.

While in this scenario namespace ns1 may use the IP of ns2 and this will create network problems of course.

The default webhook i think it checking if an IPs is already used, not if it's overflowing in the excludeIPs range.
