### ISSUE TITLE
subnet private flag not honoured in a vpc-overlapped CIDR environment

### ISSUE THREAD

**Issue by patrizio-bassi** [kubeovn/kube-ovn#2654]
# Expected Behavior

I would like to dedicate a underlay subnet range for each K8s namespace.
Let's say i assign 10.0.0.0/16 to the whole K8s cluster and that i would like to logically assign ranges to namespaces, for instance:

10.0.0.10-10.0.0.20 (always mask /16) range to namespace ns1
10.0.0.21-10.0.0.30 (always mask /16) range to namespace ns2
....and so on.

I would create 2 VPCs and 2 subnets with the same CIDR address plan, setting the "private = true" flag in subnet definition. I would expect the traffic between the pods in different namespaces to be dropped, while it isn't.

# Actual Behavior

Pod in ns1, with 10.0.0.10/16 ip address can ping pod in ns2 with ip 10.0.0.21/26 address.

# Steps to Reproduce the Problem

1. create a vpc limited to the first namespace (i.e. ns1)
2. create a vpc limited to the second namespace (i.e. ns2)
3. create a subnet limited to namespace ns1 and linked to vpc of step 1), setting private: true param and a strict ip range (using excludeIPs)
4. create a subnet limited to namespace ns2 and linked to vpc of step 2), setting private: true param and a strict ip range (using excludeIPs)
5. create one pod in each ns, they will get IPs from dedicated ip range
6. ping each other, will work (shouldn't)

# Additional Info

workaround found is the explicitely ban the whole network 10.0.0.0/16 traffic and allow only the dedicated ip address.

`  acls:
    - action: drop
      direction: to-lport
      match: ip4.src == 10.0.0.0/16 && ip
      priority: 1345
    - action: drop
      direction: from-lport
      match: ip4.src == 10.0.0.0/16 && ip
      priority: 1345
    - action: allow
      direction: to-lport
      match: 10.0.0.10 <= ip4.src < 10.0.0.20 && ip
      priority: 2123
    - action: allow
      direction: from-lport
      match: 10.0.0.10 <= ip4.src < 10.0.0.20 && ip
      priority: 2123
`

- Kubernetes version:

1.26

- kube-ovn version:
  
1.10.4

- operation-system/kernel version:
  
5.15.0-67-generic

looking at https://github.com/kubeovn/kube-ovn/blob/1a474fd988345e87ce5170d81c9570fc5df4f133/pkg/ovs/ovn-nbctl-legacy.go#L700
it looks like that when creating the Subnet default acls it doesn't check for
1) excludeIPs range
2) if there is a overlap with other Subnets even if attached to different VPCs

**Comment by patrizio-bassi** [comment]
Can we Mark this as a RFE?

> > I would like to dedicate a underlay subnet range for each K8s namespace.
> 
> VPC only works for overlay subnets now, Kube-OVN will not connect the underlay subnet to the VPC router so there is no VPC level isolation for underlay subnet.

**Comment by patrizio-bassi** [comment]
Can we consider this as a RFE?

**Comment by oilbeater** [comment]
we will update it in the docs
