### ISSUE TITLE
vpc模式下是否支持多个外部网络，使用特定的外部网络绑定特定的vpc-nat-gw

### ISSUE THREAD

**Issue by lytos666** [kubeovn/kube-ovn#2679]
### Feature request

创建外部网络以及vpc-nat-gw这两个对象时，并没有相关配置绑定关系，如何使用特定的vpc-nat-gw绑定特定的外部网络？

### Use case

多租户场景下，一个租户对应一个vpc，有多个外部网络，一个/多个租户需要对应到特定的外部网络；

部署方式：  本地环境部署，版本为：v1.10.10

网络连接： bond0聚合口下，配置了多个vlan，bond0.1312（用于管理），bond0.1313（用于VPC外部网络1），bond0.1314（用于VPC外部网络2）

当前环境：测试环境两个租户，创建了2个vpc，以及两个外部网络，两个vpc-nat-gw，在租户A中需要使用到bond0.1313这个vlan的外部网络，在租户B中需要使用到bond0.1314这个vlan的外部网络；

当前存在问题：在创建外部网络以及vpc-nat-gw时，并没有配置可以指定特定的vpc-nat-gw绑定特定的外部网络，无法实现特定租户的vpc下使用特定的外部网络；

**Comment by oilbeater** [comment]
当前版本没有这个功能，可以等待未来支持

**Comment by shane965** [comment]
> 当前版本没有这个功能，可以等待未来支持

最近正在做这部分的调研，可以考虑指派给我，然后大家再一起讨论下这个需求的细节，以免遗漏

**Comment by bobz965** [comment]
> 当前版本没有这个功能，可以等待未来支持

@oilbeater hi， 有个小伙伴他们那边做这个需求的排期比较靠前，我们这边也有计划这个特性，我这边可以指派到对应人员

**Comment by bobz965** [comment]
finished，please refer to https://kubeovn.github.io/docs/v1.12.x/guide/vpc/
