### ISSUE TITLE
kubeovn/sriov-network-operator service 未正常创建

### ISSUE THREAD

**Issue by Longchuanzheng** [kubeovn/kube-ovn#2682]
# Expected Behavior

正常安装 sriov-network-operator 
Successfully installed sriov-network-operator .

# Actual Behavior

基于https://kubeovn.github.io/docs/v1.11.x/advance/offload-mellanox/#sriov-network-operator-sr-iov-device-plugin这个教程。
apply 了相关yaml ，但是service 没有被创建。

![image](https://user-images.githubusercontent.com/49519342/233243190-0faf3049-6348-44cf-bfd0-24841c7756b6.png)

Based on this https://kubeovn.github.io/docs/v1.11.x/advance/offload-mellanox/#sriov-network-operator-sr-iov-device-plugin tutorial. I try to install sriov-network-operator

```
git clone --depth=1 https://github.com/kubeovn/sriov-network-operator.git
kubectl apply -k sriov-network-operator/deploy
```
while the service/sriov-network-operator doesn't appear.

operator 的日志中没有明显问题
![image](https://user-images.githubusercontent.com/49519342/233244770-cff7c6da-6780-4db7-8290-850e60a2d5bc.png)
其他组件running 后，感觉 operator 开始同步节点信息了
![image](https://user-images.githubusercontent.com/49519342/233245426-7f8c79f0-1b4c-4f0b-8805-d8696dd52e3a.png)

# Steps to Reproduce the Problem

1.
```
git clone --depth=1 https://github.com/kubeovn/sriov-network-operator.git
kubectl apply -k sriov-network-operator/deploy
```
2.
```
kubectl get -n kube-system all | grep sriov
```

# Additional Info

- Kubernetes version:
```
 v1.21.5
```

- kube-ovn version:
  
```
1.11.1
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
```
centos 7
3.10.0-957.el7.x86_64
```

**Comment by wangyd1988** [comment]
现在来看没有场景使用这个service，所以把这个service去掉了，后续我改下文档。sriov-network-operator 生成的vf满足你们offload的使用吗

**Comment by Longchuanzheng** [comment]
@wangyd1988 感谢大佬解答。
我理解 operaotr 会根据SriovNetworkNodePolicy创建VF并通过 device-plugin 将SR-IOV 资源注册到 Kubernetes Node 中。创建相关 SriovNetworkNodePolicy 后在node上会有体现，就像文档中展示的。
![image](https://user-images.githubusercontent.com/49519342/233280680-7d1b8c5f-52ff-44b6-909e-9f379d3149d2.png)

不知道这样理解对不对？如果是这样，那我们在使用sriov-network-operator时还遇到了一些问题，我新开了一个issue /issues/2685，详细说明我们遇到的问题。
