### ISSUE TITLE
vlan模式，集群外部网络如何实现负载均衡的方式访问内部的POD

### ISSUE THREAD

**Issue by lytos666** [kubeovn/kube-ovn#2702]
### Feature request

kube-ovn部署方式为vlan部署，POD直接使用物理vlan网络地址，在这种环境下集群外部的网络如何通过负载均衡的方式去访问多个POD；

### Use case

部署方式为vlan，创建了provider、vlan、subnet、ns，在测试的ns中创建了1个deployment，5个nginx副本，外部网络需要通过负载均衡的方式访问到这5个nginx的POD；
=================================
[root@master kube-ovn]# kubectl get vlan
NAME       ID     PROVIDER
ovn-vlan   1313   provider
vlan1314   1314   provider
=================================

======================================================================================
[root@master kube-ovn]# kubectl get subnet
NAME              PROVIDER   VPC           PROTOCOL   CIDR            PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                  U2OINTERCONNECTIONIP
join              ovn        ovn-cluster   IPv4       100.64.0.0/16   false     false   false     distributed   2        65531         0        0             [100.64.0.1] 
ovn-default       ovn        ovn-cluster   IPv4       10.13.13.0/24   false     false   true      distributed   45       189           0        0             [10.13.13.1..10.13.13.20]
vlan1314-subnet   ovn        ovn-cluster   IPv4       10.13.14.0/24   true      false   false     distributed   6        247           0        0             [10.13.14.1] 
======================================================================================

======================================================================================
[root@master template]# kubectl get pod -n vlan1314 -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
busybox                            1/1     Running   0          54m   10.13.14.2   node01   <none>           <none>
starter-backend-866d8d78b5-7t4b8   1/1     Running   0          53m   10.13.14.6   master   <none>           <none>
starter-backend-866d8d78b5-ndrp4   1/1     Running   0          53m   10.13.14.3   node01   <none>           <none>
starter-backend-866d8d78b5-pc495   1/1     Running   0          53m   10.13.14.4   master   <none>           <none>
starter-backend-866d8d78b5-qzbsz   1/1     Running   0          53m   10.13.14.5   node01   <none>           <none>
starter-backend-866d8d78b5-xq2s8   1/1     Running   0          53m   10.13.14.7   master   <none>           <none>
======================================================================================

部署方式：裸机部署（centos7.6），两个节点，kube-ovn版本为：v1.10.10，部署方式为vlan模式

网络连接：bond0聚合口下，bond0.1312为管理地址（配置在物理机器下），vlan1314位业务vlan，提供给POD使用

当前环境：在ns中创建了5个nginx的pod，地址为物理网络vlan1314的地址，集群外部的网络可以直接通过vlan1314的地址直接访问到这5个nginx的pod，外部网络需要通过负载均衡的方式去访问这5个nginx的pod；

当前存在问题： 
            在vlan模式下部署，服务器物理接口下并没有配置配置bond0.1314这个vlan地址，无法使用SVC NodePort方式将服务发布到物理网络中，进群外部的网络无法通过负载均衡的方式访问到内部的POD；
            在kube-ovn是否有内置的负载均衡器，外部网络通过负载均衡的方式访问内部的POD这种需求如何实现？

**Comment by zhangzujian** [comment]
NodePort 不要求节点 IP 必须和 Pod 网段相同。

**Comment by lytos666** [comment]
节点IP是10.13.12.X/24地址，对应的是管理网
POD的业务网地址是10.13.14.X/24，对应的是业务网，两个地址是互相隔离无法访问的。
用NodePort，由于节点上只存在10.13.12.X/24的地址，这个时候用NodePort发布出去就只有在10.13.12.X/24的管理网能够访问到节点的地址，无法发布到业务网里面去（节点并没有10.13.14.X的这个地址）

**Comment by bobz965** [comment]
或许可以这样：
1. 业务网预留一部分ip段作为前段ip
2. 业务ovs网桥作为kube-vip或者metalLB的负载均衡器LB external依附的网卡
3. 由于业务ovs网桥和pod可以互通，所以应该可以

**Comment by lytos666** [comment]
感谢，我试试
