### ISSUE TITLE
当kube-ovn-controller重启并且kubevirt创建的pod非running时 kubevirt 的vm无法保持ip(已设置keep-vm-ip=true)

### ISSUE THREAD

**Issue by shl87652549** [kubeovn/kube-ovn#2709]
# Expected Behavior
 kubevirt的vm保持原先的ip与mac
# Actual Behavior
kubevirt的vm被分配了新的ip与mac
# Steps to Reproduce the Problem

1.记录原先kubevirt创建pod的ip和mac并使其进入非running状态
2.重启kube-ovn-controller
3.检查新kubevirt创建pod的ip和mac

# Additional Info

- Kubernetes version:
    
   Kubernetes version v1.22.7

- kube-ovn version:
   
    kube-ovn version v1.10.4-no-avx512

- operation-system/kernel version:
  
  centos 7   4.18.0-240.22.1.el7

 初步分析：当kube-ovn-controller重启时在func (c *Controller) InitIPAM()中会遍历pods：
    	for _, pod := range pods {
		if pod.Spec.HostNetwork || !isPodAlive(pod) {
			continue
		}

   在func isPodAlive中有：
	if p.Status.Phase == v1.PodFailed && p.Spec.RestartPolicy == v1.RestartPolicyNever {
		return false
	}
   而kubevirt创建的pod ，RestartPolicy固定赋值为k8sv1.RestartPolicyNever，所以遍历到该pod ，isPodAlive会返回false，导致InitIPAM()跳过此pod。
   所以推定在kube-ovn-controller重启并且kubevirt创建的pod在非running时 ipam无法获取到该pod注解中的已分配ip和mac，所以无法在kubevirt重新创建pod时使用之前pod的ip和mac；
   以上仅是个人的分析

**Comment by hongzhen-ma** [comment]
建议更新 v1.11.3 的镜像验证下。
kubevirt vm stop 之后，对应的vm pod 删除了，但是保留了对应的 IP crd
在kube-ovn-controller重启的时候，是通过 IP crd 来恢复 kubevirt vm 的 lsp，之后再启动 vm，应该能复用原来的地址信息。
