### ISSUE TITLE
kubeovn是否支持 k8s on openstack VM？

### ISSUE THREAD

**Issue by yuguanxiang** [kubeovn/kube-ovn#2714]
就是openstack VM里跑k8s， 然后想用kubeovn，
是否支持， 有没有相应的文档或者例子

多谢！

**Comment by oilbeater** [comment]
正常部署 k8s 和 kube-ovn 即可，没有特别的用法

**Comment by yuguanxiang** [comment]
那这种支持pod 和 vm共享 vm的ovs， 都分配vm所在的vpc的地址吗

**Comment by oilbeater** [comment]
> 那这种支持pod 和 vm共享 vm的ovs， 都分配vm所在的vpc的地址吗
不支持

**Comment by yuguanxiang** [comment]
好的谢谢！
