### ISSUE TITLE
自定义VPC内怎么使用域名访问外网？

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#2720]
### Feature request

1. 按照官方文档，配置自定义VPC以及自定义VPC内的VPC DNS成功。

2. 自定义VPC内的pod能够通过ip访问外网：（157.148.69.74是百度的ip）
![图片](https://user-images.githubusercontent.com/25982171/234534737-c6dff873-c42f-4f9f-932f-1b1caa658bc1.png)

3. 自定义VPC内的pod也能解析集群内的服务：
![图片](https://user-images.githubusercontent.com/25982171/234535568-943e5913-77b1-496e-b822-c4a538d37834.png)

4. 但是自定义VPC内的pod不能通过域名访问外网：
![图片](https://user-images.githubusercontent.com/25982171/234535927-0471bab4-efd1-4e46-95a3-59c5c0d56fc4.png)

5.在pod内部的dns加上节点的dns地址，pod就能通过域名访问外网：
![图片](https://user-images.githubusercontent.com/25982171/234536501-6380d0e5-2652-4c5d-b2c0-f319311cf5e7.png)
![图片](https://user-images.githubusercontent.com/25982171/234536695-cd386b6f-77ef-485b-8f07-17edf109114b.png)

kubeovn默认VPC的pod是不需要在pod内部额外配置dns的，自定义VPC内的pod能否也有类似的方案？

目前使用的是kubeovn v1.11.3
谢谢

**Comment by oilbeater** [comment]
@ShaPoHun 是不是 vpc dns 里的 upstream dns 现在还没有配置

**Comment by ShaPoHun** [comment]
dns pod启动时会获取所在节点的/etc/resolv.conf，或者手动修改configmap: kube-system/vpc-dns-corefile来支持

**Comment by geniusxiong** [comment]
> 

你好，上述使用的是kube-ovn1.11.3版本，好像dns pod确实有add节点的dns，但是好像容器存在报错：
![图片](https://user-images.githubusercontent.com/25982171/234747911-70f30d6e-a463-409b-b3d1-fa9d3103227f.png)
是不是因为报错的原因，导致dns没有加入？

**Comment by ShaPoHun** [comment]
你打印下dns pod yaml信息

**Comment by geniusxiong** [comment]
> 你打印下dns pod yaml信息

不好意思，刚才贴的是集群coredns的终端信息，好像是不让进coredns终端。

另外，自定义vpc的dns pod的yaml，我贴一下：
`kind: Pod
apiVersion: v1
metadata:
  name: vpc-dns-dns-vpc-nat-2-6b88567945-jj67k
  generateName: vpc-dns-dns-vpc-nat-2-6b88567945-
  namespace: kube-system
  labels:
    k8s-app: vpc-dns-dns-vpc-nat-2
    pod-template-hash: 6b88567945
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "kube-ovn",
          "interface": "eth0",
          "ips": [
              "10.0.40.25"
          ],
          "mac": "00:00:00:3D:EE:62",
          "default": true,
          "dns": {},
          "gateway": [
              "10.0.40.1"
          ]
      },{
          "name": "default/ovn-nad",
          "interface": "net1",
          "ips": [
              "10.16.0.81"
          ],
          "mac": "00:00:00:F0:65:56",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: default/ovn-nad
    kubesphere.io/restartedAt: '2023-04-26T07:56:10.193Z'
    ovn-nad.default.ovn.kubernetes.io/allocated: 'true'
    ovn-nad.default.ovn.kubernetes.io/cidr: 10.16.0.0/16
    ovn-nad.default.ovn.kubernetes.io/gateway: 10.16.0.1
    ovn-nad.default.ovn.kubernetes.io/ip_address: 10.16.0.81
    ovn-nad.default.ovn.kubernetes.io/logical_router: ovn-cluster
    ovn-nad.default.ovn.kubernetes.io/logical_switch: ovn-default
    ovn-nad.default.ovn.kubernetes.io/mac_address: '00:00:00:F0:65:56'
    ovn-nad.default.ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn-nad.default.ovn.kubernetes.io/routed: 'true'
    ovn.kubernetes.io/allocated: 'true'
    ovn.kubernetes.io/cidr: 10.0.40.0/24
    ovn.kubernetes.io/gateway: 10.0.40.1
    ovn.kubernetes.io/ip_address: 10.0.40.25
    ovn.kubernetes.io/logical_router: vpc-nat-2
    ovn.kubernetes.io/logical_switch: vpc-nat-subnet2
    ovn.kubernetes.io/mac_address: '00:00:00:3D:EE:62'
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/routed: 'true'
spec:
  volumes:
    - name: config-volume
      configMap:
        name: vpc-dns-corefile
        items:
          - key: Corefile
            path: Corefile
        defaultMode: 420
    - name: kube-api-access-mb9l2
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  initContainers:
    - name: init-route
      image: 'kubeovn/vpc-nat-gateway:v1.11.0'
      command:
        - sh
        - '-c'
        - >
          ip route add ${KUBERNETES_SERVICE_HOST} via 10.16.0.1 dev net1;ip
          route add 58.22.96.66 via 10.16.0.1 dev net1;
      resources: {}
      volumeMounts:
        - name: kube-api-access-mb9l2
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
  containers:
    - name: coredns
      image: 'registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.8.0'
      args:
        - '-conf'
        - /etc/coredns/Corefile
      ports:
        - name: dns
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: metrics
          containerPort: 9153
          protocol: TCP
      resources:
        limits:
          memory: 170Mi
        requests:
          cpu: 100m
          memory: 70Mi
      volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /etc/coredns
        - name: kube-api-access-mb9l2
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
          drop:
            - all
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: Default
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: vpc-dns
  serviceAccount: vpc-dns
  nodeName: master
  securityContext: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                    - vpc-dns-dns-vpc-nat-2
            topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priorityClassName: system-cluster-critical
  priority: 2000000000
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
`
实际上，在初始容器上看，是有dns信息的，但是自定义VPC内的pod是无法通过域名访问百度

**Comment by ShaPoHun** [comment]
你通过nslookup www.baidu.com 172.8.0.3解析正常吗

**Comment by geniusxiong** [comment]
> 你通过nslookup [www.baidu.com](http://www.baidu.com) 172.8.0.3解析正常吗

解析好像正常，但是没ping通域名，不过能ping通内外网的ip

![图片](https://user-images.githubusercontent.com/25982171/234772268-530381a5-10a6-4ec8-a6ad-9d0bc61df305.png)

**Comment by ShaPoHun** [comment]
vpc-dns-config中的`coredns-vip`参数要配置为和集群dns的地址一致，这样vpc内pod解析dns时才能能指向vpc-dns

**Comment by ShaPoHun** [comment]
nslookup www.baidu.com 172.8.0.3解析正常，说明vpc-dns功能正常。ping 百度不通的原因是，pod的dns解析的服务器地址是`/etc/resolv.conf`中的nameserver，所以你需要把该coredns-vip设置为该nameserver，这样pod才能ping通

**Comment by geniusxiong** [comment]
> 



> nslookup [www.baidu.com](http://www.baidu.com) 172.8.0.3解析正常，说明vpc-dns功能正常。ping 百度不通的原因是，pod的dns解析的服务器地址是`/etc/resolv.conf`中的nameserver，所以你需要把该coredns-vip设置为该nameserver，这样pod才能ping通

试了下，自定义vpd内部的nameserver是一个169.254.25.10的地址

![图片](https://user-images.githubusercontent.com/25982171/235032490-f6f9002d-3157-4621-9323-75b9036c8b25.png)

然后把coredns-vip也设置成这个地址，确实就能用域名访问外网了，感谢！

但是这个ip是什么的虚ip呢，我找了下好像没有找到
