### ISSUE TITLE
vlan模式部署，pod无法访问ClusterIP类型发布的SVC服务

### ISSUE THREAD

**Issue by lytos666** [kubeovn/kube-ovn#2735]
### Feature request
vlan模式部署，pod直接使用物理vlan网络地址，使用clusterIP创建SVC，pod无法访问该域名，pid无法访问dns的svc地址，ping这个服务svc的地址也无法通信；

### Use case
部署环境
         kube-ovn 1.11.3
         操作系统 centos7.6
网络环境
          物理网络上创建了vlan1312（10.13.12.X），vlan1313（10.13.13.X），vlan1314（10.13.14.X）
          宿主机上聚合口bond0
           bond0.1312，宿主机上bond0.1312这个接口用于管理
           default pod cidr 为vlan 1313，该vlan在宿主机上没有配置地址，coredns使用的是该vlan地址；
           业务的pod地址为vlan 1314 的地址，10.13.14.X
问题现象
1、创建了一个nginx的deployment，2副本，创建了一个ClusterIP的svc；
![image](https://user-images.githubusercontent.com/131284025/235093870-b3091756-6c9d-4ffe-b143-a36cce46261a.png)

![image](https://user-images.githubusercontent.com/131284025/235093962-ef0ee57a-46ff-4d0b-aa6d-d666f37c5130.png)
             
![image](https://user-images.githubusercontent.com/131284025/235093665-27a7c98f-b966-4dec-a660-9eaed9d16406.png)

2、创建了一个测试容器busybox，使用域名去访问nginx的svc，无法访问，dns域名无法解析，无法访问到coredns的svc地址
         
![image](https://user-images.githubusercontent.com/131284025/235095895-d9c44274-c3f5-4c6d-ae1f-e694efb22855.png)

**Comment by bobz965** [comment]
部署脚本前100行贴一下

**Comment by lytos666** [comment]
@bobz965 hello，当前我将业务vlan的的subnet的逻辑网关开启，就能正常访问dns，以及svc的地址了，当前有几个疑问，不知道我的理解对不对，有空可以一起看看呗。

当前的疑问：

1、我在未开启逻辑网关之前，一直是使用的是物理交换机的物理网络网关，pod能够跨网段通信，且能够正常访问到互联网，为什么无法访问到svc的地址段？
2、在存在物理网关的情况下，pod的跨网段通信直接交给物理网关就OK了，我的理解是不需要开启逻辑网关功能，pod访问SVC是需要依赖于逻辑网关么？
3、我的理解是kube-ovn中创建的vlan以及subnet，这个地址段如果不存在与物理交换机网络下，这个时候就需要开启逻辑网关，然后在物理网络上写kube-ovn中业务vlan的路由，下一条指向逻辑网关的节点，让pod的流量能够在物理网络中通过。
4、我开启了逻辑网关以后，逻辑网关地址为10.13.14.1以及10.13.15.1 这两个地址与物理交换机的物理网关是存在冲突的，这种情况下是否会存在问题？
5、我开启了逻辑网关，且kube-ovn中的创建的vlan网段与物理交换机上的vlan网段是一致的，这种部署方式是否存在问题？


当前的部署拓扑图如下：

![image](https://user-images.githubusercontent.com/131284025/235200703-9821a84e-44a3-467a-a482-af944ac68fc8.png)

**Comment by bobz965** [comment]
> ```shell
> # VLAN Config only take effect when NETWORK_TYPE is vlan
> PROVIDER_NAME="provider"
> VLAN_INTERFACE_NAME="bond0"
> VLAN_NAME="ovn-vlan"
> VLAN_ID="1313"
> ```

# VLAN Config only take effect when NETWORK_TYPE is vlan
PROVIDER_NAME="provider"
VLAN_INTERFACE_NAME="bond0"
VLAN_NAME="ovn-vlan"
VLAN_ID="1313"
这几行可以看出你想直接用vlan 网络，bond0给ovs网桥用，

ENABLE_NP=${ENABLE_NP:-true}  关掉
ENABLE_VLAN=${ENABLE_VLAN:-false} 打开 意味着默认网络就是vlan网络
VLAN_NIC=${VLAN_NIC:-} 配这个而不是自己直接加了一行

建议再熟悉下文档，看看vlan直接部署该怎么部署

**Comment by lytos666** [comment]
https://kubeovn.github.io/docs/v1.11.x/start/underlay/
官网上的文档部署underlay网络对如下参数并未详细说明，您有相关的文档或者案例方便分享下么：
![image](https://user-images.githubusercontent.com/131284025/235306626-fd61f1f7-ef84-4c11-b470-39715d106331.png)

您这边的建议是我需要修改如下三个参数，然后重新部署。VLAN_NIC=${VLAN_NIC:-}  这个参数如何填写呢？

```shell
ENABLE_NP=${ENABLE_NP:-true}                                                 #改为flase
ENABLE_VLAN=${ENABLE_VLAN:-false}                                       #改为true
VLAN_NIC=${VLAN_NIC:-}                                                           #这个参数如何填写呢？
```

**Comment by bobz965** [comment]
> https://kubeovn.github.io/docs/v1.11.x/start/underlay/ 官网上的文档部署underlay网络对如下参数并未详细说明，您有相关的文档或者案例方便分享下么： ![image](https://user-images.githubusercontent.com/131284025/235306626-fd61f1f7-ef84-4c11-b470-39715d106331.png)
> 
> 您这边的建议是我需要修改如下三个参数，然后重新部署。VLAN_NIC=${VLAN_NIC:-} 这个参数如何填写呢？
> 
> ```shell
> ENABLE_NP=${ENABLE_NP:-true}                                                 #改为flase
> ENABLE_VLAN=${ENABLE_VLAN:-false}                                       #改为true
> VLAN_NIC=${VLAN_NIC:-}                                                           #这个参数如何填写呢？


![image](https://user-images.githubusercontent.com/7981158/235309810-3dad3522-a912-4ef2-a5b1-1f4184647dca.png)


不是这个么？ 你看看代码

![image](https://user-images.githubusercontent.com/7981158/235309847-1e063f36-b7ec-415e-b3bc-88a74d70087d.png)
