### ISSUE TITLE
在自定义vpc下的pod上，无法ping通 vpc-nat-gw-gw1-0所在的node

### ISSUE THREAD

**Issue by tghfly** [kubeovn/kube-ovn#2739]
# Expected Behavior
1、在自定义vpc下的pod中，可以ping通集群中任意node
2、在vpc-nat-gw-gw1-0中，可以ping通集群中任意node

# Actual Behavior
1、在自定义vpc下的pod中，不能ping通vpc-nat-gw-gw1-0所在的node，但可以ping通其他node节点。
2、在vpc-nat-gw-gw1-0中，不能ping通vpc-nat-gw-gw1-0所在的node，但可以ping通其他node节点。
# Steps to Reproduce the Problem
1. 参考 (https://kubeovn.github.io/docs/v1.11.x/guide/vpc/)
2. 参考 ( https://github.com/kubeovn/kube-ovn/issues/2710)

# Additional Info

- Kubernetes version: v1.26.3
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

#  kube-ovn version: 
```
v1.11.3
```

# operation-system/kernel version:
```
CentOS 7.9 Linux master 5.4.240-1.el7.elrepo.x86_64 
```

**Comment by bobz965** [comment]
ipvlan 也ping不通主网卡， macvlan 应该也一样。 这应该不是bug。 可以看下terway ipvlan怎么把node网卡和pod网卡拉平的

**Comment by oilbeater** [comment]
Macvlan 下主机网卡和宿主机网卡无法直接互通，需要交换机开启 hairpin 模式

**Comment by oilbeater** [comment]
> 请问怎么开启hairpin,我现在实验环境是vmware workstation虚拟机环境

这个需要查看 vmware 相关的配置手册，一般来讲我们会把 nat-gateway 放在特定的节点，并不要求所在节点必须和 nat-gateway 能够互访

**Comment by willzhang** [comment]
我的怎么可以, vmware vsphere环境，物理机环境，主网卡是k8s管理，另一个网卡是macvlan做gw，都是同一个段192.168.1.x
```
root@node100:~# hostname -I
192.168.1.100 20.65.0.2 
root@node100:~# 
root@node100:~# kubectl -n ns1 exec -it vpc1-pod  -- ping 192.168.1.100
PING 192.168.1.100 (192.168.1.100): 56 data bytes
64 bytes from 192.168.1.100: seq=0 ttl=63 time=3.232 ms
64 bytes from 192.168.1.100: seq=1 ttl=63 time=1.811 ms
64 bytes from 192.168.1.100: seq=2 ttl=63 time=1.773 ms
64 bytes from 192.168.1.100: seq=3 ttl=63 time=1.602 ms
64 bytes from 192.168.1.100: seq=4 ttl=63 time=2.046 ms
```
