### ISSUE TITLE
does kube-ovn-pinger cost too much RAM？

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2764]
![image](https://user-images.githubusercontent.com/7981158/236608307-2118211d-c8c2-4224-a3b9-113c3f186d56.png)

**Comment by bobz965** [comment]
it looks like one pinger cost more than 1G RAM

**Comment by oilbeater** [comment]
You can use top on the host to check the RSS usage of kube-ovn-pinger

**Comment by bobz965** [comment]
![image](https://user-images.githubusercontent.com/7981158/236613974-1854f820-f64a-455b-b517-852d111d51a7.png)


retest again, not see this issue again. maybe my env has something who eat the ram.
