### ISSUE TITLE
是否支持okd?

### ISSUE THREAD

**Issue by zzzzzhy** [kubeovn/kube-ovn#2767]
请问能在okd上使用吗,我试着安装了两次,全部失败了,不知道是不是配置没写对还是本来就不支持,过来问一下
使用的配置:
只修改了SVC_CIDR="10.96.0.0/12"   这一项
value更换为oc get configmaps -n kube-system cluster-config-v1 -o yaml得到的network service ip
出现的情况:
安装完[Step 3/6] Install Kube-OVN,pod开始运行起来之后会破坏所有节点的网卡,导致IP全部丢失

**Comment by oilbeater** [comment]
Kube-OVN 目前只在标准 kubernetes 上进行测试，没有对 okd 做过专门适配，okd 对网络插件的管理有一套自己的体系，第三方网络插件应该需要关闭某些网络管理 operator，建议咨询 okd 的技术人员问一下第三方网络插件应该如何安装。

**Comment by zzzzzhy** [comment]
> Kube-OVN 目前只在标准 kubernetes 上进行测试，没有对 okd 做过专门适配，okd 对网络插件的管理有一套自己的体系，第三方网络插件应该需要关闭某些网络管理 operator，建议咨询 okd 的技术人员问一下第三方网络插件应该如何安装。
好的,感谢解答
