### ISSUE TITLE
特殊集群下，自定义VPC访问外网方案

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#2793]
### Feature request

目前在一个k8s集群中，使用kubevrt创建了几台虚机，然后用这几台虚机再创建了个k8s集群。
两个集群都是用的kubeovn作为网络插件，版本都是1.11.3
目标是能在虚机创建的k8s集群内，使用自定义vpc访问外网。

### Use case

目前使用虚机创建的k8s集群内，自定义VPC无法访问外网。
怀疑是ovn-vpc-external-network的配置问题。
附上ovn-vpc-external-network的配置：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/06a9089e-fa63-4b13-a037-5884f9fdbb13)

自定义VPC网关pod的网卡信息：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/92a93895-16dc-4162-bbe8-71f6fe73bdce)

自定义VPC网关pod的路由：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/869ba596-b800-4454-8edb-8dd8b370bf5d)

自定义VPC网关内ping外部网关 10.32.0.1
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/7c0c4490-ac8e-483c-8225-3e865f9e6797)
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/c2d1231f-462b-41fc-9257-395c0a777553)

麻烦指点一下，这个环境下的自定义VPC需要如何配置才能访问外网（上层的局域网以及公网），谢谢

**Comment by shane965** [comment]
可以试试创建一个EIP，再ping一下试试

参考 https://kubeovn.github.io/docs/v1.12.x/guide/vpc/ 页面下的评论：
```
在使用vpc-nat-gw时需要注意：
nat gw创建之后，net1 arp时关闭的，ping不通 网关，创建eip后会自动打开arp，可以ping通
```

**Comment by geniusxiong** [comment]
> 可以试试创建一个EIP，再ping一下试试
> 
> 参考 https://kubeovn.github.io/docs/v1.12.x/guide/vpc/ 页面下的评论：
> 
> ```
> 在使用vpc-nat-gw时需要注意：
> nat gw创建之后，net1 arp时关闭的，ping不通 网关，创建eip后会自动打开arp，可以ping通
> ```

创建了个eip，好像确实有点不一样的地方：

![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/d37b7e33-4bb3-44a7-a65b-6c7af72b97c9)

网关pod内抓包，和之前对比，只有OUT了，而且会收到10.32.0.1的arp报文：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/ff75ed81-94fd-41b7-be00-cbfd514981a6)

在宿主机（虚拟机）上抓包，也有out的包和arp报文
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/b82b8cc3-60c7-47b2-aa37-b6789841fcba)

不过还是ping不通

**Comment by geniusxiong** [comment]
刚才又测试了一下，如果网关pod访问的是集群的其他节点，集群的其他节点是有回包的，但是网关pod收不到

网关pod ping 集群的另一个节点，ip是10.32.0.190
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/9e3c9930-3024-4589-afc4-f50718a296f3)

在那个节点上抓包，是有收到包，以及有回复的：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/d46ce03a-7615-48a2-8d05-e3b10328e823)

不过在网关pod抓包，只有发出的，没有回包，在网关pod所在的宿主机抓包，也是只有发包，没有回包：
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/6311a920-a09a-458d-ba8d-5fed7d80f8b5)
