### ISSUE TITLE
How do you update CRDs when there are changes in pkg/apis?

### ISSUE THREAD

**Issue by phosae** [kubeovn/kube-ovn#2802]
I've browsed the project code and some PRs like
- [388 chore: change crd form v1beta1 to v1](https://github.com/kubeovn/kube-ovn/pull/388)
- [2753, feat: natgw qos](https://github.com/kubeovn/kube-ovn/pull/2753)

However, I couldn't find any convenient ways (make targets, hack shell scripts) to update CRDs in `install.sh`, `charts` and `yamls` convinient.

How do you handle this?
@oilbeater @shane965

**Comment by shane965** [comment]
> I've browsed the project code and some PRs like
> 
> * [388 chore: change crd form v1beta1 to v1](https://github.com/kubeovn/kube-ovn/pull/388)
> * [2753, feat: natgw qos](https://github.com/kubeovn/kube-ovn/pull/2753)
> 
> However, I couldn't find any convenient ways (make targets, hack shell scripts) to update CRDs in `install.sh`, `charts` and `yamls` convinient.
> 
> How do you handle this? @oilbeater @shane965

I manually maintain the CRD files in this project. this is not a good way.

Can we maybe use some tools to generate the CRD files in the future? @oilbeater

**Comment by oilbeater** [comment]
There are a few historical reasons why we had to manage the CRDs and controller-runtime framework manually. When we first built kube-ovn, the kube-builder tools were not yet mature enough for our needs. Going forward, we can investigate ways to automate the generation of CRDs and optimize our workflow.
