### ISSUE TITLE
New IPPool resource for fine-grained subnet cidr division. 

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#2811]
### Feature request

By dividing the CIDR into segments for management, we can bind a segment to a namespace, thus improving ease of use.

**Comment by patriziobassi** [comment]
It would be nice to allow the users to specify the ippool name in pod/deployments/… annotation without the need to use ip ranges in annotations

**Comment by patriziobassi** [comment]
Hi, in which release is this feature expected to land? 1.11.x ?

**Comment by oilbeater** [comment]
> Hi, in which release is this feature expected to land? 1.11.x ?

@patriziobassi This new feature includes API changes and fundamental changes to the IPAM component, and we plan to release it in the 1.12 release.

**Comment by patriziobassi** [comment]
> > Hi, in which release is this feature expected to land? 1.11.x ?
> 
> @patriziobassi This new feature includes API changes and fundamental changes to the IPAM component, and we plan to release it in the 1.12 release.

great! any ETA for it?

**Comment by oilbeater** [comment]
@patriziobassi Most of the code work is ready, we are trying to organize the document and release related work, and it should be officially released at the end of this month. You can try the master branch to check if it works before release and we will appreciate for that.
