### ISSUE TITLE
which is default subnet when custom subnet attached default namespace?

### ISSUE THREAD

**Issue by todaygood** [kubeovn/kube-ovn#2854]
# Expected Behavior

default subnet  always is ovn-default .

# Actual Behavior

default subnet  is not ovn-default .

# Steps to Reproduce the Problem

1. create subnet  A  designated with default namespace.
2. create pod 
3. I find the pod's ip of step2  is allocated in subnet A . 

# Additional Info

- Kubernetes version:
1.26.2
  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version: 1.11.3
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by oilbeater** [comment]
@todaygood Did you create the pod not in the default namespace?

**Comment by todaygood** [comment]
> Did you create the pod not in the default namespace?
In my step1, the subnet which is bound to default and AAA namespace  and its default property is "false".
In my step2 ,  the pod which  I created  is in default namespace. 

>The default subnet means namespace not bind to a specific subnet will use this subnet 
I agreee with you , but  ` kubectl get subnet ` do not  show namespace info and show "default property", so It is easily misleaded.

**Comment by oilbeater** [comment]
Yes, the output of `kubectl get subnet` should be improved
