### ISSUE TITLE
microk8s kube-ovn addon - ovn pinger and ovn cni containers in crashloopbackoff

### ISSUE THREAD

**Issue by parshva-shah-dsw** [kubeovn/kube-ovn#2874]
# Expected Behavior
All pods should get deployed 

<img width="611" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/117802398/eb16f42e-1a17-42a8-96e7-55730942a7a1">

# Actual Behavior
<img width="584" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/117802398/3eb0bfd2-4117-4ce3-afa4-26c8a8deb55a">

ovn controller pod logs :-

6 subnet.go:318] format subnet ovn-default, changed false
W0526 11:23:02.624182       6 warnings.go:70] unknown field "status.availableIPs"
W0526 11:23:02.624198       6 warnings.go:70] unknown field "status.usingIPs"
W0526 11:23:02.637754       6 warnings.go:70] unknown field "status.availableIPs"
W0526 11:23:02.637776       6 warnings.go:70] unknown field "status.usingIPs"
E0526 11:23:02.638029       6 subnet.go:603] subnet ovn-default cidr 10.1.0.0/16 conflict with node v2-master address 10.1.0.17
I0526 11:23:02.638274       6 event.go:285] Event(v1.ObjectReference{Kind:"Subnet", Namespace:"", Name:"ovn-default", UID:"b8ecb6a7-c449-4706-9711-1ab7c3a33fa2", APIVersion:"kubeovn.io/v1", ResourceVersion:"155805", FieldPath:""}): type: 'Warning' reason: 'ValidateLogicalSwitchFailed' subnet ovn-default cidr 10.1.0.0/16 conflict with node v2-master address 10.1.0.17
W0526 11:23:02.651569       6 warnings.go:70] unknown field "status.availableIPs"
W0526 11:23:02.651588       6 warnings.go:70] unknown field "status.usingIPs"
E0526 11:23:02.651810       6 subnet.go:186] error syncing 'ovn-default': subnet ovn-default cidr 10.1.0.0/16 conflict with node v2-master address 10.1.0.17, requeuing

# Additional Info

- Kubernetes version: v1.26.4 - MicroK8s v1.26.4 revision 5219
- kube-ovn version: v1.10.0
- operation-system/kernel version: Red Hat Enterprise Linux 8.8 (Ootpa)
  
We are installing kube-ovn add on in microk8s in RHEL 8.8. 
Below steps were used to enable add on in microk8s https://microk8s.io/docs/addon-kube-ovn
Please help here if anyone have faced same kind of issues while installing.

**Comment by oilbeater** [comment]
@parshva-shah-dsw I think it's a bug on how microk8s try to install kube-ovn. The CRDs are not up to date and the pod CIDRs overlapped with Node CIDRs. You can file an issue to the microk8s community or try to delete kube-ovn and calico then install kube-ovn manually from https://kubeovn.github.io/docs/v1.11.x/en/start/one-step-install/

**Comment by parshva-shah-dsw** [comment]
@oilbeater  thanks for your help. we have raised issue to microk8s community also.

After following the steps shared in the link. we installed and it worked well in single node setup. but in multi node setup it is failing in kube ovn cni pod 

<img width="521" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/117802398/50c74882-67fd-4734-be56-e017a5f608c4">


kube ovn cni logs : - 

-------------------------------------------------------------------------------
Kube-OVN:
  Version:       v1.11.6
  Build:         2023-05-25_06:34:48
  Commit:        git-f071a97
  Go Version:    go1.19.9
  Arch:          amd64
-------------------------------------------------------------------------------
I0530 07:37:19.665298  197316 config.go:148] node name not specified in command line parameters, fall back to the environment variable
I0530 07:37:19.665320  197316 config.go:315] no --kubeconfig, use in-cluster kubernetes config
I0530 07:37:19.683753  197316 k8s.go:25] succeeded to dial apiserver "10.152.183.1:443"
I0530 07:37:19.698344  197316 config.go:166] daemon config: &{ eth0 br-phy 1400 1360 false mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0xc0002849c0 0xc0006101e0 unifyai-v2-main 10.96.0.0/12  true false false 10665 geneve /etc/cni/net.d /kube-ovn/01-kube-ovn.conflist 01-kube-ovn.conflist provider  kube-system external true true}
I0530 07:37:19.705246  197316 cniserver.go:179] finish adding chassis annotation
I0530 07:37:19.722035  197316 ovs_linux.go:426] wait ovn0 gw ready

Any idea on this issue @oilbeater would be a great help

**Comment by oilbeater** [comment]
Did you install kube-ovn on the failed node before? If so, you need to follow the uninstall step here https://kubeovn.github.io/docs/v1.11.x/en/ops/delete-worker-node/ to clean up the node

**Comment by parshva-shah-dsw** [comment]
@oilbeater 
Now all pods are up

<img width="468" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/117802398/d4674329-00a9-405b-bfcc-45e580b58ac7">



<img width="514" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/117802398/38525f1e-8336-46a9-b907-0a7c89daa07e">

while connecting to internet from inside the pod there are timeout errors in-frequently. any idea on this?
