### ISSUE TITLE
kube-ovn need a tool to sync manifests including in install.sh and charts and yamls

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2881]
### Feature request

类似 operator-sdk 有两个方便的脚手架生成工具
make generate
make manifests

目前类似 make generate的实现方式在 kube-ovn/hack 目录下面，但是kube-ovn 目前有三份crd等配置相关的维护位置，需要有一个 类似 make manifests 的工具，可以`一次性`同步 install.sh, charts, yamls 等目录下 manifests 相关的文件

**Comment by shane965** [comment]
看起来和这个issue要实现的功能有点类似 #2802

**Comment by bobz965** [comment]
> 看起来和这个issue要实现的功能有点类似 #2802

是的，维护的位置比较多，很需要一个工具
