### ISSUE TITLE
namespace annotation to set default subnet

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#2892]
### Feature request

ovn-default is the default subnet used by system pods such as those in the kube-system namespace.

When creating a new namespace and creating a new subnet restricted to that namespace, it would be good to have the possibility to add an annotation on the namespace it selft to select the new custom subnet ad default, so the user doesn't need to annotate each pod/deployment, otherwise it will keep on using the "ovn-default" subnet.

Thank you

**Comment by oilbeater** [comment]
It looks like a bug, when create a subnet and set the namespaces field to the new created ns it should automatically bind the namespace to the subnet. Can you give a reproducible steps

**Comment by patriziobassi** [comment]
It's a design issue, because if i add 2 dedicated Networks i would like to set a default one and specify the other when needed

**Comment by oilbeater** [comment]
The annotation will be added to namespace by the order of the 2 subnets bind to it. You can edit the annotation `ovn.kubernetes.io/logical_switch: subnet1,subnet2` and put the default one at the first place

**Comment by patriziobassi** [comment]
Good, so i will give a try and get back to you

**Comment by patriziobassi** [comment]
trying to remove:
`kubectl annotate ns cos ovn.kubernetes.io/logical_switch-`
i get:
`W0613 19:14:05.081765       6 namespace.go:63] no logical switch annotation for ns cos
`

even setting the annotation on creation doesn't work.

**Comment by oilbeater** [comment]
You need to set the namespace into the `namespaces` field in two subnets spec, the controller will set the annotation automatically in the namespace and then you can reorder them by namespace annotation.
