### ISSUE TITLE
ovs-dpdk场景下helm部署和install.sh脚本部署存在差异

### ISSUE THREAD

**Issue by lynn901** [kubeovn/kube-ovn#2898]
# Expected Behavior
部署结果相同
# Actual Behavior
instal脚本部署后，会创建两个deamonset ovs-ovn 和ovs-ovn-dpdk
helm部署，只会创建ovs-ovn一个deamonset
# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eki.0", GitCommit:"83c85a6e50757c6bbb81c6ceaac60234c1161817", GitTreeState:"clean", BuildDate:"2021-10-19T08:30:59Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eki.2.4.0", GitCommit:"426a9d4ae52a439beead2a83262d1bc2210905ba", GitTreeState:"clean", BuildDate:"2023-01-18T10:05:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}


- kube-ovn version:
  
  ```
master
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
 BigCloud Enterprise Linux For Euler 21.10 LTS
4.19.90-2211.2.0.0176.oe1.x86_64
  ```

<!-- Any other additional information -->

**Comment by hongzhen-ma** [comment]
Sorry. This problem is introduced in PR  https://github.com/kubeovn/kube-ovn/pull/2833

**Comment by hongzhen-ma** [comment]
I check install.sh in branch release-1.11, this problem should also exist.
I'll modify it soon.

**Comment by lynn901** [comment]
> Sorry. This problem is introduced in PR #2833

如果采用这样的方式，一个集群就没办法同时有普通ovs的node和dpdk类型的node了
