### ISSUE TITLE
使用loadbalacner功能时 创建loadbalacner service ip之后无法外部访问

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#2905]
参考https://kubeovn.github.io/docs/v1.11.x/guide/loadbalancer-service/ 使用Lb功能，服务创建之后lb ip 可以分配，但是lb的ip无法访问,在lb的pod内部iptables -t nat -L -n -v查看，也没找到dnat规则，这种情况一般是什么原因导致的呢

k8s 版本1.20
kube-ovn：kube-ovn:v1.11.1
multus-cni: 0.3.1

**Comment by oilbeater** [comment]
请把使用的步骤贴一下

**Comment by wolgod** [comment]
> 请把使用的步骤贴一下

问题解决了，underlay模式下，lb的子网和主机的子网在一个wlan下 lb就可以使用了
