### ISSUE TITLE
虚拟机关闭的情况下，重启kube-ovn-controller，ip会被释放

### ISSUE THREAD

**Issue by liuzhen21** [kubeovn/kube-ovn#2916]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. 关闭虚拟机
2. 重启kube-ovn-controller
3. 虚拟机的ip被释放

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

现象和 https://github.com/kubeovn/kube-ovn/issues/2344 一致， 
https://github.com/kubeovn/kube-ovn/pull/2504 并没有解决我的问题，我的环境中并没有
```
vm.Spec.Template.ObjectMeta.Annotations[util.AttachmentNetworkAnnotation]
```
util.AttachmentNetworkAnnotation 在pod中有，在vm中没有
gcLogicalSwitchPort() 在启动的时候执行，释放了关闭状态下虚拟机的ip

**Comment by hongzhen-ma** [comment]
util.AttachmentNetworkAnnotation 在pod中有，在vm中没有

这个是怎么配置的？可以单独给 vm pod 添加附加网卡吗？

**Comment by liuzhen21** [comment]
> util.AttachmentNetworkAnnotation 在pod中有，在vm中没有
> 
> 这个是怎么配置的？可以单独给 vm pod 添加附加网卡吗？
vm里配置有网卡，但是没有这个annotion
这个annotion是kubevirt在创建pod时添加的
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go 
的1265行左右
```
func generatePodAnnotations(vmi *v1.VirtualMachineInstance) (map[string]string, error) {
	annotationsSet := map[string]string{
		v1.DomainAnnotation: vmi.GetObjectMeta().GetName(),
	}
	for k, v := range filterVMIAnnotationsForPod(vmi.Annotations) {
		annotationsSet[k] = v
	}

	annotationsSet[podcmd.DefaultContainerAnnotationName] = "compute"

	nonAbsentIfaces := vmispec.FilterInterfacesSpec(vmi.Spec.Domain.Devices.Interfaces, func(iface v1.Interface) bool {
		return iface.State != v1.InterfaceStateAbsent
	})
	nonAbsentNets := vmispec.FilterNetworksByInterfaces(vmi.Spec.Networks, nonAbsentIfaces)
	multusAnnotation, err := GenerateMultusCNIAnnotation(vmi.Namespace, nonAbsentIfaces, nonAbsentNets)
	if err != nil {
		return nil, err
	}
	if multusAnnotation != "" {
		annotationsSet[MultusNetworksAnnotation] = multusAnnotation
	}

```
