### ISSUE TITLE
kube-ovn 升级方案

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#2920]
我现在使用kube-ovn的版本是v1.8.2 ,但是有严重的bug，如果我想升级v1.11.3的话，在官网没有找到相应的升级文档，请问有什么升级的文档介绍吗

**Comment by bobz965** [comment]
或许 可以参考下这个： 
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/8f887cd7-a16e-49f1-a014-1397981c581b)

**Comment by oilbeater** [comment]
建议比对一下 install.sh 里 yaml 的区别再去 apply

**Comment by wolgod** [comment]
> 建议比对一下 install.sh 里 yaml 的区别再去 apply

官方能否提供一个标准的跨版本升级的方案呢

**Comment by zhoulw** [comment]
> 或许 可以参考下这个： ![image](https://user-images.githubusercontent.com/7981158/244600701-8f887cd7-a16e-49f1-a014-1397981c581b.png)

大佬，问一下，切换到原生的ovn-eip，有对应的升级的脚本吗？

**Comment by bobz965** [comment]
> > 或许 可以参考下这个： ![image](https://user-images.githubusercontent.com/7981158/244600701-8f887cd7-a16e-49f1-a014-1397981c581b.png)
> 
> 大佬，问一下，切换到原生的ovn-eip，有对应的升级的脚本吗？

暂时没有，可以多模拟测试下
