### ISSUE TITLE
 ovn-central 出现 inconsistent data

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#2943]
ovn-version: 1.8.2
按照官方的restore命令去恢复，根据脚本内容执行过程中某一部出现异常，脚本就会完全退出，  

restore 命令大致流程为
a.将ovn-central 副本数设置为0
b.重新生成standalone数据库文件ovnnb_db_standalone.db
c. 移除三个节点上的nb和sb
d. 将第一个节点上的ovnnb_db_standalone.db mv成ovnnb_db.db
e.将ovn-central副本数改为3
f.将工作节点所有ovs-ovn 重启

但是执行到d的时候失败，导致整个脚本退出了，然后整个集群的ovs-ovn和ovn-cni 的pod全crash掉了，整个集群网络不可用了，
后来通过手动将ovn-central 副本数改为3 ，集群才恢复

问题1： 如果不生成ovnnb_db_standalone.db 直接把三个节点数据删除，貌似重新生成pod的ip 也不会发生变化，应该会重新从annotation同步吧，那么生成standalone的意义何在？

问题2： 1.8.2 版本为啥ovn-central 副本设为0后，ovs-ovn和ovn-cni的pod会crash，但是在1.11.1 版本上测试倒没有出现这个问题

**Comment by oilbeater** [comment]
1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出

**Comment by wolgod** [comment]
> 1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
> 2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出

感谢您的回答，我另外一个集群使用的是1.11.1,在集群没出现不一致的情况下，我尝试执行restore，出现以下错误
`wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2
wait all ovn-central pods running, availabel 2`

然后pod状态如下

`ovn-central-669c468f55-5kwrw           1/1     Running            0                     <none>
ovn-central-669c468f55-65rsw           0/1     CrashLoopBackOff   4                  <none>
ovn-central-669c468f55-6jl7b           1/1     Running `
其中ovn-central-669c468f55-65rsw 是存在备份数据库的节点，无法启动，错误日志如下
` * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
ovsdb-tool: ovsdb error: /etc/ovn/ovnnb_db.db: cannot identify file type
detected database corruption for file /etc/ovn/ovnnb_db.db, rebuild it.
ovsdb-tool: /etc/ovn/ovnnb_db.db: not a clustered database
failed to get sid from nb db file /etc/ovn/ovnnb_db.db
 * ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running`
是因为没有出现不一致不能执行吗？还是存在其他问题呢

**Comment by oilbeater** [comment]
也可以执行这个命令，有可能是 /etc/origin/ovn 目录下有其他文件干扰了备份和还原

**Comment by wolgod** [comment]
> 也可以执行这个命令，有可能是 /etc/origin/ovn 目录下有其他文件干扰了备份和还原

测试过多次都不行，恢复办法就是把crash的pod所在节点的 /etc/origin/ovn  目录下由standalone 的nb文件删除，才能恢复

**Comment by caohuilong** [comment]
> > 1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
> > 2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出
> 
> 感谢您的回答，我另外一个集群使用的是1.11.1,在集群没出现不一致的情况下，我尝试执行restore，出现以下错误
> 
> ```
> wait all ovn-central pods running, availabel 2
> wait all ovn-central pods running, availabel 2
> wait all ovn-central pods running, availabel 2
> ```
> 
> 然后pod状态如下
> 
> ```
> ovn-central-669c468f55-5kwrw           1/1     Running            0                     <none>
> ovn-central-669c468f55-65rsw           0/1     CrashLoopBackOff   4                  <none>
> ovn-central-669c468f55-6jl7b           1/1     Running 
> ```
> 
> 其中ovn-central-669c468f55-65rsw 是存在备份数据库的节点，无法启动，错误日志如下 ` * ovn-northd is not running
> 
> * ovnnb_db is not running
> * ovnsb_db is not running
>   ovsdb-tool: ovsdb error: /etc/ovn/ovnnb_db.db: cannot identify file type
>   detected database corruption for file /etc/ovn/ovnnb_db.db, rebuild it.
>   ovsdb-tool: /etc/ovn/ovnnb_db.db: not a clustered database
>   failed to get sid from nb db file /etc/ovn/ovnnb_db.db
> * ovn-northd is not running
> * ovnnb_db is not running
> * ovnsb_db is not running`
>   是因为没有出现不一致不能执行吗？还是存在其他问题呢

用ovsdb-tool cluster-to-standalone转换出来的数据库文件启动ovn-central，也遇到了这个问题。但是用原始的数据库文件启动ovn-central报如下错误：

**Comment by wolgod** [comment]
> > > 1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
> > > 2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出
> > 
> > 
> > 感谢您的回答，我另外一个集群使用的是1.11.1,在集群没出现不一致的情况下，我尝试执行restore，出现以下错误
> > ```
> > wait all ovn-central pods running, availabel 2
> > wait all ovn-central pods running, availabel 2
> > wait all ovn-central pods running, availabel 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后pod状态如下
> > ```
> > ovn-central-669c468f55-5kwrw           1/1     Running            0                     <none>
> > ovn-central-669c468f55-65rsw           0/1     CrashLoopBackOff   4                  <none>
> > ovn-central-669c468f55-6jl7b           1/1     Running 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其中ovn-central-669c468f55-65rsw 是存在备份数据库的节点，无法启动，错误日志如下 ` * ovn-northd is not running
> > 
> > * ovnnb_db is not running
> > * ovnsb_db is not running
> >   ovsdb-tool: ovsdb error: /etc/ovn/ovnnb_db.db: cannot identify file type
> >   detected database corruption for file /etc/ovn/ovnnb_db.db, rebuild it.
> >   ovsdb-tool: /etc/ovn/ovnnb_db.db: not a clustered database
> >   failed to get sid from nb db file /etc/ovn/ovnnb_db.db
> > * ovn-northd is not running
> > * ovnnb_db is not running
> > * ovnsb_db is not running`
> >   是因为没有出现不一致不能执行吗？还是存在其他问题呢
> 
> 用ovsdb-tool cluster-to-standalone转换出来的数据库文件启动ovn-central，也遇到了这个问题。但是用原始的数据库文件启动ovn-central报如下错误，还是没法恢复集群： ![508127ec8f3912c24cfb76f270b671b](https://user-images.githubusercontent.com/26712324/248613501-5a2b4a67-3f7e-4298-bd78-c9e82b84090f.png)

只能把三个节点的数据库文件都删了，完全重建才可以

**Comment by wolgod** [comment]
@oilbeater  我再次遇到了ovnsb 出现了inconsistent data,
不过通过查看日志发现，当出现错误的时候三个节点同时报了以下错误
`2023-08-04T04:40:49.397Z|00657|ovsdb_server|ERR|syntax "["set",[]]": syntax error: set must have 1 to 4294967295 members but 0 are present`
然后之后新创建的pod就无法分配成功ip
然后在三个节点里sb的数据文件里都发现了以下数据
![image](https://github.com/kubeovn/kube-ovn/assets/4132442/e28c7c66-5c95-4dfa-bdc6-ee4ffb25206a)

然后我尝试在三个节点把这些数据删除后，集群仍然没有恢复，然后我把ovn-central scale成0，然后在scala成3 这个时候集群状态显示ok,不过我在另外的测试集群尝试通过命令往sb里插入数据，提示的错误和上面日志里一样，但是数据并没有写入
<img width="1378" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/4132442/49490098-ca83-4d13-a975-81d244e425b2">

但我现在无法找到在inconsistent data的集群里，为什么三个节点都会写入以上的记录，看comment 应该是northd进程写的，northd进程去操作sb应该也会遵守sb的schema约束吧，还是说有其他写入场景？
非常期待您的答复

**Comment by DWC666** [comment]
> > 1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
> > 2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出
> 
> 感谢您的回答，我另外一个集群使用的是1.11.1,在集群没出现不一致的情况下，我尝试执行restore，出现以下错误
> 
> ```
> wait all ovn-central pods running, availabel 2
> wait all ovn-central pods running, availabel 2
> wait all ovn-central pods running, availabel 2
> ```
> 
> 然后pod状态如下
> 
> ```
> ovn-central-669c468f55-5kwrw           1/1     Running            0                     <none>
> ovn-central-669c468f55-65rsw           0/1     CrashLoopBackOff   4                  <none>
> ovn-central-669c468f55-6jl7b           1/1     Running 
> ```
> 
> 其中ovn-central-669c468f55-65rsw 是存在备份数据库的节点，无法启动，错误日志如下 ` * ovn-northd is not running
> 
> * ovnnb_db is not running
> * ovnsb_db is not running
>   ovsdb-tool: ovsdb error: /etc/ovn/ovnnb_db.db: cannot identify file type
>   detected database corruption for file /etc/ovn/ovnnb_db.db, rebuild it.
>   ovsdb-tool: /etc/ovn/ovnnb_db.db: not a clustered database
>   failed to get sid from nb db file /etc/ovn/ovnnb_db.db
> * ovn-northd is not running
> * ovnnb_db is not running
> * ovnsb_db is not running`
>   是因为没有出现不一致不能执行吗？还是存在其他问题呢

同样遇到了这个问题，请问官方有解决方案吗？

**Comment by DWC666** [comment]
> 1. 目前针对数据库文件完全不存在做了处理，能够恢复 vpc，subnet 和 pod 的网络信息，但是一些其他配置目前没有测试可能存在遗漏，从数据库恢复是更稳妥的方案
> 2. 1.11 版本进行了处理，再 ovn-central 中断的情况下不会退出

请问nb数据库文件不存在时，ovn使用哪里的数据重建nb数据库文件？

**Comment by oilbeater** [comment]
1.8 版本已经比较老了，过程中我们碰到过一些 ovn 数据库的 bug，这些问题在新版本已经很少再遇到了，建议升级到新版本再看有没有类似问题
