### ISSUE TITLE
ipam not release not used ip

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2997]
# Expected Behavior
ipam should release not used ip
# Actual Behavior
ipam not release not used ip
# Steps to Reproduce the Problem

1. deploy master install.sh
1. create subnet, create pod, delete pod, 
1.

# Additional Info
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/fe618a65-cd79-4e84-8330-0ddc685f8520)

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
This issue may be fixed in #2977. Please use the latest version and try again.
