### ISSUE TITLE
crd ippool seems lost rbac in install.sh

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#2999]
# Expected Behavior

# Actual Behavior

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/a0e88b80-6d48-4ec6-93a7-be210bccbfa0)

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
Looks like the `install.sh` is not correct. Please use the latest `install.sh` and try again.
