### ISSUE TITLE
how about change nat-gw base image as ubuntu22.04 as the other image

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3025]
# Expected Behavior

# Actual Behavior

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/c3d07cce-b0b6-4f12-8931-be8d16af2019)

apk install seems is unstable than ubuntu22.04 apt  

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by shane965** [comment]
I have encountered a similar issue before, and it is usually resolved by changing the APK repository, just as follows:

```
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN set -ex \
    && apk update --allow-untrusted \
    && apk upgrade --allow-untrusted  \
    && apk add --no-cache  --allow-untrusted \
    bash \
    iproute2 \
    iptables \
    iputils \
    tcpdump \
    conntrack-tools
```

If this issue can be resolved by changing the nat-gw base image, I think it could be beneficial, especially for those who need to build their own images.

**Comment by bobz965** [comment]
> I have encountered a similar issue before, and it is usually resolved by changing the APK repository, just as follows:
> 
> ```
> RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
> 
> RUN set -ex \
>     && apk update --allow-untrusted \
>     && apk upgrade --allow-untrusted  \
>     && apk add --no-cache  --allow-untrusted \
>     bash \
>     iproute2 \
>     iptables \
>     iputils \
>     tcpdump \
>     conntrack-tools
> ```
> 
> If this issue can be resolved by changing the nat-gw base image, I think it could be beneficial, especially for those who need to build their own images.

thanks for your reply
