### ISSUE TITLE
multi nic: multus call kube-ovn oom-killled

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3043]
# Expected Behavior

# Actual Behavior
if multus limit to 50Mi, `multus-daemon call kubeovn` will be oom killed（sacrifice child）.  
# Steps to Reproduce the Problem

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/9ec1093a-cc2a-4c62-86b8-028a71e6b956)
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/f6e1c0dd-ddbc-4af1-a0fe-db4552521964)

it looks like kube-ovn cost total-vm: 785284KB, anon rss 19656KB, file rss: 34184KB

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
Which version are you using? I cannot reproduce the OOM error.

**Comment by bobz965** [comment]
> Which version are you using? I cannot reproduce the OOM error.

ohhh,  it is kube-ovn:v1.11.9

**Comment by zhangzujian** [comment]
I cannot reproduce this error in v1.11.9 either. Could you please provide more details?

**Comment by bobz965** [comment]
> I cannot reproduce this error in v1.11.9 either. Could you please provide more details?

噢 我们的环境之前有很多 vm 在重建，可能是在这种情况下，导致并发的调用  kube-ovn-cni 二进制同时存在多个，从另一个角度看，将 multus-daemon 的内存设置小一点可以稳定复现，但是我这边最想弄清楚的点是 为什么 oom kill 信息显示的调用者和被调用者（kubeovn 二进制）占用的内存会那么多，我不太清楚一个 kubeovn cni 二进制的调用一般情况下应该占用多少内存。
