### ISSUE TITLE
Unable to install kube-ovn 1.12.0 on k8s 1.21.5 with install.sh directly 

### ISSUE THREAD

**Issue by Longchuanzheng** [kubeovn/kube-ovn#3044]
# Expected Behavior
Install kube-ovn 1.12.0 on k8s 1.21.5 with install.sh directly 
# Actual Behavior
Something went wrong:
![b0798cd6d275e7be5b065b31fa62b6a](https://github.com/kubeovn/kube-ovn/assets/49519342/93ba845e-7570-479f-b074-b0774e1bead7)

# Steps to Reproduce the Problem

1.exec bash install.sh

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
1.21.5
```

- kube-ovn version:
  
```
1.12.0 
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

we need to delete 
```
x-kubernetes-validations:
  - rule: "self  oldselfunamespaces :
    message: "This field is immutable. “
```
as well as change `maxUnavailable ` from 0 to 1 at line 3490

**Comment by zhangzujian** [comment]
Thanks for the report! Kube-OVN v1.12.0 requires k8s >= v1.23, and we will update the document recently.
