### ISSUE TITLE
a bug in the method ChassisExist

### ISSUE THREAD

**Issue by DWC666** [kubeovn/kube-ovn#3049]
# Expected Behavior
when the chassis not exist, the method ChassisExist return false
# Actual Behavior
the method ChassisExist return true
# Steps to Reproduce the Problem
if the output is a empty str, the method will return true, because len(strings.Split(output, "\n")) is 1, not 0.
<img width="895" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/44437799/d153408d-0782-43b9-9f2d-0f16b8030df6">

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
v1.11.3
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
Could you please commit a PR to fix it?
