### ISSUE TITLE
master kube-ovn unknown flag: --enable-tproxy

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3089]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. run master install.sh
1.
1.

# Additional Info
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/95d57d7b-ae0e-4f23-8c23-8cb4102fe2bc)

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by zhangzujian** [comment]
Pull the latest image and try again.

**Comment by bobz965** [comment]
> Pull the latest image and try again.
> 
> v1.12.0 has not been released, You should pull the latest image when you are using the newest installation script/chart.

ok
