### ISSUE TITLE
这里的代码是这样子的吗？”lr-routes-add“

### ISSUE THREAD

**Issue by zhoulw** [kubeovn/kube-ovn#3096]
ovn nbctl中有批量添加routes的命令吗？ 

由于截图无法上传：

```  .../pkg/ovs/ovn-nb-logical_router_route.go  ```

55行：

```
if err = c.Transact("lr-routes-add", ops); err != nil {
		return fmt.Errorf("add static routes to %s: %v", lrName, err)
	}
```
应该是：``` lr-route-add``` 吧？

**Comment by zhoulw** [comment]
@gugulee  大佬，麻烦看下哈

**Comment by gugulee** [comment]
CreateLogicalRouterStaticRoutes 函数可以一次添加多条路由，不过需要你自己建立 routes 对象，https://github.com/kubeovn/kube-ovn/blob/88218743189db426fd6d97272a670762b71ba1ae/pkg/ovs/ovn-nb-logical_router_route.go#L26

具体使用方式可以看看这个函数相应的单元测试
