### ISSUE TITLE
kube-ovn-cni中开启bfdd服务

### ISSUE THREAD

**Issue by zhoulw** [kubeovn/kube-ovn#3097]
kube-ovn-cni daemon中的bfdd-control服务好像是没有在container的启动脚本中开启。 导致出现以下报错：
```
I0731 15:39:12.434317   48249 ovs_linux.go:368] MAC addresses of gateway 10.120.31.254 is dc:ef:80:5a:44:12
I0731 15:39:12.434352   48249 ovs_linux.go:369] network 10.120.31.20/24 with gateway 10.120.31.254 is ready for interface ovnext0 after 1 checks
E0731 15:39:12.513679   48249 ovs_linux.go:463] failed to get bfdd status, exit status 1
```

```
root@hci-ctl-1:/kube-ovn# bfdd-control status           
Error connecting to beacon on 127.0.0.1:957: Connection refused
root@hci-ctl-1:/kube-ovn# 
```

我也不太确定，应该是在DaemonSet中加入：
```
bfdd-beacon --control=Node-INTERNAL-IP:PORT
```

**Comment by zhoulw** [comment]
@bobz965  大佬，麻烦看一下是不是这样的

**Comment by bobz965** [comment]
`bfdd-control status   `   should run inside the ovnext namespace,

**Comment by zhoulw** [comment]
> `bfdd-control status ` should run inside the ovnext namespace,

```
[root@hci-ctl-1 ecmp-bfd]# ip netns exec ovnext bfdd-control status
There are 0 sessions:
[root@hci-ctl-1 ecmp-bfd]# 
````
是这样的哈？ 那是不是我哪里配错了，报错了。

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/def3f702-92a0-4d29-966e-9592bfdd5c79)

代码有检查，而且配置结果有打印，log 等级调到3

**Comment by zhoulw** [comment]
> ![image](https://user-images.githubusercontent.com/7981158/257179328-def3f702-92a0-4d29-966e-9592bfdd5c79.png)
> 
> 代码有检查，而且配置结果有打印，log 等级调到3
 
3Q，Thanks a lot！
