### ISSUE TITLE
新增策略路由把之前的路由删除了

### ISSUE THREAD

**Issue by wangshuai199398** [kubeovn/kube-ovn#3102]
# Expected Behavior
新增一条策略路由
# Actual Behavior
之前的几条路由删除了
# Steps to Reproduce the Problem
1. 之前的路由
Routing Policies
     31000                           ip4.dst == 10.244.0.0/16           allow
     31000                           ip4.dst == 100.64.0.0/16           allow
     30000                           ip4.dst == 172.16.10.180         reroute                100.64.0.2
     30000                           ip4.dst == 172.16.10.189         reroute                100.64.0.3
     30000                            ip4.dst == 172.16.10.27         reroute                100.64.0.4
     29000                ip4.src == $ovn.default.master1_ip4         reroute                100.64.0.2
     29000                ip4.src == $ovn.default.master2_ip4         reroute                100.64.0.4
     29000                ip4.src == $ovn.default.master3_ip4         reroute                100.64.0.3

2.kubectl apply -f vpc_default_route.yam 添加路由
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: ovn-cluster
spec:
  policyRoutes:
    - action: allow
      match: ip4.dst==10.0.0.0/16
      priority: 31000
3.之后的路由
Routing Policies
     31000                           ip4.dst == 10.244.0.0/16           allow
     31000                           ip4.dst == 100.64.0.0/16           allow
     31000                               ip4.dst==10.0.0.0/16           allow
     29000                ip4.src == $ovn.default.master1_ip4         reroute                100.64.0.2
     29000                ip4.src == $ovn.default.master2_ip4         reroute                100.64.0.4
     29000                ip4.src == $ovn.default.master3_ip4         reroute                100.64.0.3

# Additional Info
有一条路由也被删了
之前的路由
[root@master1 ~]# k ko nbctl lr-route-list ovn-cluster
IPv4 Routes
Route Table <main>:
              10.0.0.0/16               169.254.0.5 dst-ip
                0.0.0.0/0                100.64.0.1 dst-ip
之后的路由
IPv4 Routes
Route Table <main>:
                0.0.0.0/0                100.64.0.1 dst-ip
- Kubernetes version:
1.24.10
  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  1.11.8
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  "CentOS Linux 8"
5.15.63-1.el8.x86_64
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by bobz965** [comment]
感觉正确的结果， 应该是要 vpc spec policy 路由表 和 nb lr-route-list 保持幂等

**Comment by wangshuai199398** [comment]
> 感觉正确的结果， 应该是要 vpc spec policy 路由表 和 nb lr-route-list 保持幂等

大佬，请问一下，我apply 默认vpc ovn-cluster，正确的做法是什么啊？ 我看可能会影响ovn-cluster之前的配置。

**Comment by bobz965** [comment]
> 感觉正确的结果， 应该是要 vpc spec policy 路由表 和 nb lr-route-list 保持幂等

@张祖建 这个默认vpc的策略路由好像没有用spec来统一维护，看起来像是个bug

**Comment by wangshuai199398** [comment]
> > 感觉正确的结果， 应该是要 vpc spec policy 路由表 和 nb lr-route-list 保持幂等
> 
> @张祖建 这个默认vpc的策略路由好像没有用spec来统一维护，看起来像是个bug

对 默认vpc能通过yaml文件配置吗？

**Comment by qiutingjun** [comment]
some policies are maintained by codes in node.go and not reflected in the vpc spec, finally caused this problem.
```
		if nodeIP != "" {
			match := fmt.Sprintf("ip%d.dst == %s", af, nodeIP)
			action := ovnnb.LogicalRouterPolicyActionReroute
			externalIDs := map[string]string{
				"vendor":         util.CniTypeName,
				"node":           node.Name,
				"address-family": strconv.Itoa(af),
			}
			klog.Infof("add policy route for router: %s, match %s, action %s, nexthop %s, externalID %v", c.config.ClusterRouter, match, action, ip, externalIDs)
			if err = c.ovnNbClient.AddLogicalRouterPolicy(c.config.ClusterRouter, util.NodeRouterPolicyPriority, match, action, []string{ip}, externalIDs); err != nil {
				klog.Errorf("failed to add logical router policy for node %s: %v", node.Name, err)
				return err
			}
```

**Comment by oilbeater** [comment]
默认 vpc 的路由规则需要考虑 subnet 的网关模式和网关配置，会生成和更新大量特定的策略路由，现在没有考虑在默认 vpc 手动设置策略路由的情况
