### ISSUE TITLE
Using SwitchLBRule within vpc has no effect 

### ISSUE THREAD

**Issue by xuanyingcool** [kubeovn/kube-ovn#3130]
### Feature request

I need load balancing for my pod under vpc, according to the docs I created SwitchLBRule and Vip, I can't access it using ip+port inside the pod

My pods are all nginx.

I don't know if it's because I didn't understand the docs or I'm doing something wrong.

### Use case

kubectl get vpc
NAME          ENABLEEXTERNAL   ENABLEBFD   STANDBY   SUBNETS                  NAMESPACES
ovn-cluster   false            false       true      ["join","ovn-default"]   
test-vpc-1    false            false       true      ["net1"]                 ["ns4"]

kubectl get pods -n ns4 -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
ngx-vpc1-85dd6545f6-jl5f7   1/1     Running   0          2d20h   10.0.1.3   master   <none>           <none>
ngx-vpc1-85dd6545f6-w9f4s   1/1     Running   0          2d20h   10.0.1.2   node1    <none>           <none>
ngx-vpc1-85dd6545f6-z68cx   1/1     Running   0          2d20h   10.0.1.4   node1    <none>           <none>

kubectl get vip
NAME           NS    V4IP       MAC                 V6IP    PMAC   SUBNET   READY   TYPE
static-vip01         10.0.1.7   00:00:00:50:B0:AF   <nil>          net1     true    switch_lb_vip

kubectl get slr
NAME                VIP          PORT(S)                  SERVICE                             AGE
cjh-slr-nginx       10.0.1.7     8888/TCP                 ns4/slr-cjh-slr-nginx               2d6h
vpc-dns-test-cjh1   10.96.0.10   53/UDP,53/TCP,9153/TCP   kube-system/slr-vpc-dns-test-cjh1   2d20h

kubectl exec -it ngx-vpc1-85dd6545f6-jl5f7 -n ns4 -- curl 10.0.1.7:8888
curl: (28) Failed to connect to 10.0.1.7 port 8888: Operation timed out
command terminated with exit code 28

**Comment by bobz965** [comment]
I tried in my env, I think there are some limitations now:


``` bash


(.venv) root@empty:~/test/kube-ovn/lb-to-subnet/vip-cust-vpc# k get po -n ns1 -o wide
NAME         READY   STATUS    RESTARTS   AGE   IP         NODE                     NOMINATED NODE   READINESS GATES
lb-client    1/1     Running   0          29m   10.1.0.2   kube-ovn-worker          <none>           <none>
netshoot-0   1/1     Running   0          29m   10.1.0.3   kube-ovn-worker          <none>           <none>
netshoot-1   1/1     Running   0          29m   10.1.0.4   kube-ovn-control-plane   <none>           <none>

7db6f56c-52cf-4f36-84b3-45416822cca9    vpc-vpc1-tcp-loa    tcp        10.106.199.187:80      10.1.0.3:8000,10.1.0.4:8000
                                                            tcp        10.96.0.102:8000       10.1.0.3:8000,10.1.0.4:8000
(.venv) root@empty:~/test/kube-ovn/lb-to-subnet/vip-cust-vpc# k exec -it -n ns1           lb-client -- bash
lb-client:~# curl 10.96.0.102:8000
netshoot-0
lb-client:~#

# test passed

```

在自定义vpc 场景下的 subnet 中， 只有 svc cidr 的vip会触发 lb 规则，其他的ip 均不会，包括文档中的 1.1.1.1 等 vip，之前是可以的。


``` bash

7db6f56c-52cf-4f36-84b3-45416822cca9    vpc-vpc1-tcp-loa    tcp        1.1.1.1:8000           10.1.0.3:8000,10.1.0.4:8000
                                                            tcp        10.106.199.187:80      10.1.0.3:8000,10.1.0.4:8000
(.venv) root@empty:~/test/kube-ovn/lb-to-subnet/vip-cust-vpc#
(.venv) root@empty:~/test/kube-ovn/lb-to-subnet/vip-cust-vpc#
(.venv) root@empty:~/test/kube-ovn/lb-to-subnet/vip-cust-vpc# k exec -it -n ns1           lb-client -- bash
lb-client:~#
lb-client:~# curl 10.106.199.187:80
netshoot-0
lb-client:~# curl 1.1.1.1:8000

```

@oilbeater 大佬，你有空的话帮忙看下这个，可能是哪里加了限制，目前lb的vip 限制为只能使用 svc cidr 中的ip

**Comment by xuanyingcool** [comment]
我使用了service尝试 是可以了


kubectl get svc -n ns4
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
vpc-svc-1   ClusterIP   10.111.42.214   <none>        8887/TCP   148m

kubectl get pods -n ns4 -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
ngx-vpc1-85dd6545f6-jl5f7   1/1     Running   0          3d15h   10.0.1.3   master   <none>           <none>
ngx-vpc1-85dd6545f6-w9f4s   1/1     Running   0          3d15h   10.0.1.2   node1    <none>           <none>
ngx-vpc1-85dd6545f6-z68cx   1/1     Running   0          3d15h   10.0.1.4   node1    <none>           <none>

kubectl exec -it ngx-vpc1-85dd6545f6-z68cx -n ns4 -- curl 10.111.42.214:8887
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>

**Comment by bobz965** [comment]
> 我使用了service尝试 是可以了
> 
> kubectl get svc -n ns4 NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE vpc-svc-1 ClusterIP 10.111.42.214 8887/TCP 148m
> 
> kubectl get pods -n ns4 -o wide NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES ngx-vpc1-85dd6545f6-jl5f7 1/1 Running 0 3d15h 10.0.1.3 master ngx-vpc1-85dd6545f6-w9f4s 1/1 Running 0 3d15h 10.0.1.2 node1 ngx-vpc1-85dd6545f6-z68cx 1/1 Running 0 3d15h 10.0.1.4 node1
> 
> kubectl exec -it ngx-vpc1-85dd6545f6-z68cx -n ns4 -- curl 10.111.42.214:8887
> 
> <title>Welcome to nginx!</title> <style>

我看好像有 PR了，等下周吧
