### ISSUE TITLE
GitHub page HelmChart bug

### ISSUE THREAD

**Issue by aminmr** [kubeovn/kube-ovn#3167]
# Expected Behavior
The helm chart on the GitHub page (https://kubeovn.github.io/kube-ovn/) is the same as the directory in the kube-ovn project and is normally deployed on the cluster.

# Actual Behavior
The helm chart is not the same. In the GitHub page helm package v1.12.0, the `kube-ovn-cni` daemonSet has a parameter called `--node-local-dns-ip=` which is not known:

```bash
unknown flag: --node-local-dns-ip
Usage of ./kube-ovn-daemon:
      --add_dir_header                      If true, adds the file directory to the header of the log messages
      --alsologtostderr                     log to standard error as well as files (no effect when -logtostderr=true)
      --bind-socket string                  The socket daemon bind to. (default "/run/openvswitch/kube-ovn-daemon.sock")
      --cluster-router string               The router name for cluster router (default "ovn-cluster")
      --cni-conf-dir string                 Path of the CNI config directory. (default "/etc/cni/net.d")
      --cni-conf-file string                Path of the CNI config file. (default "/kube-ovn/01-kube-ovn.conflist")
      --cni-conf-name string                Specify the name of kube ovn conflist name in dir /etc/cni/net.d/, default: 01-kube-ovn.conflist (default "01-kube-ovn.conflist")
unknown flag: --node-local-dns-ip
```
# Steps to Reproduce the Problem

1. helm repo add kubeovn https://kubeovn.github.io/kube-ovn/
2. helm install kube-ovn kubeovn/kube-ovn --set MASTER_NODES=$Node_IP
3. k -n kube-system logs -f kube-ovn-cni-r42bx (One of the kube-ovn-cni pods)

# Additional Info

- Kubernetes version:
`1.25.6`

  **Output of `kubectl version`:**

```  
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2023-07-20T07:37:53Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **kube-ovn version**:
`1.12.0`

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
```
"Debian GNU/Linux 11 (bullseye)"
```
  **Output of `uname -r`:**
```
5.10.0-25-amd64
```

**Comment by zhangzujian** [comment]
Cannot reproduce it. Please try to pull image `kubeovn/kube-ovn:v1.12.0` and try again.

**Comment by zhangzujian** [comment]
Thanks for the report! Will fix it ASAP.
