### ISSUE TITLE
 request ip return 500 configure

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#3170]
# Expected Behavior
 pod ip分配正常

# Actual Behavior

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c2ac51cb17944c18f257a114cbf5b31595769f2029493a424bc864a2f8002c45": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed IP address 10.24.118.16 has already been used by host with MAC 00:00:00:83:f9:81

# Steps to Reproduce the Problem

  使用kube-ovn 1.11.1 每次加k8s节点都会出现10分钟左右的pod ip报错信息，这10分钟内如果有pod申请ip就会报以下错误
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c2ac51cb17944c18f257a114cbf5b31595769f2029493a424bc864a2f8002c45": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed IP address 10.24.118.16 has already been used by host with MAC 00:00:00:83:f9:81

# Additional Info

- Kubernetes version:

  ```
  1.20.1
  ```

- kube-ovn version:
  
 ```
1.11.1
 ```
- operation-system/kernel version:
  
```
5.4.231-1.el7.elrepo.x86_64  
```

**Comment by zhangzujian** [comment]
此问题一修复，更新至 v1.11 最新版本即可。

**Comment by wolgod** [comment]
> 此问题已修复，更新至 v1.11 最新版本即可。

能否告知在具体哪个小版本修复的呢？

**Comment by wolgod** [comment]
> 此问题已修复，更新至 v1.11 最新版本即可。

能否告知在具体哪个小版本修复的呢？
