### ISSUE TITLE
duplicate ip address created on different LSPs

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#3181]
# Expected Behavior

# Actual Behavior
During chart upgrade, duplicate ip address is created on a new LSP:

```txt
switch 0e566c86-bf9c-40bc-bb61-46637b802fdb (ovn-default)
    port kube-ovn-pinger-vgcsx.kube-system
        addresses: ["00:00:00:4F:37:95 10.16.0.4"]
    port kube-ovn-pinger-zg6fv.kube-system
        addresses: ["00:00:00:8E:AC:73 10.16.0.6"]
    port kube-ovn-pinger-p7fjm.kube-system
        addresses: ["00:00:00:96:72:9C 10.16.0.5"]
    port coredns-5d78c9869d-fmbfr.kube-system
        addresses: ["00:00:00:6D:8C:E0 10.16.0.3"]
    port coredns-5d78c9869d-4tsvz.kube-system
        addresses: ["00:00:00:F2:E3:69 10.16.0.2"]
    port kube-ovn-pinger-vnkjv.kube-system
        addresses: ["00:00:00:37:BB:77 10.16.0.6"]
    port ovn-default-ovn-cluster
        type: router
        router-port: ovn-cluster-ovn-default
```

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  v1.12/master
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by bobz965** [comment]
@zhangzujian 你这个是 1.11 的版本吗? 我们在 1.11 遇到了类似的 bug

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/3e45c8c3-c416-4a20-838b-0f431cc2556e)

v1.11.13

**Comment by zhangzujian** [comment]
通过 libovsdb 创建 LSP 时没有检查 IP 地址是否有冲突。

**Comment by bobz965** [comment]
我们的这个问题是因为有时候在部署前清理了 ip crd。导致 ipam 恢复的时候，没有从 ip 恢复成功。 但是 pinger pod 还在跑。所以会出现 ip 冲突的情况。目前已确认修复。

https://github.com/kubeovn/kube-ovn/pull/3589

**Comment by bobz965** [comment]
同样，我们也是使用 chart
helm uninstall 等操作，之前先执行下 cleanup.sh

helm uninstall 可能有待分析优化的点。
