### ISSUE TITLE
subnet spec vips vs  vip crd

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3187]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/028601f6-d537-4ba1-8253-02907572411b)

按照当前的代码来看，这两者的 vip 基本功能是一样的

- vip crd 本身尚未实现 安全组下的 AAP （https://docs.openstack.org/developer/dragonflow/specs/allowed_address_pairs.html）
- subnet 的 vip 是将 vip 作为所有 lsp 的 AAP

后续可以 vip crd 支持 app 后，或许 可以考虑移除这个逻辑

**Comment by abasitt** [comment]
@zbb88888 I am trying to understand the vip-app concept.. Let's say i have two pods that I want to share same vip to provide HA for underlay subnet. I attached the vip annotation to the deployment and the pods come up.
what do i do next?. do i have to find a way or use multus to inject the vip in these pods? 
is that enough or the pods still need keepalived or vrrp daemon to provide failover?
