### ISSUE TITLE
limit bgp announcements

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#3211]
# Expected Behavior

each worker announces only its hosted pods

# Actual Behavior
in a Layer3 scenario, where workers are deployed on different L3 networks, when BGP speakers are enabled they announce all the nets/pods without any possibility to filter on availability zone or worker containers.

This create problems on upstream connectivity because of asymmetrical routing

# Steps to Reproduce the Problem

1. create a cluster with workers deployed on different AZ (and, thus, different L3 networks)
2. create an overlay network with some pods
3. label workers and network with bgp=on
4. check bgp announcements

# Additional Info

- Kubernetes version: 1.28

- kube-ovn version: 1.11.10

**Comment by oilbeater** [comment]
@KillMaster9 could you please take a look at this and https://github.com/kubeovn/kube-ovn/issues/3212

**Comment by patriziobassi** [comment]
Hi, as example calico users blocksize parameter in order not to announce only /32 addresses but optimise in /26 default prefixes https://docs.tigera.io/calico/latest/reference/resources/ippool

**Comment by KillMaster9** [comment]
> @KillMaster9 could you please take a look at this and #3212
 OK！

**Comment by KillMaster9** [comment]
> Hi, as example calico uses blocksize parameter in order not to announce only /32 addresses but optimise in /26 default prefixes https://docs.tigera.io/calico/latest/reference/resources/ippool
> 
> This optimization may affect the ipam functionality too.

1. Yes, Calico's IPAM mechanism divides network segments according to nodes. Route aggregation is performed when Calico's bird advertises routes to the outside world. 
2. The IPAM mechanism of kube-ovn is different from calico and is a decentralized mechanism；

**Comment by KillMaster9** [comment]
Similar to k8s service, can set a TrafficPolicy attribute. If it is Local, only the Pod resources of this node can be published. If it is Cluster, all Pod resources can be published. The default is Cluster. The Metallb also expanded this function. @oilbeater

**Comment by patriziobassi** [comment]
Hi,

can you please provide an example how to set this filtering? i may give a try now.

thank you
