### ISSUE TITLE
kube-ovn中创建了三个k8s service对象，分别是 ovn-nb, ovn-sb, ovn-northd， 他们作用是什么？

### ISSUE THREAD

**Issue by DWC666** [kubeovn/kube-ovn#3249]
查看了源码，似乎只有kube-ovn-leader-checker中会去查看ovn-northd svc是否存在，其他地方并没有看到使用这三个对象；
另外，创建这三个对象后似乎会自动去设置环境变量OVN_NB_SERVICE_HOST， OVN_NB_SERVICE_PORT，OVN_SB_SERVICE_HOST，OVN_SB_SERVICE_PORT的值，但查看代码并没有发现相关设置env的逻辑。
希望得到解释，谢谢！

**Comment by zhangzujian** [comment]
这三个 Service 目前只是作为标记使用，可以快速查看当前 OVN NB/SB/Northd 的 leader 是哪个 Pod。

OVN_NB_SERVICE_HOST/OVN_NB_SERVICE_PORT 是 k8s 自动设置的。

**Comment by zhangzujian** [comment]
依赖这三个 Service 的只有 kubectl-ko 插件。另外 kube-ovn-pinger 应该也会访问 ovn-sb。

**Comment by DWC666** [comment]
明白了，谢谢
