### ISSUE TITLE
想咨询下 kube-ovn 升级那块的文档或者步骤，看了官方中文文档没找到

### ISSUE THREAD

**Issue by HuangTD1** [kubeovn/kube-ovn#3255]

**Comment by bobz965** [comment]
一般都是直接用更新版本的 install.sh  或者 helm 直接升级

**Comment by wolgod** [comment]
> 一般都是直接用更新版本的 install.sh 或者 helm 直接升级
不需要卸载旧版本吗 直接执行install.sh?

**Comment by bobz965** [comment]
> > 一般都是直接用更新版本的 install.sh 或者 helm 直接升级
> 
> 不需要卸载旧版本吗 直接执行install.sh?

亲测 1.10 升 1.11， 1.11 升 1.12  不需要卸载
