### ISSUE TITLE
Website: Link to Developer Docs not working

### ISSUE THREAD

**Issue by AnaisUrlichs** [kubeovn/kube-ovn#3269]
Hi there,
not sure where the website is kept but the link to the developer docs is not working anymore:
Linked to: https://github.com/kubeovn/kube-ovn/blob/master/docs/development.md
https://www.kube-ovn.io/
<img width="1005" alt="Screenshot 2023-10-02 at 16 45 30" src="https://github.com/kubeovn/kube-ovn/assets/33576047/2cd07c6a-e660-4d08-ba19-098e377e3aa8">

**Comment by oilbeater** [comment]
@AnaisUrlichs Thanks for the report, we will fix it soon. You can try https://kubeovn.github.io/docs/v1.12.x/en/reference/dev-env/ for development guide
