### ISSUE TITLE
Install and compile the STT in newer kernels

### ISSUE THREAD

**Issue by aminmr** [kubeovn/kube-ovn#3291]
### Feature request

I tried to compile the STT module on the Debian 11 kernel(5.10.0-25-amd64 and 5.15.12), and I had problems. The document and the patch are not up to date. It's needed to update the docs and the patch for newer kernels.
I am volunteering to enhance this module. I need a little help. @oilbeater 

### Use case

The STT protocol is an early tunneling protocol supported by the OVN that uses TCP-like headers to take advantage of the TCP offload capabilities common to modern NICs and significantly increase TCP throughput. The protocol also has a long header to support full OVN capabilities and large-scale datapaths.

**Comment by oilbeater** [comment]
@aminmr can you paste the error log here?
