### ISSUE TITLE
Under distributed gateway, VM pods not using current running node as gateway after migration

### ISSUE THREAD

**Issue by cclake** [kubeovn/kube-ovn#3298]
# Expected Behavior
kubevirt VM using current running node as gateway after migration

# Actual Behavior
When creating a new VM, this VM will use the node it currently running on as gateway. But after kubevirt VM migration, VM pod keep using original node as gateway even after original node lose network connectivity which causing VM lose connection to hosts outside cluster

# Steps to Reproduce the Problem

1. 
1.
1.

# Additional Info

- Kubernetes version: v1.23.17
- kube-ovn version: 1.12.0 (install overlay mode)
- kubevirt version: v1.0.0

k8s cluster using cilium as main CNI plugin and kube-ovn as second CNI plugin. Kubevirt VMs are created under default subnet and default VPC. Default subnet's gateway type is distributed with natOutgoing set to false and "keep-vm-ip = true" on kube-ovn-controller. 

After VM migration, we can observed that lsp of this VM would belonged to these port group: "ovn.default.\<old node hostname\>, ovn.default.\<new node hostname\> and node.\<new node hostname\>". (Not sure if this is related to the problem we encounter) 

Is there some configuration we can adjusted to make VM using new node as gateway after migration. Or when original gateway failed, it can using new node as gateway automatically.

- operation-system/kernel version:
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  Ubuntu 20.04.6 LTS
  5.15.0-69-generic
  ```

**Comment by bobz965** [comment]
Is the vm in the ovn-default subnet ?

**Comment by zhangzujian** [comment]
Thanks for the report!

The OVN port group `ovn.default.<old node hostname>` should be updated after the migration.

**Comment by cclake** [comment]
Thanks for the reply, After removing vm lsp from `ovn.default.<old node hostname>`, the vm use the node it currently running on as gateway. 

Is the update mechanism possible to be included into kubeovn?

**Comment by zhangzujian** [comment]
> Thanks for the reply, After removing vm lsp from `ovn.default.<old node hostname>`, the vm use the node it currently running on as gateway.
> 
> Is the update mechanism possible to be included into kubeovn?

Thanks for the information. This is a bug and we will fix it as soon as possible.
