### ISSUE TITLE
Why kube-ovn-monitor readinessProbe and livenessProbe need to check ovn-controller.pid?  What is the purpose?

### ISSUE THREAD

**Issue by DWC666** [kubeovn/kube-ovn#3330]
<img width="381" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/44437799/9859eb5c-2db3-4aa9-a129-3157af6df3c0">

**Comment by oilbeater** [comment]
It's a bug, the probe should check the 10661 cp port
