### ISSUE TITLE
use perf can't see specific function names within this container

### ISSUE THREAD

**Issue by JasinlikeEatingOrange** [kubeovn/kube-ovn#3335]
### Feature request

 I'm using 'perf' for container performance testing, but I can't see specific function names within this container. I searched in English, and it seems like you can't see them inside containers. I don't know how to configure it. Has anyone had a similar experience?
![img_v2_8e52453e-4117-46e5-804c-4c69e26f19bg](https://github.com/kubeovn/kube-ovn/assets/35122784/82dab473-6fd1-4cb8-ba5a-42fa5f873d5c)

### Use case
![img_v2_a6512301-157a-411a-9350-f61a2d3f578g](https://github.com/kubeovn/kube-ovn/assets/35122784/e1ad7059-84e6-415d-be71-308d009ed0a9)

This is a screenshot of the command I used. I'm capturing flame graph information using 'perf' on the host side. 
Is my approach correct? If not, what are the specific steps for performance tuning, and where should I look for them? I can't see information about each function call, as shown in the screenshot above.

### Expected Results
![img_v2_d126b94d-b618-4e3e-91f0-55ead9028c5g](https://github.com/kubeovn/kube-ovn/assets/35122784/8ef78b21-0259-493b-b36e-c1550d8bcd16)

**Comment by oilbeater** [comment]
To get the flame graph below you need to use the command `perf record -F 999 -a -g -p $(pidof qperf)` the target is the qperf process
