### ISSUE TITLE
Integration with OpenStack

### ISSUE THREAD

**Issue by LiamLea** [kubeovn/kube-ovn#3357]
# som quesions
1. Is it possible to use the subnet in the openstack?
1. Can i use kube-ovn to manage openstack network?

### Question 1

I wonder if there's any way to use the subnet created by openstack in k8s-ovn. I think it is possible in theory.
* for example
```shell
$ kubectl get vpc 
NAME                                           ENABLEEXTERNAL   STANDBY   SUBNETS                                                                                                  NAMESPACES
neutron-6b412af2-5e61-461e-b93e-1549c4f45251   false            true      ["neutron-8c0f90c1-3b87-4aae-ae73-a87e98eb8849","net2","neutron-9bd921d6-d451-4c25-802a-42f6b9991db8"]   ["net2"]
ovn-cluster                                    false            true      ["join","ovn-default","subnet1"]                                                                         
```
  * I want to put my pods in the neutron-9bd921d6-d451-4c25-802a-42f6b9991db8 subnet. 
    * If it supports , how to do it.
### Question 2
As far as i know, kube-ovn now can only mange the network flows within openstack and cannot control the lifecycle of the networks. Therefore,  i still need to use the openstack API to manage the openstack network. Is this understanding correct?

**Comment by bobz965** [comment]
the  `cms` role for ovn  is neutron or  kube-ovn.

if you use neutron to create the vpc and subnet, I think you can try to create the kube-ovn crd to map the already exist neutron created ovn resources.
