### ISSUE TITLE
Is it possible to put pods in different k8s cluster into the same VPC?

### ISSUE THREAD

**Issue by LiamLea** [kubeovn/kube-ovn#3407]
I know it supports interconnecting two OVN deployements through [OVN-IC](https://kubeovn.github.io/docs/v1.11.x/en/advance/with-ovn-ic/). But this method cannot place pods on the either side into the same VPC.
Is there any way to put pods in different k8s clusters into the same VPC?

**Comment by oilbeater** [comment]
It is not supported by Kube-OVN. To enable VPC across different k8s clusters, you will need a standalone OVN located outside of the k8s clusters. This will help to manage all networks in different clusters. But this is not what Kube-OVN is designed for.
