### ISSUE TITLE
Version1.12.0-When using the OVN-EIPfeature, restarting the kube-ovn-controller component can result in the abnormal deletion of the lr-lb (logical router load balancer) in OVN-NB

### ISSUE THREAD

**Issue by zhoulw** [kubeovn/kube-ovn#3418]
When using the OVN-EIPfeature, restarting the kube-ovn-controller component can result in the abnormal deletion of the lr-lb (logical router load balancer) in OVN-NB.
* step1:

I create Odnat first:
```
# kubectl apply -f dnat-all.yaml 
ovndnatrule.kubeovn.io/shanghai-master1-dnat created
ovndnatrule.kubeovn.io/shanghai-worker1-dnat created
ovndnatrule.kubeovn.io/shanghai-master2-dnat created
ovndnatrule.kubeovn.io/shanghai-worker2-dnat created
ovndnatrule.kubeovn.io/shanghai-master3-dnat created
ovndnatrule.kubeovn.io/shanghai-worker3-dnat created
```

* step2:

in the nb:
```
# ovn-nbctl lr-lb-list test                           
UUID                                    LB                  PROTO      VIP             IPs
5ba503ba-cb55-4693-a365-7fc563b57104    shanghai-master1    tcp        10.5.46.0:22    10.115.0.11:22
4fc5d348-d30c-4096-8d5b-977ad1c4ede8    shanghai-master2    tcp        10.5.46.3:22    10.115.0.12:22
ce6d8504-0590-49b1-a32b-7795a5b989d1    shanghai-master3    tcp        10.5.46.5:22    10.115.0.13:22
74a1ebc7-e804-4db6-9698-14aa668dce91    shanghai-worker1    tcp        10.5.46.1:22    10.115.0.101:22
0b3b3edd-5cf5-48ee-89f8-208d9bf951d1    shanghai-worker2    tcp        10.5.46.4:22    10.115.0.102:22
d12fa97a-a27f-40ae-9841-574299e9faa2    shanghai-worker3    tcp        10.5.46.6:22    10.115.0.103:22
```

* step3:

restart kube-ovn-controller:
```
kubectl rollout restart deployment -n kube-system kube-ovn-controller 
```

null in nb:
```
kubectl rollout restart deployment -n kube-system kube-ovn-controller 

# ovn-nbctl lr-lb-list test          
NULL HERE
```

and also in ovn-snat, When create a osnat and delete it, the rules in ovn-nb has not been deleted.  When snat and dnat are used at the same time, it may even happen that the upper cluster cannot access the external network.

The scenario where this error occurs is "k8s nested k8s".

**Comment by bobz965** [comment]
please attach the kube-ovn version

**Comment by bobz965** [comment]
please try the latest 1.12.3

**Comment by zhoulw** [comment]
> please try the latest 1.12.3

The same error will still occur in version 1.12.3. Just like the following situation.
1. ``` rollout restart controller```
2. lr-lb will be deleted like below:
```
root@hci-node-3:/kube-ovn# ovn-nbctl lr-lb-list test   
UUID                                    LB                  PROTO      VIP              IPs
76c4e6d1-25b3-43d8-8055-fe09adb2f30f    shanghai-master1    tcp        10.5.46.3:22     10.115.0.11:22
13d0823f-e724-4f48-ae34-3ab1aefc1588    shanghai-master2    tcp        10.5.46.5:22     10.115.0.12:22
ff273147-8a96-400e-aaea-0a77f8572b00    shanghai-master3    tcp        10.5.46.7:22     10.115.0.13:22
4e37fe39-d7c0-4cf6-8c39-5f58f1e678f2    shanghai-worker1    tcp        10.5.46.4:22     10.115.0.101:22
20abf080-05c2-443a-8f8a-5962923c0e6b    shanghai-worker2    tcp        10.5.46.6:22     10.115.0.102:22
f6805046-cae3-48da-99aa-a7b725c2e8e1    shanghai-worker3    tcp        10.5.46.10:22    10.115.0.103:22
root@hci-node-3:/kube-ovn# ovn-nbctl lr-lb-list test
root@hci-node-3:/kube-ovn# 
```

3. When I only use osnat, the L2 Kubernetes cluster nodes **can** access the Internet. However, when I create odnat, the higher-level cluster nodes lose access to the Internet. Restarting controller removes the odnat's lr-nb and restores network connectivity.

I want to know if lr-nat and lr-lb are incompatible with each other, or if there might be other configuration issues. Can you reproduce this issue here? Thanks~

**Comment by zhoulw** [comment]
> please try the latest 1.12.3




> please try the latest 1.12.3

重启后还是会删除原有的lr-lb，我看gc里面有逻辑应该是删除ls-lb的，请问下是不是哪里有配置会重启时删除lr-lb的哈？

**Comment by bobz965** [comment]
你的意思是 你使用的 ovn-dnat 建的 lr lb 资源，在kube-ovn-controller 重启之后被删除了？

**Comment by zhoulw** [comment]
> 你的意思是 你使用的 ovn-dnat 建的 lr lb 资源，在kube-ovn-controller 重启之后被删除了？

是的，应该是重启的时候，在gc里面被清掉了

**Comment by zhoulw** [comment]
k

> > 你的意思是 你使用的 ovn-dnat 建的 lr lb 资源，在kube-ovn-controller 重启之后被删除了？
> 
> 是的，应该是重启的时候，在gc里面被清掉了

**Comment by bobz965** [comment]
我后面有空测试下这个。
