### ISSUE TITLE
版本1.12.0，删除虚拟机后，lsp未正常删除，需要等待gc清理

### ISSUE THREAD

**Issue by zhoulw** [kubeovn/kube-ovn#3424]
# Bug Report
删除虚拟机后，lsp未正常删除，需要等待gc清理
## Expected Behavior
删除虚拟机后，lsp应随删除虚拟机pod之后删除。
## Actual Behavior
虚拟机pod后，lsp未正常立即删除，只能等待gc的清理，导致在同vpc下另外一个子网创建同名的虚拟机，lsp重复检测是全局检测，检测重复lsp后并不创建新的lsp。
## Steps to Reproduce the Problem

1. subnet-1 创建虚拟机

2. 暂停、删除虚拟机，等待vm-pod删除，查看lsp依然存在。

3. 在subnet-2创建同名的虚拟机，导致未正常创建lsp

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`: 1.23.15**

**Comment by hongzhen-ma** [comment]
虚拟机如果在 Running 状态删除，lsp 会立即删除。
虚拟机在关机状态，可能会涉及重新启动，需要保留原来的虚拟机 IP 地址，这个是有 kube-ovn-controller 中的 keep-vm-ip 参数取值决定的。

可以尝试将 keep-vm-ip 参数设置为 false，然后再验证下虚拟机关机状态删除，是否还保留 lsp 记录

**Comment by hongzhen-ma** [comment]
这种关机更新 subnet 的情况，应该有过处理，需要看一下是不是没有覆盖到。正常来说，修改subnet之后，需要修改 lsp 记录的 IP地址。

**Comment by zhoulw** [comment]
> 虚拟机如果在 Running 状态删除，lsp 会立即删除。 虚拟机在关机状态，可能会涉及重新启动，需要保留原来的虚拟机 IP 地址，这个是有 kube-ovn-controller 中的 keep-vm-ip 参数取值决定的。
> 
> 可以尝试将 keep-vm-ip 参数设置为 false，然后再验证下虚拟机关机状态删除，是否还保留 lsp 记录

使用keep-vm-ip=true，running状态直接删除vm，依然需要等待gc。

**Comment by zhoulw** [comment]
> 这种关机更新 subnet 的情况，应该有过处理，需要看一下是不是没有覆盖到。正常来说，修改subnet之后，需要修改 lsp 记录的 IP地址。

我看代码里面是，新增pod添加lsp的时候：
```
func (c *OVNNbClient) CreateLogicalSwitchPort(lsName, lspName, ip, mac, podName, namespace string, portSecurity bool, securityGroups, vips string, enableDHCP bool, dhcpOptions *DHCPOptionsUUIDs, vpc string) error {
	exist, err := c.LogicalSwitchPortExists(lspName)
	if err != nil {
		klog.Error(err)
		return err
	}
```
这个lsp-name和子网名应该是不相关的，相同的虚拟机pod-name可能会导致相同的lspname，感觉可能这里的逻辑是否需要更改下
