### ISSUE TITLE
创建 VPC 网关绑定eth0后，无法正常分配mac地址

### ISSUE THREAD

**Issue by haopengstack** [kubeovn/kube-ovn#3431]
k8s 1.23.17 基于Containerd 部署单机，想测试kube-ovn vpc功能，但是一直无法创建成功vpc网关，也无法绑定eip等功能，请教大神帮忙看下
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/73850a67-4dd6-47c7-8747-0310a5c1ea7c)

![image](https://github.com/kubeovn/kube-ovn/assets/14845541/9082f55e-974b-4547-a41b-fc5fa5e82ff5)

![image](https://github.com/kubeovn/kube-ovn/assets/14845541/eb9dc90e-447e-462f-8080-3ac8b75d2cb4)

**Comment by haopengstack** [comment]
ip addr 如下：
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/c53a20ff-6f73-49f9-9607-1fbf8008177e)
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/7ed9752b-bb29-4466-8bc9-e5d9eefb71ec)

**Comment by bobz965** [comment]
什么版本，看下 kube-ovn-controller 的 log，看下 nat gw pod 的 err

**Comment by haopengstack** [comment]
> 什么版本，看下 kube-ovn-controller 的 log，看下 nat gw pod 的 err

用的v1.12.3 ，本机ip 192.168.10.161  连接机房交换机 （access 192.168.10.1/24） 
kube-ovn-controller日志
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/4e6bb26d-6d85-4c5e-81fa-e1507eff0549)
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/379be8c1-1940-4b36-b6f1-f102ff9bf3f4)
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/109aa1c1-b5c5-4d6f-a4ac-8e98f2c4197b)
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/76d61008-7465-4506-9571-203c7a26b151)
![image](https://github.com/kubeovn/kube-ovn/assets/14845541/178ea8c8-12ba-42fd-9a32-71866d7f0665)

**Comment by bobz965** [comment]
看起来 nat gw pod 已经起来了，在 nat gw pod 启动之后创建 eip snat 应该能够成功。

**Comment by haopengstack** [comment]
> 看起来 nat gw pod 已经起来了，在 nat gw pod 启动之后创建 eip snat 应该能够成功。

会不会是交换机的问题 我放开trunk模式试试

**Comment by NeverTeaser** [comment]
遇到同样的问题，不确定是否是交换机的问题
---
Encountering the same problem, not sure if it is a switch problem

**Comment by bobz965** [comment]
vpc nat gw 使用的是 macvlan， 这里即使kube-ovn ipam 分配了 mac地址，也没有实际意义。没有mac地址本身应该不是一个bug
