### ISSUE TITLE
log show ip already released， but subnet status still show it is in using

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3458]
kube-ovn 1.12.3 

kube-ovn 1.12.4

# Bug Report
log show ip already released， but subnet status still show it is in using

## Expected Behavior
log show ip already released， the subnet status should show it is not in using
## Actual Behavior

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/6d2c2d66-94e9-4b08-bffd-5ae29e6ba611)

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/2460bb3f-16ca-4d36-902b-321799f255ab)

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
  (paste your output here)

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by zhangzujian** [comment]
IP is reserved for VM if `--keep-vm-ip` is set to `true`.

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/e14d3daa-559f-4d64-8752-72780fafb7cd)


ip is also removed， i will fix it like this later

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/95d16874-9219-43c8-b5ad-f6864749e2d6)
