### ISSUE TITLE
默认VPC下，按照ovn eip snat dnat配置后，宿主机无法访问网络，其他设备也无法ping通宿主机

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#3460]
# Bug Report
1. 按照https://kubeovn.github.io/docs/v1.12.x/advance/ovn-eip-fip-snat/这个文档，配置provider-network，Vlan，Subnet后，再配置00-centralized-external-gw-no-ip.yaml，宿主机网络就无法访问外网了，其他节点（集群内外都试过）也无法访问该节点
## Expected Behavior
宿主机能够正常访问网络，也能被其他设备访问
## Actual Behavior
1.  宿主机上查看kubectl  ko nbctl show
![714a82b44da7682d71b067241765fcb](https://github.com/kubeovn/kube-ovn/assets/25982171/8c5ee74b-ff29-44de-b539-332933ee2e93)
2.  然后查看kubectl ko vsctl master-0 list open
![2ce8edef1065925d109dc61818a342b](https://github.com/kubeovn/kube-ovn/assets/25982171/ae6a285e-6f0f-47a8-afef-42f085836f2a)
3. 删除configmap，删除ovn-bridge-mappings和ovn-chassis-mac-mappings后，问题依旧
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/671d54cd-8d8c-48ce-af74-a55b3f724765)

## Steps to Reproduce the Problem

1. 按照https://kubeovn.github.io/docs/v1.12.x/advance/ovn-eip-fip-snat/这个文档，配置provider-network，Vlan，Subnet
2.  配置00-centralized-external-gw-no-ip.yaml

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  1.18.6

  ```

- kube-ovn version:
  
  ```bash
  1.12.2

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
Kylin Linux Advanced Server V10 (Lance)
  **Output of `uname -r`:**
4.19.90-52.22.v2007.ky10.x86_64
  ```bash
  (paste your output here)
  
  ```

宿主机只有单网卡，是不是和这个也有关系，文档好像没有标注要用单独一张网卡实现eip功能

**Comment by geniusxiong** [comment]
> 是的，这里用到了underlay，underlay需要单独的网卡

大佬，能帮忙看下怎么恢复宿主机网络么

**Comment by oilbeater** [comment]
需要删除对应的 providernetwork 资源，可以通过带外进主机停掉 kubelet 避免 ovs 操作网卡
