### ISSUE TITLE
kube-ovn-cni cannot run on kernel v6.6.2

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#3473]
# Bug Report

## Actual Behavior

```txt
time="2023-11-29T14:38:42+08:00" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2023-11-29T14:38:42+08:00" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
```

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
  (paste your output here)

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by hongzhen-ma** [comment]
https://github.com/kubeovn/kube-ovn/issues/3602

**Comment by hongzhen-ma** [comment]
https://github.com/kubeovn/kube-ovn/pull/3601  合入后应该解决这个问题了
