### ISSUE TITLE
希望修改.spec.template.metadata.annotations 中的annotations不重启pod

### ISSUE THREAD

**Issue by victory460** [kubeovn/kube-ovn#3480]
# Bug Report
`如果工作负载为 Deployment、DaemonSet 或 StatefulSet，对应的 Annotation 需要配置在资源的 .spec.template.metadata.annotations 中。`
这样配置会导致修改后，pod重启。
## Expected Behavior
如何不重启，就能修改配置，一般有哪些方案？
## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
  (paste your output here)

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by bobz965** [comment]
这个重启好像不是kube-ovn触发的

**Comment by zhangzujian** [comment]
非 CNI 问题，你可以去 k8s 社区咨询。
