### ISSUE TITLE
cannot ping join switch router 100.64.0.1 from node itself

### ISSUE THREAD

**Issue by chairwa** [kubeovn/kube-ovn#3483]
# Bug Report

## Expected Behavior
can ping join switch router 100.64.0.1 from node itself

## Actual Behavior
cannot ping join switch router 100.64.0.1 from node itself
ping 100.64.0.1
PING 100.64.0.1 (100.64.0.1) 56(84) bytes of data.

The reason seems to be that ovn0 mac is different with join switch node port mac.

tcpdump -ne -i ovn0 icmp and src 100.64.0.1
12:52:27.394005 00:00:00:71:99:14 > 00:00:00:91:88:f8, ethertype IPv4 (0x0800), length 98: 100.64.0.1 > 100.64.0.2: ICMP echo reply, id 7, seq 7251, length 64

ip addr show ovn0
5: ovn0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 00:00:00:6b:b0:43 brd ff:ff:ff:ff:ff:ff
    inet 100.64.0.2/16 brd 100.64.255.255 scope global ovn0

kubectl ko nbctl show
switch dc68833d-db84-40c8-bc5f-25bbf6327daf (join)
    port node-harry
        addresses: ["00:00:00:91:88:F8 100.64.0.2"]

## Steps to Reproduce the Problem

one-click installation
1. wget https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.12/dist/images/install.sh
2. sudo ./install.sh

## Additional Info

- Kubernetes version:

kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7+k3s2", GitCommit:"575bce7689f4be112bd0099362fb8d5f2e39398e", GitTreeState:"clean", BuildDate:"2023-11-08T02:32:49Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7+k3s2", GitCommit:"575bce7689f4be112bd0099362fb8d5f2e39398e", GitTreeState:"clean", BuildDate:"2023-11-08T02:32:49Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

- kube-ovn version:
v1.12.3

- operation-system/kernel version:
  
Ubuntu 22.04.3 LTS
6.2.0-32-generic

Only one node has the problem. Other nodes (ubuntu 20.04 and 22.04) ok

**Comment by oilbeater** [comment]
Perhaps the node was previously used to join a Kubernetes cluster and has not been properly cleaned up. You can try https://kubeovn.github.io/docs/v1.12.x/en/ops/delete-worker-node/ to clean the node and rejoin the cluster.

**Comment by chairwa** [comment]
The following cleaning statements fixed the problem.

rm -rf /var/run/openvswitch
rm -rf /var/run/ovn
rm -rf /etc/origin/openvswitch/
rm -rf /etc/origin/ovn/
rm -rf /etc/cni/net.d/00-kube-ovn.conflist
rm -rf /etc/cni/net.d/01-kube-ovn.conflist
rm -rf /var/log/openvswitch
rm -rf /var/log/ovn
