### ISSUE TITLE
1.12.3 默认VPC内使用OVN EIP，但是ping的回包还是原ip

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#3502]
# Bug Report
根据https://kubeovn.github.io/docs/v1.12.x/advance/ovn-eip-fip-snat/ 配置**默认vpc**内的一个虚机使用eip
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/b6161727-89f4-4951-8aed-79088d23aee9)
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/bd745185-7e99-43ca-8450-70d91e3d9c37)
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/e6400e36-af32-4b75-ba5f-84bf255bfd1a)

虽然可以ping通，但是不能ssh连接
但是ping的回包是原ip地址，没有做nat转换
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/6b4855a7-3273-4c2b-9633-83b213437a7e)
ssh连不上，也是没有eip的回包
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/f5829331-3cd6-4bdc-9d5b-c5a5fff38a35)
![图片](https://github.com/kubeovn/kube-ovn/assets/25982171/5d5e0f23-b593-4a30-99da-a6bdabad1715)

## Expected Behavior
ping的回包应该是eip地址，ssh要能通
## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
 1.18.6

  ```

- kube-ovn version:
  
  ```bash
1.12.3

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  4.19.113-3.nfs.x86_64
  
  ```

**Comment by bobz965** [comment]
麻烦贴下你的 install.sh 的 ENABLE_xx 那几行相关的配置，自定义 vpc 目前没这个 bug。 怀疑可能跟一些特性开启有关系

**Comment by geniusxiong** [comment]
> 麻烦贴下你的 install.sh 的 ENABLE_xx 那几行相关的配置，自定义 vpc 目前没这个 bug。 怀疑可能跟一些特性开启有关系

好的
IPV6=${IPV6:-false}
DUAL_STACK=${DUAL_STACK:-false}
ENABLE_SSL=${ENABLE_SSL:-false}
ENABLE_VLAN=${ENABLE_VLAN:-false}
CHECK_GATEWAY=${CHECK_GATEWAY:-true}
LOGICAL_GATEWAY=${LOGICAL_GATEWAY:-false}
U2O_INTERCONNECTION=${U2O_INTERCONNECTION:-false}
ENABLE_MIRROR=${ENABLE_MIRROR:-false}
VLAN_NIC=${VLAN_NIC:-}
HW_OFFLOAD=${HW_OFFLOAD:-false}
ENABLE_LB=${ENABLE_LB:-true}
ENABLE_NP=${ENABLE_NP:-true}
ENABLE_EIP_SNAT=${ENABLE_EIP_SNAT:-true}
LS_DNAT_MOD_DL_DST=${LS_DNAT_MOD_DL_DST:-true}
ENABLE_EXTERNAL_VPC=${ENABLE_EXTERNAL_VPC:-true}
CNI_CONFIG_PRIORITY=${CNI_CONFIG_PRIORITY:-01}
ENABLE_LB_SVC=${ENABLE_LB_SVC:-false}
ENABLE_NAT_GW=${ENABLE_NAT_GW:-false}
ENABLE_KEEP_VM_IP=${ENABLE_KEEP_VM_IP:-true}
ENABLE_ARP_DETECT_IP_CONFLICT=${ENABLE_ARP_DETECT_IP_CONFLICT:-true}
NODE_LOCAL_DNS_IP=${NODE_LOCAL_DNS_IP:-}
# exchange link names of OVS bridge and the provider nic
# in the default provider-network
EXCHANGE_LINK_NAME=${EXCHANGE_LINK_NAME:-false}
# The nic to support container network can be a nic name or a group of regex
# separated by comma, if empty will use the nic that the default route use
IFACE=${IFACE:-}
# Specifies the name of the dpdk tunnel iface.
# Note that the dpdk tunnel iface and tunnel ip cidr should be diffierent with Kubernetes api cidr, otherwise the route will be a proble$
DPDK_TUNNEL_IFACE=${DPDK_TUNNEL_IFACE:-br-phy}
ENABLE_BIND_LOCAL_IP=${ENABLE_BIND_LOCAL_IP:-true}
ENABLE_TPROXY=${ENABLE_TPROXY:-false}
OVS_VSCTL_CONCURRENCY=${OVS_VSCTL_CONCURRENCY:-100}
ENABLE_COMPACT=${ENABLE_COMPACT:-false}

# debug
DEBUG_WRAPPER=${DEBUG_WRAPPER:-}

您看看，自定义VPC好像是没问题，我这个问题出现在默认VPC

**Comment by bobz965** [comment]
我感觉配置没问题，应该就是引入了一个bug

**Comment by geniusxiong** [comment]
> 我感觉配置没问题，应该就是引入了一个bug

有计划修复？

**Comment by bobz965** [comment]
@oilbeater 大佬，默认vpc好像引入了一个bug，感觉跟路由有关系，导致eip snat的流量没有经过nat规则转化就回包了

**Comment by geniusxiong** [comment]
@oilbeater 大佬，这个有修改计划么？

**Comment by a180285** [comment]
1.12.4 默认 VPC 也有同样的问题， ovn-eip 不生效。
NAT 行为只受 subnet ovn-default 的影响。natOutgoing: false ，修改这个参数会影响 NAT
但修改 ovn eip 在 默认 VPC 下不生效

**Comment by a180285** [comment]
经过一番研究发现，通过添加如下 route 可以实现 eip nat。 
@geniusxiong 可以尝试一下
```bash
kubectl ko nbctl lr-policy-add ovn-cluster 31000 'ip4.src == 10.5.193.243' reroute 10.5.0.1
kubectl ko nbctl lr-policy-list ovn-cluster
```
其中 
* 10.5.193.243 是 pod 的 IP
* 10.5.0.1 是物理 vlan 中的 gateway IP

怀疑可能是默认 VPC 下的 pod 全部路由到 join subnet ，而无法 snat 了
环境：
* join subnet: 100.64.0.0/16
* ovn-default subnet: 10.5.192.0/18
```
kubectl ko nbctl lr-policy-list ovn-cluster
Routing Policies
     31000                           ip4.dst == 10.5.192.0/18           allow
     31000                           ip4.dst == 100.64.0.0/16           allow
     30000                              ip4.dst == 10.5.0.143         reroute                100.64.0.2
     30000                              ip4.dst == 10.5.0.144         reroute                100.64.0.3
     30000                              ip4.dst == 10.5.0.145         reroute                100.64.0.4
     29000                           ip4.src == 10.5.192.0/18         reroute                100.64.0.2, 100.64.0.3, 100.64.0.4

kubectl ko nbctl lr-nat-list ovn-cluster
TYPE             GATEWAY_PORT          EXTERNAL_IP        EXTERNAL_PORT    LOGICAL_IP          EXTERNAL_MAC         LOGICAL_PORT
dnat_and_snat                          10.5.0.18                           10.5.193.243        00:00:00:D3:51:4B    default-pod4.default
```

@bobz965 上面的分析正确吗，是不是可以通过代码强制加 policy route 来修复这个问题呢

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/0252006f-7fb5-407a-91d4-1688b33ee98a)

https://kubeovn.github.io/docs/v1.13.x/guide/eip-snat/

你对照下这个eip的使用方式是否可以正常使用？ 然后对照下看是否是你的策略路由的维护逻辑。如果一致，应该就没问题。
只是这个功能我之前测试过很多次，都是可以正常使用的，之前不记得有配置这样的策略路由。

**Comment by a180285** [comment]
我之前 pod 没有加 annotation ，只是使用自定义 VPC 一样，使用了 ovnFIP 这个 yaml

@bobz965 是指所有 VPC (不管默认还是自定义 VPC) 的 pod 要使用 ovn EIP/FIP 都需要对应的 pod annotation 吗？还是默认 VPC 的 pod 才需要加这个 annotation ?

BTW: 我默认和自定义 VPC 下的 pod 都没加过个 annotation。我以为这个 annotation 是给  IptableEIP/FIP 使用的

**Comment by bobz965** [comment]
> 我之前 pod 没有加 annotation ，只是使用自定义 VPC 一样，使用了 ovnFIP 这个 yaml
> 
> @bobz965 是指所有 VPC (不管默认还是自定义 VPC) 的 pod 要使用 ovn EIP/FIP 都需要对应的 pod annotation 吗？还是默认 VPC 的 pod 才需要加这个 annotation ?
> 
> BTW: 我默认和自定义 VPC 下的 pod 都没加过个 annotation。我以为这个 annotation 是给 IptableEIP/FIP 使用的

这个 annotation 和 ovn fip 是同样的 ovn 的资源，只不过只有在默认 vpc 下才能用。如果默认 vpc 下这个 annotation 的 eip 能够正常使用，我理解默认 vpc下的 ovn eip fip 保持同样的维护方式就能修复。

**Comment by geniusxiong** [comment]
> ![image](https://private-user-images.githubusercontent.com/7981158/299147113-0252006f-7fb5-407a-91d4-1688b33ee98a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTAxNDMsIm5iZiI6MTcwNjA4OTg0MywicGF0aCI6Ii83OTgxMTU4LzI5OTE0NzExMy0wMjUyMDA2Zi03ZmI1LTQwN2EtOTFkNC0xNjg4YjMzZWU5OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDk1MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q1MjI0MmI3MDBjYTMyOTk4ZGFjZjA2N2Y1OTM5MDQxOWU5MWQxNzBiOTc1ZWQwNTg5MzFlNmY1YjRjMWI5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pHb9fzvgsZrkeru23ZYSVIA5VGiJ7jSdkai0wOMKwpQ)
> 
> https://kubeovn.github.io/docs/v1.13.x/guide/eip-snat/
> 
> 你对照下这个eip的使用方式是否可以正常使用？ 然后对照下看是否是你的策略路由的维护逻辑。如果一致，应该就没问题。 只是这个功能我之前测试过很多次，都是可以正常使用的，之前不记得有配置这样的策略路由。

@bobz965 通过annotation绑定eip好像可以，但是实际使用的时候不好用，因为pod重建后，需要重新绑定eip，对于虚机来说，重启就会丢失eip，需要重新绑定。所以我们考虑用ovn eip fip方案替代直接通过annotation绑定eip。
谢谢 @a180285 提的修改方法，我回头试试。

**Comment by a180285** [comment]
我这边使用 annotation 创建 pod 会报错

kube-ovn-controller 日志
```
I0124 21:46:30.063745       1 ovn-nb-logical_router_route.go:102] logical router ovn-cluster del static routes: []
E0124 21:46:30.070997       1 pod.go:405] error syncing 'default/default-pod9': generate operations for port group ovn.default.caas.144 update ports [default-pod9.default]: get port group ovn.default.caas.144: get port group ovn.default.caas.144: object not found, requeuing
I0124 21:46:30.071011       1 pod.go:559] handle add/update pod default/default-pod9
I0124 21:46:30.071314       1 pod.go:772] sync pod default/default-pod9 routed
I0124 21:46:30.071326       1 vpc.go:689] vpc ovn-cluster add static route: &{Policy:policySrc CIDR:10.5.192.68 NextHopIP:10.5.0.1 ECMPMode: BfdID: RouteTable:}
I0124 21:46:30.072349       1 ovn-nb-logical_router_route.go:102] logical router ovn-cluster del static routes: []
E0124 21:46:30.072663       1 pod.go:405] error syncing 'default/default-pod9': generate operations for port group ovn.default.caas.144 update ports [default-pod9.default]: get port group ovn.default.caas.144: get port group ovn.default.caas.144: object not found, requeuing
I0124 21:46:31.913792       1 pod.go:559] handle add/update pod default/default-pod9
I0124 21:46:31.913996       1 pod.go:772] sync pod default/default-pod9 routed
I0124 21:46:31.914009       1 vpc.go:689] vpc ovn-cluster add static route: &{Policy:policySrc CIDR:10.5.192.68 NextHopIP:10.5.0.1 ECMPMode: BfdID: RouteTable:}
I0124 21:46:31.914742       1 ovn-nb-logical_router_route.go:102] logical router ovn-cluster del static routes: []
E0124 21:46:31.915177       1 pod.go:405] error syncing 'default/default-pod9': generate operations for port group ovn.default.caas.144 update ports [default-pod9.default]: get port group ovn.default.caas.144: get port group ovn.default.caas.144: object not found, requeuing
I0124 21:46:33.000953       1 pod.go:950] handle delete pod default/default-pod9
I0124 21:46:33.000977       1 pod.go:438] take 0 ms to handle delete pod default/default-pod9
I0124 21:46:36.364520       1 ovn_eip.go:334] handle del ovn eip eip-static
E0124 21:46:36.364562       1 ovn_eip.go:636] ovn eip 'eip-static' is still in use, finalizer will not be removed
E0124 21:46:36.364571       1 ovn_eip.go:344] failed to handle remove ovn eip finalizer , ovn eip 'eip-static' is still in use, finalizer will not be removed
E0124 21:46:36.364591       1 ovn_eip.go:202] error syncing 'eip-static': ovn eip 'eip-static' is still in use, finalizer will not be removed, requeuing
I0124 21:46:36.364596       1 ovn_eip.go:334] handle del ovn eip vpc2-external-1
E0124 21:46:36.364602       1 ovn_eip.go:636] ovn eip 'vpc2-external-1' is still in use, finalizer will not be removed
E0124 21:46:36.364607       1 ovn_eip.go:344] failed to handle remove ovn eip finalizer , ovn eip 'vpc2-external-1' is still in use, finalizer will not be removed
E0124 21:46:36.364612       1 ovn_eip.go:202] error syncing 'vpc2-external-1': ovn eip 'vpc2-external-1' is still in use, finalizer will not be removed, requeuing
I0124 21:46:36.477584       1 ovn_eip.go:334] handle del ovn eip eip-static-for-snat
E0124 21:46:36.477602       1 ovn_eip.go:636] ovn eip 'eip-static-for-snat' is still in use, finalizer will not be removed
E0124 21:46:36.477607       1 ovn_eip.go:344] failed to handle remove ovn eip finalizer , ovn eip 'eip-static-for-snat' is still in use, finalizer will not be removed
E0124 21:46:36.477617       1 ovn_eip.go:202] error syncing 'eip-static-for-snat': ovn eip 'eip-static-for-snat' is still in use, finalizer will not be removed, requeuing
```

pod 状态
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: default-pod9
  namespace: default
  uid: 587dcfb4-6d9e-41fd-9bf3-e222052962d3
  resourceVersion: '4017839'
  creationTimestamp: '2024-01-24T13:46:29Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"ovn.kubernetes.io/eip":"10.5.0.201"},"name":"default-pod9","namespace":"default"},"spec":{"containers":[{"command":["sleep","10d"],"image":"docker.io/jonlabelle/network-tools","name":"default-pod9"}]}}
    ovn.kubernetes.io/allocated: 'true'
    ovn.kubernetes.io/cidr: 10.5.192.0/18
    ovn.kubernetes.io/eip: 10.5.0.201
    ovn.kubernetes.io/gateway: 10.5.196.1
    ovn.kubernetes.io/ip_address: 10.5.192.68
    ovn.kubernetes.io/logical_router: ovn-cluster
    ovn.kubernetes.io/logical_switch: ovn-default
    ovn.kubernetes.io/mac_address: 00:00:00:97:E4:3F
    ovn.kubernetes.io/pod_nic_type: veth-pair
status:
  phase: Pending
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-01-24T13:46:30Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-01-24T13:46:30Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [default-pod9]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-01-24T13:46:30Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [default-pod9]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-01-24T13:46:30Z'
  hostIP: 10.5.0.144
  startTime: '2024-01-24T13:46:30Z'
  containerStatuses:
    - name: default-pod9
      state:
        waiting:
          reason: ContainerCreating
      lastState: {}
      ready: false
      restartCount: 0
      image: cr.sihe.cloud/docker.io/jonlabelle/network-tools
      imageID: ''
      started: false
  qosClass: BestEffort
```

创建 pod 的 yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: default-pod9
  annotations:
    ovn.kubernetes.io/eip: 10.5.0.201
spec:
  containers:
    - name: default-pod9
      image: docker.io/jonlabelle/network-tools
      command:
        - sleep
        - 10d
```

**Comment by a180285** [comment]
从日志看，使用 annotation 的情况下，会加一个 route ，看上去就是和我 PR 中做的事情一样，但不知道为什么 pod 没有创建成功

```
I0124 21:46:31.914009       1 vpc.go:689] vpc ovn-cluster add static route: &{Policy:policySrc CIDR:10.5.192.68 NextHopIP:10.5.0.1 ECMPMode: BfdID: RouteTable:}
```

**Comment by a180285** [comment]
看了一下 port group

确实没有上面日志说的 `ovn.default.caas.144`

```
E0124 21:46:31.915177       1 pod.go:405] error syncing 'default/default-pod9': generate operations for port group ovn.default.caas.144 update ports [default-pod9.default]: get port group ovn.default.caas.144: get port group ovn.default.caas.144: object not found, requeuing
```

```

_uuid               : f462af4f-fb01-4919-b860-f9a87b1d682f
acls                : []
external_ids        : {np="node/caas-144"}
name                : node.caas.144
ports               : []
root@caas-144:~# kubectl ko nbctl list Port_Group | grep name
name                : node.caas.145
name                : node.caas.143
name                : ovn.sg.sg.example
name                : ovn.sg.sg.kube.system
name                : ovn.sg.sg.example.2
name                : ovn.sg.kubeovn_deny_all
name                : node.caas.144
```

**Comment by a180285** [comment]
我通过临时创建同名 pg 先绕过了这个 issue ，让 pod 先创成功，但是发现

```
root@caas-143:~# kubectl ko nbctl lr-route-list ovn-cluster
IPv4 Routes
Route Table <main>:
              10.5.192.19                  10.5.0.1 src-ip
                0.0.0.0/0                100.64.0.1 dst-ip
root@caas-143:~# kubectl ko nbctl lr-policy-list ovn-cluster
Routing Policies
     31000                           ip4.dst == 10.5.192.0/18           allow
     31000                           ip4.dst == 100.64.0.0/16           allow
     30000                              ip4.dst == 10.5.0.143         reroute                100.64.0.2
     30000                              ip4.dst == 10.5.0.144         reroute                100.64.0.3
     30000                              ip4.dst == 10.5.0.145         reroute                100.64.0.4
     29000                           ip4.src == 10.5.192.0/18         reroute                100.64.0.2, 100.64.0.3, 100.64.0.4
```
似乎 policy route 覆盖了日志添加的 static route

pod 的流量还是从 node 出去了
```
default-pod8:/# traceroute -n 10.2.200.52
traceroute to 10.2.200.52 (10.2.200.52), 30 hops max, 46 byte packets
 1  10.5.196.1  2.598 ms  1.364 ms  0.691 ms
 2  10.5.0.143  0.865 ms  0.003 ms  0.002 ms
 3  10.5.0.1  2.591 ms  0.866 ms  0.811 ms
...

default-pod8:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
1034: eth0@if1035: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:e0:b0:85 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.5.192.19/18 brd 10.5.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fee0:b085/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by zcq98** [comment]
> 经过一番研究发现，通过添加如下 route 可以实现 eip nat。 @geniusxiong 可以尝试一下
> 
> ```shell
> kubectl ko nbctl lr-policy-add ovn-cluster 31000 'ip4.src == 10.5.193.243' reroute 10.5.0.1
> kubectl ko nbctl lr-policy-list ovn-cluster
> ```
> 
> 其中
> 
> * 10.5.193.243 是 pod 的 IP
> * 10.5.0.1 是物理 vlan 中的 gateway IP
> 
> 怀疑可能是默认 VPC 下的 pod 全部路由到 join subnet ，而无法 snat 了 环境：
> 
> * join subnet: 100.64.0.0/16
> * ovn-default subnet: 10.5.192.0/18
> 
> ```
> kubectl ko nbctl lr-policy-list ovn-cluster
> Routing Policies
>      31000                           ip4.dst == 10.5.192.0/18           allow
>      31000                           ip4.dst == 100.64.0.0/16           allow
>      30000                              ip4.dst == 10.5.0.143         reroute                100.64.0.2
>      30000                              ip4.dst == 10.5.0.144         reroute                100.64.0.3
>      30000                              ip4.dst == 10.5.0.145         reroute                100.64.0.4
>      29000                           ip4.src == 10.5.192.0/18         reroute                100.64.0.2, 100.64.0.3, 100.64.0.4
> 
> kubectl ko nbctl lr-nat-list ovn-cluster
> TYPE             GATEWAY_PORT          EXTERNAL_IP        EXTERNAL_PORT    LOGICAL_IP          EXTERNAL_MAC         LOGICAL_PORT
> dnat_and_snat                          10.5.0.18                           10.5.193.243        00:00:00:D3:51:4B    default-pod4.default
> ```
> 
> @bobz965 上面的分析正确吗，是不是可以通过代码强制加 policy route 来修复这个问题呢

@bobz965 这个问题可能和之前multiple distributed gateway ports问题是一样的 https://github.com/kubeovn/ovn/pull/4，逻辑流表可能没有正确下发is_chassis_resident和outport，因为1.12没有引入我之前对ovn的修复。我待会儿测试一下是不是这个问题，按理说无需配置静态/策略路由。

**Comment by a180285** [comment]
@zcq98 和multiple dgw的bug无关的话。你本地可以复现这个 BUG 吗？还是你本地不能复现这个 BUG 呢

**Comment by zcq98** [comment]
> @zcq98 和multiple dgw的bug无关的话。你本地可以复现这个 BUG 吗？还是你本地不能复现这个 BUG 呢

1.12.4 可以复现，添加策略路由就正常了

**Comment by a180285** [comment]
@oilbeater 大佬对这个修复 PR 怎么看 https://github.com/kubeovn/kube-ovn/pull/3666

**Comment by caijian76** [comment]
1.13最新版还是相同问题。望解决。
