### ISSUE TITLE
node上kube-ovn组件和pod全部重启

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#3533]
k8s集群版本：1.20.21
kube-ovn:  1.11.1和1.11.10
内核：5.4.231-1.el7.elrepo.x86_64
节点数量一个240一个70
最近出现了一个现象：
每当在集群上创建statefulset的pod时，如果这个node上短时间内没有被调度过pod，这个时候新起pod的几个node
上的所有组件包括kube-ovn都会重启，我现在不知道是否是kube-ovn组件引起的网络闪断，不知道我需要提供什么信息能够定位？

**Comment by bobz965** [comment]
应该有err log 记录下来吧？

**Comment by wolgod** [comment]
我在ovn-ovs的controller的log 只看到收到新的pod的逻辑流表，然后这个时候所有的pod都重启了，我感觉像是ovn做了什么操作，导致所有的pod的网络被删除了，然后kubelet 又给拉起来，pod的event里面可以看到类似的信息
` Normal   Killing            43m (x2 over 3d20h)  kubelet  Stopping container driver-registrar
  Normal   SandboxChanged     43m (x2 over 3d20h)  kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Killing            43m (x2 over 3d20h)  kubelet  Stopping container csi-cephfsplugin
  Normal   Killing            43m (x2 over 3d20h)  kubelet  Stopping container liveness-prometheus
`

**Comment by oilbeater** [comment]
kube-ovn 不会做删除 pod 的操作，可以看下 kubelet 的日志，看现象像是出现了数据不一致 kubelet 强行停止所在节点的 pod

**Comment by wolgod** [comment]
已查到原因和kube-ovn无关
