### ISSUE TITLE
cleanup.sh htbqos crd deletion looks like blocked

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3548]
# Bug Report

## Actual Behavior
cleanup.sh htbqos crd deletion looks like blocked
## Steps to Reproduce the Problem

1. e2e run 
1.
1.

## Additional Info
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/9ae3ce4a-f991-4faa-a35a-05e4e9cc2f89)

- Kubernetes version:
master 
  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
master ha e2e

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by oilbeater** [comment]
I checked a successful action at [this link](https://github.com/kubeovn/kube-ovn/actions/runs/7272388441/job/19816407322), and it also lacks the htbqos deletion output.

**Comment by bobz965** [comment]
ohh, htbqoses.kubeovn.io looks like not need anymore

<img width="1229" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/7981158/3ad5972d-a862-4f48-bfaa-afb6206ba731">

**Comment by bobz965** [comment]
htbqos crd api not exist anymore
