### ISSUE TITLE
IPAM status is not correct when update subnet excludeIPs field

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#3574]
# Bug Report

## Expected Behavior

When update the subnet excludeIPs field, the ipam status should be updated accordingly.

## Actual Behavior

The `usingIPRange` and `usingIPs` mismatch, and may lead to ip duplication from  https://github.com/kubeovn/kube-ovn/pull/3368 report

## Steps to Reproduce the Problem

1. Init a kind cluster with default settings, IPs from `10.16.0.6-10.16.0.9` are used and the `v4usingIPrange` and `v4usingIPs` match.

```
  v4availableIPrange: 10.16.0.2-10.16.0.5,10.16.0.10-10.16.0.254
  v4availableIPs: 249
  v4usingIPrange: 10.16.0.6-10.16.0.9
  v4usingIPs: 4
```
2. Update the subnet ovn-default add `10.16.0.5..10.16.0.10` to excludeIPs, and then the `v4usingIPrange` and `v4usingIPs` mismatch.
```
  v4availableIPrange: 10.16.0.2-10.16.0.4,10.16.0.11-10.16.0.254
  v4availableIPs: 247
  v4usingIPrange: 10.16.0.6-10.16.0.9
  v4usingIPs: 0
```

3. Restart two kube-ovn-pinger pods, and then the `v4usingIPrange` and `v4usingIPs` still mismatch.

```
  v4availableIPrange: 10.16.0.4,10.16.0.8-10.16.0.9,10.16.0.11-10.16.0.254
  v4availableIPs: 245
  v4usingIPrange: 10.16.0.2-10.16.0.3,10.16.0.6-10.16.0.7
  v4usingIPs: 2
```

4. Restart the kube-ovn-controller, then the IP used in range of excludeIPs get lost

```
  v4availableIPrange: 10.16.0.4,10.16.0.11-10.16.0.254
  v4availableIPs: 245
  v4usingIPrange: 10.16.0.2-10.16.0.3
  v4usingIPs: 2
```

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0

  ```

- kube-ovn version:
  
  ```bash
master, 1.12

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by hongzhen-ma** [comment]
In PR  https://github.com/kubeovn/kube-ovn/pull/3550
The calcSubnetStatusIP and calcDualSubnetStatusIP are moved after c.ipam.AddOrUpdateSubnet since subnet.Status.availableIPrange valued from IPAM.
After the PR is merged, the problem should be resolved.
