### ISSUE TITLE
failed to set checksum off for genev_sys_6081, exit status 92

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3605]
# Bug Report

## Expected Behavior
set checksum off for genev_sys_6081 ok
## Actual Behavior
failed to set checksum off for genev_sys_6081, exit status not 0

## Steps to Reproduce the Problem

1.install master kube-ovn
1.
1.

## Additional Info

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/ddb5a5f8-bbb2-46df-bee6-a51d1ff585fa)

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
master

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```

**Comment by zcq98** [comment]
genev_sys_6081的设置放在了genev_sys_6081被创建之前了，92表示无法找到网卡设备。

**Comment by zcq98** [comment]
另外单个master节点也不会创建genev_sys_6081网卡，也会报这个错，但不影响
