### ISSUE TITLE
update 方法接口应该也要注入 vendor

### ISSUE THREAD

**Issue by fanriming** [kubeovn/kube-ovn#3610]
https://github.com/kubeovn/kube-ovn/blob/9a77310e0f6fc3ae2a5bb4f5f9f3d4604598d41c/pkg/ovs/ovn-nb-logical_switch_port.go#L714C43-L714C43

**Comment by bobz965** [comment]
@fanriming 大佬， CreateLogicalSwitchPortOp 有设置 vendor 是不是已经足够了？ 这个 bug 出现的原因是啥来着？

**Comment by fanriming** [comment]
> @fanriming 大佬， CreateLogicalSwitchPortOp 有设置 vendor 是不是已经足够了？ 这个 bug 出现的原因是啥来着？

是我本地旧版本代码的问题，已经修改了，我关闭这个issue
