### ISSUE TITLE
install.sh 里配置POD_CIDR地址池后，创建出的pod并没有按地址池中的地址分配ip，并且controller的log报错AddressOutOfRange

### ISSUE THREAD

**Issue by LY-today** [kubeovn/kube-ovn#3620]
# Bug Report

## Expected Behavior
修改了install.sh脚本中POD_CIDR的地址池后，pod的ip应该从POD_CIDR地址池中分配ip，而不是分配脚本里之前默认的10.16.0.0/16段以内的；同时通过annotation的ovn.kubernetes.io/ip_address指定ip为修改POD_CIDR池后里面的ip时controller不应该报错AddressOutOfRange，导致pod一致无法ready，无法初始化ip
## Actual Behavior
修改了POD_CIDR的地址池后，如果不指定annotation的ovn.kubernetes.io/ip_address，pod的ip为之前脚本默认的10.16.0.0/16段，指定了ovn.kubernetes.io/ip_address后，controller报错AddressOutOfRange
## Steps to Reproduce the Problem

1.修改install.sh 脚本中POD_CIDR的值为10.251.207.0/24，POD_GATEWAY为10.251.207.1
2.不指定annotation的ovn.kubernetes.io/ip_address，创建kubevirt的vm，pod的ip会是10.16.0.0/16段内
3.指定annotation的ovn.kubernetes.io/ip_address为10.251.207.3，controller报错：AddressOutOfRange

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

- kube-ovn version:
v1.12.0

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
CentOS Linux 7 (Core)
4.19.84-300.el7.x86_64

**Comment by LY-today** [comment]
controller配置如下：
```
Args:
      /kube-ovn/start-controller.sh
      --default-cidr=10.251.207.0/24
      --default-gateway=10.251.207.1
      --default-gateway-check=true
      --default-logical-gateway=false
      --default-u2o-interconnection=false
      --default-exclude-ips=
      --node-switch-cidr=100.64.0.0/16
      --service-cluster-ip-range=10.96.0.0/12
      --network-type=geneve
      --default-interface-name=
      --default-exchange-link-name=false
      --default-vlan-id=100
      --ls-dnat-mod-dl-dst=true
      --pod-nic-type=veth-pair
      --enable-lb=true
      --enable-np=true
      --enable-eip-snat=true
      --enable-external-vpc=true
      --logtostderr=false
      --alsologtostderr=true
      --gc-interval=360
      --inspect-interval=20
      --log_file=/var/log/kube-ovn/kube-ovn-controller.log
      --log_file_max_size=0
      --enable-lb-svc=false
      --keep-vm-ip=true
      --pod-default-fip-type=
      --node-local-dns-ip=
```

**Comment by bobz965** [comment]
`kubectl get subnet` 查看下 ovn-default 的子网是否成功修改

**Comment by LY-today** [comment]
> `kubectl get subnet` 查看下 ovn-default 的子网是否成功修改

没有修改成功，还是默认的10.16.0.0/16，那我接下来是手动kubectl edit subnet ovn-default，让他的cidrBlock和gateway和我的install.sh里面的一样才能符合预期吗？

**Comment by LY-today** [comment]
@bobz965 按https://kubeovn.github.io/docs/v1.12.x/ops/change-default-subnet/ 操作完后，创建vm报错：连接virt-api 被拒绝，网络不通了

**Comment by bobz965** [comment]
> > `kubectl get subnet` 查看下 ovn-default 的子网是否成功修改
> 
> 没有修改成功，还是默认的10.16.0.0/16，那我接下来是手动kubectl edit subnet ovn-default，让他的cidrBlock和gateway和我的install.sh里面的一样才能符合预期吗？

如果还没上业务的话，建议清理下kube-ovn，走重新部署。
