### ISSUE TITLE
Ovs-ovn Use ovn-central service cluster IP as OVN_DB_IPS rather than real NODE_IPs

### ISSUE THREAD

**Issue by lmxia** [kubeovn/kube-ovn#3668]
# Feature request
Ovs-ovn Use ovn-central service cluster IP as OVN_DB_IPS rather than real NODE_IPs

## Use case
When deploy ``kube-ovn`` we need to  label specific nodes with ``ovn-master`` label. And config the daemonset ovs-ovn with env OVN_DB_IPS="real node ip", that makes a little troublesome on some cases like CI.

So, should we use ``ovn-central `` service ``cluster IP`` to set env OVN_DB_IPS in ovs-ovn instead?

I have tried, but failed, as shown in pic below, any suggestions?

![WechatIMG59](https://github.com/kubeovn/kube-ovn/assets/11245380/87ba619c-a9d0-4864-a0c7-8e3fa64306bf)

**Comment by oilbeater** [comment]
`ovn-central` works in a cluster DB mode like etcd, the client need to connect directly to all available nodes to find the leader. You can try to connected to `ovn-sb` or `ovn-nb` which point to the leader Pod only. However we meet lots of trouble when connected with ClusterIP long ago so we finally choose to connected to all node directly.

**Comment by lmxia** [comment]
I miss used  svc cluster ip， sorry， close this issue.

**Comment by lmxia** [comment]
I miss used nb-svc as sb-svc, for now, it works well.

Is it suggested to use cluster ip in prod?

**Comment by oilbeater** [comment]
> Is it suggested to use cluster ip in prod?

We didn't recommend it, clusterIP relies on kube-proxy to switch endpoints when leader change, sometimes it takes a long time, during this time the network might break.

**Comment by lmxia** [comment]
Thanks, i see.

But, how if there is single replicas of `ovn-central`? may that be fine?

**Comment by oilbeater** [comment]
> how if there is single replicas of ovn-central?

That's fine, but the problem is that there is no high available at all.
