### ISSUE TITLE
Update helm chart repository

### ISSUE THREAD

**Issue by aminmr** [kubeovn/kube-ovn#3679]
# Bug Report

## Expected Behavior
I expected the Kube-OVN helm chart repository(https://kubeovn.github.io/kube-ovn/) to have all 1.12.x versions.

## Actual Behavior
It only has the 1.12.0 version of the helm chart

## Steps to Reproduce the Problem

1. helm repo add kubeovn https://kubeovn.github.io/kube-ovn/
2. helm search repo kubeovn/kube-ovn --versions

**Comment by hongzhen-ma** [comment]
After https://github.com/kubeovn/kube-ovn/pull/3691 is merged，it seems that chart-releaser-action does not work correctly.
Continue to resolve this problem.

**Comment by hongzhen-ma** [comment]
https://github.com/fabianlee/helmpubtest1/tree/main/.github/workflows

参考这个示例，以及在 https://github.com/helm/chart-releaser-action/issues/36 中的讨论
如果需要在github workflow中正确执行 chart-releaser-action，应该是需要修改charts 目录，在 charts 和 Chart.yaml 文件中间，再添加一层目录，例如修改为 charts/kube-ovn/Chart.yaml 这种格式。
这样应该能正常执行chart 发布流水线，避免以下的问题
<img width="929" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/67130442/78d2e8c4-5fff-4960-a40f-95bb63cd97ce">
