### ISSUE TITLE
v1.12.4 helm chart is failing to unknown flag --ls-ct-skip-dst-lport-ips 

### ISSUE THREAD

**Issue by lukasmrtvy** [kubeovn/kube-ovn#3708]
# Bug Report
kube-ovn-controller ( v1.12.4 ) , from helm chart ( https://github.com/kubeovn/kube-ovn/blob/release-1.12/charts/templates/controller-deploy.yaml#L102 ) fails to start due `unknown flag: --ls-ct-skip-dst-lport-ips`

**Comment by hongzhen-ma** [comment]
The archive tgz file has also beed updated same as the released v1.12.4.
https://github.com/kubeovn/kube-ovn/releases/tag/v1.12.4
