### ISSUE TITLE
helm chart is not available => 404

### ISSUE THREAD

**Issue by lukasmrtvy** [kubeovn/kube-ovn#3709]
# Bug Report

Helm chart releases in https://kubeovn.github.io/kube-ovn/index.yaml are pointing to https://github.com/kubeovn/kube-ovn/kube-ovn-1.12.4.tgz artifact instead of https://github.com/kubeovn/kube-ovn/blob/gh-pages/kube-ovn-1.12.4.tgz , this causes 404.

**Comment by oilbeater** [comment]
@lukasmrtvy Thanks for the report, the maintainer is still on vocation and we will try to fix it soon.

**Comment by hongzhen-ma** [comment]
@lukasmrtvy Thanks. The index.yaml has beed updated.
