### ISSUE TITLE
External gw config always includes all nodes disregarding the type mentioned in the ConfigMap

### ISSUE THREAD

**Issue by akbarkn** [kubeovn/kube-ovn#3715]
# Bug Report
In v1.12.4, the external gw config always includes all nodes disregarding the type mentioned in the `ConfigMap`. 
I have 2 nodes, node-01 and node-02. I set the external gw only to node-01 with type `centralized`, but somehow node-02 is always annotated as external gw and bridge of `br-external` also created there.

## Expected Behavior
External gw node should only be assigned to node-01

## Actual Behavior
node-01 and node-02 become external gw node

## Steps to Reproduce the Problem

1. Apply ovn-external-gw-config `ConfigMap`
```bash
apiVersion: v1
data:
  type: "centralized"
  enable-external-gw: "true"
  external-gw-addr: 192.168.56.254
  external-gw-nic: eno2
  external-gw-nodes: node-01
  nic-ip: 192.168.56.252/24
  nic-mac: 0c:c4:7a:00:ee:ff
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
```

2. Observe the annotation on all nodes
```
$ kubectl get nodes node-01 -o yaml | grep ovn.kubernetes.io/external-gw
    ovn.kubernetes.io/external-gw: "true"

$ kubectl get nodes node-02 -o yaml | grep ovn.kubernetes.io/external-gw
    ovn.kubernetes.io/external-gw: "true"
```

3. Observe bridges on all nodes
```
$ kubectl ko vsctl node-01 list-br
br-external
br-int

$ kubectl ko vsctl node-02 list-br
br-external
br-int
```
## Additional Info

- Kubernetes version:

  ```bash
  v1.26.12
  ```

- kube-ovn version:
  
  ```bash
  v1.12.4
  ```

- operation-system/kernel version:

  ```bash
  "Ubuntu 20.04.5 LTS"
  5.4.0-170-generic
  ```

## Possible Cause
I found that there's a change in the v1.12.4 to handle the external gw node (#3500), but it causes the `gwNodes` value in [here](https://github.com/kubeovn/kube-ovn/blob/v1.12.4/pkg/controller/external_gw.go#L233) always having all nodes as previously assigned [here](https://github.com/kubeovn/kube-ovn/blob/v1.12.4/pkg/controller/external_gw.go#L223) .

**Comment by a180285** [comment]
@oilbeater We found this node label has been fix in v.1.12.8
But the type: "centralized" is still not work.
we expect that all traffic go in and out by  "external-gw-nodes: node-01"
But it works like distributed, traffic go in and out just by the host node. Not the external-gw-nodes

**Comment by bobz965** [comment]
@a180285  hi, thanks for your info. 
in the case of `you expect that all traffic go in and out by "external-gw-nodes: node-01"`:
how about trying to  delete the  node label, if you don't want the node to be the `gw node`.

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/04b942b2-c396-41bf-b104-977915021f2b)

**Comment by bobz965** [comment]
$ kubectl get nodes node-01 -o yaml | grep ovn.kubernetes.io/external-gw
    ovn.kubernetes.io/external-gw: "true"

$ kubectl get nodes node-02 -o yaml | grep ovn.kubernetes.io/external-gw
    ovn.kubernetes.io/external-gw: "true"

delete the `ovn.kubernetes.io/external-gw: "true"` from the node-02. 

then the gw should be only one `node-01 `.

**Comment by oilbeater** [comment]
should be fixed in https://github.com/kubeovn/kube-ovn/pull/3724
