### ISSUE TITLE
netem qos does not work in RedHat 8.7 environment

### ISSUE THREAD

**Issue by hongzhen-ma** [kubeovn/kube-ovn#3758]
# Bug Report

## Expected Behavior
netem qos works 
## Actual Behavior
netem qos  does not work correctly

## Steps to Reproduce the Problem
1.  install kube-ovn  in redhat 8.7 cluster
2.  configure netem qos for pod
3.  test netem qos 

## Additional Info

- Kubernetes version:
v1.27.7

- kube-ovn version:
kube-ovn v1.12.5

- operation-system/kernel version:

<img width="1615" alt="企业微信截图_ad9d5464-53be-4fc6-b554-c214227ee891" src="https://github.com/kubeovn/kube-ovn/assets/67130442/f4179c73-f108-4271-994d-80fb1ae4e22d">

**Comment by zhangzujian** [comment]
[Available qdiscs in RHEL](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/linux-traffic-control_configuring-and-managing-networking#available-qdiscs-in-rhel_linux-traffic-control)

```shell
yum install -y kernel-modules-extra && modprobe sch_netem
```
