### ISSUE TITLE
CRD that can reserve ip via annotation

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3799]
# Bug Report

## Expected Behavior
I created a test CRD using KubeBuilder.  I'd like for this CRD to be able to reserve an address in an ippool via spec.template.metadata.annotations.ovn.kubernetes.io/ip_pool: $macaddr

## Actual Behavior
No address is allocated.

## CRD Definition
```
apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"webapp.my.domain/v1","kind":"Guestbook","metadata":{"annotations":{},"name":"testwithaddr","namespace":"default"},"spec":{"foo":"baz","template":{"metadata":{"annotations":{"ovn.kubernetes.io/ip_pool":"52:54:00:b6:31:12"}}}}}
  creationTimestamp: "2024-03-06T05:38:05Z"
  generation: 4
  name: testwithaddr
  namespace: default
  resourceVersion: "1167788"
  uid: f68715d0-fcf7-42b3-bd21-a07343101a6c
spec:
  foo: baz
  template:
    metadata:
      annotations:
        ovn.kubernetes.io/ip_pool: 52:54:00:b6:31:12
```
## IPPOOL 
```
~ ❯❯❯ k get ippool testpool -o yaml
apiVersion: kubeovn.io/v1
kind: IPPool
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeovn.io/v1","kind":"IPPool","metadata":{"annotations":{},"name":"testpool"},"spec":{"ips":["10.16.3.0/24"],"namespaces":["kube-system","default"],"subnet":"ovn-default"}}
  creationTimestamp: "2024-03-06T04:29:07Z"
  generation: 2
  name: testpool
  resourceVersion: "1150253"
  uid: 263a2855-0122-4df4-bcd8-61dbf80c333c
spec:
  ips:
  - 10.16.3.0/24
  namespaces:
  - kube-system
  - default
  subnet: ovn-default
status:
  conditions:
  - lastTransitionTime: "2024-03-06T04:29:07Z"
    lastUpdateTime: "2024-03-06T04:29:07Z"
    reason: UpdateIPAMSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-03-06T04:29:07Z"
    lastUpdateTime: "2024-03-06T04:29:07Z"
    message: Not Observed
    reason: Init
    status: Unknown
    type: Error
  v4AvailableIPRange: 10.16.3.0-10.16.3.255
  v4AvailableIPs: 256
  v4UsingIPRange: ""
  v4UsingIPs: 0
  v6AvailableIPRange: ""
  v6AvailableIPs: 0
  v6UsingIPRange: ""
  v6UsingIPs: 0

```

## Subnet
```
~ ❯❯❯ k get subnet ovn-default -o yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  creationTimestamp: "2024-03-04T23:14:17Z"
  finalizers:
  - kube-ovn-controller
  generation: 1
  name: ovn-default
  resourceVersion: "1123164"
  uid: fbe29482-4196-4bf4-8cdb-910eec7af688
spec:
  cidrBlock: 10.16.0.0/16
  default: true
  enableLb: true
  excludeIps:
  - 10.16.0.1
  gateway: 10.16.0.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
status:
  activateGateway: ""
  conditions:
  - lastTransitionTime: "2024-03-04T23:14:19Z"
    lastUpdateTime: "2024-03-04T23:21:39Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Validated
  - lastTransitionTime: "2024-03-04T23:14:19Z"
    lastUpdateTime: "2024-03-04T23:14:19Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-03-04T23:14:19Z"
    lastUpdateTime: "2024-03-04T23:14:19Z"
    message: Not Observed
    reason: Init
    status: Unknown
    type: Error
  dhcpV4OptionsUUID: ""
  dhcpV6OptionsUUID: ""
  natOutgoingPolicyRules: []
  u2oInterconnectionIP: ""
  u2oInterconnectionVPC: ""
  v4availableIPrange: 10.16.0.5-10.16.0.6,10.16.0.8,10.16.0.10-10.16.0.11,10.16.0.16,10.16.0.35,10.16.0.40,10.16.0.46,10.16.0.50-10.16.0.51,10.16.0.55-10.16.255.254
  v4availableIPs: 65491
  v4usingIPrange: 10.16.0.2-10.16.0.4,10.16.0.7,10.16.0.9,10.16.0.12-10.16.0.15,10.16.0.17-10.16.0.34,10.16.0.36-10.16.0.39,10.16.0.41-10.16.0.45,10.16.0.47-10.16.0.49,10.16.0.52-10.16.0.54
  v4usingIPs: 42
  v6availableIPrange: ""
  v6availableIPs: 0
  v6usingIPrange: ""
  v6usingIPs: 0

```

## Steps to Reproduce the Problem
1.  Create a CRD with kubebuilder
2.  Extend the Spec to include spec.templates.metadata.annotations
3.  Apply a CRD with an annotation

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
~ ❯❯❯ kubectl version                                                                                                                                                                    
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+rke2r1
  ```

- kube-ovn version:
  
  ```bash
 version: v1.12.7
  ```

**Comment by bobz965** [comment]
I think you can use ip pool to reserve a set of  IP first.
 and then use the IP from it on your own apps.

**Comment by Smithx10** [comment]
Good Day @bobz965, @zhangzujian 

I will try to clarify what I am attempting to do.

Currently were have a Go application that NetBoots Machines.  In order to do this,  the application runs a DHCP server, and the application is in charge of pushing down the correct IPXE config with the correct information to join our Cluster running KubeOVN.    The Go application DHCP Server would use KubeOVN IPAM to serve addresses for my host networks.

I'd like to create a set of CRDs that define "Machines" that use KubeOVN IPAM for reserving addresses for my physical machines.   I've boot strapped a simple demo controller to test the functionality of reserving / marking addresses in-use on a subnet.    Machines also would keep aggregation / bond information etc... but that isn't relevant to KubeOVN.


I'd like for these addresses to be shown as "in use"....
 they will be the addresses used for:
   The underlay interface
   The internal node-ip
   The external node-ip
   A Storage network addr.
 
 In this scenario,  what approach would you take?  I've seen several notes in the documentation about using annotation from any CRD but the code doesn't seem to be written in this manner,  unless I misread or am mistaken.

**Comment by zhangzujian** [comment]
> I'd like for these addresses to be shown as "in use"....

Not supported in Kube-OVN currently.

**Comment by zhangzujian** [comment]
You can create IP CRs to "mark" the ip as in use:

```yaml
apiVersion: kubeovn.io/v1
kind: IP
metadata:
  finalizers:
  - example.com/dhcp-server # your controller
  labels:
    ovn-default: ""
    ovn.kubernetes.io/ip_reserved: "true"
    # ovn.kubernetes.io/node-name: kube-ovn-control-plane
    ovn.kubernetes.io/subnet: ovn-default
  name: dhcp-ip1
spec:
  # attachIps: []
  # attachMacs: []
  # attachSubnets: []
  # containerID: ""
  ipAddress: 10.16.0.100
  # macAddress: 00:00:00:ED:91:0D
  # namespace: ""
  # nodeName: kube-ovn-control-plane
  # podName: kube-ovn-control-plane
  podType: VirtualMachine
  subnet: ovn-default
  v4IpAddress: 10.16.0.100
  # v6IpAddress: ""
```

**Comment by bobz965** [comment]
> You can create IP CRs to "mark" the ip as in use:
> 
> ```yaml
> apiVersion: kubeovn.io/v1
> kind: IP
> metadata:
>   finalizers:
>   - example.com/dhcp-server # your controller
>   labels:
>     ovn-default: ""
>     ovn.kubernetes.io/ip_reserved: "true"
>     # ovn.kubernetes.io/node-name: kube-ovn-control-plane
>     ovn.kubernetes.io/subnet: ovn-default
>   name: dhcp-ip1
> spec:
>   # attachIps: []
>   # attachMacs: []
>   # attachSubnets: []
>   # containerID: ""
>   ipAddress: 10.16.0.100
>   # macAddress: 00:00:00:ED:91:0D
>   # namespace: ""
>   # nodeName: kube-ovn-control-plane
>   # podName: kube-ovn-control-plane
>   podType: VirtualMachine
>   subnet: ovn-default
>   v4IpAddress: 10.16.0.100
>   # v6IpAddress: ""
> ```

yeah, the IP CR exists, which means it is used from a subnet or an ip pool.

**Comment by Smithx10** [comment]
Awesome I think this will work out just fine then.  Thank you so much for your time and patience.
