### ISSUE TITLE
kube-virt+kube-ovn多网卡情况下，IP分配错误

### ISSUE THREAD

**Issue by OneWithoutName** [kubeovn/kube-ovn#3842]
# Bug Report
kube-virt+kube-ovn组合使用，使用多网卡，每个网卡为不同的vpc的子网，IP分配有误。
## Expected Behavior
2个自定义网卡IP分别使用各自指定子网下的IP
## Actual Behavior
2个自定义网卡均为其中1子网下的IP
## Steps to Reproduce the Problem

1.创建名为命名空间namespace。并创建2个Subnet，网段分别为10.0.1.0/24和10.0.3.0/24

> [root@node153 ~]# kubectl get Subnet vpc-testsubnet1
NAME              PROVIDER   VPC        PROTOCOL   CIDR          PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                             U2OINTERCONNECTIONIP
vpc-testsubnet1   ovn        testvpc1   IPv4       10.0.1.0/24   false     false   false     distributed   5        185           0        0             ["10.0.1.0..10.0.1.63","10.0.1.254"]

kubectl get Subnet vpc-testsubnet4
NAME              PROVIDER   VPC        PROTOCOL   CIDR          PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                             U2OINTERCONNECTIONIP
vpc-testsubnet4   ovn        testvpc4   IPv4       10.0.4.0/24   false     false   false     distributed   0        190           0        0             ["10.0.4.0..10.0.4.63","10.0.4.254"]

2.创建vm资源
[root@node153 ~]# kubectl get vm -n chunbo i-szc15xgh -o yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    virt-resource/alias-name: lhj-006
    virt-resource/creator-id: 1df71957d770436493a84f24d9344853
    virt-resource/creator-name: admin
    virt-resource/description: ""
    virt-resource/project-id: b5df7746-4c9a-49cd-a474-d9bacf406214
    virt-resource/project-name: ""
    virt-resource/system-disk-config: '{"size":"20Gi","OS":"ubuntu xxx"}'
  creationTimestamp: "2024-03-19T02:09:45Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  generation: 2
  name: i-szc15xgh
  namespace: chunbo
  resourceVersion: "7766984"
  uid: 979500ae-7eee-4df0-94eb-e734a4edf9be
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        virt-resource/alias-name: lhj-006
        virt-resource/creator-id: 1df71957d770436493a84f24d9344853
        virt-resource/creator-name: admin
        virt-resource/description: ""
        virt-resource/project-id: b5df7746-4c9a-49cd-a474-d9bacf406214
        virt-resource/project-name: ""
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: vol-gejg5wpy
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: eth0
          - bridge: {}
            name: eth1
          rng: {}
        machine:
          type: q35
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: lhj-006
      networks:
      - multus:
          networkName: kube-system/vpc-testsubnet1
        name: eth0
      - multus:
          networkName: kube-system/vpc-testsubnet4
        name: eth1
      nodeSelector:
        kubernetes.io/hostname: node154
      volumes:
      - dataVolume:
          name: dv-vol-gejg5wpy
        name: vol-gejg5wpy
      - cloudInitNoCloud:
          networkDataBase64: dmVyc2lvbjogMgpldGhlcm5ldHM6CiAgZXRoMDoKICAgIGRoY3A0OiB0cnVlCiAgICBnYXRld2F5NDogIiIKICAgIG1hdGNoOgogICAgICBtYWNhZGRyZXNzOiAiIgogICAgbmFtZXNlcnZlcnM6CiAgICAgIGFkZHJlc3NlczoKICAgICAgLSAxMTQuMTE0LjExNC4xMTQKICBldGgxOgogICAgZGhjcDQ6IHRydWUKICAgIGdhdGV3YXk0OiAiIgogICAgbWF0Y2g6CiAgICAgIG1hY2FkZHJlc3M6ICIiCiAgICBuYW1lc2VydmVyczoKICAgICAgYWRkcmVzc2VzOgogICAgICAtIDExNC4xMTQuMTE0LjExNAogIGV0aDI6CiAgICBkaGNwNDogdHJ1ZQogICAgZ2F0ZXdheTQ6ICIiCiAgICBtYXRjaDoKICAgICAgbWFjYWRkcmVzczogIiIKICAgIG5hbWVzZXJ2ZXJzOgogICAgICBhZGRyZXNzZXM6CiAgICAgIC0gMTE0LjExNC4xMTQuMTE0Cg==
          userDataBase64: I2Nsb3VkLWNvbmZpZw0KdXBkYXRlczoNCiAgbmV0d29yazoNCiAgICB3aGVuOiBbJ2Jvb3QnXQ0KdGltZXpvbmU6IEFzaWEvU2hhbmdoYWkNCnBhY2thZ2VzOg0KIC0gY2xvdWQtaW5pdA0KcGFja2FnZV91cGRhdGU6IHRydWUNCnNzaF9wd2F1dGg6IHRydWUNCmRpc2FibGVfcm9vdDogZmFsc2UNCmNocGFzc3dkOiB7Imxpc3QiOiJyb290OjFxYXpAV1NYIixleHBpcmU6IEZhbHNlfQ0KcnVuY21kOg0KIC0gc2VkIC1pICIvUGVybWl0Um9vdExvZ2luL3MvXi4qJC9QZXJtaXRSb290TG9naW4geWVzL2ciIC9ldGMvc3NoL3NzaGRfY29uZmlnDQogLSBzeXN0ZW1jdGwgcmVzdGFydCBzc2hkLnNlcnZpY2U=
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-19T18:39:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: null
    message: All of the VMI's DVs are bound and not running
    reason: AllDVsReady
    status: "True"
    type: DataVolumesReady
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  created: true
  desiredGeneration: 2
  observedGeneration: 2
  printableStatus: Running
  ready: true
  volumeSnapshotStatuses:
  - enabled: true
    name: vol-gejg5wpy
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]

3. 观察pod信息的网卡信息，发现均使用了testsubnet1的网段信息。
[root@node153 ~]# kubectl describe po -n chunbo  virt-launcher-i-szc15xgh-4px4w
Name:             virt-launcher-i-szc15xgh-4px4w
Namespace:        chunbo
Priority:         0
Service Account:  default
Node:             node154/10.210.20.154
Start Time:       Wed, 20 Mar 2024 02:39:24 +0800
Labels:           kubevirt.io=virt-launcher
                  kubevirt.io/created-by=00d940f8-1d04-469f-bcf9-f98b4b3e9e25
                  kubevirt.io/nodeName=node154
                  vm.kubevirt.io/name=lhj-006
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "kube-ovn",
                        "interface": "eth0",
                        "ips": [
                            "10.0.1.67"
                        ],
                        "mac": "00:00:00:A8:E8:E7",
                        "default": true,
                        "dns": {},
                        "gateway": [
                            "10.0.1.254"
                        ]
                    },{
                        "name": "kube-system/vpc-testsubnet1",
                        "interface": "pod9c32a8c7e59",
                        "ips": [
                            "10.0.1.64"
                        ],
                        "mac": "00:00:00:99:30:AC",
                        "dns": {}
                    },{
                        "name": "kube-system/vpc-testsubnet4",
                        "interface": "pod980816f36b7",
                        "ips": [
                            "10.0.1.68"
                        ],
                        "mac": "00:00:00:53:75:BA",
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks:
                    [{"name":"vpc-testsubnet1","namespace":"kube-system","interface":"pod9c32a8c7e59"},{"name":"vpc-testsubnet4","namespace":"kube-system","in...
                  kubectl.kubernetes.io/default-container: compute
                  kubevirt.io/domain: i-szc15xgh
                  kubevirt.io/migrationTransportUnix: true
                  kubevirt.io/vm-generation: 2
                  ovn.kubernetes.io/allocated: true
                  ovn.kubernetes.io/cidr: 10.0.1.0/24
                  ovn.kubernetes.io/gateway: 10.0.1.254
                  ovn.kubernetes.io/ip_address: 10.0.1.67
                  ovn.kubernetes.io/logical_router: testvpc3
                  ovn.kubernetes.io/logical_switch: vpc-testsubnet3
                  ovn.kubernetes.io/mac_address: 00:00:00:A8:E8:E7
                  ovn.kubernetes.io/pod_nic_type: veth-pair
                  ovn.kubernetes.io/routed: true
                  ovn.kubernetes.io/virtualmachine: i-szc15xgh
                  post.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--unfreeze", "--name", "i-szc15xgh", "--namespace", "chunbo"]
                  post.hook.backup.velero.io/container: compute
                  pre.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--freeze", "--name", "i-szc15xgh", "--namespace", "chunbo"]
                  pre.hook.backup.velero.io/container: compute
                  virt-resource/alias-name: lhj-006
                  virt-resource/creator-id: 1df71957d770436493a84f24d9344853
                  virt-resource/creator-name: admin
                  virt-resource/description:
                  virt-resource/project-id: b5df7746-4c9a-49cd-a474-d9bacf406214
                  virt-resource/project-name:
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/allocated: true
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/cidr: 10.0.1.0/24
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/gateway: 10.0.1.254
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/ip_address: 10.0.1.64
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/logical_router: testvpc3
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/mac_address: 00:00:00:99:30:AC
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/pod_nic_type: veth-pair
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/routed: true
                  vpc-testsubnet1.kube-system.ovn.kubernetes.io/virtualmachine: i-szc15xgh
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/allocated: true
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/cidr: 10.0.1.0/24
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/gateway: 10.0.1.254
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/ip_address: 10.0.1.68
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/logical_router: testvpc3
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/mac_address: 00:00:00:53:75:BA
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/pod_nic_type: veth-pair
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/routed: true
                  vpc-testsubnet4.kube-system.ovn.kubernetes.io/virtualmachine: i-szc15xgh
Status:           Running
IP:               10.0.1.67
IPs:
  IP:           10.0.1.67
Controlled By:  VirtualMachineInstance/i-szc15xgh
Containers:
  compute:
    Container ID:  containerd://32f8b541ea1df5a3981d312d43bba316727ab4e29de0dcc15a883ca7fedeb047
    Image:         os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher:v1.2.0
    Image ID:      os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher@sha256:692f9fc8cb5432c4d0ac295c101cfc5f099aa519da4906ae0bda9e555bd2d589
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher-monitor
      --qemu-timeout
      256s
      --name
      i-szc15xgh
      --uid
      00d940f8-1d04-469f-bcf9-f98b4b3e9e25
      --namespace
      chunbo
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --grace-period-seconds
      45
      --hook-sidecars
      0
      --ovmf-path
      /usr/share/OVMF
      --run-as-nonroot
    State:          Running
      Started:      Wed, 20 Mar 2024 02:39:29 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                            2
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      memory:                         1376Mi
    Requests:
      cpu:                            2
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      ephemeral-storage:              50M
      memory:                         1376Mi
    Environment:
      XDG_CACHE_HOME:               /var/run/kubevirt-private
      XDG_CONFIG_HOME:              /var/run/kubevirt-private
      XDG_RUNTIME_DIR:              /var/run
      KUBEVIRT_RESOURCE_NAME_eth0:
      KUBEVIRT_RESOURCE_NAME_eth1:
      POD_NAME:                     virt-launcher-i-szc15xgh-4px4w (v1:metadata.name)
    Mounts:
      /var/run/kubevirt from public (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-private from private (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/hotplug-disks from hotplug-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
    Devices:
      /dev/vol-gejg5wpy from vol-gejg5wpy
  guest-console-log:
    Container ID:  containerd://79ae3f8372f1c42c8315a16febb36bdf48e65b1fc954ae106d06c9f62b099504
    Image:         os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher:v1.2.0
    Image ID:      os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher@sha256:692f9fc8cb5432c4d0ac295c101cfc5f099aa519da4906ae0bda9e555bd2d589
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-tail
    Args:
      --logfile
      /var/run/kubevirt-private/00d940f8-1d04-469f-bcf9-f98b4b3e9e25/virt-serial0-log
    State:          Running
      Started:      Wed, 20 Mar 2024 02:39:30 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     15m
      memory:  60M
    Requests:
      cpu:     15m
      memory:  60M
    Environment:
      VIRT_LAUNCHER_LOG_VERBOSITY:  2
    Mounts:
      /var/run/kubevirt-private from private (ro)
Readiness Gates:
  Type                                   Status
  kubevirt.io/virtual-machine-unpaused   True
Conditions:
  Type                                   Status
  kubevirt.io/virtual-machine-unpaused   True
  Initialized                            True
  Ready                                  True
  ContainersReady                        True
  PodScheduled                           True
Volumes:
  private:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  public:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  container-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  vol-gejg5wpy:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  dv-vol-gejg5wpy
    ReadOnly:   false
  hotplug-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Guaranteed
Node-Selectors:  kubernetes.io/arch=amd64
                 kubernetes.io/hostname=node154
                 kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 5s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 5s
Events:
  Type    Reason                  Age    From                     Message
  
  Normal  Scheduled               3m28s  default-scheduler        Successfully assigned chunbo/virt-launcher-i-szc15xgh-4px4w to node154
  Normal  SuccessfulAttachVolume  3m27s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c8e2f3c0-723f-4a68-96a6-ab9dfebd9370"
  Normal  SuccessfulMountVolume   3m25s  kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-c8e2f3c0-723f-4a68-96a6-ab9dfebd9370" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-c8e2f3c0-723f-4a68-96a6-ab9dfebd9370/dev"
  Normal  SuccessfulMountVolume   3m25s  kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-c8e2f3c0-723f-4a68-96a6-ab9dfebd9370" volumeMapPath "/var/lib/kubelet/pods/25787ecc-d648-4923-8683-4c82a906f89e/volumeDevices/kubernetes.io~csi"
  Normal  AddedInterface          3m24s  multus                   Add eth0 [10.0.1.67/24] from kube-ovn
  Normal  AddedInterface          3m24s  multus                   Add pod9c32a8c7e59 [10.0.1.64/24] from kube-system/vpc-testsubnet1
  Normal  AddedInterface          3m23s  multus                   Add pod980816f36b7 [10.0.1.68/24] from kube-system/vpc-testsubnet4
  Normal  Pulled                  3m23s  kubelet                  Container image "os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher:v1.2.0" already present on machine
  Normal  Created                 3m23s  kubelet                  Created container compute
  Normal  Started                 3m23s  kubelet                  Started container compute
  Normal  Pulled                  3m23s  kubelet                  Container image "os-harbor-svc.default.svc.cloudos:443/helm/kubevirt/virt-launcher:v1.2.0" already present on machine
  Normal  Created                 3m23s  kubelet                  Created container guest-console-log
  Normal  Started                 3m22s  kubelet                  Started container guest-console-log

## Additional Info

- Kubernetes version:
v1.27.6

- kube-virt version:
 v1.20

- kube-ovn version:
 v1.12.4

- multus version:
 v4.0.2 
 
- os info:
 X86 openEular

**Comment by xieyanker** [comment]
你的multus资源 net-attach-def `kube-system/vpc-testsubnet1` 和 `kube-system/vpc-testsubnet4` 配置的具体内容是否有区别？

**Comment by OneWithoutName** [comment]
> 你的multus资源 net-attach-def `kube-system/vpc-testsubnet1` 和 `kube-system/vpc-testsubnet4` 配置的具体内容是否有区别？

看了下，没有区别。

[root@node153 ~]# kubectl describe net-attach-def  -n kube-system   vpc-testsubnet1
Name:         vpc-testsubnet1
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2024-03-13T22:56:20Z
  Generation:          1
  Resource Version:    768872
  UID:                 e39f86d3-f67c-43ee-8a3f-1e96cb5e96d8
Spec:
  Config:  {"cniVersion":"0.3.0","provider":"vpc-testsubnet1.kube-system.ovn","server_socket":"/run/openvswitch/kube-ovn-daemon.sock","type":"kube-ovn"}
Events:    <none>
[root@node153 ~]# kubectl describe net-attach-def  -n kube-system   vpc-testsubnet4
Name:         vpc-testsubnet4
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2024-03-14T19:16:28Z
  Generation:          1
  Resource Version:    1571792
  UID:                 b4f1c16c-8770-4862-ac45-10f06354c322
Spec:
  Config:  {"cniVersion":"0.3.0","provider":"vpc-testsubnet4.kube-system.ovn","server_socket":"/run/openvswitch/kube-ovn-daemon.sock","type":"kube-ovn"}
Events:    <none>

**Comment by OneWithoutName** [comment]
![IP1](https://github.com/kubeovn/kube-ovn/assets/20835236/5692e559-71fa-4452-bc34-b64cc95bf6d8)
![pic](https://github.com/kubeovn/kube-ovn/assets/20835236/dde00f89-fcce-422c-a2f9-4b31c197aedd)
![POD2](https://github.com/kubeovn/kube-ovn/assets/20835236/32400506-3bb7-4c89-8cfe-af9e53cf0cbf)

附上我第一复现时，multus和kube-ovn-controller的截图，和issue中用例略有出入，但基本上是一致的。kube-ovn-controller中日志展示从 不同的vpc子网中获取IP，multus日志显示从相同的vpc子网获取IP。不知道这个信息能否提供一些价值。

**Comment by xieyanker** [comment]
我看到你的pod上有这三个annotations：
`ovn.kubernetes.io/logical_switch: vpc-testsubnet3`
`vpc-testsubnet1.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3`
`vpc-testsubnet4.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3`
默认网卡和两个自定义网卡都指定了vpc-testsubnet3子网，是因为你把namespace `chunbo`和subnet `vpc-testsubnet3`关联起来了吗？

**Comment by OneWithoutName** [comment]
> 我看到你的pod上有这三个annotations： `ovn.kubernetes.io/logical_switch: vpc-testsubnet3` `vpc-testsubnet1.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3` `vpc-testsubnet4.kube-system.ovn.kubernetes.io/logical_switch: vpc-testsubnet3` 默认网卡和两个自定义网卡都指定了vpc-testsubnet3子网，是因为你把namespace `chunbo`和subnet `vpc-testsubnet3`关联起来了吗？


vpc-testsubnet3和vpc-testsubnet1都关联了chunbo这一命名空间，这三个注解应该是kube-ovn下发的。

**Comment by xieyanker** [comment]
你现在的subnet `vpc-testsubnet1` 和 `vpc-testsubnet4` 中的 `provider` 都是 `ovn`，我感觉你应该改成 `vpc-testsubnet1.kube-system.ovn` 和 `vpc-testsubnet4.kube-system.ovn`。

**Comment by OneWithoutName** [comment]
确实是这个问题。改了以后可以了，谢谢，不过我看kube-ovn文档-使用指南中，VPC使用的yaml模板是没有提到要显式设置provider。

**Comment by xieyanker** [comment]
> 确实是这个问题。改了以后可以了，谢谢，不过我看kube-ovn文档-使用指南中，VPC使用的yaml模板是没有提到要显式设置provider。

你看一下这个例子 https://kubeovn.github.io/docs/stable/advance/multi-nic/#kube-ovn-subnet

**Comment by OneWithoutName** [comment]
> > 确实是这个问题。改了以后可以了，谢谢，不过我看kube-ovn文档-使用指南中，VPC使用的yaml模板是没有提到要显式设置provider。
> 
> 你看一下这个例子 https://kubeovn.github.io/docs/stable/advance/multi-nic/#kube-ovn-subnet

好的，多谢。
