### ISSUE TITLE
kubeovn chart values doesn't have ENABLE_IC=true

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3850]
I'm installing KubeOVN in hopes to use the Cluster Interconnect feature,  While doing so I noticed I cannot set 
ENABLE_IC=true as documented here:
https://kubeovn.github.io/docs/v1.12.x/en/advance/with-ovn-ic/#prerequisites

**Comment by zhangzujian** [comment]
Please use the latest version:

https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.12/dist/images/install.sh

**Comment by zhangzujian** [comment]
Thanks for the report.

You can install chart with `--set func.ENABLE_IC=true` to enable OVN IC.
