### ISSUE TITLE
how to create  subnet without a gateway?

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3870]
I have a storage underlay network that doesn't route.... how do I create a subnet without a gateway?

**Comment by zhangzujian** [comment]
You can set the subnet's `.spec.u2oInterconnection` to `true` to use a logical gateway.

**Comment by Smithx10** [comment]
While deleting and recreating storage0 i encountered kube-ovn crashing.

Anytime I create storage0 it results in a crash of the kube-ovn-controller

am running 1.13.  

```
I0326 03:53:53.206548       1 init.go:619] start to sync subnets
E0326 03:53:53.207347       1 subnet.go:2223] ipam subnet storage0 has no ip in using, but some ip cr left: ip 1, vip 0, iptable eip 0, ovn eip 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x560e836c4768]

goroutine 117 [running]:
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).syncSubnetCR(0xc00084bb08)
        github.com/kubeovn/kube-ovn/pkg/controller/init.go:636 +0x668
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).Run(0xc00084bb08, {0x560e84c7b858, 0xc0005222d0})
        github.com/kubeovn/kube-ovn/pkg/controller/controller.go:780 +0x1df
github.com/kubeovn/kube-ovn/pkg/controller.Run({0x560e84c7b858, 0xc0005222d0}, 0xc00041c308)
        github.com/kubeovn/kube-ovn/pkg/controller/controller.go:733 +0xb845
github.com/kubeovn/kube-ovn/cmd/controller.CmdMain.func3({0x560e84c7b858?, 0xc0005222d0?})
        github.com/kubeovn/kube-ovn/cmd/controller/controller.go:117 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run in goroutine 1
        k8s.io/client-go@v12.0.0+incompatible/tools/leaderelection/leaderelection.go:213 +0xe6

```

**Comment by Smithx10** [comment]
I was hoping to just not have any gateway and just have the endpoints on the underlay connect only to eachother.   This subnet has no need for any connectivity outside of itself.  I do notice the subnet keeps giving it the default value of the first available address.  By using under2overlay interconnect true.... will that attempt to route over one of the overlays?

**Comment by zhangzujian** [comment]
You can create a VPC and set the subnet's `.spec.vpc` to the VPC name. Set `.spec.u2oInterconnection` to `true` at the same time.

**Comment by Smithx10** [comment]
This seems like a lot to go through to just have no gateway for an underlay.  I guess we can just set the ignoreGatewayCheck just have it be ignored.
