### ISSUE TITLE
Central Place for Annotation Documentation

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3886]
Kube-OVN heavily uses annotations for many functions,  it would be nice if the Reference page listed all of the Kube-OVN annotations that a user can apply and what their purpose / function is.   

The dependency change for an annotation to function should be clearly defined in this documentation.  

Learning these patterns takes much experimentation at the moment.    

I am going to attempt to write some of this in a very clear manner,  but there are still annotations I don't know how to use yet.

**Comment by bobz965** [comment]
Thanks, you can post a PR to the `kubeovn/docs` repo,  we can give details about the annotations you don't know in the PR.

**Comment by oilbeater** [comment]
Hi, @Smithx10 are you still working on this? Most of the annotation can be found here: https://github.com/kubeovn/kube-ovn/blob/master/pkg/util/const.go. You can first write down the annotations you know, and we will supplement the explanations of other annotations based on your format.You can first write down the annotations you know, and we will supplement the explanations of other annotations based on your format.

**Comment by oilbeater** [comment]
Finished by https://github.com/kubeovn/docs/pull/168
