### ISSUE TITLE
Waiting for daemon set "kube-ovn-cni" rollout to finish: 0 of 1 updated pods are available...

### ISSUE THREAD

**Issue by zhenliangliang** [kubeovn/kube-ovn#3892]
my k8s version:1.28.8
kube-ovn version: 1.12
执行bash install.sh 安装到kube-ovn-cni 一直提示超时，已确认 /etc/cni/net.d目录下无其他网络插件，k8s集群也是新安装的环境

**Comment by zhenliangliang** [comment]
执行结果：
[Step 3/6] Install Kube-OVN
configmap/ovn-vpc-nat-config created
configmap/ovn-vpc-nat-gw-config created
deployment.apps/kube-ovn-controller created
daemonset.apps/kube-ovn-cni created
daemonset.apps/kube-ovn-pinger created
deployment.apps/kube-ovn-monitor created
service/kube-ovn-monitor created
service/kube-ovn-pinger created
service/kube-ovn-controller created
service/kube-ovn-cni created
Waiting for deployment "kube-ovn-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "kube-ovn-controller" successfully rolled out
Waiting for daemon set "kube-ovn-cni" rollout to finish: 0 of 1 updated pods are available...
error: timed out waiting for the condition

**Comment by zhenliangliang** [comment]
I0401 11:59:16.013921   63485 config.go:169] node name not specified in command line parameters, fall back to the environment variable
I0401 11:59:16.013952   63485 config.go:347] no --kubeconfig, use in-cluster kubernetes config
I0401 11:59:16.014592   63485 k8s.go:27] succeeded to dial apiserver "10.96.0.1:443"
I0401 11:59:16.072073   63485 config.go:187] daemon config: &{ eth1 br-phy 1400 1360 false mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0xc0001d1860 0xc000328710 node1 10.96.0.0/12 ovn-cluster join true false false 10665 geneve /etc/cni/net.d /kube-ovn/01-kube-ovn.conflist 01-kube-ovn.conflist provider eth1 kube-system external true true /var/lib/kubelet false 8100 8101 false 100}
I0401 11:59:16.090081   63485 cniserver.go:55] init node gw
I0401 11:59:16.119280   63485 ovs_linux.go:409] wait ovn0 gw ready
W0401 11:59:19.120617   63485 ovs.go:34] 100.64.0.2 network not ready after 3 ping to gateway 100.64.0.1
W0401 11:59:22.120862   63485 ovs.go:34] 100.64.0.2 network not ready after 6 ping to gateway 100.64.0.1
W0401 11:59:25.120912   63485 ovs.go:34] 100.64.0.2 network not ready after 9 ping to gateway 100.64.0.1
W0401 11:59:28.120777   63485 ovs.go:34] 100.64.0.2 network not ready after 12 ping to gateway 100.64.0.1
W0401 11:59:31.120873   63485 ovs.go:34] 100.64.0.2 network not ready after 15 ping to gateway 100.64.0.1
W0401 11:59:34.120680   63485 ovs.go:34] 100.64.0.2 network not ready after 18 ping to gateway 100.64.0.1
W0401 11:59:37.120439   63485 ovs.go:34] 100.64.0.2 network not ready after 21 ping to gateway 100.64.0.1
W0401 11:59:40.120580   63485 ovs.go:34] 100.64.0.2 network not ready after 24 ping to gateway 100.64.0.1
W0401 11:59:43.120618   63485 ovs.go:34] 100.64.0.2 network not ready after 27 ping to gateway 100.64.0.1
W0401 11:59:46.120650   63485 ovs.go:34] 100.64.0.2 network not ready after 30 ping to gateway 100.64.0.1
W0401 11:59:49.120220   63485 ovs.go:34] 100.64.0.2 network not ready after 33 ping to gateway 100.64.0.1
W0401 11:59:52.120931   63485 ovs.go:34] 100.64.0.2 network not ready after 36 ping to gateway 100.64.0.1

**Comment by zhangzujian** [comment]
检查一下 ovs-ovn 以及 ovn-central 是否正常。

**Comment by zhenliangliang** [comment]
> 检查一下 ovs-ovn 以及 ovn-central 是否正常。

![kube-ovn](https://github.com/kubeovn/kube-ovn/assets/42161318/3d6d82ae-4101-47bb-ab50-f34a0b8bbfce)
看pod状态是running，就没注意看里面的日志，但看日志，貌似不正常，
ovs-ovn的日志：
.......
2024-04-01T08:15:42.816Z|00556|patch|WARN|Bridge 'br-office' not found for network 'office'
2024-04-01T08:15:42.817Z|00557|patch|WARN|Bridge 'br-pn-piqi3rlh' not found for network 'pn-piqi3rlh'
2024-04-01T08:15:42.817Z|00558|patch|WARN|Bridge 'br-provider' not found for network 'provider'
2024-04-01T08:15:42.817Z|00559|patch|WARN|Bridge 'br-office' not found for network 'office'
2024-04-01T08:15:47.817Z|00560|patch|WARN|Bridge 'br-pn-piqi3rlh' not found for network 'pn-piqi3rlh'
2024-04-01T08:15:47.817Z|00561|patch|WARN|Bridge 'br-provider' not found for network 'provider'
2024-04-01T08:15:47.817Z|00562|patch|WARN|Bridge 'br-office' not found for network 'office'
2024-04-01T08:15:47.818Z|00563|patch|WARN|Bridge 'br-pn-piqi3rlh' not found for network 'pn-piqi3rlh'
2024-04-01T08:15:47.818Z|00564|patch|WARN|Bridge 'br-provider' not found for network 'provider'
2024-04-01T08:15:47.818Z|00565|patch|WARN|Bridge 'br-office' not found for network 'office'

 ovn-central日志：
* ovn-northd is not running
 * ovnnb_db is not running
 * ovnsb_db is not running
[{"uuid":["uuid","b0758eb0-75f9-44ac-a937-c3a5bc0aa54e"]},{"uuid":["uuid","40626311-d93c-43fb-a7b5-965019d0bccd"]}]
[{"uuid":["uuid","7b67eb49-dae1-4e99-92dd-9704e855798b"]},{"uuid":["uuid","48fb822c-5e50-4d19-bab7-f0422d3ab2fb"]}]
ovsdb-client: failed to connect to "tcp:[10.252.29.2]:6641" (Connection refused)
 * Starting ovsdb-nb
2024-04-01T08:10:02Z|00001|reconnect|INFO|unix:/var/run/ovn/ovnnb_db.sock: connecting...
2024-04-01T08:10:02Z|00002|reconnect|INFO|unix:/var/run/ovn/ovnnb_db.sock: connected
 * Waiting for OVN_Northbound to come up
 * Starting ovsdb-sb
2024-04-01T08:10:02Z|00001|reconnect|INFO|unix:/var/run/ovn/ovnsb_db.sock: connecting...
2024-04-01T08:10:02Z|00002|reconnect|INFO|unix:/var/run/ovn/ovnsb_db.sock: connected
 * Waiting for OVN_Southbound to come up
 * Starting ovn-northd
I0401 16:10:02.872702     521 ovn.go:105] no --kubeconfig, use in-cluster kubernetes config

**Comment by zhangzujian** [comment]
kubectl get node -o wide 看一下操作系统版本和内核版本。

**Comment by zhenliangliang** [comment]
目前看应该是kube-ovn版本问题，我测试如下：
k8s版本：v1.26.X

kube-ovn版本:v1.10.10

部署方式：kubekey

插件部署成功

情况二：

k8s版本：v1.28.X

kube-ovn版本:v1.10.10/v1.11.16

部署方式：kubeadm

插件部署成功
