### ISSUE TITLE
请教一下，通过switchlb创建的vip类型问题

### ISSUE THREAD

**Issue by wangshuai199398** [kubeovn/kube-ovn#3910]
# Feature request

创建一个switchlb，yaml为：

apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name:  cjh-slr-nginx
spec:
  vip: 1.1.1.1
  sessionAffinity: ClientIP
  namespace: default
  selector:
    - app:nginx
  ports:
  - name: dns
    port: 8888
    targetPort: 80
    protocol: TCP

代码中会创建一个vip，这个vip类型为空，为什么类型不设置为switch_lb_vip类型呢？

而通过vip yaml创建switch_lb_vip类型的vip

apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: slr-01
spec:
  subnet: ovn-default
  type: switch_lb_vip

代码中会创建一个logical_switch_port，创建这个logical_swtich_port 有什么用啊？

**Comment by bobz965** [comment]
1. 代码中会创建一个vip，这个vip类型为空，为什么类型不设置为switch_lb_vip类型呢？

这个是健康检查用的 vip。详情查看 ovn 健康检查 switch lb 的测试用例


2. type: switch_lb_vip

相关代码中会创建一个 logical_switch_port，创建这个logical_swtich_port 有什么用啊？

让 ovn ovs 知道 这个 vip 的 ip 和 mac。 以便于触发 lb 规则的流表。 详情可以抓包看。
