### ISSUE TITLE
Is it possible to create a custom Layer 2 network?

### ISSUE THREAD

**Issue by monkey92t** [kubeovn/kube-ovn#3916]
In the documentation, there are default Overlay and Underlay networks to choose from. The Overlay network creates a virtual bridge named br-int, while the Underlay network creates a bridge with a custom name (temporarily also called br-int). Subsequently, the eth0 interfaces of the containers created will all be connected to the br-int bridge. If additional interfaces are created using MULTUS, they will also be connected to the br-int bridge, just like eth0.
﻿
My goal is to create a separate Layer 2 network for the MULTUS interfaces, where eth0 remains connected to the default br-int, while the MULTUS interfaces are connected to a custom bridge. In other words, I want to create a bridge similar to br-int called br-int2, which will manage all MULTUS interfaces. The eth0 interface will be used for the default container management network, while the br-int2 interface will be responsible for the business network.
﻿
I can create multiple ProviderNetworks, which will create multiple bridges, and this seems to achieve my goal. However, I'm not sure how to specify different ProviderNetworks for pods (VMIs). By default, all container interfaces are connected to br-int. How can I specify that MULTUS interfaces should be connected to other ProviderNetworks while eth0 remains in the default network?

**Comment by zhangzujian** [comment]
Actually, all ovs interfaces are connected to br-int, including underlay. The difference is that underlay interfaces are programmed to be connected to underlay bridges logically.

If you want to use underlay for the attachment networks, you can create an underlay subnet and set its `.spec.provider` as documented, such as `nad-name.nad-ns.ovn` and refer this provider name in multus network attachment definition.
