### ISSUE TITLE
Routing Gateway API (Ingress) to Custom VPC

### ISSUE THREAD

**Issue by MuNeNICK** [kubeovn/kube-ovn#3931]
# Feature request

I would like to request a feature that enables routing for Gateway API (Ingress) to Custom VPCs. This feature is crucial for IaaS providers who are considering the adoption of Kubernetes + Kube-OVN and are planning to implement API Gateway functionalities.

## Use case

 In a scenario where customers are required to deploy services on a custom VPC, owning one namespace per account, the ability to manage the Gateway API on the provider side becomes essential. Customers should be able to link their services to the Gateway API using HTTPRoute. However, the current limitation with custom VPCs not being able to communicate with the default VPC poses a significant challenge. This feature would solve this problem by allowing seamless communication and routing capabilities between custom VPCs and the Gateway API, thereby enhancing the flexibility and scalability of the services provided to the customers.

Is there currently a solution to this problem? Your assistance would be greatly appreciated.
![gateway_api drawio](https://github.com/kubeovn/kube-ovn/assets/72444129/57475f77-2b0f-47b6-9161-511c3d3837e4)

**Comment by oilbeater** [comment]
The VPC network is designed to be isolated from one another, which can lead to IP address space overlap. As a result, connecting two VPCs becomes challenging and may compromise the goal of maintaining VPC isolation. In this scenario, considering a subnet per tenant approach rather than a VPC per tenant mode may better suit your requirements.

**Comment by MuNeNICK** [comment]
> The VPC network is designed to be isolated from one another, which can lead to IP address space overlap. As a result, connecting two VPCs becomes challenging and may compromise the goal of maintaining VPC isolation. In this scenario, considering a subnet per tenant approach rather than a VPC per tenant mode may better suit your requirements.

@oilbeater 
Thank you for your reply.
As a requirement, we would like to allow customers to use any CIDR of their choice.
In the custom subnet scenario, we understand that it is not possible to have overlapping CIDR configurations, so this cannot meet our requirements.
With custom VPCs, customers can use any CIDR they want, and overlapping CIDRs are not an issue, so we would prefer to adopt this scenario if possible.
Currently, is it correct to conclude that the Gateway API cannot be used in conjunction with the custom VPC scenario?

**Comment by oilbeater** [comment]
If the Gateway API controller relies on the network to transfer information between the default VPC and custom VPC, this is not possible under the current architecture. If the controller uses other non-network methods such as sockets or files for information transfer, then it can work. However, most controllers do not work in this way.
