### ISSUE TITLE
自建subnet中有一个ip的pod无法创建（跳过此ip其他可以），查看ovs-pod日志报错

### ISSUE THREAD

**Issue by SunStriderVII** [kubeovn/kube-ovn#3939]
自建subnet：10-1-1-vm-backup，创建pod到.24时报错无法创建，跳过.24 ip，其他可以成功创建。
集群中所有ovs-ovn pod日志均有大量如下报错：
lflow|WARN|error parsing match "ip4.src == $10.1.1.vm.backup.node1_ip4":'$'must be followed by a valid identifier

kube-ovn版本1.11.0

**Comment by oilbeater** [comment]
子网以数字开头会存在问题，以字母开头再试一下

**Comment by yangwanggaofeng** [comment]
> 子网以数字开头会存在问题，以字母开头再试一下

ip不跳过，换一个node就可以正常拉起pod，仅在集群的一个node上出现了此问题

并且在我们的k8s环境，有四个子网都是数字开头的，ip使用了400多个，均没问题
