### ISSUE TITLE
[BUG]  集群中有四个节点，但只有一个节点的默认vpc下的pod无法访问 k8s svc ip:443 endpoint

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#3970]
### Kube-OVN Version

master, release1.12-mc

### Kubernetes Version

v1.21.5

### Operation-system/Kernel Version

4.19.90-2107.6.0.0192.8.oe1

### Description

该节点 node上直接访问 svc 是ok的，但是该节点上默认vpc下的ovn-default的pod访问svc都是不通的。

抓包看的时候，包确实从pod网卡出来到了 ovn0，但是回包的时候总是 port unreacheable。

下面对比的正常节点和异常节点的抓包文件。

从该节点上的 pod 访问 k8s svc endpoint，并在 该node 上的 kube-ovn-cni 中抓包

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/2f4b093c-ea38-409c-a450-a1d2048b05f4)

> 这个图可能是我iptables -F 清理之前抓到的，清理之后我发现就无法复现该情况了，而且目前的iptables对比见下图

wireshark 对比了正常的节点和异常的节点

### 正常的 

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/94d43aa6-0c13-4a67-a259-c4f1a0c0387d)

### 异常的

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/95e957de-f263-4360-b7b8-365b42b0f95f)

我对比了不同节点的 sysctl  发现没有区别，而且默认vpc的路由都具备。这个现象好像是触发了 reject-with icmp-port-unreachable iptables 规则 ，所以对比了下 两个节点的 iptables 规则。然后发现 6081 的规则是缺失的，同时还缺失了一条别的规则。

docker 的iptables 规则可以忽略，重点应该在 iptables  input accept 规则的缺失。

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/1630702f-bc93-4b39-90e2-d8edcc13e309)

### Steps To Reproduce

常规部署集群，但不排除集群已经部署过1.11的kube-ovn

### Current Behavior

存在一个节点无法访问 svc

### Expected Behavior

所有节点都可以访问 svc

**Comment by zhangzujian** [comment]
The SYN packet has an incorrect TTL of value 1 (or 2). Check your sysctl TTL setting `net.ipv4.ip_default_ttl` on the node.

**Comment by zhangzujian** [comment]
The SYN packet has an incorrect TTL of value 1 (or 2). Check the sysctl variable `net.ipv4.ip_default_ttl` on the node.

**Comment by bobz965** [comment]
the ttl is just the same 

bad node:

```bash

[root@node01 deployer]# sysctl -a | grep -i ttl
net.ipv4.inet_peer_maxttl = 600
net.ipv4.inet_peer_minttl = 120
net.ipv4.ip_default_ttl = 64

```


good node:

``` bash
[root@node02 ~]#  sysctl -a | grep -i ttl
net.ipv4.inet_peer_maxttl = 600
net.ipv4.inet_peer_minttl = 120
net.ipv4.ip_default_ttl = 64

```

**Comment by bobz965** [comment]
The negative scenario is displayed below now. :

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/3a1aedcb-5108-470a-bb34-ebabd05aca06)


![image](https://github.com/kubeovn/kube-ovn/assets/7981158/8535d62a-5685-40a3-8cbd-f898fda9bfd9)

**Comment by bobz965** [comment]
我使用如下两种方式尝试下跟踪iptables有丢包，但是并没有跟到 pod 源ip 以及 10.233.0.1 丢包的log

``` bash

iptables -A INPUT -j LOG --log-prefix "Dropped: "

iptables -A INPUT -m state --state NEW -j LOG --log-prefix "New Connection: "

```

还有其他比较直接的跟踪定位工具嘛？ deepflow能跟踪到这个包为什么回 icmp port unreachable 嘛？

**Comment by bobz965** [comment]
而且，这个现象跟 这两个规则缺失会不会有关系呢？

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/7d5932be-a05a-4921-8c03-bcfbcde7eabe)

**Comment by zhangzujian** [comment]
> 我使用如下两种方式尝试下跟踪iptables有丢包，但是并没有跟到 pod 源ip 以及 10.233.0.1 丢包的log
> 
> ```shell
> iptables -A INPUT -j LOG --log-prefix "Dropped: "
> 
> iptables -A INPUT -m state --state NEW -j LOG --log-prefix "New Connection: "
> ```
> 
> 还有其他比较直接的跟踪定位工具嘛？ deepflow能跟踪到这个包为什么回 icmp port unreachable 嘛？

Use `xtables-monitor -t`.

[Network address translation part 1 – packet tracing](https://fedoramagazine.org/network-address-translation-part-1-packet-tracing/)

**Comment by bobz965** [comment]
我在两个节点上，分别基于 各自 node 的 netshoot pod设置了两条跟踪 syn 包的规则，上述跟踪不到的原因是因为确实还没到建立连接的阶段，在 syn 和 ack（回）的时候，就已经触发了 icmp port unreachable。

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/ba2362a6-712f-4c82-8aac-e4deeca6e714)



![image](https://github.com/kubeovn/kube-ovn/assets/7981158/c06f33ae-6b1f-4a40-b1c0-46943ec4ed6c)



不知道为什么，出现问题的节点 node1 的 kube-ovn  的 iptables 规则，没有触发到，反而直接触发了 k8s kube-service 的规则。

**Comment by bobz965** [comment]
``` bash

[root@csy-wx-pm-os01-eis-node01 deployer]# iptables-save | grep -i ovn-pre
:OVN-PREROUTING - [0:0]
:OVN-PREROUTING - [0:0]
-A PREROUTING -m comment --comment "kube-ovn prerouting rules" -j OVN-PREROUTING
-A OVN-PREROUTING -i ovn0 -m set --match-set ovn40subnets src -m set --match-set KUBE-CLUSTER-IP dst,dst -j MARK --set-xmark 0x4000/0x4000
-A OVN-PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set --match-set KUBE-NODE-PORT-LOCAL-TCP dst -j MARK --set-xmark 0x80000/0x80000
-A OVN-PREROUTING -p tcp -m set --match-set ovn40other-node src -m set --match-set KUBE-NODE-PORT-LOCAL-TCP dst -j MARK --set-xmark 0x4000/0x4000
-A OVN-PREROUTING -p udp -m addrtype --dst-type LOCAL -m set --match-set KUBE-NODE-PORT-LOCAL-UDP dst -j MARK --set-xmark 0x80000/0x80000
-A OVN-PREROUTING -p udp -m set --match-set ovn40other-node src -m set --match-set KUBE-NODE-PORT-LOCAL-UDP dst -j MARK --set-xmark 0x4000/0x4000
[root@csy-wx-pm-os01-eis-node01 deployer]#



[root@csy-wx-pm-os01-eis-node02 ~]# iptables-save | grep -i ovn-pre
:OVN-PREROUTING - [0:0]
:OVN-PREROUTING - [0:0]
-A PREROUTING -m comment --comment "kube-ovn prerouting rules" -j OVN-PREROUTING
-A OVN-PREROUTING -i ovn0 -m set --match-set ovn40subnets src -m set --match-set KUBE-CLUSTER-IP dst,dst -j MARK --set-xmark 0x4000/0x4000
-A OVN-PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set --match-set KUBE-NODE-PORT-LOCAL-TCP dst -j MARK --set-xmark 0x80000/0x80000
-A OVN-PREROUTING -p tcp -m set --match-set ovn40other-node src -m set --match-set KUBE-NODE-PORT-LOCAL-TCP dst -j MARK --set-xmark 0x4000/0x4000
-A OVN-PREROUTING -p udp -m addrtype --dst-type LOCAL -m set --match-set KUBE-NODE-PORT-LOCAL-UDP dst -j MARK --set-xmark 0x80000/0x80000
-A OVN-PREROUTING -p udp -m set --match-set ovn40other-node src -m set --match-set KUBE-NODE-PORT-LOCAL-UDP dst -j MARK --set-xmark 0x4000/0x4000
[root@csy-wx-pm-os01-eis-node02 ~]#





###### 对比 ovn ovn40subnets 的 ipset


[root@csy-wx-pm-os01-eis-node02 ~]# ipset list | grep -A 11  ovn40subnets
Name: ovn40subnets-nat
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 440
References: 2
Number of entries: 1
Members:
10.222.0.0/18

Name: ovn40subnets-distributed-gw
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 504
References: 1
Number of entries: 2
Members:
100.64.0.0/16
10.222.0.0/18


--
Name: ovn40subnets
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 504
References: 12
Number of entries: 2
Members:
100.64.0.0/16
10.222.0.0/18


--
Name: ovn40subnets-nat-policy
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 376
References: 1
Number of entries: 0
Members:



[root@csy-wx-pm-os01-eis-node01 deployer]# ipset list | grep -A 11  ovn40subnets
Name: ovn40subnets
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 504
References: 12
Number of entries: 2
Members:
100.64.0.0/16
10.222.0.0/18

--
Name: ovn40subnets-nat
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 440
References: 2
Number of entries: 1
Members:
10.222.0.0/18

Name: ovn40subnets-distributed-gw
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 504
References: 1
Number of entries: 2
Members:
100.64.0.0/16
10.222.0.0/18

--
Name: ovn40subnets-nat-policy
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 376
References: 1
Number of entries: 0
Members:



```

目前看起来 iptables的内容以及ipset的内容确实是一致的。

**Comment by bobz965** [comment]
在 iptables中，规则是按照添加顺序来匹配的，即先添加的规则优先匹配。因此，可以说 iptables 规则是有优先级的，后添加的规则会覆盖先添加的规则。

要查看nat表中所有规则的优先级顺序，可以使用以下命令：

iptables -t nat -L --line-numbers

这个命令将列出nat表中的所有规则，并显示规则的行号，行号越小的规则优先级越高，会先匹配到。您可以根据规则的行号来了解规则的优先级顺序，以便更好地理解iptables中nat表规则的匹配顺序。


![image](https://github.com/kubeovn/kube-ovn/assets/7981158/5a88732b-f249-478e-92e1-2bcd6676555f)


经对比，优先级确实有区别，但是不太清楚这个优先级如何稳定控制。

还是无法控制？

kube-proxy 先于 kube-ovn 配置， kube-service的级别就优先？

**Comment by bobz965** [comment]
手动清理所有规则，尝试实现 ovn-prerouting 优先

``` bash 
iptables -F;iptables -X;iptables -t nat -F;iptables -t nat -X;iptables -t mangle -F;iptables -t mangle -X;  iptables -t nat -L --line-numbers 

```


清理后，不重启 kube-ovn-cni 以及 kube-proxy 规则会自动刷上来，
但是看到了 ovn-prerouting 先刷出来，但是随后，kube-service 的 规则又是序列为1。 也就是说，kube-proxy 应该控制了它的规则顺序会抢占到第一位。

但是其他三个节点都是 kube-service 在第二位。

**Comment by bobz965** [comment]
虽然 iptables 可以支持指定序列号插入规则，但是看了下 k8s proxy 的源码并不是指定序列号插入的，而且如果是指定序列号插入，那么其他节点一定也是 kube-service 为 1.


![image](https://github.com/kubeovn/kube-ovn/assets/7981158/39775ca5-2429-44e1-a09b-46e5b036db09)



要在iptables的NAT表中指定顺序号插入规则，可以使用-I选项来指定规则插入的位置。以下是一个示例命令：

```
 iptables -t nat -I PREROUTING 2 -s 192.168.1.0/24 -j DNAT --to-destination 10.0.0.1

```
在这个示例中，-I PREROUTING 2表示将规则插入到NAT表的PREROUTING链中的第2个位置。您可以根据需要调整顺序号来指定规则的插入位置。

请注意，iptables规则是按照添加的顺序执行的，因此通过指定顺序号来插入规则可以控制规则的执行顺序。

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/b38281f0-6fbd-4a2b-93bd-c10be84d5662)


代码 log 显示，这个优先级就是第一的，但是结果就是第二的。

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/a6c56cfd-b064-4f87-adce-b357add52cbb)


问题结论：

1. k8s ipvs proxier.go 虽然没有指定位置参数，但是一旦添加就是添加到第一位。
所以如果kube-proxy 后添加配置，那么 kube-ovn的配置就变成第二位的，就会出问题


临时解决就是手动清理kube-ovn的ovn-prerouting，触发kube-ovn添加。


可靠解决：kube-ovn 需要检查这条规则的顺序，如果不是第一位则删除再添加，保证其为第一位的。

**Comment by bobz965** [comment]
如果 kube-proxy 先部署， kube-ovn 后部署，那么两者都稳定跑。那么确实不会复现。

如果一开始 kube-proxy就没跑起来，然后kube-ovn先部署。那么就稳定复现。

因为 kube-proxy 也是检查规则有无再I（insert）的。但是先清理规则，一般都是 kube-ovn 先生效（周期较kube-proxy短）。


在iptables nat 为空的时候， 由于 kube-proxy 和 kube-ovn 的逻辑都是认为自己的规则是第一位的，但是谁先起来，谁的规则就会变成第二位的。

但是 kube-ovn 这边必须要保证自己的规则是第一位的。

**Comment by bobz965** [comment]
问题梳理参考：

https://www.cnblogs.com/clouders/p/6544584.html

https://fedoramagazine.org/network-address-translation-part-1-packet-tracing/
