### ISSUE TITLE
[BUG] The Probability of Duplicate MAC Addresses

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#4001]
### Kube-OVN Version

1.11.9

### Kubernetes Version

1.20.1

### Operation-system/Kernel Version

"CentOS Linux 7 (Core)"
5.4.231-1.el7.elrepo.x86_64

### Description

```
func GenerateMac() string {
	prefix := "00:00:00"
	b := make([]byte, 3)
	_, err := rand.Read(b)
	if err != nil {
		klog.Errorf("generate mac error: %v", err)
	}

	mac := fmt.Sprintf("%s:%02X:%02X:%02X", prefix, b[0], b[1], b[2])
	return mac
} 
```

如果集群里频繁创建pod，mac地址存在重复的可能，在underlay网络下会存在问题

### Steps To Reproduce

在集群中发现不同的pod的mac地址出现重复

### Current Behavior

mac地址出现重复

### Expected Behavior

mac地址不重复

**Comment by oilbeater** [comment]
理论上冲突的概率是 1/(256*256*256) 实在大概什么样的规模下发现冲突的

**Comment by wolgod** [comment]
> 理论上冲突的概率是 1/(256_256_256) 实在大概什么样的规模下发现冲突的

500台node节点，有10台机器作为jenkins的salve起动态pod,发现好几次其他业务的pod已经申请了该mac，但是jenkins起的pod也申请了该mac，交换机处理就有问题然后就会影响其他业务正在运行的pod

**Comment by wolgod** [comment]
从概率上来看出现重复概率还挺高
<img width="1031" alt="企业微信截图_78cd7c33-c3c8-448e-beb6-054484343a6d" src="https://github.com/kubeovn/kube-ovn/assets/4132442/c64169b3-b3b1-4c81-a0a8-1b53d6796fa3">

这个如果改成除了第一个00，后面的都随机应该可行吧

**Comment by oilbeater** [comment]
如果是这样我倾向于直接在 mac 里嵌入 IP 这样在 IPv4 的情况下至少可以保证绝对的不冲突

**Comment by oilbeater** [comment]
参考了下 cilium 的实现 https://github.com/cilium/cilium/blob/8c7e442ccd48b9011a10f34a128ec98751d9a80e/pkg/mac/mac.go#L106 这应该是最大随机化的做法了

**Comment by wolgod** [comment]
> 参考了下 cilium 的实现 https://github.com/cilium/cilium/blob/8c7e442ccd48b9011a10f34a128ec98751d9a80e/pkg/mac/mac.go#L106 这应该是最大随机化的做法了

看代码这个实现和已有实现6位全随机，没啥大的区别吧

**Comment by oilbeater** [comment]
主要是第一个字节最后两位需要特殊设置，不然可能变成组播的 mac 地址。这个实现应该可以指数级下降冲突概率了，ipv6 的地址范围可能会比 mac 地址还大，也不能直接用 ip 来生成 mac 还是先只能用这种随机算法
