### ISSUE TITLE
huge amount of flows on large-scale cluster   大规模环境 流表过多问题

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#4053]
### Description

kube-ovn IPAM模型 支持一个subnet可以给所有nodes使用，在IP地址分配上有很大的灵活性，但同时会导致大规模下 每个节点上流表数量会非常多。

假设500 nodes，每个node 100个pods，50k个pods，10k个 services。 
以cluster svc 产生的流表为例，10k个services 对应10k个 lb rules，假设集群使用了1个vpc N个subnets(logical switch) 承载这10k个svc，因为 cluster svc 是将 lb 加到ls上实现，那么每个 logical switch 都会添加 10k 个lb rules。因为每个node可以使用所有subnets，那么每个节点会产生 10k*N 条 cluster svc相关的流表规则。

ovn-kubernetes 的IPAM模型是 `subnet-per-node`，基于这个模型 ovn-kubernetes 通过`Distributed Gateway Ports` 实现每个node上只生成自己subnet的流表，参考：https://www.openvswitch.org/support/ovscon2021/slides/scale_ovn.pdf 里的`Trade IP mobility for scalability`

所以，请教下大家，针对kube-ovn 的IPAM模型，有哪些减少流表数量的经验或者最佳实践。

### Who will benefit from this feature?

every kube-ovn user

**Comment by oilbeater** [comment]
针对 lb 的话，新版本的 ovn 支持 [load_balancer_group](https://www.mankier.com/5/ovn-nb#Load_Balancer_Group_TABLE) ，我印象里用这个可以做到流表复用，不过不是太确定可能得试一下

**Comment by oilbeater** [comment]
还有一种可能就是在调度的时候控制一个 subnet 的 pod 只调度到一组机器上，有可能能减少别的节点的 lb 流表数量

**Comment by chestack** [comment]
@bobz965 @oilbeater  感谢回复

[load_balancer_group](https://www.mankier.com/5/ovn-nb#Load_Balancer_Group_TABLE) 貌似是NB层面的复用, 对于节点上的openflow规则 可能无法起到复用效果 https://mail.openvswitch.org/pipermail/ovs-dev/2021-October/388220.html。
如果ovs/ovn 有机制，可以实现节点上不同ls可以复用 相同的clusterip到endpoints的openflow 规则，会是个不错的方案。

当前我们的规避方案  是尽量拆分pods/subnets到M个vpcs, 这样10k个svcs 分散到每个vpc的lb上的数量是 10k/M, 这样即使 vpcs之间IC互联 每个节点上依然需要同步所有N个subnets的lb相关的流表，拆分后每个节点需要 10k/M *N,  比一个vpc 需要10k*N 条 数量少些

**Comment by chestack** [comment]
https://github.com/kubeovn/kube-ovn  FAQ 里提到的测试, 除了pods数量，是否测过 cluster svc 和 ACL等功能带来的流表问题

```
Q: How about the scalability of Kube-OVN?

A: We have simulated 200 Nodes with 10k Pods by kubemark, and it works fine. Some community users have deployed one cluster with 500 Nodes and 10k+ Pods in production. It's still not reach the limitation, but we don't have enough resources to find the limitation.
```

**Comment by oilbeater** [comment]
@chestack 这个社区用户主要是用来跑虚拟机的，猜测没有太多的 svc 和 acl 功能。按照我们的经验 networkpolicy 里 except cidr 规则会导致流表膨胀，别的类型的规则还不会出现单条导致流表迅速膨胀的情况
