### ISSUE TITLE
[BUG] CI Kube-OVN Conformance E2E (ipv4, overlay) err `kubevirt crd not exist`

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#4056]
### Kube-OVN Version

master

### Kubernetes Version

1.30

### Operation-system/Kernel Version

1

### Description

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/8ff870ca-dfe0-4fa4-85f5-f7bfa4917193)

### Steps To Reproduce

run ci

### Current Behavior

Kube-OVN Conformance E2E (ipv4, overlay) err `kubevirt crd not exist`

### Expected Behavior

Kube-OVN Conformance E2E (ipv4, overlay) no err

**Comment by zhangzujian** [comment]
Please attach the github actions workflow URL.

**Comment by bobz965** [comment]
> Please attach the github actions workflow URL.

等复现了我再贴一下，忘记贴了。
