### ISSUE TITLE
[BUG] v.1.12.16没有enableMulticastSnoop

### ISSUE THREAD

**Issue by tghfly** [kubeovn/kube-ovn#4087]
### Kube-OVN Version

 v.1.12.16

### Kubernetes Version

 v.1.27.6

### Operation-system/Kernel Version

centos8.4  kernel-5.4.235

### Description

v.1.12.x的subnet没有enableMulticastSnoop，crd和源码都没有该属性，v1.9.x有

### Steps To Reproduce

v.1.12.x的subnet没有enableMulticastSnoop，crd和源码都没有该属性，v1.9.x有

### Current Behavior

v.1.12.x的subnet没有enableMulticastSnoop，crd和源码都没有该属性，v1.9.x有

### Expected Behavior

v.1.12.x的subnet应该要有enableMulticastSnoop

**Comment by changluyi** [comment]
可能之前代码没有同步过来，这个我有时间加上。

您的意思是vpc 不同子网，开启了enableMulticastSnoop后，组播报文不能跨子网么？

**Comment by changluyi** [comment]
有 ， 你可以参考这个
ovn-nbctl set logical_switch {uuid} other_config:mcast_snoop="true"
ovn-nbctl set logical_switch {uuid} other_config:mcast_querier="false"

如果要开启mcast_querier的话可以手动给参考如下

kubectl ko nbctl set logical_switch {uuid} other_config:mcast_snoop="true"
kubectl ko nbctl set logical_switch {uuid} other_config:mcast_querier="true"
kubectl ko nbctl set logical_switch {subnet_name} other_config:mcast_snoop=true other_config:mcast_querier=true other_config:mcast_ip4_src="10.16.0.1" other_config:mcast_eth_src="00:00:00:ac:4e:5d"

mcast_ip4_src 和 mcast_eth_src 是overlay网关的ip 和mac

**Comment by changluyi** [comment]
https://github.com/kubeovn/kube-ovn/pull/4105
