### ISSUE TITLE
[BUG] VPC 下存在子网可以被删除

### ISSUE THREAD

**Issue by protream** [kubeovn/kube-ovn#4104]
### Kube-OVN Version

v1.12.16

### Kubernetes Version

v1.28.8

### Operation-system/Kernel Version

6.1.0-20-amd64

### Description

vpc 下有子网还是可以被删除，删除后查看subnet关联的是被删除的vpc，重新按原来vpc的名字创建vpc后，新建的 vpc 没有关联原来的子网

### Steps To Reproduce

1、创建vpc
2、创建子网关联vpc
3、删除vpc

### Current Behavior

vpc被删除

### Expected Behavior

vpc 下存在子网不能被删除

**Comment by bobz965** [comment]
webhook already covered this.

![image](https://github.com/user-attachments/assets/647b6107-2c75-4cf4-b13a-4e21c07f3500)
