### ISSUE TITLE
[BUG] Unnecessary RBAC permissions in Helm CHarts

### ISSUE THREAD

**Issue by Yseona** [kubeovn/kube-ovn#4108]
### Kube-OVN Version

v1.12.0

### Kubernetes Version

N/A

### Operation-system/Kernel Version

N/A

### Description

The bug is that the Deployment `kube-ovn-controller` in the charts has too much RBAC permission than it needs. The service account of `kube-ovn-controller` is bound to a clusterrole ([ovn-CR.yaml#L7](https://github.com/kubeovn/kube-ovn/blob/e67d5f12b750ca4c04b632c3dabd94b047d1f1e5/charts/kube-ovn/templates/ovn-CR.yaml#L7)) with the following permissions:

- `patch` verb of the `deployments/services/statefulsets` resource (ClusterRole)
- `create/update` verb of the `pods` resource (ClusterRole)

After reading the source code of [kubeovn/kube-ovn](https://github.com/kubeovn/kube-ovn), I didn't find any Kubernetes API usages using these permissions. Besides, some of these unused permissions may have potential risks. For example, if malicious users gain control of a Kubernetes node running a `kube-ovn-controller` pod, they can use the "patch deployments" permission to edit existing workloads, create privileged containers with malicious container images.

Therefore, for security reasons, I suggest checking these permissions to determine if they are truly unnecessary. If they are, the issue should be fixed by removing the unnecessary permission or other feasible methods. 

### Steps To Reproduce

Use helm chart with default values.

### Current Behavior

None

### Expected Behavior

None

**Comment by hongzhen-ma** [comment]
I have checked the latest code in master branch and release-1.12

The permission about deploy/statefulset
![image](https://github.com/kubeovn/kube-ovn/assets/67130442/712c8ab3-21bd-415a-9a90-985941319298)
thers is no patch permission.

permission about services
![image](https://github.com/kubeovn/kube-ovn/assets/67130442/2df2a1d3-bb6d-4cb4-aa06-7a4c008f1915)
thers is no patch permission.

permission about pods
![image](https://github.com/kubeovn/kube-ovn/assets/67130442/710636f2-87b1-4552-9d15-896f61940da9)
thers is not create/update permission.

Maybe the permission exists in kube-ovn v1.12.0. 
The latest release version in release-1.12 is v1.12.16, maybe you can update the to the latest code and have a check again.

**Comment by Yseona** [comment]
Ok. Thank you so much for your time and patience.
