### ISSUE TITLE
kube-ovn on old intel x86_64 processors.

### ISSUE THREAD

**Issue by Orfheo** [kubeovn/kube-ovn#4142]
I don't think this issue is a actually about a bug and probably can't be considered a feature request, not sure how to get info about this topic, probably this will look like a support request.

Any way, I've some old Intel x86_64 system around (2008), with CPU lacking "sse4.2,popcnt" features where I would like to run small kubernetes nodes with kube-ovn.

Unfortunately as soon as I try to start an ovs-ovn container on these nodes (1.12.16 or 1.13.0) I immediately get, as to be expected, an "invalid opcode" trap from ovs-dbtool.

I recompiled kube-ovn-base 1.12.16 amd64  image from scratch, without the infamous " -msse4.2 -mpopcnt" gcc compiler options which force to use these instructions, and the new kube-ovn:v1.12.16 image seems to run correctly on these old nodes with a locally generated kube-ovn:v1.12.16.

I guess is the only way to go? Or it may be considered an option to have a docker.io registry image available for old nodes?

Thanks, Orfheo.

**Comment by oilbeater** [comment]
@Orfheo Thanks for the report. The SSE4.2 and popcnt instruction sets can hugely improve the performance of string manipulation, which is a crucial part of the OVS and OVN flow operations. Most of the x86_64 CPUs manufactured after 2013 already support these instruction set, that is why we enabled them by default. 

For your issue, currently I believe the only solution is to modify the compiler options like you did and then manually rebuild the image. 

Adding an image for an old CPU is not a complex task. However, the Docker image does not have an architecture type for old x86_64. Therefore, we need to add a new image tag, such as “v1.13.0-x86-legacy”. And due to limitations in pipeline resources, we can only perform a small amount of testing on this image.

**Comment by Orfheo** [comment]
> @Orfheo Thanks for the report. The SSE4.2 and popcnt instruction sets can hugely improve the performance of string manipulation, which is a crucial part of the OVS and OVN flow operations. Most of the x86_64 CPUs manufactured after 2013 already support these instruction set, that is why we enabled them by default.
> 
> For your issue, currently I believe the only solution is to modify the compiler options like you did and then manually rebuild the image.
> 
> Adding an image for an old CPU is not a complex task. However, the Docker image does not have an architecture type for old x86_64. Therefore, we need to add a new image tag, such as “v1.13.0-x86-legacy”. And due to limitations in pipeline resources, we can only perform a small amount of testing on this image.

That exactly what I thought. Thanks!

May I use this thread to ask which is the correct procedure for creating a local kube-ovn-base docker image, in a working development environment, under Ubuntu 22.04, with custom compiled ovs/ovn debian packages installed?

I had been successfully a couple of times with 1.12.16, but with the master 1.13.0 version I always end with the docker.io ovs/ovn executables stored in the local base image (verified with timestamp and md5sum from a container).

I'm probably doing things in the wrong way, not much experience in managing docker buildx images

Non clear from the documentation to my eyes, I'm basically doing 'make base-amd64' followed by 'make release'.

Thanks again, Orfheo.

**Comment by zhangzujian** [comment]
Docker image created by executing `make base-amd64` has a tag named `v1.13.0-amd64`, so you need to retag it:

```shell
make base-amd64
docker tag kubeovn/kube-ovn-base:v1.13.0-amd64 kubeovn/kube-ovn-base:v1.13.0
make release
```

**Comment by Orfheo** [comment]
Apologies, I missed miserably that now in debian .deb packages the executables are automatically "reproducible builds"

https://reproducible-builds.org/docs/source-date-epoch/

which get the timestamps from the debian/changelog, so my check on timestamps was just a miss as the date is always the same, 2024-06-07

-rwxr-xr-x root/root    918160 2024-06-07 15:58 ./usr/bin/ovsdb-tool

My kube-ovn-base image was correct, I had been too much prudent.

The executables in my base and in the one just published on docker-hub have same size and timestamp, I'll check the published "amd64-legacy" base image as soon as I can.

Thank you so much!! Orfheo.

**Comment by Orfheo** [comment]
Probably an OutOfTopic, but debugging this trap issue on my old nodes I had a good reason for carefully read the Dockerfile.base structure.

A clever solution!

My best compliment to the people who found this solution!! Using an ubuntu container as the ovs/ovn builder to create the debian ovs/ovn packages in /packages and then mount, on the same stream, this directory in the ubuntu container which install the packages and clean the image is really a nice trick, one which worth to be remembered and saved in the personal brain toolbox!

In the attempt to understand the timestamp trouble I've manually replicated the streams from Kubernetes pods so I really had the occasion to verify the logic.

As simple and nice as it can be!

Guess the solution almost touch the Kolmogorov complexity of the problem!

Wonderful!
