### ISSUE TITLE
[BUG] gc lsp 的时候， 如果 子网不存在，会导致 kube-ovn-controller 崩溃。

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#4149]
### Kube-OVN Version

master

### Kubernetes Version

master k8s

### Operation-system/Kernel Version

4.19

### Description

gc 的时候，如果 子网不存在，会导致 kube-ovn-controller 崩溃。

### Steps To Reproduce

1

### Current Behavior

gc 的时候，如果 子网不存在，会导致 kube-ovn-controller 崩溃。

### Expected Behavior

gc 的时候，如果 子网不存在，不会导致 kube-ovn-controller 崩溃。

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/99fe4a6c-fcbc-4f44-97a1-8b6c3bfd78d9)

**Comment by zhangzujian** [comment]
这不是 LS 不存在导致的 GC 失败，而是 VM LSP 变更了 LS 后 external-ids 没更新吧。

**Comment by zhangzujian** [comment]
我们的 E2E case 里也要增加对 LSP external-ids 的检查。

**Comment by bobz965** [comment]
> 这不是 LS 不存在导致的 GC 失败，而是 VM LSP 变更了 LS 后 external-ids 没更新吧。

应该是的。
