### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by YuqiangChi** [kubeovn/kube-ovn#4174]
### Description

Kube-OVN可以支持解析SRv6的SRH吗？

**Comment by oilbeater** [comment]
请详细描写背景和需求，不然没办法通过一句话来给出判断

**Comment by YuqiangChi** [comment]
刘老师您好，感谢您的回复，下面我详细描述一下背景：我现在想做一个基于容器的安全资源服务链功能，已开发了IDS,vFW等安全能力且容器化部署在k8s上，作为一个安全资源池，为外部网络的数据流量提供安全防护。现在想尝试通过kube-ovn将k8s外部的流量流入这个安全资源池，并指定要通过哪些容器，从而实现安全服务链。需求：SRv6会有一个SRH可以指定这个流量具体流向哪里，我想把SRv6技术和我们的插件结合起来，让SRv6数据流量到达OVN控制器时，OVN控制器可以解析SRH，进而为这些数据流量生成OVS转发表，指定他们要经过哪些安全服务。并在安全服务结束时，提供一个可编程的API接口，再次编写SRH包头，让数据流量发送给外部网络的下一个节点。

**Comment by oilbeater** [comment]
OVN 本身不支持这种流量编排的能力，社区有一些 sfc 相关的项目可能会更合适一些

**Comment by YuqiangChi** [comment]
我之前也调研了一些SFC相关的论文与项目，我看大家在实现K8S的SFC主要有两种方法，一种是基于服务网格的，比如使用NSM；另一种是基于SDN和OVS实现的；所以想再请问一下Kube-OVN可以实现或者借助什么工具一起可以实现SFC的功能吗？
