### ISSUE TITLE
[BUG] need to manually enable the Promiscuous mode for the Nic on VirtualBox VM  

### ISSUE THREAD

**Issue by jcshare** [kubeovn/kube-ovn#4181]
### Kube-OVN Version

v.1.12.12

### Kubernetes Version

v.1.30.1

### Operation-system/Kernel Version

ubuntu@worker1:~$ uname -a
Linux worker1 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Description

 the Promisous mode of the Nic on VirtualBox VM cannot get enabled by click related button on VirtualBOX VM GUI, it need to enable it via ip command("ip link set enp0s3 promisc on"), or the north-south traffic of a user defined VPC will be blocked. 

### Steps To Reproduce

as mentioned above

### Current Behavior

the north-south traffic of a user defined VPC will be blocked. 

### Expected Behavior

the north-south traffic of a user defined VPC will be OK.

**Comment by zhangzujian** [comment]
Are you using vpc nat gateway?
