### ISSUE TITLE
[BUG] vpc网关pod删除后，pod使用的弹性外网ip未释放

### ISSUE THREAD

**Issue by author970** [kubeovn/kube-ovn#4200]
### Kube-OVN Version

v1.12.11

### Kubernetes Version

v1.27.6

### Operation-system/Kernel Version

Linux node152 5.10.0-136.12.0.86.4.hl202.x86_64 #1 SMP Fri Mar 10 14:42:11 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Description

1、创建vpc-nat-vpc资源，自动创建statefulSet及Pod，通过命令kubectl get ip -A 可查看到一个vpc subnet ip（即LanIP）和一个macvlan类型(弹性外网)subnet的子网的ip被使用，其中弹性外网ip没有mac地址；
2、重启vpc-nat-gw资源对应的Pod，再通过命令kubectl get ip -A可查看到新的macvlan类型(弹性外网)subnet的子网的ip被使用，查询弹性外网subnet资源status中可用ip资源，发现1中的弹性外网IP，并未变为可用。
![企业微信截图_17188785695591](https://github.com/kubeovn/kube-ovn/assets/173365946/7c4903c3-38f2-4f48-879b-ea8bad2800b1)
![企业微信截图_17188786707688](https://github.com/kubeovn/kube-ovn/assets/173365946/de04154b-96ae-402a-bd6b-e84f0c4917f9)
![企业微信截图_17188787445365](https://github.com/kubeovn/kube-ovn/assets/173365946/1cbe5d26-ba32-47d5-810e-1c5fc613ec39)

### Steps To Reproduce

1、创建vpc-nat-vpc资源，自动创建statefulSet及Pod，通过命令kubectl get ip -A 可查看到一个vpc subnet ip（即LanIP）和一个macvlan类型(弹性外网)subnet的子网的ip被使用，其中弹性外网ip没有mac地址；
2、重启vpc-nat-gw资源对应的Pod，再通过命令kubectl get ip -A可查看到新的macvlan类型(弹性外网)subnet的子网的ip被使用，查询弹性外网subnet资源status中可用ip资源，发现1中的弹性外网IP，并未变为可用。

### Current Behavior

vpc网关重启后，未释放弹性外网ip

### Expected Behavior

vpc网关重启后，可正常释放弹性外网ip。

**Comment by jcshare** [comment]
v1.12.17 上也有这问题

**Comment by author970** [comment]
恢复途径：
针对init状态的vpc网关pod，查询未释放的ip资源，查询方法（kubectl get ip -A | grep vpc-nat-gw名称），手动删除历史vpc网关pod 占用的ip（kubectl delete ip xxxx）,再重启vpc网关pod

**Comment by zhangzujian** [comment]
@author970 Could you please try the latest v1.12 version? The image tags are v1.12.19-x86 and v1.12.19-arm.

**Comment by author970** [comment]
> @author970 Could you please try the latest v1.12 version? The image tags are v1.12.19-x86 and v1.12.19-arm.

OK. When we subsequently upgrade kube-ovn to v1.12.19 and subsequent versions, we will conduct verification and reply with the verification results.

**Comment by author970** [comment]
After verification, it is found that by upgrading kube-ovn to version v1.12.22, this issue has been resolved.
