### ISSUE TITLE
[BUG] 跨节点访问，节点访问容器hostport不通

### ISSUE THREAD

**Issue by OneWithoutName** [kubeovn/kube-ovn#4204]
### Kube-OVN Version

V1.12.16

### Kubernetes Version

1.27.6

### Operation-system/Kernel Version

欧拉操作系统，5.10.0-136.12.0.86.4.hl202.x86_64

### Description

将K8S所运行的宿主机网络称为集群网，另一张和K8S无关的网卡称为管理网。跨节点执行curl  集群网IP:hostport，最终请求会超时，同节点curl  集群网IP:hostport 可正常返回。跨节点执行curl  管理网IP:hostport可正常返回。
![image](https://github.com/kubeovn/kube-ovn/assets/20835236/8e500c98-03f3-4b0c-a459-196b341af683)
如上图，访问集群网192.166.0.50:48011超时，访问管理网10.210.18.50:48011正常访问。

![image](https://github.com/kubeovn/kube-ovn/assets/20835236/999532b1-7648-461e-a8e2-228e28beafc8)
如上图，同节点访问，管理网和集群网均可以正常访问。
![image](https://github.com/kubeovn/kube-ovn/assets/20835236/49eb044d-db26-48f3-94d7-7f2ddbe3a79d)
如上图，容器跨节点访问hostport，管理网和集群网均可以正常访问。

![image](https://github.com/kubeovn/kube-ovn/assets/20835236/fc0b1413-26d9-4bb6-9f26-ce601eedc83d)
![image](https://github.com/kubeovn/kube-ovn/assets/20835236/5cbbba95-f6db-48be-92e4-9b843bed4b6f)

经过抓包，客户端不断发送SYN TCP报文，服务端收到报文不断返回SYN/ACK  TCP报文，且报文已发送至客户端节点的ovn0网卡，如上图。似乎客户端并没有对SYN/ACK进行响应，导致客户端和服务端均不断重试发送。

另经其他环境确认，单网卡的K8S也会出现此问题，似乎是最新的几个版本才有的，之前使用v1.12.12，应该没出现此问题。

### Steps To Reproduce

1. 使用kube-ovn v1.12.16版本，宿主机是单网卡和双网卡都可以
2. 创建一个deployment，使用hostPort暴露应用。
3. 选一个没有此deployment运行的节点，通过curl  访问deployment所在节点的集群网IP+hostPort，访问超时。

### Current Behavior

跨节点访问，节点访问hostport超时。

### Expected Behavior

跨节点访问，节点访问hostport可正常返回。

**Comment by oilbeater** [comment]
子网使用的是分布式网关还是集中式网关

**Comment by OneWithoutName** [comment]
> 子网使用的是分布式网关还是集中式网关

![image](https://github.com/kubeovn/kube-ovn/assets/20835236/65c15568-0439-45b4-bd88-3be0dee9193d)
shi'y使用分布式网关

**Comment by zhangzujian** [comment]
@OneWithoutName 

使用 hostport 是基于什么需求场景？
从 k8s 集群的其它节点上 curl 这个 hostport 也很奇怪，为什么不直接用 service 域名或者 service ip 访问呢？

**Comment by OneWithoutName** [comment]
> @OneWithoutName
> 
> 使用 hostport 是基于什么需求场景？ 从 k8s 集群的其它节点上 curl 这个 hostport 也很奇怪，为什么不直接用 service 域名或者 service ip 访问呢？

对内和对外提供kong网关的服务，并且不能接受DNAT，否则获取不到客户端的真实源IP，需要用一种统一的暴露方式，所以不用service ip，对内的话，如果客户端是hostnetwork的话，访问kong网关就会出现这个问题。

**Comment by OneWithoutName** [comment]
再补充一下，集群外同网段的某台物理机访问此hostport，也是可以正常访问的。我怀疑是，去的时候，走的是节点网络，目的地址是目的节点的集群网IP，SYN/ACK报文返回时，因为走的是geneve的隧道封装，源地址也变为容器地址，所以客户端不认这个SYN/ACK报文？

**Comment by zhangzujian** [comment]
nodeA => nodeB+hostport => DNAT => pod
pod => GENEVE 封装 => nodeB => nodeA

所以无法正常访问。

目前暂时没有办法在不做 SNAT 的情况下实现需求。

**Comment by oilbeater** [comment]
如果吧 node+hostport 也当成一个 OVN L2 LB 是不是可以绕过这个问题

**Comment by OneWithoutName** [comment]
> nodeA => nodeB+hostport => DNAT => pod pod => GENEVE 封装 => nodeB => nodeA
> 
> 所以无法正常访问。
> 
> 目前暂时没有办法在不做 SNAT 的情况下实现需求。


上面这种是可以获取到源IP的， externalTrafficPolicy的NodePort service那种跨节点转发的是不行的。或者我们抛开源IP这个事，就分析一下hostport本身这个问题，毕竟从K8S规范来说也没有禁止这种用法。

**Comment by zhangzujian** [comment]
在 Kube-OVN Overlay 网络里，你可以简单理解为 Pod 与其它节点是三层直通且不经过本节点的。所以你如果使用了 Kube-OVN + hostport，不支持从其他节点通过 k8s internal-ip 访问 hostport。

k8s 规范并不禁止 hostport，我只是给你解释为什么会出现这种无法访问的情况。

**Comment by oilbeater** [comment]
在 Kube-OVN Overlay 里 Pod 访问 hostport 的路径如下：
Pod A -> Node B hostport -> Pod C

这是 Pod A 发送包的目的地址是 Node B 的 hostport 地址，而 Pod C 的回包目的地址是 Pod A 的地址。在 Pod A 来看回包的地址从 Node B 变成了 Pod C，五元组不匹配无法通信。

其他 CNI 可能能通的前提是 Pod C 的回包会经过 Node B 的网络栈可以做反向的地址翻译。

**Comment by OneWithoutName** [comment]
> 在 Kube-OVN Overlay 里 Pod 访问 hostport 的路径如下： Pod A -> Node B hostport -> Pod C
> 
> 这是 Pod A 发送包的目的地址是 Node B 的 hostport 地址，而 Pod C 的回包目的地址是 Pod A 的地址。在 Pod A 来看回包的地址从 Node B 变成了 Pod C，五元组不匹配无法通信。
> 
> 其他 CNI 可能能通的前提是 Pod C 的回包会经过 Node B 的网络栈可以做反向的地址翻译。


我在上面的判断也是这样认为的。目的地址变了，那看来就是确实是不能这么用了

**Comment by OneWithoutName** [comment]
> 在 Kube-OVN Overlay 网络里，你可以简单理解为 Pod 与其它节点是三层直通且不经过本节点的。所以你如果使用了 Kube-OVN + hostport，不支持从其他节点通过 k8s node 的 internal-ip 访问 hostport。
> 
> k8s 规范并不禁止 hostport，我只是给你解释为什么会出现这种无法访问的情况。

明白了

**Comment by kldancer** [comment]
> 在 Kube-OVN Overlay 网络里，你可以简单理解为 Pod 与其它节点是三层直通且不经过本节点的。所以你如果使用了 Kube-OVN + hostport，不支持从其他节点通过 k8s node 的 internal-ip 访问 hostport。
> 
> k8s 规范并不禁止 hostport，我只是给你解释为什么会出现这种无法访问的情况。

你好，请问有支持的规划吗？
