### ISSUE TITLE
[BUG] need to handle the failure during allocate multiple IPs for a single pod, or it will exhausted the whole IP Pool.

### ISSUE THREAD

**Issue by jcshare** [kubeovn/kube-ovn#4210]
### Kube-OVN Version

v.1.12.17 and master

### Kubernetes Version

v1.27

### Operation-system/Kernel Version

"Ubuntu 20.04.6 LTS" / 5.4.0-186-generic

### Description

it looks like no handling for the failure of IP allocation during create the VPC GW pod, and the whole External IP Pool get exhausted by this problem.

after done some research, I found out the root cause looks like below:
```
pod.go
// do the same thing as add pod
func (c *Controller) reconcileAllocateSubnets(cachedPod, pod *v1.Pod, needAllocatePodNets []*kubeovnNet) (*v1.Pod, error) {
	namespace := pod.Namespace
	name := pod.Name
	klog.Infof("sync pod %s/%s allocated", namespace, name)

	isVMPod, vmName := isVMPod(pod)
	podType := getPodType(pod)
	podName := c.getNameByPod(pod)
	// todo: isVmPod, getPodType, getNameByPod has duplicated logic

	// Avoid create lsp for already running pod in ovn-nb when controller restart
	for _, podNet := range needAllocatePodNets {
		// the subnet may changed when alloc static ip from the latter subnet after ns supports multi subnets
		v4IP, v6IP, mac, subnet, err := c.acquireAddress(pod, podNet)
		if err != nil {
			c.recorder.Eventf(pod, v1.EventTypeWarning, "AcquireAddressFailed", err.Error())
			klog.Error(err)
			return nil, err  <<<<<<<< here, need to release those allocated IP address in previous loop
		} 
                ...
       }
```

an vpc-gw pod info:
```
root@master:~# kubectl describe pod vpc-nat-gw-tanant1-pro1-vpc1-net1-gw-0 -n kube-system
Name:             vpc-nat-gw-tanant1-pro1-vpc1-net1-gw-0
Namespace:        kube-system
Priority:         0
Service Account:  default
Node:             worker2/192.168.1.118
Start Time:       Fri, 21 Jun 2024 11:13:32 +0000
Labels:           app=vpc-nat-gw-tanant1-pro1-vpc1-net1-gw
                  controller-revision-hash=vpc-nat-gw-tanant1-pro1-vpc1-net1-gw-658dfcff4
                  ovn.kubernetes.io/vpc-nat-gw=true
                  statefulset.kubernetes.io/pod-name=vpc-nat-gw-tanant1-pro1-vpc1-net1-gw-0
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "kube-ovn",
                        "interface": "eth0",
                        "ips": [
                            "172.22.1.254"
                        ],
                        "mac": "00:00:00:16:07:58",
                        "default": true,
                        "dns": {},
                        "gateway": [
                            "172.22.1.1"
                        ]
                    },{
                        "name": "kube-system/ovn-vpc-external-network",
                        "interface": "net1",
                        "ips": [
                            "192.168.1.19"
                        ],
                        "mac": "02:26:74:5d:03:a3",
                        "dns": {}
                    }]

```

### Steps To Reproduce

create and delete vpc nat gate multiple times

### Current Behavior

the external IP CIDR get exhausted by this problem

### Expected Behavior

nice handling for the IP allocating/releasing to avoid such a problem.

**Comment by jcshare** [comment]
can some expert help fix this issue as I have no authority to do it,
many thanks

**Comment by bobz965** [comment]
please attach the err log in the kube-ovn-controller pod about the nat gw pod `allocate ip`

**Comment by jcshare** [comment]
701 I0619 12:07:04.058569       6 ipam.go:60] allocate v4 192.168.1.10, v6 , mac  for kube-system/vpc-nat-gw-gw1-vpc-1-0 from subnet ovn-vpc-external-network
  702 I0619 12:07:04.071551       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet net1-vpc-1
  703 E0619 12:07:04.072121       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet net1-vpc-1, err NoAvailableAddress
  704 I0619 12:07:04.072830       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet ovn-default
  705 E0619 12:07:04.073320       6 ipam.go:89] failed to allocate static ip 10.0.1.254 for kube-system/vpc-nat-gw-gw1-vpc-1-0
  706 E0619 12:07:04.073525       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet ovn-default, err AddressOutOfRange
  707 E0619 12:07:04.073788       6 pod.go:620] AddressOutOfRange
  708 E0619 12:07:04.074250       6 pod.go:405] error syncing 'kube-system/vpc-nat-gw-gw1-vpc-1-0': AddressOutOfRange, requeuing
  709 I0619 12:07:04.074177       6 event.go:298] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"vpc-nat-gw-gw1-vpc-1-0", UID:"d61e58b5-c8f8-4f79-86cc-4e6d8724f475", AP      IVersion:"v1", ResourceVersion:"2632", FieldPath:""}): type: 'Warning' reason: 'AcquireAddressFailed' AddressOutOfRange
  710 I0619 12:07:04.080417       6 pod.go:550] handle add/update pod kube-system/vpc-nat-gw-gw1-vpc-1-0
  711 I0619 12:07:04.083914       6 pod.go:346] enqueue update pod kube-system/vpc-nat-gw-gw1-vpc-1-0
  712 I0619 12:07:04.086506       6 pod.go:607] sync pod kube-system/vpc-nat-gw-gw1-vpc-1-0 allocated
  713 I0619 12:07:04.087707       6 ipam.go:60] allocate v4 192.168.1.11, v6 , mac  for kube-system/vpc-nat-gw-gw1-vpc-1-0 from subnet ovn-vpc-external-network
  714 I0619 12:07:04.097194       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet net1-vpc-1
  715 E0619 12:07:04.097443       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet net1-vpc-1, err NoAvailableAddress
  716 I0619 12:07:04.097556       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet ovn-default
  717 E0619 12:07:04.097627       6 ipam.go:89] failed to allocate static ip 10.0.1.254 for kube-system/vpc-nat-gw-gw1-vpc-1-0
  718 E0619 12:07:04.097700       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet ovn-default, err AddressOutOfRange
  719 E0619 12:07:04.097851       6 pod.go:620] AddressOutOfRange
  720 E0619 12:07:04.097949       6 pod.go:405] error syncing 'kube-system/vpc-nat-gw-gw1-vpc-1-0': AddressOutOfRange, requeuing
  721 I0619 12:07:04.098040       6 pod.go:550] handle add/update pod kube-system/vpc-nat-gw-gw1-vpc-1-0
  722 I0619 12:07:04.098105       6 event.go:298] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"vpc-nat-gw-gw1-vpc-1-0", UID:"d61e58b5-c8f8-4f79-86cc-4e6d8724f475", AP      IVersion:"v1", ResourceVersion:"2633", FieldPath:""}): type: 'Warning' reason: 'AcquireAddressFailed' AddressOutOfRange
  723 I0619 12:07:04.101424       6 pod.go:607] sync pod kube-system/vpc-nat-gw-gw1-vpc-1-0 allocated
  724 I0619 12:07:04.101533       6 ipam.go:60] allocate v4 192.168.1.12, v6 , mac  for kube-system/vpc-nat-gw-gw1-vpc-1-0 from subnet ovn-vpc-external-network
  725 I0619 12:07:04.107169       6 pod.go:346] enqueue update pod kube-system/vpc-nat-gw-gw1-vpc-1-0
  726 I0619 12:07:04.107456       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet net1-vpc-1
  727 E0619 12:07:04.107559       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet net1-vpc-1, err NoAvailableAddress
  728 I0619 12:07:04.107574       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet ovn-default
  729 E0619 12:07:04.107581       6 ipam.go:89] failed to allocate static ip 10.0.1.254 for kube-system/vpc-nat-gw-gw1-vpc-1-0
  730 E0619 12:07:04.107585       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet ovn-default, err AddressOutOfRange
  731 E0619 12:07:04.107645       6 pod.go:620] AddressOutOfRange
  732 E0619 12:07:04.108065       6 pod.go:405] error syncing 'kube-system/vpc-nat-gw-gw1-vpc-1-0': AddressOutOfRange, requeuing
  733 I0619 12:07:04.108083       6 pod.go:550] handle add/update pod kube-system/vpc-nat-gw-gw1-vpc-1-0
  734 I0619 12:07:04.107846       6 event.go:298] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"vpc-nat-gw-gw1-vpc-1-0", UID:"d61e58b5-c8f8-4f79-86cc-4e6d8724f475", AP      IVersion:"v1", ResourceVersion:"2642", FieldPath:""}): type: 'Warning' reason: 'AcquireAddressFailed' AddressOutOfRange
  735 I0619 12:07:04.110791       6 pod.go:607] sync pod kube-system/vpc-nat-gw-gw1-vpc-1-0 allocated
  736 I0619 12:07:04.110947       6 ipam.go:60] allocate v4 192.168.1.13, v6 , mac  for kube-system/vpc-nat-gw-gw1-vpc-1-0 from subnet ovn-vpc-external-network
  737 I0619 12:07:04.116781       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet net1-vpc-1
  738 E0619 12:07:04.116801       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet net1-vpc-1, err NoAvailableAddress
  739 I0619 12:07:04.116809       6 ipam.go:72] allocating static ip 10.0.1.254 from subnet ovn-default
  740 E0619 12:07:04.116901       6 ipam.go:89] failed to allocate static ip 10.0.1.254 for kube-system/vpc-nat-gw-gw1-vpc-1-0
  741 E0619 12:07:04.116916       6 pod.go:1762] failed to get static ip 10.0.1.254, mac <nil>, subnet ovn-default, err AddressOutOfRange
  742 E0619 12:07:04.117040       6 pod.go:620] AddressOutOfRange

**Comment by bobz965** [comment]
err： `failed to get static ip 10.0.1.254, mac , subnet ovn-default, err AddressOutOfRange
719 E0619 12:07:04.097851 6 pod.go:620] AddressOutOfRange`


please attatch `kubectl get subnet`  details:

**Comment by jcshare** [comment]
the root cause should be identified as above, we need to handle the exception gracefully.
I have rebuild my setup, so paste the subnet and VPC's definition as below:
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc-1
spec:
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.254
      policy: policyDst
  namespaces:
    - ns1
    - ns2
    - ns3
    - ns4
    - ns5
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1-vpc-1
spec:
  vpc: vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  excludeIps:
    - 10.0.1.254
  namespaces:
    - ns1

```

**Comment by jcshare** [comment]
per the log above,it looks exist another problem(as you mentioned ), the controller shouldn't allocate the "10.0.1.254" for ovn-default subnet

**Comment by bobz965** [comment]
where is your 10.0.1.0/24 subnet ???

**Comment by jcshare** [comment]
> where is your 10.0.1.0/24 subnet ???

could you help take a deep look at the problem?   it should be easy to reproduce with my configuration above.
my testbed got broken by the problem and I have rebuild it, so you cannot see  the subnet in my current setup.

many thanks

**Comment by jcshare** [comment]
I have reproduced it with a new VPC named "vpc-3" with related log files
could you help take a look?
many thanks
[1.12.7-IP-Allocation-bug.zip](https://github.com/user-attachments/files/15950698/1.12.7-IP-Allocation-bug.zip)

**Comment by bobz965** [comment]
> where is your 10.0.1.0/24 subnet ???

sorry,  I think when you get subnet: it show all the subnet, but i do not find the 10.0.1.0/24 subnet

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/cc47bf5a-5802-4eb9-b53e-50fa384960e1)

**Comment by jcshare** [comment]
> > where is your 10.0.1.0/24 subnet ???
> 
> sorry, I think, when you get subnet: it shows all the subnets, but, i do not find the 10.0.1.0/24 subnet
> 
> ![image](https://private-user-images.githubusercontent.com/7981158/344120216-cc47bf5a-5802-4eb9-b53e-50fa384960e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MjkxOTEsIm5iZiI6MTcxOTYyODg5MSwicGF0aCI6Ii83OTgxMTU4LzM0NDEyMDIxNi1jYzQ3YmY1YS01ODAyLTRlYjktYjUzZS01MGZhMzg0OTYwZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDI0MTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmNWIyNmFjMmRkNTY3OTVjMzhlNjg0ODE3NTM2OTE1N2NkYzFiOTc0YjZlMmVmM2IxNzkxYjViNjdjMmI4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ufhz3_Sst_BQ9I9YSsfZREkq8bMvXda4EQFzGxP0uuI)

could you refer to my reply above : https://github.com/kubeovn/kube-ovn/issues/4210#issuecomment-2185711409

**Comment by jcshare** [comment]
it looks like the [problem ](https://github.com/kubeovn/kube-ovn/issues/4210#issue-2367640303) is obviously, can we help fix it if possible?
many thanks

**Comment by bobz965** [comment]
you do not have the vpc subnet `10.0.1.0/24`, if you use the 10.0.1.0.254,  you should create it. 
if you use vpc3 subnet, I think you should use 10.0.3.254.

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/27db968a-0f8d-4fda-8736-a6b19fc47387)

**Comment by jcshare** [comment]
"if you use vpc3 subnet, I think you should use 10.0.3.254."

yes, I'm using 10.0.3.254 for vpc3, please refer to vpc3(rather than vpc1) related configuration/debug info in the tar ball

thanks

**Comment by bobz965** [comment]
![image](https://github.com/kubeovn/kube-ovn/assets/7981158/5fe23553-4130-4a57-8989-5ca8eabd0d57)


![image](https://github.com/kubeovn/kube-ovn/assets/7981158/2b6d3c27-de6f-4f4a-8a82-6a4cfac3e411)


hi @zhangzujian, it seems IPAM has a problem ?
