### ISSUE TITLE
[BUG] Unable to delete subnet due to leftover IP

### ISSUE THREAD

**Issue by reski-rukmantiyo** [kubeovn/kube-ovn#4243]
### Kube-OVN Version

v1.12.12

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

### Operation-system/Kernel Version

"Ubuntu 22.04.4 LTS"
5.15.0-113-generic

### Description

Try to create script from [Config VPC](https://kubeovn.github.io/docs/v1.12.x/en/guide/vpc/).
All the scripts is compiled into 1 file. Due to problem in #4241, I try to delete using the same file kubectl delete -f config-vpc.yaml.

After wait a few minutes, got these messages

```
E0630 03:56:23.001854      13 subnet.go:921] inconsistency detected in status of subnet attach-subnet : subnet attach-subnet has 1 v4 ip in use, while the v4 using ip range is empty
E0630 03:56:23.001927      13 subnet.go:246] error syncing 'attach-subnet': subnet attach-subnet has 1 v4 ip in use, while the v4 using ip range is empty, requeuing
```

### Steps To Reproduce

1. Compile [Config VPC](https://kubeovn.github.io/docs/v1.12.x/en/guide/vpc/) into 1 file
2. kubectl apply -f config-vpc.yaml
3. kubectl delete -f config-vpc.yaml

### Current Behavior

Subnet cannot be delete due to multus net-attachment-def deleted first before subnet.
When i try to apply the net-attachment-def again, then delete, somehow it dont work.

Solution is to delete leftover ip in kubectl get ip, then check for name of deleted subnet.

### Expected Behavior

Subnet can be delete although net-attachment-def already deleted

**Comment by bobz965** [comment]
how about deleting the ip manually before deleting the subnet ？

**Comment by reski-rukmantiyo** [comment]
Yes, this is possible to have a routine to delete all ips that related with those subnet.

**Comment by bobz965** [comment]
user should make sure all ips is deleted before delete subnet.

**Comment by reski-rukmantiyo** [comment]
yes, thanks for this. Let me close this.
