### ISSUE TITLE
[BUG] failed to lookup pf ens5: no buffer space available

### ISSUE THREAD

**Issue by zhiwei-han** [kubeovn/kube-ovn#4252]
### Kube-OVN Version

v1.11

### Kubernetes Version

# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

### Operation-system/Kernel Version

kernek version:
# uname -r
5.10.135

OS：
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Description

其中一个worker node os是Ubuntu， pod能够正常起来，
不能ready 的pod 所在的worker node 使用的OS是 debian，使用sriov资源，满规格分配512个vf，出现如下问题：
error adding container to network "kube-ovn": RPC failed; request ip return 500 configure nic failed failed to lookup pf ens5: no buffer space available

### Steps To Reproduce

1 创建满规格vf，切换switchdev
2 install kube-ovn cni
3 安装sriov device plugin
4 创建pod

### Current Behavior

创建pod 不能正常启动

### Expected Behavior

pod能正常起来

**Comment by zhangzujian** [comment]
512 may be too big for [netlink](https://github.com/vishvananda/netlink) to get all VFs. Please try to set a smaller VF number and try again.

**Comment by zhiwei-han** [comment]
> 512 may be too big for [netlink](https://github.com/vishvananda/netlink) to get all VFs. Please try to set a smaller VF number and try again.

Yes， the smaller number of VFs can work . My Nic needs to support up to 512 VFs, and this issue only occurs in the KO cni environment.  Do you knows the root cause?

**Comment by zhiwei-han** [comment]
> 512 may be too big for [netlink](https://github.com/vishvananda/netlink) to get all VFs. Please try to set a smaller VF number and try again.

Another important clue， this issue occurs on Debian OS but not on Ubuntu.
