### ISSUE TITLE
GLIBC_2.34 requested on kube-ovn docker hub images.

### ISSUE THREAD

**Issue by Orfheo** [kubeovn/kube-ovn#4267]
This morning  I tried to update the kube-ovn images, a new pull, of the master branch (v1.13.0), on my Ubuntu-20.04 K8s experimental cluster.

With my surprise the image didn't start correctly, I had been rewarded with the message:

  /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found
  
  when kube-ovn-cni try to load the "loopback" command /opt/cni/bin.
  
  For what I know Ubuntu-20.04 do not support libc-2.34.so, the current libc.so.6 version is 2.31.
  
Does this mean I've to rebuild the kube-ovn image by myself locally to update the kube-ovn master version under Ubuntu-20.04?

**Comment by oilbeater** [comment]
Maybe we need to disable the cgo when building the cni plugins. Can you check this @zhangzujian ?
