### ISSUE TITLE
[BUG] [KIND] ovs-ovn: modinfo: ERROR: Module openvswitch not found

### ISSUE THREAD

**Issue by tgdfool2** [kubeovn/kube-ovn#4286]
### Kube-OVN Version

v1.12.20 (also tested with v1.13.0)

### Kubernetes Version

kind v1.29.2

### Operation-system/Kernel Version

MacBook M1, macOS Sonoma 14.5
Docker Desktop v4.31.0

### Description

Trying to deploy kind / kube-ovn through Makefile targets, results in ovs-ovn Pods in CrashLoopBackOff due to missing openvswitch module.

Not sure if this could be related to the ARM-based architecture, as I don't have a AMD64-based system to test.

### Steps To Reproduce

Tested with Helm Chart installation:
1. make kind-init
2. make kind-install-chart

As well as with manifests installation:
1. make kind-init
2. make kind-install 

### Current Behavior

ovs-ovn Pods stuck in CrashLoopBackOff due to missing openvswitch module:
```
> stern -n kube-system ovs
kube-system ovs-ovn-s5mh2 openvswitch OVN_REMOTE_PROBE_INTERVAL is set to 10000
kube-system ovs-ovn-s5mh2 openvswitch OVN_REMOTE_OPENFLOW_INTERVAL is set to 180
kube-system ovs-ovn-s5mh2 openvswitch modinfo: ERROR: Module openvswitch not found.
kube-system ovs-ovn-wvsg8 openvswitch OVN_REMOTE_PROBE_INTERVAL is set to 10000
kube-system ovs-ovn-wvsg8 openvswitch OVN_REMOTE_OPENFLOW_INTERVAL is set to 180
kube-system ovs-ovn-wvsg8 openvswitch modinfo: ERROR: Module openvswitch not found.
```

### Expected Behavior

All kube-ovn Pods up-and-running

**Comment by hongzhen-ma** [comment]
I encountered the same problem. The problem is caused by docker. 
After testing and confirmation, it was normal before docker 4.26.0(included) version.
Starting from version 4.27.0, this problem has appeared.

**Comment by oilbeater** [comment]
From https://github.com/docker/for-mac/issues/7151, openvswitch is built-in modules since docker for mac 4.27. We need to change the logical to find if openvswitch module is already loaded.

**Comment by zhangzujian** [comment]
Check whether the kernel module is listed in the modules.builtin file, for example:

```shell
$ docker exec kube-ovn-control-plane sh -c 'grep -w tun /lib/modules/`uname -r`/modules.builtin'
kernel/drivers/net/tun.ko
```
