### ISSUE TITLE
[BUG] 跨节点pod之间无法互相ping通

### ISSUE THREAD

**Issue by chonghua1** [kubeovn/kube-ovn#4325]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

k3s v1.29.6+k3s2

### Operation-system/Kernel Version

server: "Ubuntu 22.04.4 LTS" 6.5.0-44-generic
agent: "Ubuntu 20.04.6 LTS"  5.15.0-113-generic

### Description

在server节点和agent节点上分别创建了一个pod，pod 和 host node 之间的通信正常，但pod之间无法互相ping通，位于agent节点的pod也无法ping通server节点；

server节点和agent节点通过开源5G项目连接，server是5GC，agent是UE。当部署到wifi网络上时一切正常，但部署到5G系统里出现了上述问题。

server节点和agent节点之间通信正常；

在agent节点的网卡上可以看到icmp流量，但没有reply；
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4795291510439307492 skey=@crypt_777de82d_35f5f09d00d1f80a27d5db2734b72af8 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/ac06e96a-b872-40fa-8f38-b7c86db5d16e)

pods的运行情况：

![image](https://github.com/user-attachments/assets/3bc57590-7300-44b7-82bf-acba605b487f)

![image](https://github.com/user-attachments/assets/d23c8fd9-538a-4d71-be64-35c8a3a02954)

### Steps To Reproduce

k3s cluster with 2 nodes. One serves as 5g core network, another is 5g UE. Deploy pods on two different nodes.

`k exec -it talker-deployment-6b87c44cf9-9vgff /bin/bash` 
`ping 10.16.0.18`

### Current Behavior

The pods on the different nodes can't communicate with each other

### Expected Behavior

The connectivity between pods should be fine

**Comment by zhangzujian** [comment]
同时在两个节点上抓包，看哪里丢包了？大概率是节点之间无法正常传输 vxlan/geneve 封装包。

**Comment by chonghua1** [comment]
> 同时在两个节点上抓包，看哪里丢包了。大概率是节点之间无法正常传输 vxlan/geneve 封装包。

隧道协议换成了vxlan,

从agent节点pod ping server节点pod，在server节点的vxlan_sys_4789 interface抓包可以看到reply，在agent节点的网卡抓包也有reply，但是ping没有回复
![image](https://github.com/user-attachments/assets/1cccfd38-5e89-45c2-83b4-306f1c25225d)
![image](https://github.com/user-attachments/assets/20b8b975-6388-4a9c-b71d-94d2c40f01f0)
![image](https://github.com/user-attachments/assets/321cd830-4c03-45b5-bc9a-4c80479c7e6b)

从server节点pod ping agent节点pod，vxlan_sys_4789 interface抓包只有request，在5G UE agent网卡处抓包也只能看到request：
![image](https://github.com/user-attachments/assets/dc39de32-41e3-4594-9b51-08aa268cc7c8)
![image](https://github.com/user-attachments/assets/872bece0-087d-4f9b-b2dd-481405f902f7)

**Comment by chonghua1** [comment]
> 同时在两个节点上抓包，看哪里丢包了。大概率是节点之间无法正常传输 vxlan/geneve 封装包。

kube-ovn-cni-dqnml 组件重启了很多次,  ovs-ovn-72ftl组件日志也有一些问题：
![image](https://github.com/user-attachments/assets/46fbb0c7-ff49-4151-affc-f6b3bb973a26)
![image](https://github.com/user-attachments/assets/665aedfd-9844-420c-b7b3-7ab9f847abdf)
![image](https://github.com/user-attachments/assets/11f0afe1-2378-4404-ab03-94954a31198d)

**Comment by zhangzujian** [comment]
错误已经很明显了。这不是 kube-ovn 的 bug。

**Comment by chonghua1** [comment]
> 错误已经很明显了。这不是 kube-ovn 的 bug。

请问是因为agent节点和server节点之间的网络问题吗？但是节点之间的通信测试了应该没问题
