### ISSUE TITLE
[BUG] kube-ovn部署之后卸载，卸载之后再部署无法正常运行

### ISSUE THREAD

**Issue by yanruogu** [kubeovn/kube-ovn#4379]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.28.10

### Operation-system/Kernel Version

ubuntu22.04/5.15.0-60-generic

### Description

在一个部署了kube-ovn的kubernetes集群上把kube-ovn卸载了，再重新部署，kube-ovn-pinger无法正常运行

### Steps To Reproduce

1. 部署方式，使用的helm部署： 
```
helm fetch kubeovn/kube-ovn
tar xf kube-ovn-v1.12.19.tgz
cd kube-ovn
helm install kube-ovn ./
```

3. 执行卸载： 
```
helm delete kube-ovn
```
5. 再次安装：
```
helm install kube-ovn ./
```
6. 此时发现kube-ovn-pinger无法正常运行： 
![2b5d25524870d8d3fa3a2a2302f15f0](https://github.com/user-attachments/assets/475fb9ed-6d8d-4fba-be6b-5c916ebeafb1)
7. 检查事件： 
![abb24b8b5172264bce6cfa8e5e3efcb](https://github.com/user-attachments/assets/1a3a202e-3817-4194-bab1-d0744cf78306)
8. 查看kube-ovn-controller日志： 
![e9e152829084506337f868ffc70d467](https://github.com/user-attachments/assets/611a191e-cff0-43f0-a8d7-75a610e963a5)

### Current Behavior

看kube-ovn-controller的日志，像是在helm delete的时候，有个啥资源一直处于terminating状态。。。没删掉，所以重新部署回来的时候，这资源不正常还是咋的？

### Expected Behavior

如上

**Comment by oilbeater** [comment]
卸载需要参考文档 https://kubeovn.github.io/docs/stable/start/uninstall/
