### ISSUE TITLE
OVS-DPDK multinode K8s traffic flow information request

### ISSUE THREAD

**Issue by tarun28jain** [kubeovn/kube-ovn#438]
Hi,

Require some information regarding traffic flow in case of OVS-DPDK using userspace CNI with Kubeovn

I have created a multinode Kubernetes setup over openstack VMs leveraging OVS-DPDK.
I have virtio type of network interfaces available inside the VMs.

Kubernetes in VMS have Kubeovn as default CNI installed with DPDK support and Userspace CNI.
When i launch a pod with DPDK based interfaces and run L3FWD and PKTGEN sample app as given in Userspace Github, pods are able to communicate when they are on same kubernetes node but when pods are on different nodes, these sample applications are not able to communicate with each other.

I understand that as also mentioned, userspace CNI does not take care of southbound data connectivity and some manual configuration needs to be done.
Just need to check if there are any configuration/steps available for adding this virtio type of nics available in my VM for DPDK based connectivity.

My Setup configuration are as follows
Baremetal OS: Ubuntu18
Openstack: Rocky release with OVS-DPDK bridges
K8s Version: 1.13
VM OS: Ubuntu18

**Comment by oilbeater** [comment]
@tarun28jain  I'm not an export of OVS-DPDK, I guess you can add a separate bridge in ovs for dpdk and add the virtio nic as the uplink to  connect other vms. Maybe @garyloug can provide some hints.

**Comment by tarun28jain** [comment]
Hi,

Thanks for the suggestion.
I tried the mentioned scenario.
Userspace CNI created a bridge of type "netdev" based on its CRD.
But when i try binding virtio_net based nic to either "vfio-pci" or "uio_pci_generic" i gives error.
Nic gets binded to vfio-pci driver on kubernetes nodes as per suggestion given here: https://github.com/openvswitch/ovs-issues/issues/191
But it gives error inside ovs-ovn container created by Kubeovn script using DPDK image based on Fedora.

Also i tried setting up multinode K8s without kubeovn and Weave as default cni and installed ovs-dpdk on my master and minion nodes only and the using userspace cni, i created pods and dpdk based bridge.
Then i added interface from K8s node only to dpdk based ovs bridge but traffic is still not flowing from one node to another.

Do i need to add some rules on the bridge for traffic to flow or anything else is required?

**Comment by przemeklal** [comment]
Hi, can you share OVS-DPDK logs from ovs-ovn container so that we can see why exactly it fails after you have bound the virtio NIC? I have a theory that it may be failing on the port initialization because of the missing mounts - OVS probably needs access to the /dev/vfio/ (or /dev/uio if you're using igb_uio/uio_pci_generic) on the VM's filesystem to initialize it, currently this volume mount is missing.

Using this virtio NIC in kernel mode and attaching it to the netdev bridge will cause issues with packets being copied/duplicated between userspace and kernel stack which will result in terrible performance (something around 10 Kbps from my experience).

Another thing to consider is the port security in OpenStack (anti-spoofing). If you have it enabled (it usually is enabled by default) then any packets with source MAC that doesn't match virtio's interface MAC will be dropped. Userspace CNI creates new vhostuser sockets that have their own MAC addresses. So regardless of the kernel/DPDK mode, you'll have to disable it for the entire neutron subnet or at least for those virtio ports you want to bind to DPDK.

**Comment by przemeklal** [comment]
But in general, binding virtio interface to the userspace driver and adding it to the same netdev bridge as the virtio user socket is a way to go.

**Comment by tarun28jain** [comment]
Hi,

After yum update in ovs-ovn conatiner, When i try binding the nic to vfio driver it gives me error as

```
[root@test /]# dpdk-devbind.py --bind=vfio_pci 0000:00:04.0
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
Error: bind failed for 0000:00:04.0 - Cannot open /sys/bus/pci/drivers/vfio_pci/bind
Error: unbind failed for 0000:00:04.0 - Cannot open /sys/bus/pci/drivers//unbind
```
While nothing is updated in log file "/var/log/openvswitch/ovs-vswitchd.log"

Other details are

```
root@test:~# ethtool -i ens4
driver: virtio_net
version: 1.0.0
firmware-version:
expansion-rom-version:
bus-info: 0000:00:04.0
supports-statistics: no
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

[root@test /]# ovs-vsctl show
d0096f2b-3802-4338-ac5f-f18e0dc9def8
    Bridge br0
        datapath_type: netdev
        Port br0
            Interface br0
                type: internal
        Port f130682ef0f3-net1
            Interface f130682ef0f3-net1
                type: dpdkvhostuser
    Bridge br-int
        fail_mode: secure
        Port ovn0
            Interface ovn0
                type: internal
        Port br-int
            Interface br-int
                type: internal
        Port mirror0
            Interface mirror0
                type: internal
        Port f130682ef0f3_h
            Interface f130682ef0f3_h
        Port "996c856e406e_h"
            Interface "996c856e406e_h"
        Port d7bd6ba7e283_h
            Interface d7bd6ba7e283_h
        Port "79ad5e52b456_h"
            Interface "79ad5e52b456_h"
    ovs_version: "2.13.0"
```

Do i need to check some other logs for OVS-DPDK?

**Comment by oilbeater** [comment]
@tarun28jain from the log above, I guess you can try to mount `/sys/bus/pci/drivers` into the ovs-ovn container.

**Comment by przemeklal** [comment]
@tarun28jain The general practice is that one does the driver binding on the host, before starting the containerized DPDK application.
So, something like this:
1. Bind your host/VM interface to VFIO-PCI driver on the **host/VM level**.
2. Only after that, start your OVS-DPDK container/pod (the OVN one). Remember that /dev/vfio from the host must be mounted. If there's anything else that needs mounting from the host, you'll see it in the vswitchd logs, mainly in the EAL init section.
3. Attach your network interface (the one that you've bound to the vfio-pci driver) to the OVS-DPDK netdev bridge using ovs-vsctl command and it's PCI address, Because /dev/vfio is mounted it should be accessible inside the container. If there's anything else missing you'll likely see it in the vswitchd logs.

**Comment by tarun28jain** [comment]
Hi,

As per these steps mentioned, i dont have ovs-dpdk binaries running on my kubernetes vms.
Also i am not able to install them after setting up kubeovn as due to some lock files issue while starting binary which is being used by Kube-ovn.
These running binaries of ovs and dpdk are available inside the container only which i am using to bind the interface and adding it to ovs-dpdk bridge.

Currently i am trying suggestion as given above by mounting sys drivers path in ovs-ovn conatiners if i am able to bind using that.
Will update shortly.

Thanks

**Comment by ranjmish** [comment]
@tarun28jain : is it solved ?

**Comment by tarun28jain** [comment]
Hi,

Sorry for delay.

I tried binding the nic inside ovs-ovn container by mounting `/sys/bus/pci/drivers` while installing kubeovn with dpdk.
Now i logged in to ovs-ovn container and after running command `echo 1 > /sys/module/vfio/parameters/enable_unsafe_noiommu_mode`, i am able to bind nic with vfio-pci driver

```
[root@test /]# dpdk-devbind.py --status
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12
lspci: Unable to load libkmod resources: error -12

Network devices using DPDK-compatible driver
============================================
0000:00:04.0 'Virtio network device 1000' drv=vfio-pci unused=

Network devices using kernel driver
===================================
0000:00:03.0 'Virtio network device 1000' if=ens3 drv=virtio-pci unused=vfio-pci *Active*

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================
```
But after that when i tried adding this nic as port to ovs-dpdk bridge, it failed as follows
```
[root@test /]# ovs-vsctl add-port br0 dpdk0 -- set Interface dpdk0 type=dpdk options:dpdk-devargs=0000:00:04.0
ovs-vsctl: Error detected while setting up 'dpdk0': Error attaching device '0000:00:04.0' to DPDK.  See ovs-vswitchd log for details.
ovs-vsctl: The default log directory is "/var/log/openvswitch".
[root@test /]# ovs-vsctl show
4c127344-559d-4d73-a544-3b9de3c8eb25
    Bridge br0
        datapath_type: netdev
        **Port dpdk0
            Interface dpdk0
                type: dpdk
                options: {dpdk-devargs="0000:00:04.0"}
                error: "Error attaching device '0000:00:04.0' to DPDK"**
        Port br0
            Interface br0
                type: internal
    Bridge br-int
        fail_mode: secure
        Port eeb038cf1842_h
            Interface eeb038cf1842_h
        Port br-int
            Interface br-int
                type: internal
```
OVS logs are as follows
```
[root@test /]# tail -f /var/log/openvswitch/ovs-vswitchd.log
2020-09-01T11:27:49.797Z|00249|dpdk|INFO|EAL: PCI device 0000:00:04.0 on NUMA socket 0
2020-09-01T11:27:49.798Z|00250|dpdk|INFO|EAL:   probe driver: 1af4:1000 net_virtio
2020-09-01T11:27:49.798Z|00251|dpdk|WARN|EAL:  0000:00:04.0 not managed by VFIO driver, skipping
2020-09-01T11:27:49.798Z|00252|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (12)
2020-09-01T11:27:49.798Z|00253|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (12)
2020-09-01T11:27:49.798Z|00254|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (12)
2020-09-01T11:27:49.798Z|00255|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (0)
2020-09-01T11:27:49.798Z|00256|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (1e)
2020-09-01T11:27:49.798Z|00257|dpdk|ERR|EAL: Can't read from PCI bar (0) : offset (c)
2020-09-01T11:27:49.798Z|00258|dpdk|ERR|virtio_init_queue(): virtqueue does not exist
2020-09-01T11:27:49.798Z|00259|dpdk|ERR|EAL: fail to disable req notifier.
2020-09-01T11:27:49.798Z|00260|dpdk|ERR|EAL: fail to disable req notifier.
2020-09-01T11:27:49.798Z|00261|dpdk|ERR|EAL: Driver cannot attach the device (0000:00:04.0)
2020-09-01T11:27:49.798Z|00262|dpdk|ERR|EAL: Failed to attach device on primary process
2020-09-01T11:27:49.798Z|00263|netdev_dpdk|WARN|Error attaching device '0000:00:04.0' to DPDK
2020-09-01T11:27:49.798Z|00264|netdev|WARN|dpdk0: could not set configuration (Invalid argument)
2020-09-01T11:27:49.798Z|00265|dpdk|ERR|Invalid port_id=32
```

Please let me know in case faced similar issue or any pointers would be really appreciated.

Regards,
Tarun

**Comment by nilanjan-samajdar** [comment]
Just to add, the reason @tarun28jain  is trying to use VFIO PCI Driver is linked to this issue -
https://github.com/openvswitch/ovs-issues/issues/191

**Comment by oilbeater** [comment]
Close stale issues.
