### ISSUE TITLE
[BUG] kata-container checksum

### ISSUE THREAD

**Issue by Volcano139** [kubeovn/kube-ovn#4436]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.27.13

### Operation-system/Kernel Version

Linux master 5.10.149-1.el7.x86_64 #1 SMP Tue Oct 18 00:26:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Description

kubernetes使用kata-container，为容器配置TCP探针，探针无法正常工作，抓包发现checksum存在问题

### Steps To Reproduce

kubernetes使用kata-container，为容器配置TCP探针，探针无法正常工作，抓包发现checksum存在问题

### Current Behavior

探针失效

### Expected Behavior

探针应该正常工作

**Comment by zhangzujian** [comment]
1. 请提供问题细节，比如抓包结果，虚拟机网络工作模式等；
2. 如果只有虚拟机有问题，大概率不是 CNI 本身的问题，请提供虚拟机的内核版本，检查虚拟机网卡的 checksum offload 配置（ethtool -k eth0），并尝试用 ethtool -K 关闭对应的 checksum offload。

**Comment by Volcano139** [comment]
您好：
&nbsp; 在默认子网下的kata pod，tcp、http探针正常，自定义VPC下的kata pod，tcp、http探针失败。pod中抓包没有报文，kube-ovn-cni中有报文
&nbsp; kube-ovn-cni 启动命令参数：--enable-mirror=false --enable-arp-detect-ip-conflict=true --encap-checksum=false --service-cluster-ip-range=10.234.0.0/16 --iface= --dpdk-tunnel-iface=br-phy --network-type=geneve --default-interface-name= --cni-conf-name=01-kube-ovn.conflist --logtostderr=false --alsologtostderr=true --log_file=/var/log/kube-ovn/kube-ovn-cni.log --log_file_max_size=200 --kubelet-dir=/var/lib/kubelet --enable-tproxy=true --ovs-vsctl-concurrency=100
kube-ovn版本为1.12.19，kata-container部署方式参考https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md



容器探针



在pod中抓包

kube-ovn-cni日志



在kube-ovn-cni中抓包





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubeovn/kube-ovn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月4日(星期三) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubeovn/kube-ovn] [BUG] kata-container checksum (Issue #4436)





  
请提供问题细节，比如抓包结果，虚拟机网络工作模式等；
 
如果只有虚拟机有问题，大概率不是 CNI 本身的问题，请提供虚拟机的内核版本，检查虚拟机网卡的 checksum offload 配置（ethtool -k eth0），并尝试用 ethtool -K 关闭对应的 checksum offload。

**Comment by Volcano139** [comment]
在默认子网下的kata pod，tcp、http探针正常，自定义VPC下的kata pod，tcp、http探针失败。pod中抓包没有报文，kube-ovn-cni中有报文
  kube-ovn-cni 启动命令参数：--enable-mirror=false --enable-arp-detect-ip-conflict=true --encap-checksum=false --service-cluster-ip-range=10.234.0.0/16 --iface= --dpdk-tunnel-iface=br-phy --network-type=geneve --default-interface-name= --cni-conf-name=01-kube-ovn.conflist --logtostderr=false --alsologtostderr=true --log_file=/var/log/kube-ovn/kube-ovn-cni.log --log_file_max_size=200 --kubelet-dir=/var/lib/kubelet --enable-tproxy=true --ovs-vsctl-concurrency=100
kube-ovn版本为1.12.19，kata-container部署方式参考https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md
![image](https://github.com/user-attachments/assets/2920db58-996d-4e22-a745-5b106178cf81)
容器探针
![image](https://github.com/user-attachments/assets/7e5090ef-3b8a-4b0a-84ec-54399c84fbaf)
在pod中抓包
![image](https://github.com/user-attachments/assets/5d4df248-e6ae-4a52-a5f5-c7c132a6d908)
kube-ovn-cni日志
![image](https://github.com/user-attachments/assets/f4a0dc97-e8e1-49e6-8200-3820a382a9c8)
在kube-ovn-cni中抓包
![image](https://github.com/user-attachments/assets/da7347d1-a87f-4d3d-856a-283062b5870e)

**Comment by zhangzujian** [comment]
@changluyi 有时间看一下这个 tproxy 的问题。

**Comment by zhangzujian** [comment]
进 VM 对应的 Pod 内， curl 一下 Pod IP + 15021 端口，看能不能通。

**Comment by Volcano139** [comment]
> 进VM对应的Pod内，curl一下Pod IP + 15021端口，看能不能通。

在pod中，可以正常请求，在同一Subnet下的其他pod，也可以正常请求
![image](https://github.com/user-attachments/assets/5d7ae9fa-6e3b-4514-b485-6bb00192716b)

**Comment by Volcano139** [comment]
> > 进VM对应的Pod内，curl一下Pod IP + 15021端口，看能不能通。
> 
> 在pod中，可以正常请求，在相同子网下的其他pod中，也可以正常请求 ![图像](https://private-user-images.githubusercontent.com/59766572/365092162-5d7ae9fa-6e3b-4514-b485-6bb00192716b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTE5NzEsIm5iZiI6MTcyNTYxMTY3MSwicGF0aCI6Ii81OTc2NjU3Mi8zNjUwOTIxNjItNWQ3YWU5ZmEtNmUzYi00NTE0LWI0ODUtNmJiMDAxOTI3MTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4MzQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZDVhMDM3MTBiYjVjNTQxNzliNDhhYTRlZGQ3Y2RmNTYxMjQzZDQ5Njc2MmI2YmUyYzBhYmQ2MmFjNDBjZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._zvV1sg0XqpBpe9yAiLiFPPoJJcBND0QDxnxYRPScrg)

pod本身的探针端口也是15021

**Comment by Volcano139** [comment]
pod内另一个容器的探针端口为8080，kube-ovn通过15020代理，在Subnet下另一个pod可以正常请求
![image](https://github.com/user-attachments/assets/00df0f59-d8b5-43a7-98b8-3a30c4d9bd26)
![image](https://github.com/user-attachments/assets/535ec74e-e472-464c-be27-e5a787d13587)
