### ISSUE TITLE
[BUG] Statefulset 无法固定ip

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#4479]
### Kube-OVN Version

v1.11.10

### Kubernetes Version

v1.20.11

### Operation-system/Kernel Version

"CentOS Linux 7 (Core)"

### Description

Statefulset 无法固定ip

### Steps To Reproduce

k8s的两个node节点的containerd的存储路径路径磁盘超过85%，触发了pod的驱逐，然后pod在两台机器之见来回驱逐多次，才成功创建成功，然后发现StatefulSet的pod ip 发送了变化
日志如下
### I0905 07:09:12.056244       7 pod.go:1577] pod's ip  is not in the range of subnet subnet-ark-apisix-0, delete pod
根据1.11.10的代码发现1577行，ip没有取到所以导致，认为pod ip 不在子网范围内所以把pod的ips资源删掉了

```
	if podSubnet != nil && !util.CIDRContainIP(podSubnet.Spec.CIDRBlock, pod.Annotations[util.IpAddressAnnotation]) {
		klog.Infof("pod's ip %s is not in the range of subnet %s, delete pod", pod.Annotations[util.IpAddressAnnotation], podSubnet.Name)
		return true, nil
	}
```

### Current Behavior

无法固定住StatefulSet的ip

### Expected Behavior

固定住StatefulSet的ip

**Comment by bobz965** [comment]
升级下 1.11 到最新版试试呢？

**Comment by wolgod** [comment]
> 升级下 1.11 到最新版试试呢？

咱们有相关的升级步骤文档吗，毕竟是好几百台机器的线上机器，升级得慎重，也担心引入其他更严重bug
