### ISSUE TITLE
[BUG] 使用underlay方式安装失败

### ISSUE THREAD

**Issue by kinbod** [kubeovn/kube-ovn#4485]
### Kube-OVN Version

v1.12.22

### Kubernetes Version

v1.28.12

### Operation-system/Kernel Version

fedora server40  linux kernel 5.8

### Description

修改install.sh的参数ENABLE_VLAN=true;POD_CIDR=underlaycidr;POD_GATEWAY=underlaygateway其他参数没有动。然后安装。

### Steps To Reproduce

1.fedora server40  linux kernel 5.8 集群6个节点，三个master，三个node，使用sealos搭建的集群
2.修改install.sh的参数ENABLE_VLAN=true;POD_CIDR=underlaycidr;POD_GATEWAY=underlaygateway其他参数没有动

### Current Behavior

1.安装后卡在这里
![d1786a0912ef130709ef9f470bea139](https://github.com/user-attachments/assets/13ac6e13-8ef7-4337-85a0-4e3e5a70cc0d)
2.kube-ovn-cni无法正常启动
![0377cee281b72f812fdbaad83f86551](https://github.com/user-attachments/assets/5dd4a9f8-ab8d-41dd-902d-3886fcf2f9b0)
3.查看cni日志
![bb18c70da57921d7c1e0d3b6722dce5](https://github.com/user-attachments/assets/b5a37946-4b7a-40f7-83b1-8ebddee533a8)
4.默认子网
![71ccc45720a40afa7ae9187931ad5aa](https://github.com/user-attachments/assets/05565a3b-ecd4-4a7a-a0f0-5ae06809e85d)
5.cni在ping子网join的网关的时候无法ping通

### Expected Behavior

1.正常安装

**Comment by bobz965** [comment]
sealos 这个我不太熟悉，ovn-default 和 join 子网一开始创建出来就是图里面的 cidr么？

**Comment by kinbod** [comment]
> sealos 这个我不太熟悉，ovn-default 和 join 子网一开始创建出来就是图里面的 cidr么？

是的

**Comment by kinbod** [comment]
> Hey @kinbod, I'm here to help you with your Kube-OVN issue. Let's work together to solve this!
> 
> I found some similar closed issues that might help you resolve the problem:
> 
> 1. **[BUG] kube-ovn underlay模式下无法正常创建pod**: This issue was resolved by a pull request that modified the CNI server to not set sysctl variables [[1]](https://github.com/kubeovn/kube-ovn/issues/4394).
> 2. **1.11.3 underlay模式安装失败，pod无法正常通信**: This issue was resolved by enabling promiscuous mode on the virtual platform's vswitch network [[2]](https://github.com/kubeovn/kube-ovn/issues/2803).
> 3. **kube-ovn,controller和 cni的pod处于CrashLoopBackOff状态**: This issue was related to a CIDR conflict and was resolved by correcting the CIDR settings [[3]](https://github.com/kubeovn/kube-ovn/issues/2374).
> 
> For your specific issue, here are some steps and checks you can perform:
> 
> 1. **Ensure `CHECK_GATEWAY` is set to `false`**: Modify the `install.sh` script to set `CHECK_GATEWAY` to `false` to disable the gateway check, which might be causing the issue:
>    ```shell
>    CHECK_GATEWAY=${CHECK_GATEWAY:-false}
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Re-run the installation after making this change [[4]](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/install.sh).
> 2. **Verify `POD_CIDR` and `POD_GATEWAY` values**: Ensure that the `POD_CIDR` and `POD_GATEWAY` parameters are correctly set in the `install.sh` script. They should be in the correct format:
>    
>    * `POD_CIDR`: `"10.16.0.0/16"` for IPv4 or `"fd00:10:16::/112"` for IPv6.
>    * `POD_GATEWAY`: `"10.16.0.1"` for IPv4 or `"fd00:10:16::1"` for IPv6 [[5]](https://github.com/kubeovn/kube-ovn/blob/master/test/e2e/kube-ovn/underlay/underlay.go)[[6]](https://github.com/kubeovn/kube-ovn/blob/master/charts/kube-ovn/values.yaml)[[4]](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/install.sh).
> 3. **Check VLAN settings**: Since you have set `ENABLE_VLAN=true`, ensure that the VLAN settings are correctly configured in the `install.sh` script and `values.yaml` file:
>    ```shell
>    if [ "$ENABLE_VLAN" = "true" ]; then
>      NETWORK_TYPE="vlan"
>      ENABLE_EIP_SNAT=${ENABLE_EIP_SNAT:-false}
>      if [ "$VLAN_NIC" != "" ]; then
>        VLAN_INTERFACE_NAME="$VLAN_NIC"
>      fi
>    fi
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Ensure that the `VLAN_INTERFACE_NAME` and other VLAN-specific settings are correctly set in the `values.yaml` file [[4]](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/install.sh)[[6]](https://github.com/kubeovn/kube-ovn/blob/master/charts/kube-ovn/values.yaml).
> 4. **Network readiness checks**: The `kube-ovn-cni` component performs network readiness checks. Ensure that the ARP resolution or ping check for the gateway is successful. If the gateway is an IPv4 address and `underlayGateway` is true, the function attempts to resolve the MAC address of the gateway using ARP. For other types of gateways, it performs a ping check [[7]](https://github.com/kubeovn/kube-ovn/blob/master/pkg/daemon/ovs_linux.go).
> 
> By following these steps, you should be able to resolve the issue with the `kube-ovn-cni` component failing to start.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

还是安装不成功

**Comment by oilbeater** [comment]
join 子网应该是 overlay 的，这个不通可能是环境问题，这个环境是不是之前装过 kube-ovn 没有做清理

**Comment by kinbod** [comment]
> join 子网应该是 overlay 的，这个不通可能是环境问题，这个环境是不是之前装过 kube-ovn 没有做清理

这是自己本地的环境，这个要怎么清理呢？？？删除/etc/下面的cni,然后重启所有机器？？

**Comment by bobz965** [comment]
> > join 子网应该是 overlay 的，这个不通可能是环境问题，这个环境是不是之前装过 kube-ovn 没有做清理
> 
> 这是自己本地的环境，这个要怎么清理呢？？？删除/etc/下面的cni,然后重启所有机器？？

please refer: https://kubeovn.github.io/docs/v1.13.x/start/uninstall/

**Comment by kinbod** [comment]
嗯，是的，我删除的时候就是执行的这个脚本
________________________________
发件人: bobz965 ***@***.***>
发送时间: 2024年9月7日 13:09
收件人: kubeovn/kube-ovn ***@***.***>
抄送: Bodkin Quan ***@***.***>; Mention ***@***.***>
主题: Re: [kubeovn/kube-ovn] [BUG] 使用underlay方式安装失败 (Issue #4485)


join 子网应该是 overlay 的，这个不通可能是环境问题，这个环境是不是之前装过 kube-ovn 没有做清理

这是自己本地的环境，这个要怎么清理呢？？？删除/etc/下面的cni,然后重启所有机器？？

please refer: https://kubeovn.github.io/docs/v1.13.x/start/uninstall/

―
