### ISSUE TITLE
[Feature Request] 重新连接新的ovn-nb-db的leader节点后，全量拉取数据改为增量拉取monitor_cond_since

### ISSUE THREAD

**Issue by 15923218307** [kubeovn/kube-ovn#4519]
### Description

从 https://github.com/kubeovn/kube-ovn/pull/2627 修改历史中看到：源代码为增量拉取数据monitor_cond_since，但是此修改记录改为了全量拉取，但是我通过测试并没有发现此修改中描述的问题，想咨询一下当时是什么情况下产生的cache中缺少了数据了呢

**Comment by zhangzujian** [comment]
偶现的问题，原因不明。修改 monitor method 以后就没再遇到过了。
