### ISSUE TITLE
[Feature Request] 大规模节点下的性能优化问题

### ISSUE THREAD

**Issue by alin-code** [kubeovn/kube-ovn#4537]
### Description

2000物理节点下，3节点的南北向数据库独占物理机，在下发200000 pod时遇到下发缓慢的问题，南北向数据库会囤积大量数据，并且查询和更新变得异常缓慢，使用命令行调用还会出现oom的情况

我尝试理解了下ovsdb的源码，它看上去是事件驱动后单线程处理请求，这样的架构是否有优化的方向和空间

![image](https://github.com/user-attachments/assets/5b7055e2-1b63-4637-93d2-a8bdda2b578e)

![image](https://github.com/user-attachments/assets/114e052e-06f0-4e29-99ba-6bf4869d986a)

Thanks, alin

**Comment by zhangzujian** [comment]
> 我尝试理解了下ovsdb的源码，它看上去是事件驱动后单线程处理请求，这样的架构是否有优化的方向和空间

你指的是 ovsdb-server 还是 libovsdb？二者都不是我们开发维护的，建议你去对应的社区咨询讨论一下。

**Comment by alin-code** [comment]
> > 我尝试理解了下ovsdb的源码，它看上去是事件驱动后单线程处理请求，这样的架构是否有优化的方向和空间
> 
> 你指的是 ovsdb-server 还是 libovsdb？二者都不是我们开发维护的，建议你去对应的社区咨询讨论一下。

是ovsdb-server，在OVN社区也有issue，但暂未得到回复
