### ISSUE TITLE
[BUG] Initialization of nodes is too slow when adding new nodes or restarting kube-ovn-controller in a large-scale cluster

### ISSUE THREAD

**Issue by cmdy** [kubeovn/kube-ovn#4538]
### Kube-OVN Version

v1.12.21

### Kubernetes Version

v1.28.11

### Operation-system/Kernel Version

"CentOS Linux 7 (Core)"
6.6.35-2406.el7.bzl.x86_64

### Description

In large-scale cluster (node ​​1045, subnet 101), when adding nodes in batches, the node readiness time is too long. Through monitoring, we can see that the AddNode work queue latency has reached the hour level.
![image](https://github.com/user-attachments/assets/f8173940-b398-4c0a-9c84-3b3195698e04)

### Steps To Reproduce

1. add 1000+ node and 100+ subnet
2. restart kube-ovn-controller or continue to add more nodes

### Current Behavior

The time it takes to add a new node to be ready is too long

### Expected Behavior

New nodes are ready quickly

**Comment by wardahub-design** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by cmdy** [comment]
I found that there are many for loops in the code when processing Logical_Router_Policy And Port_Group。

In handleAddNode
``` golang
for _, subnet := range subnets {
        if (subnet.Spec.Vlan != "" && !subnet.Spec.LogicalGateway) || subnet.Spec.Vpc != c.config.ClusterRouter || subnet.Name == c.config.NodeSwitch || subnet.Spec.GatewayType != kubeovnv1.GWDistributedType {
            continue
        }
        if err = c.createPortGroupForDistributedSubnet(node, subnet); err != nil {
            klog.Errorf("failed to create port group for node %s and subnet %s: %v", node.Name, subnet.Name, err)
            return err
        }
        if err = c.addPolicyRouteForDistributedSubnet(subnet, node.Name, v4IP, v6IP); err != nil {
            klog.Errorf("failed to add policy router for node %s and subnet %s: %v", node.Name, subnet.Name, err)
            return err
        }
        // policy route for overlay distributed subnet should be reconciled when node ip changed
        c.addOrUpdateSubnetQueue.Add(subnet.Name)
    }

```

```golang
func (c *OVNNbClient) listLogicalRouterPoliciesByFilter(lrName string, filter func(route *ovnnb.LogicalRouterPolicy) bool) ([]*ovnnb.LogicalRouterPolicy, error) {
    klog.V(3).Infof("list logical router policy %s", lrName)
    start := time.Now()
    lr, err := c.GetLogicalRouter(lrName, false)
    if err != nil {
        klog.Error(err)
        return nil, err
    }
    policyList := make([]*ovnnb.LogicalRouterPolicy, 0, len(lr.Policies))

    for _, uuid := range lr.Policies {
        startPolicy := time.Now()
        policy, err := c.GetLogicalRouterPolicyByUUID(uuid)
        if err != nil {
            if errors.Is(err, client.ErrNotFound) {
                continue
            }
            return nil, err
        }
        if filter == nil || filter(policy) {
            policyList = append(policyList, policy)
        }
        if time.Since(startPolicy).Milliseconds() > 100 {
            klog.V(3).Infof("take to %vms get logical router policy %s lr policies len %v policy %v", time.Since(startPolicy).Milliseconds(), lrName, len(lr.Policies), policy)
        }
    }

    klog.V(3).Infof("take to %vms list logical router policy %s", time.Since(start).Milliseconds(), lrName)

    return policyList, nil
}
```
When the number of Logical_Router_Policy is  106744 ,I tested the processing time.
![image](https://github.com/user-attachments/assets/04c0a30e-5578-48e7-8b71-451b2a4e6675)

**Comment by cmdy** [comment]
> I found that there are many for loops in the code when processing Logical_Router_Policy And Port_Group。
> 
> In handleAddNode
> 
> ```go
> for _, subnet := range subnets {
>         if (subnet.Spec.Vlan != "" && !subnet.Spec.LogicalGateway) || subnet.Spec.Vpc != c.config.ClusterRouter || subnet.Name == c.config.NodeSwitch || subnet.Spec.GatewayType != kubeovnv1.GWDistributedType {
>             continue
>         }
>         if err = c.createPortGroupForDistributedSubnet(node, subnet); err != nil {
>             klog.Errorf("failed to create port group for node %s and subnet %s: %v", node.Name, subnet.Name, err)
>             return err
>         }
>         if err = c.addPolicyRouteForDistributedSubnet(subnet, node.Name, v4IP, v6IP); err != nil {
>             klog.Errorf("failed to add policy router for node %s and subnet %s: %v", node.Name, subnet.Name, err)
>             return err
>         }
>         // policy route for overlay distributed subnet should be reconciled when node ip changed
>         c.addOrUpdateSubnetQueue.Add(subnet.Name)
>     }
> ```
> 
> ```go
> func (c *OVNNbClient) listLogicalRouterPoliciesByFilter(lrName string, filter func(route *ovnnb.LogicalRouterPolicy) bool) ([]*ovnnb.LogicalRouterPolicy, error) {
>     klog.V(3).Infof("list logical router policy %s", lrName)
>     start := time.Now()
>     lr, err := c.GetLogicalRouter(lrName, false)
>     if err != nil {
>         klog.Error(err)
>         return nil, err
>     }
>     policyList := make([]*ovnnb.LogicalRouterPolicy, 0, len(lr.Policies))
> 
>     for _, uuid := range lr.Policies {
>         startPolicy := time.Now()
>         policy, err := c.GetLogicalRouterPolicyByUUID(uuid)
>         if err != nil {
>             if errors.Is(err, client.ErrNotFound) {
>                 continue
>             }
>             return nil, err
>         }
>         if filter == nil || filter(policy) {
>             policyList = append(policyList, policy)
>         }
>         if time.Since(startPolicy).Milliseconds() > 100 {
>             klog.V(3).Infof("take to %vms get logical router policy %s lr policies len %v policy %v", time.Since(startPolicy).Milliseconds(), lrName, len(lr.Policies), policy)
>         }
>     }
> 
>     klog.V(3).Infof("take to %vms list logical router policy %s", time.Since(start).Milliseconds(), lrName)
> 
>     return policyList, nil
> }
> ```
> 
> When the number of Logical_Router_Policy is 106744 ,I tested the processing time. ![image](https://private-user-images.githubusercontent.com/20875408/368949970-04c0a30e-5578-48e7-8b71-451b2a4e6675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDIwNzQsIm5iZiI6MTcyNjc0MTc3NCwicGF0aCI6Ii8yMDg3NTQwOC8zNjg5NDk5NzAtMDRjMGEzMGUtNTU3OC00OGU3LThiNzEtNDUxYjJhNGU2Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEwMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjUwNTEyYjgxNTg5ODNhMzVhY2E3YjFhODc3MTY4ZmZiNTY1Nzk1M2IwYTM2NzdhY2VhYmM4NzViYmI2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G_RkNoIZTUUIGnmligdvY6MOGMNy8XfPzWvFcNnEkwY)

I think this should be adjusted to WhereCache().List
```golang
    for _, uuid := range lr.Policies {
        startPolicy := time.Now()
        policy, err := c.GetLogicalRouterPolicyByUUID(uuid)
        if err != nil {
            if errors.Is(err, client.ErrNotFound) {
                continue
            }
            return nil, err
        }
        if filter == nil || filter(policy) {
            policyList = append(policyList, policy)
        }
        if time.Since(startPolicy).Milliseconds() > 100 {
            klog.V(3).Infof("take to %vms get logical router policy %s lr policies len %v policy %v", time.Since(startPolicy).Milliseconds(), lrName, len(lr.Policies), policy)
        }
    }
```

**Comment by zhangzujian** [comment]
Thanks for the information! Could you please try [this patch](https://github.com/kubeovn/kube-ovn/commit/89dacfa20d780ade9ed71bbea54671273c7649ae.patch)?

**Comment by cmdy** [comment]
> Thanks for the information! Could you please try [this patch](https://github.com/zhangzujian/kube-ovn/commit/ec26826cbff29e7085823cd3cd6ac2d53d23385f.patch) for the latest v1.12 version?

I have adjusted this method locally and tested it. I will merge [this patch](https://github.com/zhangzujian/kube-ovn/commit/ec26826cbff29e7085823cd3cd6ac2d53d23385f.patch) after testing.
