### ISSUE TITLE
[BUG] 1.11.20 kube-ovn cni failed to run

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#4540]
### Kube-OVN Version

v1.11.20

### Kubernetes Version

v1.31.0

### Operation-system/Kernel Version

6.8.0-41-generic

### Description

![image](https://github.com/user-attachments/assets/e598cd7e-4107-44e5-8565-67926d1e8202)

![image](https://github.com/user-attachments/assets/742d1950-bd1e-492b-a353-b38bee6f0c79)

![image](https://github.com/user-attachments/assets/fce0591d-ab98-49d3-8db7-93f35c6121c8)

### Steps To Reproduce

1.  make kind-init-ha
2. make kind-install

### Current Behavior

failed

### Expected Behavior

should ok

**Comment by zhangzujian** [comment]
Kernel with newer ipset versions is not supported in v1.11. Please use v1.12 or newer versions.
