### ISSUE TITLE
Access Kubernetes API Server Service from Custom VPC

### ISSUE THREAD

**Issue by tgdfool2** [kubeovn/kube-ovn#4554]
### Kube-OVN Version

v1.12.18

### Kubernetes Version

Client Version: v1.28.13
Server Version: v1.28.13

### Operation-system/Kernel Version

Ubuntu 22.04.4 LTS

### Description

Hi Everyone,

Is there a way to allow outgoing connections from a Custom VPC to the Kubernetes API Server? We are trying to deploy an Ingress Nginx controller in a Custom VPC and this fails, as the controller cannot connect to the Kubernetes API Server:
```
I0923 12:05:14.495376       7 main.go:205] "Creating API client" host="[https://10.96.0.1:443](https://10.96.0.1/)"
```

Any chance to get this connection working?

Thanks in advance for your help!

### Steps To Reproduce

1. Deploy Custom VPC as described under https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/vpc/, including `vpc-dns`
2. Deploy Ingress Nginx Helm Chart in VPC Namespace

### Current Behavior

Connection to Kubernetes API Server Service is not working from within VPC.

### Expected Behavior

Connection to Kubernetes API Server Service working from within VPC.

**Comment by tgdfool2** [comment]
The VPC NAT Gateway cannot reach the Kubernetes API Server Service:
```
nat-gw-0:/kube-ovn# nc -zv 10.96.0.1 443
Timeout!
```

Also, there is no specific route configured in the VPC NAT Gateway that would target the Kubernetes API Server Service:
```
nat-gw-0:/kube-ovn# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.203.200.193  0.0.0.0         UG    0      0        0 net1
10.96.0.0       100.105.0.1     255.255.0.0     UG    0      0        0 eth0
10.203.200.192  0.0.0.0         255.255.255.224 U     0      0        0 net1
100.105.0.0     0.0.0.0         255.255.0.0     U     0      0        0 eth0
```

**Comment by SkalaNetworks** [comment]
Yes, sorry about that, I was copying runtime configuration from a cluster where my range is 100.100.0.0/16, considering the /24 subnet will only allow for 254 pods to access the API before you need to make a new range

**Comment by tgdfool2** [comment]
Hi @SkalaNetworks,

I did some tests with a custom Pod (not Ingress Controller) and this seems to work fine, thank you very much for your help!

I'm now going to test with the deployment of the Ingress Controller.

**Comment by tgdfool2** [comment]
Everything working as expected with the Ingress Controller deployment. Thanks again for your help @SkalaNetworks.
