### ISSUE TITLE
[BUG] sometimes' pod always being status of ContainterCreating when set inactivityTimeout

### ISSUE THREAD

**Issue by changluyi** [kubeovn/kube-ovn#4560]
### Kube-OVN Version

1.12.25

### Kubernetes Version

1.30

### Operation-system/Kernel Version

3.10.0-1160.el7.x86_64

### Description

kube-ovn-controller get a log like this， the pod gets the allocated IP, and then hang,  the handleAddOrUpdatePod function will never exist
![image](https://github.com/user-attachments/assets/2015cd8a-c4f8-43c1-84b3-a4f80b7c8134)

### Steps To Reproduce

I don't know how to reproduce

### Current Behavior

pod is always being in status of `ContainerCreating`

### Expected Behavior

pod is created successfully

**Comment by bobz965** [comment]
是不是什么锁竞争导致的呀？

**Comment by changluyi** [comment]
![image](https://github.com/user-attachments/assets/8b4399a9-a73e-43cb-8fa0-21defbf70aca)
目前追溯到是inactivityProbe开了后，这个锁hang住了

**Comment by changluyi** [comment]
目前追溯到rpclient的问题，在这两个位置都能hang住。
![image](https://github.com/user-attachments/assets/3bcfc326-21ee-42f2-ae0d-ef99b9438268)
![image](https://github.com/user-attachments/assets/7c57d0bb-e811-4646-ad81-728501580962)

**Comment by zbb88888** [comment]
我们准备加点log等复现，手动复现不了

**Comment by cmdy** [comment]
我在1.13版本也发现了这个问题，当leader切换后会偶发卡住的情况
`goroutine 966 [sync.RWMutex.Lock, 195 minutes]:
sync.runtime_SemacquireRWMutex(0x55587a3d1b32?, 0x60?, 0xc0014a3fc0?)
	runtime/sema.go:105 +0x25
sync.(*RWMutex).Lock(0xc009bb23d8?)
	sync/rwmutex.go:153 +0x6a
github.com/ovn-org/libovsdb/client.(*ovsdbClient).watchForLeaderChange.func2()
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:1160 +0x1a5
created by github.com/ovn-org/libovsdb/client.(*ovsdbClient).watchForLeaderChange in goroutine 375
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:1133 +0x2cd  `
`goroutine 3303704 [chan send, 195 minutes]:
github.com/ovn-org/libovsdb/client.(*ovsdbClient).watchForLeaderChange.func1({0x55587c4c75ca?, 0xc02a55a798?}, {0xc02a55a700?, 0x55587a3d7530?}, {0x55587d6a3cc0, 0xc00b4d9da0})
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:1116 +0x45
github.com/ovn-org/libovsdb/cache.(*EventHandlerFuncs).OnUpdate(0xc02a55a770?, {0x55587c4c75ca?, 0x1e19e30?}, {0x55587d6a3cc0?, 0xc01b054d80?}, {0x55587d6a3cc0?, 0xc00b4d9da0?})
	github.com/ovn-org/libovsdb@v0.7.0/cache/cache.go:817 +0x48
github.com/ovn-org/libovsdb/cache.(*eventProcessor).Run(0xc0075723c0, 0xc00feff650)
	github.com/ovn-org/libovsdb@v0.7.0/cache/cache.go:1167 +0x24b
github.com/ovn-org/libovsdb/cache.(*TableCache).Run.func1()
	github.com/ovn-org/libovsdb@v0.7.0/cache/cache.go:1040 +0x4f
created by github.com/ovn-org/libovsdb/cache.(*TableCache).Run in goroutine 3303703
	github.com/ovn-org/libovsdb@v0.7.0/cache/cache.go:1038 +0x99`
`goroutine 3303699 [sync.RWMutex.RLock, 195 minutes]:
sync.runtime_SemacquireRWMutexR(0x7f20b02d15b8?, 0x18?, 0xc02d8ce0d0?)
	runtime/sema.go:100 +0x25
sync.(*RWMutex).RLock(...)
	sync/rwmutex.go:72
github.com/ovn-org/libovsdb/client.(*ovsdbClient).sendEcho(0xc009bb2380, {0xc021ce4200, 0x2, 0x2}, 0xc02b145350)
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:1213 +0x75
github.com/ovn-org/libovsdb/client.(*ovsdbClient).handleInactivityProbes(0xc009bb2380)
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:1251 +0x325
created by github.com/ovn-org/libovsdb/client.(*ovsdbClient).connect in goroutine 3119720
	github.com/ovn-org/libovsdb@v0.7.0/client/client.go:319 +0xd19`

追踪堆栈信息，确实是指向了 `call := o.sendEcho(args, &reply)`

![Image](https://github.com/user-attachments/assets/4e22dc2d-d584-4654-975b-08c3bcec453f)
