### ISSUE TITLE
[BUG] underlay provider-network nic providerd by team will be down， when kube-ovn-cni restart.

### ISSUE THREAD

**Issue by changluyi** [kubeovn/kube-ovn#4622]
### Kube-OVN Version

1.13.0

### Kubernetes Version

1.30

### Operation-system/Kernel Version

3.10.0-1160.80.1.el7.x86_64

### Description

underaly team nic  will set down 

### Steps To Reproduce

underlay team nic config by below:
nmcli co add type team con-name team1 ifname team1 team.runner lacp team.link-watchers name=ethtool ipv4.method link-local
nmcli co add type team-slave con-name team1-enp175s0f0 ifname enp175s0f0 master team1
nmcli co add type team-slave con-name team1-enp175s0f1 ifname enp175s0f1 master team1
ip link set dev team1 up

and then deploy underlay subnet

### Current Behavior

underlay nic state set down

### Expected Behavior

underlay nic state should be up

**Comment by bobz965** [comment]
这个问题好像之前我们修改过，当时的处理策略是， kube-ovn 这边不要处理 nmcli 管理的网卡

**Comment by changluyi** [comment]
> 这个问题好像之前我们修改过，当时的处理策略是， kube-ovn 这边不要处理 nmcli 管理的网卡

是的 打算做一个判断 team网卡别unmanage

**Comment by changluyi** [comment]
![企业微信截图_1729061364984](https://github.com/user-attachments/assets/e2970c1d-08cf-4cd0-9fc0-32f5f1c1cf7f)
