### ISSUE TITLE
2 node HA with OVN DB Availability 

### ISSUE THREAD

**Issue by kannanvr** [kubeovn/kube-ovn#4631]
### Kube-OVN Version

1.12.26

### Kubernetes Version

1.27.10

### Operation-system/Kernel Version

5.15.0

### Description

We have a setup like 2 node HA kubernetes. We are not using etcd to bring up the cluster. Rather we are using the postgres with kine to achieve HA with 2 node. We have a keepalived component with VIP which help us to promote the master postgres DB when some reboot happens.

Now when we install kube-ovn with this 2 node HA k8s setup, we are facing the issue. When any of the node goes down OVN-DB/OVN-CEBTRAL NB and SB database is not coming up. Hence OVN central pod is restarting and the new pod on 1 available node doesn't get any IP address.

It seems OVN-DB/OVN-CENTRAL is using raft consensus algorithm. Is it possible to use active passive way of connection ? Or any way to solve this case with VIP from keepalived.

Please help us to provide your valuable feedback on the issue.

### Steps To Reproduce

Install 2 node HA 
Shutdown one of the node
Bring up the new pod
It doesn't get ip

### Current Behavior

When node goes down , new pod is not allocated with IP due to DB ISSUE

### Expected Behavior

When node goes down , new pod is allocated with IP due to DB ISSUE

**Comment by oilbeater** [comment]
To change to active-backup mode, significant modifications are required for the current ovn-central startup and deployment. We do not recommend this approach. If your scenario necessitates achieving high availability in a two-node setup, you can refer to the ovsdb documentation for modifications: [OVSDB Documentation](https://ovn-org.readthedocs.io/en/latest/ref/ovsdb.7.html#service-models).

**Comment by kannanvr** [comment]
Thanks!!!. It works
