### ISSUE TITLE
[Feature Request] Block ARP on a subnet

### ISSUE THREAD

**Issue by SkalaNetworks** [kubeovn/kube-ovn#4652]
### Description

I have a subnet with public IPs getting allocated by Kube-OVN's IPAM automatically to Kubevirt VMs.
Those VMs have an interface directly plugged on that subnet. IPs are routed to VMs using BGP.
In this setup, I do not need ARP. ARP could be used for poisoning and spoofing, allowing VMs to redirect traffic to them.
I don't think there' any way to do that right now (I'm happy if there is)

### Who will benefit from this feature?

People using Kube-OVN with Kubevirt

**Comment by zhangzujian** [comment]
How can VMs/Pods connect to each other if ARP is disabled/blocked? By adding static records into the arp/neighbor table?

**Comment by SkalaNetworks** [comment]
@zhangzujian one way is to do it statically, another way is blocking ARP responses that are malicious (responding to ARP requests when you do not own the IP address) and preventing responses with faulty MACs

Basically, PortSecurity as it exists on OpenStack. Basic port ACL to make sure the ARP responses coming out of an interface are legitimate.

I know there's an annotation called port_security on Kube-OVN but the doc says that:

> Pods bind security-groups by adding annotations, two annotations are used.
>    port_security: source address verification. If this function is enabled, only packets with ip addresses assigned by kube-ovn ipam can be exported from the pod network adapter. After this function is disabled, any ip address can be exported

This is only an L3 verification. Obviously, on a subnet shared by many VMs, ARP poisoning would be an even bigger danger. This securitygroup annotation would be a prime candidate if we're looking at where to implement that check.

**Comment by zhangzujian** [comment]
PortSecurity implemented in Kube-OVN includes pod ips, vips and MAC. So I believe it is just what you need.

**Comment by SkalaNetworks** [comment]
The documentation doesn't mention that, was it just omitted by mistake? If yes, I'll amend the docs.

**Comment by zhangzujian** [comment]
> The documentation doesn't mention that, was it just omitted by mistake?

Yes. The document need to be updated.

**Comment by SkalaNetworks** [comment]
https://github.com/kubeovn/kube-ovn/issues/4652 fixes this
