### ISSUE TITLE
[Feature Request] kube-ovn live migration function optimization

### ISSUE THREAD

**Issue by changluyi** [kubeovn/kube-ovn#4740]
### Description

The current version of kube-ovn optimization requires modifying the kubevirt code, so I hope there is a way to optimize the interruption time of live migration without modifying kubevirt.

origin pr：
https://github.com/kubeovn/kube-ovn/issues/3472 
https://github.com/kubeovn/kube-ovn/pull/3767

**Comment by changluyi** [comment]
![热迁移 drawio (1)](https://github.com/user-attachments/assets/99926ae9-32dc-4a9f-a6a1-d157d1e9b337)

**Comment by changluyi** [comment]
目前打算让kube-ovn 直接去监听vmiMigration 这个CR的状态，来变更kube-ovn的lsp配置。

**Comment by bobz965** [comment]
`监听vmiMigration 这个CR`: 如果可以的话，当然是更好的，我们一开始没有发现 kubeovn 中有监听 kubevirt 资源的代码，所以没有考虑这个。

后续，如果可以监听 vm 或者 vmi 的话，是不是有些 ip 回收的逻辑也会变得更简单，以及监听 sts。

**Comment by oilbeater** [comment]
改 kubevirt 的代码很难和上游合并，不如把网络相关的逻辑优化放在 kube-ovn 的代码里

**Comment by bobz965** [comment]
> 改 kubevirt 的代码很难和上游合并，不如把网络相关的逻辑优化放在 kube-ovn 的代码里

ok
