### ISSUE TITLE
[BUG] 设置多网卡macvlan的ip和mac，但macvlan的mac设置不

### ISSUE THREAD

**Issue by thomasnew** [kubeovn/kube-ovn#4834]
### Kube-OVN Version

v1.13.1

### Kubernetes Version

v1.28.15

### Operation-system/Kernel Version

ubuntu 22.04 64bit

### Description

![macvlan_mac](https://github.com/user-attachments/assets/e556fea7-66f8-488f-adbd-d1f31f828d2a)

上图为官网手册里的配置图，https://kubeovn.github.io/docs/stable/advance/multi-nic/

### Steps To Reproduce

如图所示，就按照官网上设置kubeovn和macvlan双网卡，指定ip和mac地址。
其中 kubeovn的ip和mac 都生效，macvlan的ip也生效，但mac不生效（系统随机生成了一个）

### Current Behavior

macvlan对应的网卡net1 的mac地址未按照预期设置。

### Expected Behavior

期望使用指定的mac地址

**Comment by zhangzujian** [comment]
Please refer to https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/examples/macvlan-pod.yml

**Comment by zhangzujian** [comment]
`tuning` plugin is not required since `macvlan` supports `mac` capability too.

**Comment by thomasnew** [comment]
> `tuning` plugin is not required since `macvlan` supports `mac` capability too.

My test show that the [ "type": "tuning" ] is must. otherwise will report failed.

Thank you for your help and issue is resolved.
