### ISSUE TITLE
[BUG] ingress annotations设置后未生效

### ISSUE THREAD

**Issue by dolibali** [kubeovn/kube-ovn#4867]
### Kube-OVN Version

v1.14.0

### Kubernetes Version

v1.21.5

### Operation-system/Kernel Version

bclinux21.10 4.19.90-2107.6.0.0192.8 x86

### Description
两个测试pod：netshoot2和netshoot3，用iperf3打流
client: netshoot2
server: netshoot3
![image](https://github.com/user-attachments/assets/76be2a1e-746a-439b-b3c9-9f1964b052bd)
正常带宽：
![image](https://github.com/user-attachments/assets/fbca80e8-7a80-4861-928c-a35ad615ef20)

修改client pod 的 ingress_rate
![image](https://github.com/user-attachments/assets/e4c69ae9-05e4-43b2-b885-5943eaab1d47)
带宽被限制为1Gbps，为ingress_rate值的1000倍
![image](https://github.com/user-attachments/assets/6a68ef99-78cd-4f0d-ac45-c866a33029c9)
限速队列和qos信息
![image](https://github.com/user-attachments/assets/ca231042-1ed4-42d8-895e-43d49feb3aec)
![image](https://github.com/user-attachments/assets/19b2d9c4-8b2b-418a-9803-88450849ba03)

配置不变角色互换后
client: netshoot3
server: netshoot2
![image](https://github.com/user-attachments/assets/fa28b428-37d6-4bd1-b58a-638aaf573722)
带宽被限制为1Mbps，符合ingress限速逻辑和数值

总结
pod的ingress设置限制了出口流量的带宽？且与ingress_rate值有1000倍的关系，不明白原理

### Steps To Reproduce

1.同节点创建两个netshoot pod，ovn-default网络
2.iperf工具打流
3.发送方pod anntations中添加：ovn.kubernetes.io/ingress_rate: "1"

**Comment by bobz965** [comment]
@oilbeater 可能某种场景有点小问题，应该影响不大。如果用户设置 QoS 较小的话，可能会比较明显，比如 kb 级别，放大后反方向的限制可能是1mb。
