### ISSUE TITLE
[BUG] OVN monitoring page in grafana missed two nodes.

### ISSUE THREAD

**Issue by thomasnew** [kubeovn/kube-ovn#4870]
### Kube-OVN Version

v1.13.1

### Kubernetes Version

v.1.32.0-rc.2

### Operation-system/Kernel Version

ubuntu 22.04

### Description

I build a k8s cluster with 3 master .
create promethues and grafana config from kubeovn website.

![image](https://github.com/user-attachments/assets/0722dee2-2542-4fc8-9813-9c7c8d881555)

ko cmd check the nb/sb status OK.
![image](https://github.com/user-attachments/assets/f4c3b388-6327-4918-a0d4-d794ae20176a)
![image](https://github.com/user-attachments/assets/87cfcb9c-191f-48ac-a2c3-3d2ad7283960)

### Steps To Reproduce

1 build k8s cluster with 3 master nodes
2 config promethues and grafana according to the kubeovn website, https://kubeovn.github.io/docs/stable/guide/prometheus-grafana/
3 check the grafana web page, select kube-ovn/OVN page , and check the instance LIST.

### Current Behavior

only list one node, which is nb master.

### Expected Behavior

expect to get 3 nodes from the list.

**Comment by oilbeater** [comment]
You need to scale the kube-ovn-monitor deployment replicas to 3 and located them on the ovn-central nodes.

**Comment by thomasnew** [comment]
> You need to scale the kube-ovn-monitor deployment replicas to 3 and located them on the ovn-central nodes.

@oilbeater , thank you. I tried and it works well. 
I'll close this issue.

**Comment by thomasnew** [comment]
close
