### ISSUE TITLE
两个内网不相通的服务器组网后,不同节点中的容器无法互相访问,请问应该怎么做才能让他们可以互相访问

### ISSUE THREAD

**Issue by liqiaoyang-pm** [kubeovn/kube-ovn#4872]
### Kube-OVN Version

v1.12.21

### Kubernetes Version

v1.31.2

### Operation-system/Kernel Version

"Ubuntu 24.04 LTS"

### Description

使用两台不同的云厂商的服务器组建k8s后使用kube-ovn组网,发现无法组网成功,如果是我的设置错误,请告诉我正确的方式

### Steps To Reproduce

ovsdb-server is running with pid 1000710
ovs-vswitchd is running with pid 1000866
iptables v1.8.7 (legacy)
I1225 09:35:39.605903 1027571 cniserver.go:35]
-------------------------------------------------------------------------------
Kube-OVN:
Version: v1.12.21
Build: 2024-08-13_14:29:04
Commit: git-d4692df
Go Version: go1.22.6
Arch: amd64
-------------------------------------------------------------------------------
I1225 09:35:39.615083 1027571 config.go:172] node name not specified in command line parameters, fall back to the environment variable
I1225 09:35:39.615106 1027571 config.go:350] no --kubeconfig, use in-cluster kubernetes config
I1225 09:35:39.647558 1027571 k8s.go:42] succeeded to dial host "https://10.152.183.1:443"
I1225 09:35:39.698164 1027571 config.go:190] daemon config: &{ eth0 br-phy 1400 1360 false mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock 0xc000007dc0 0xc0000618a0 microk8s-01-worker 10.152.183.0/24 ovn-cluster join true false false 10665 false geneve /etc/cni/net.d /kube-ovn/01-kube-ovn.conflist 01-kube-ovn.conflist provider kube-system external true true /var/snap/microk8s/current/var/lib/kubelet false 8100 8101 false 100}
I1225 09:35:39.725384 1027571 cniserver.go:55] init node gw
I1225 09:35:39.752045 1027571 ovs_linux.go:470] wait ovn0 gw ready
W1225 09:35:42.752724 1027571 ovs.go:34] 100.64.0.3 network not ready after 3 ping to gateway 100.64.0.1
W1225 09:35:45.752431 1027571 ovs.go:34] 100.64.0.3 network not ready after 6 ping to gateway 100.64.0.1
W1225 09:35:48.753148 1027571 ovs.go:34] 100.64.0.3 network not ready after 9 ping to gateway 100.64.0.1
W1225 09:35:51.753116 1027571 ovs.go:34] 100.64.0.3 network not ready after 12 ping to gateway 100.64.0.1
W1225 09:35:54.752954 1027571 ovs.go:34] 100.64.0.3 network not ready after 15 ping to gateway 100.64.0.1
W1225 09:35:57.753552 1027571 ovs.go:34] 100.64.0.3 network not ready after 18 ping to gateway 100.64.0.1
W1225 09:36:00.753061 1027571 ovs.go:34] 100.64.0.3 network not ready after 21 ping to gateway 100.64.0.1
W1225 09:36:03.753214 1027571 ovs.go:34] 100.64.0.3 network not ready after 24 ping to gateway 100.64.0.1
W1225 09:36:06.753402 1027571 ovs.go:34] 100.64.0.3 network not ready after 27 ping to gateway 100.64.0.1
W1225 09:36:09.753455 1027571 ovs.go:34] 100.64.0.3 network not ready after 30 ping to gateway 100.64.0.1
W1225 09:36:12.752627 1027571 ovs.go:34] 100.64.0.3 network not ready after 33 ping to gateway 100.64.0.1
W1225 09:36:15.753455 1027571 ovs.go:34] 100.64.0.3 network not ready after 36 ping to gateway 100.64.0.1
W1225 09:36:18.752615 1027571 ovs.go:34] 100.64.0.3 network not ready after 39 ping to gateway 100.64.0.1
W1225 09:36:21.752934 1027571 ovs.go:34] 100.64.0.3 network not ready after 42 ping to gateway 100.64.0.1
W1225 09:36:24.752563 1027571 ovs.go:34] 100.64.0.3 network not ready after 45 ping to gateway 100.64.0.1
W1225 09:36:27.753398 1027571 ovs.go:34] 100.64.0.3 network not ready after 48 ping to gateway 100.64.0.1

### Current Behavior

无法组网成功

### Expected Behavior

可以组网成功

**Comment by bobz965** [comment]
需要底层组网成功：两个物理机之间的隧道网卡是通的

**Comment by liqiaoyang-pm** [comment]
@bobz965 谢谢你的回答，但是可以说的更加详细一点吗，具体应该如何操作才能让他组网成功，感谢🙏

**Comment by bobz965** [comment]
两个物理机的同一个业务网卡在同一个vlan子网中。

**Comment by liqiaoyang-pm** [comment]
@bobz965 用kube-ovn可以实现吗

**Comment by bobz965** [comment]
> @bobz965 用kube-ovn可以实现吗

kube-ovn 只是一个应用，依赖于底层，物理机上不通没办法的
