### ISSUE TITLE
Support for windows nodes？

### ISSUE THREAD

**Issue by xmapst** [kubeovn/kube-ovn#52]
Support windows nodes to access k8s cluster through openvswitch?

**Comment by oilbeater** [comment]
Though kube-ovn now doesn't support windows nodes. OVN itself does support windows platform. We will modify the installation scripts and test windows connectivity in future.

**Comment by xmapst** [comment]
现在支持了么，有时间线吗

**Comment by oilbeater** [comment]
@xmapst 目前还没有计划，能介绍一下你们的场景和具体需求么，我们可以再安排

**Comment by oilbeater** [comment]
@xmapst 我们目前正在调研 windows 相关的支持，能不能介绍一下你们的场景（windows 版本，运行什么类型的应用，对网络有什么要求，等等），我们可以针对需求在具体排功能

**Comment by ylhyh** [comment]
> @xmapst 我们目前正在调研 windows 相关的支持，能不能介绍一下你们的场景（windows 版本，运行什么类型的应用，对网络有什么要求，等等），我们可以针对需求在具体排功能
@oilbeater 
我们有需求在Liunux集群里加入Windows节点, 在Kubernetes中组合包括Linux和Windows节点的混合集群, 因为有些应用是从Windows 单体应用迁移到Windows容器环境的, 只能运行在Windows节点中。这些应用一般是基于mcr.microsoft.com/windows/servercore的基础镜像

**Comment by oilbeater** [comment]
with v1.10.0 we finally support Windows nodes
