### ISSUE TITLE
OVN support set ipv6 address in logical switch exclude_ips filed?

### ISSUE THREAD

**Issue by feixiang43** [kubeovn/kube-ovn#581]
Hi guys I found a bug in my environment, when I set ipv6 address in logical switch other_config:exclude_ips, northd  will print follow messages: 
04T11:46:01.426Z|00027|ovn_northd|WARN|logical switch 33c578c1-6538-4e51-9a39-add71eb53d42: bad exclude_ips (excluded addresses not in subnet)
I'm not sure it was a common case, just FYI.

**Comment by oilbeater** [comment]
`other_config:exclude_ips` is not used anymore.
