### ISSUE TITLE
Questions of OVS-DPDK features.

### ISSUE THREAD

**Issue by ftiannew** [kubeovn/kube-ovn#597]
Hi, I am still confused by the OVS-DPDK features.
1.does it setup an OVS-DPDK bridge in each node ? 
2. does it just assign a vhost-user port to the pod when required ?
3. any physical NIC needed for the DPDK bridge. if not, how to perform the intra-nodes communication between the vhost-user ports ?    
4. is it possible to run a VPP application upon the vhost-user port ?
will appreciated your response.
thanks
/tian

**Comment by oilbeater** [comment]
@garyloug can you help with these questions?

**Comment by feixiang43** [comment]
2. As I know kube-ovn will create a socket file in host and no interface is create in pod. You can mount socket file directory into pod and read/write with socket.
