### ISSUE TITLE
after add networkpolicy ,cannot  access nodeport workload

### ISSUE THREAD

**Issue by inspur-wyd** [kubeovn/kube-ovn#661]
after add networkpolicy ,cannot  access nodeport workload
the ovn-controller log:

![image](https://user-images.githubusercontent.com/32732410/105973090-49ed9f00-60c7-11eb-97a7-07fab72cece5.png)

**Comment by oilbeater** [comment]
If set networkpolicy only pod and address in `ingress->from` can access the pod. Nodeport is not allowed to access the pod.

**Comment by zhugejingcheng** [comment]
> If set networkpolicy only pod and address in `ingress->from` can access the pod. Nodeport is not allowed to access the pod.

why,when cni is calico,nodeport is allowed to access the pod.

**Comment by smnblt** [comment]
could this be releated to #792 ?

**Comment by hongzhen-ma** [comment]
@inspur-wyd The #792 has been closed. So can you have a try for this issue with the latest release version？
