### ISSUE TITLE
create custom VPC lead to kube-ovn csi down

### ISSUE THREAD

**Issue by zhugejingcheng** [kubeovn/kube-ovn#672]
1、first create custom VPC 
2、then  create subnet  bind to the VPC (the cidr not used at any pvc) with namespce
3、then create namespace
4、then create deploy 
5、then update custom vpc cidr to ovn-default cidr
6、then delete pod
7、 after a few minutes ,kube-ovn csi down 
8、restart the machine, the kube-ovn-controller log 
![image](https://user-images.githubusercontent.com/32732410/106875607-d32d5300-6711-11eb-8865-a870665c3ab5.png)

**Comment by oilbeater** [comment]
@fanriming can you take a look?

**Comment by fanriming** [comment]
@zhugejingcheng 
The log says "cannot change the subnet to a single protocol", which appears to be a DualStack issue.
Please paste out the YAML of VPC Subnet and Deployment. And, which kube-ovn version are you testing on?

**Comment by hongzhen-ma** [comment]
https://github.com/kubeovn/kube-ovn/pull/707
