### ISSUE TITLE
serviceaccount:kube-system:ovn" cannot get resource ovn-vpc-external-network

### ISSUE THREAD

**Issue by hongzhen-ma** [kubeovn/kube-ovn#735]
I0406 08:50:27.098033       1 external-gw.go:35] start to remove ovn external gw
I0406 08:50:27.098197       1 vpc_nat_gateway.go:61] start to clean up vpc nat gateway
I0406 08:50:27.103798       1 endpoint.go:97] update endpoint kube-system/kube-ovn-monitor
I0406 08:50:27.119884       1 endpoint.go:97] update endpoint kube-system/kube-ovn-pinger
W0406 08:50:27.137915       1 vpc_nat_gateway.go:782] failed to get net-attach-def, network-attachment-definitions.k8s.cni.cncf.io "ovn-vpc-external-network" is forbidden: User "system:serviceaccount:kube-system:ovn" cannot get resource "network-attachment-definitions" in API group "k8s.cni.cncf.io" in the namespace "kube-system"
I0406 08:50:27.137964       1 vpc_nat_gateway.go:73] finish clean up vpc nat gateway

![image](https://user-images.githubusercontent.com/67130442/113691314-e1422480-96fe-11eb-8016-688c6470743a.png)

**Comment by fanriming** [comment]
@hongzhen-ma Fixed in another PR
https://github.com/kubeovn/kube-ovn/pull/718/commits/5251c2722310f89573337151d166a83d2e5232a1
