### ISSUE TITLE
apiserver闭环依赖

### ISSUE THREAD

**Issue by sccblue** [kubeovn/kube-ovn#750]
复现场景
运行中的node故意reboot，cni插件整体就有问题了，原因是到apiserver的LB（cluster）ip不通导致的
而这个LB又依赖CNI插件先起来，循环依赖了
具体看微信群的讨论（刚刚部署完和reboot后的截图以及对应的log都在群里）

**Comment by sccblue** [comment]
更新具体场景：有kube-proxy情况下，Node节点reboot后是无法自恢复的，是需要手工强制将那些pod（在那个reboot的Node）全部delete一遍才能自恢复

**Comment by oilbeater** [comment]
fixed https://github.com/kubeovn/kube-ovn/pull/838
