### ISSUE TITLE
install.sh一键安装脚本的bug

### ISSUE THREAD

**Issue by hugo345816** [kubeovn/kube-ovn#773]
在应用vlan-underlay网络时，我用一键安装脚本install.sh安装kube-ovn时，按照[官方文档](https://github.com/kubeovn/kube-ovn/wiki/Underlay-%E7%BD%91%E7%BB%9C%E6%94%AF%E6%8C%81)的指导部署，发现最终新建的pod（用默认的ovn-default网络）无法与外部通讯。
经过排查，发现是网关不对。
因为我是用vmware模拟的集群，所以网络不是默认的xxx.xxx.xxx.1，而是xxx.xxx.xxx.2。
官方WIKI有提到要设置 `POD_GATEWAY           设置为物理网络网关，例如192.168.1.1`
但是实际上在install.sh中并没有用到这个变量，对比官方的 [kube-ovn.yam](https://github.com/kubeovn/kube-ovn/blob/master/yamls/kube-ovn.yaml) 文档，发现在 kube-ovn-controller 处有一个定义 `- --default-gateway=10.16.0.1`
于是用kubectl edit subnet ovn-default的方式修改网关为 xxx.xxx.xxx.2，问题解决。

问题就是 install.sh 脚本中并没有用到wiki中提到的POD_GATEWAY这个变量。

**Comment by xieyanker** [comment]
最新的脚本里是有这个变量的：

https://github.com/kubeovn/kube-ovn/blob/9354cf98a231415d0878f13560386755a47cfcb4/dist/images/install.sh#L18
