### ISSUE TITLE
pod kube-ovn-cni-k2fph has panic logs if we upgrade kube-ovn from v1.6.0 to v1.6.2

### ISSUE THREAD

**Issue by sicheng216** [kubeovn/kube-ovn#789]
I0507 06:29:07.465410   27138 server.go:62] [2021-05-07T06:29:07Z] Incoming HTTP/1.1 POST /api/v1/del request
I0507 06:29:07.465496   27138 handler.go:218] delete port request {virt-handler-lcxsg kubevirt dbc9ec26ed34f76725367b12fe9f7ce07aa9d915206597b1dd12c5c22b074290   ovn }
2021/05/07 06:29:07 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 15539 [running]:
net/http.(*conn).serve.func1(0xc00036caa0)
	/home/sicheng/go16/src/net/http/server.go:1824 +0x153
panic(0x1a6e9e0, 0x2b2bcc0)
	/home/sicheng/go16/src/runtime/panic.go:971 +0x499
github.com/alauda/kube-ovn/pkg/daemon.cniServerHandler.handleDel(0xc000176300, 0x1fb32d8, 0xc00047e9a0, 0x1f4f9f0, 0xc0000c7a90, 0xc00057c160, 0xc000628810, 0xc0002f4460)
	/home/sicheng/kube-ovn/pkg/daemon/handler.go:220 +0x8d2
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0006288a0, 0xc000628810, 0xc0002f4460)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/filter.go:21 +0x8c
github.com/alauda/kube-ovn/pkg/daemon.requestAndResponseLogger(0xc000628810, 0xc0002f4460, 0xc0006288a0)
	/home/sicheng/kube-ovn/pkg/daemon/server.go:64 +0xd2
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0006288a0, 0xc000628810, 0xc0002f4460)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/filter.go:19 +0x66
github.com/emicklei/go-restful.(*Container).dispatch(0xc0005b85a0, 0x1f80cd0, 0xc0005ba540, 0xc000e56600)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/container.go:282 +0x813
net/http.HandlerFunc.ServeHTTP(0xc0002f10b0, 0x1f80cd0, 0xc0005ba540, 0xc000e56600)
	/home/sicheng/go16/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000543f00, 0x1f80cd0, 0xc0005ba540, 0xc000e56600)
	/home/sicheng/go16/src/net/http/server.go:2448 +0x1ad
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0005b85a0, 0x1f80cd0, 0xc0005ba540, 0xc000e56600)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/container.go:300 +0x4d
net/http.serverHandler.ServeHTTP(0xc0000161c0, 0x1f80cd0, 0xc0005ba540, 0xc000e56600)
	/home/sicheng/go16/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00036caa0, 0x1f84df8, 0xc000e6c380)
	/home/sicheng/go16/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/home/sicheng/go16/src/net/http/server.go:3013 +0x39b
I0507 06:29:07.504376   27138 server.go:62] [2021-05-07T06:29:07Z] Incoming HTTP/1.1 POST /api/v1/del request
I0507 06:29:07.504466   27138 handler.go:218] delete port request {virt-api-555f7bb78-j8d4s kubevirt b5868d39857aa502dd32d4c3bdf5032349d215af8905138729c559df1ebd83bb   ovn }
2021/05/07 06:29:07 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 15541 [running]:
net/http.(*conn).serve.func1(0xc00036ce60)
	/home/sicheng/go16/src/net/http/server.go:1824 +0x153
panic(0x1a6e9e0, 0x2b2bcc0)
	/home/sicheng/go16/src/runtime/panic.go:971 +0x499
github.com/alauda/kube-ovn/pkg/daemon.cniServerHandler.handleDel(0xc000176300, 0x1fb32d8, 0xc00047e9a0, 0x1f4f9f0, 0xc0000c7a90, 0xc00057c160, 0xc000628ab0, 0xc0002f4620)
	/home/sicheng/kube-ovn/pkg/daemon/handler.go:220 +0x8d2
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000628b40, 0xc000628ab0, 0xc0002f4620)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/filter.go:21 +0x8c
github.com/alauda/kube-ovn/pkg/daemon.requestAndResponseLogger(0xc000628ab0, 0xc0002f4620, 0xc000628b40)
	/home/sicheng/kube-ovn/pkg/daemon/server.go:64 +0xd2
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000628b40, 0xc000628ab0, 0xc0002f4620)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/filter.go:19 +0x66
github.com/emicklei/go-restful.(*Container).dispatch(0xc0005b85a0, 0x1f80cd0, 0xc0005ba620, 0xc000e56700)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/container.go:282 +0x813
net/http.HandlerFunc.ServeHTTP(0xc0002f10b0, 0x1f80cd0, 0xc0005ba620, 0xc000e56700)
	/home/sicheng/go16/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000543f00, 0x1f80cd0, 0xc0005ba620, 0xc000e56700)
	/home/sicheng/go16/src/net/http/server.go:2448 +0x1ad
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0005b85a0, 0x1f80cd0, 0xc0005ba620, 0xc000e56700)
	/home/sicheng/go/pkg/mod/github.com/emicklei/go-restful@v2.11.1+incompatible/container.go:300 +0x4d
net/http.serverHandler.ServeHTTP(0xc0000161c0, 0x1f80cd0, 0xc0005ba620, 0xc000e56700)
	/home/sicheng/go16/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00036ce60, 0x1f84df8, 0xc000e6c4c0)
	/home/sicheng/go16/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/home/sicheng/go16/src/net/http/server.go:3013 +0x39b

**Comment by oilbeater** [comment]
can you describe the pod `virt-api-555f7bb78-j8d4s` to check if any annotations attached to this pod

**Comment by sicheng216** [comment]
```
[root@node-220 ~]# kubectl -n kubevirt describe pod virt-api-555f7bb78-lcn2z 
Name:                 virt-api-555f7bb78-lcn2z
Namespace:            kubevirt
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Node:                 192.168.7.221/192.168.7.221
Start Time:           Fri, 07 May 2021 14:13:07 +0800
Labels:               app.kubernetes.io/component=kubevirt
                      app.kubernetes.io/managed-by=kubevirt-operator
                      app.kubernetes.io/version=v0.38.1
                      kubevirt.io=virt-api
                      pod-template-hash=555f7bb78
                      prometheus.kubevirt.io=
Annotations:          kubevirt.io/install-strategy-identifier: 6d015f5958ae332cc2c57606c88f30c0e380ad14
                      kubevirt.io/install-strategy-registry: quay.io/kubevirt
                      kubevirt.io/install-strategy-version: v0.38.1
                      ovn.kubernetes.io/allocated: true
                      ovn.kubernetes.io/cidr: 172.20.0.0/16
                      ovn.kubernetes.io/gateway: 172.20.0.1
                      ovn.kubernetes.io/ip_address: 172.20.0.69
                      ovn.kubernetes.io/logical_switch: ovn-default
                      ovn.kubernetes.io/mac_address: 00:00:00:E6:D4:3B
                      ovn.kubernetes.io/network_types: geneve
                      ovn.kubernetes.io/routed: true
                      scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   172.20.0.69
IPs:
  IP:           172.20.0.69
Controlled By:  ReplicaSet/virt-api-555f7bb78
Containers:
  virt-api:
    Container ID:  docker://38e1f4205e88469a49446600d943cd18271d530891f8d64db5298a0dbb42c6ec
    Image:         quay.io/kubevirt/virt-api@sha256:5d56548370fac393f085547e81bdb104025ad3e1b1478a296dd7d8ba16d7d394
    Image ID:      docker-pullable://quay.io/kubevirt/virt-api@sha256:5d56548370fac393f085547e81bdb104025ad3e1b1478a296dd7d8ba16d7d394
    Ports:         8443/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      virt-api
      --port
      8443
      --console-server-port
      8186
      --subresources-only
      -v
      2
    State:          Running
      Started:      Fri, 07 May 2021 14:53:11 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 07 May 2021 14:13:08 +0800
      Finished:     Fri, 07 May 2021 14:50:09 +0800
    Ready:          True
    Restart Count:  1
    Readiness:      http-get https://:8443/apis/subresources.kubevirt.io/v1/healthz delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/virt-api/certificates from kubevirt-virt-api-certs (ro)
      /etc/virt-handler/clientcertificates from kubevirt-virt-handler-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kubevirt-apiserver-token-954cv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kubevirt-virt-api-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-api-certs
    Optional:    true
  kubevirt-virt-handler-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-certs
    Optional:    true
  kubevirt-apiserver-token-954cv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-apiserver-token-954cv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
