### ISSUE TITLE
QoS bandwidth annotations are reversed

### ISSUE THREAD

**Issue by smnblt** [kubeovn/kube-ovn#795]
Kube-OVN version 1.6.2
K3S version v1.20.6+k3s1

**Issue:**
It looks like QoS bandwidth annotations are reversed. The ingress values is applied to egress, and vice-versa.

**Expected behaviour:**
Ingress annotation to limit ingress traffic. Egress annotation to limit egress traffic.

**Steps to reproduce:**
1. Within a clean install, single node cluster.
1. Create two pods with iperf3 onboard. Call them iperf-a and iperf-b
1. Expose iperf-a and iperf-b port 5201 with cluster services
1. Annotate iperf-a pod 
 ` ovn.kubernetes.io/ingress_rate: "1"`
 `   ovn.kubernetes.io/egress_rate: "20"`
 
**Test from iperf-b to iperf-a**
**Expected result**: The rate from iperf-b to iperf-a to be limited to iperf-a ingress_rate (i.e. 1Mbps).
**Obtained result**: The rate from iperf-b to iperf-a matches iperf-a egress_rate (i.e. 20 Mbps)

1. Open iperf server on iperf-a
    `kubectl exec -i -t iperf-A -- iperf3 -s`
1. Open iperf client on iperf-b
    `kubectl exec -i -t iperf-b -- iperf3 -c iperf-a`
1. Check the outcome:
![image](https://user-images.githubusercontent.com/33151427/117488524-d0d6d100-af6c-11eb-85bd-a71267301561.png)

**Test from iperf-a to iperf-b**
**Expected result**: The rate from iperf-a to iperf-n to be limited to iperf-a egress_rate (i.e. 20Mbps).
**Obtained result**: The rate from iperf-a to iperf-b matches iperf-a ingress_rate (i.e. 1 Mb)

1. Open iperf server on iperf-b
    `kubectl exec -i -t iperf-b -- iperf3 -s`
1. Open iperf client on iperf-a
    `kubectl exec -i -t iperf-a -- iperf3 -c iperf-b`
1. Check the outcome:
![image](https://user-images.githubusercontent.com/33151427/117488861-2d39f080-af6d-11eb-9dca-3c51ef277694.png)

**Test yaml files**

> apiVersion: v1
kind: Pod
metadata:  
  name: iperf-a
  labels:
    app: iperf-a
  annotations:
    ovn.kubernetes.io/ingress_rate: "1"
    ovn.kubernetes.io/egress_rate: "20"
spec:
  restartPolicy: OnFailure
  containers:
  \- name: iperf-a
    image: networkstatic/iperf3
    #args: [ "-s" ]
    command:
      \- sleep
      \- "3600"
    ports:
    \- containerPort: 5201
\---
apiVersion: v1
kind: Service
metadata:
  name: iperf-a
  labels:
    app: iperf-a
spec:
  ports:
  \- port: 5201
    targetPort: 5201
  selector:
    app: iperf-a
\---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-b
  labels:
    app: iperf-b
spec:
  restartPolicy: OnFailure
  containers:
 \- name: iperf-b
    image: networkstatic/iperf3
    ports:
      \- containerPort: 5201
    command:
      \- sleep
      \- "3600"
    # args: [ "-c",  "iperf-server" ]
    #iperf3 -c iperf-server
\---
apiVersion: v1
kind: Service
metadata:
  name: iperf-b
  labels:
    app: iperf-b
spec:
  ports:
  \- port: 5201
    targetPort: 5201
  selector:
    app: iperf-b
---

**Comment by oilbeater** [comment]
@smnblt it works as expect in my environment. I wonder if it's a bug with ovs kernel datapath, what's your system version

**Comment by smnblt** [comment]
Hi @oilbeater thanks for yout feedback. I tried on two different virtual machines with same outcome.

First one is Ubuntu 20.04.2 LTS with 5.8.0-50-generic .
Second one is Ubuntu 18.04.5 LTS with 4.15.0-142-generic .

**Comment by feixiang43** [comment]
> @smnblt it works as expect in my environment. I wonder if it's a bug with ovs kernel datapath, what's your system version

I had also found a qos bug. During cni handle a pod add request, the function call chain is as follows:
```
handleAdd -> configNic -> SetInterfaceBandwidth -> Set ovs ingress_rate and qos
```
As you know ovs `ingress_rate` works on POD egress traffic, so I thinking `SetInterfaceBandwidth` passes ingress and egress parameter inversely. `handlePod` handles similarly qos logical and passes ingress/egress correctly. So this bug only works if you create a pod with qos and haven't update pod qos, after you update pod qos ingress and egress setting will be update correctly.
I thinking all `egress` and `ingress` words in qos related code  should stands on pod side, otherwise code will be a litte confusing.
