### ISSUE TITLE
cni should wait lsp port state up after binding ovs port to lsp

### ISSUE THREAD

**Issue by halfcrazy** [kubeovn/kube-ovn#827]
### Feature request
cni wait for lsp up=true after setting ovs port iface-id

![image](https://user-images.githubusercontent.com/4113173/118608652-82d39000-b7ec-11eb-9dbf-e0e90bdba2e8.png)

**Comment by oilbeater** [comment]
The `kube-ovn-cni` now has no connection to ovn-nb. If we need to check the `up` status, that means every node needs an connection to ovn-nb and sync the cache that may increase the resource burden. And the ping mechanism now can cover this situation.
