### ISSUE TITLE
workload增加mac_pool

### ISSUE THREAD

**Issue by aiyouwoqu1024** [kubeovn/kube-ovn#850]
目前像deployment这类workload资源，只有ip_pool配置，现在有一个场景需要mac地址也可以像ip_pool一样有一个可分配的池，不知有有没有什么解决方案？

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ovn-test
  name: starter-backend
  labels:
    app: starter-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starter-backend
  template:
    metadata:
      labels:
        app: starter-backend
      annotations:
        ovn.kubernetes.io/ip_pool: 10.16.0.15,10.16.0.16,10.16.0.17
        #如何实现mac_pool
    spec:
      containers:
      - name: backend
        image: nginx:alpine

**Comment by bobz965** [comment]
我有个相关的想法，是不是搞一个指定池大小的ip pool，把ip pool 和 mac pool维护在一个ip pool crd里面更好用一些，这样可以用到ipam自动分配
