### ISSUE TITLE
在KIND中部署 kubeovn

### ISSUE THREAD

**Issue by QQGoblin** [kubeovn/kube-ovn#876]
### Feature request

在KIND中部署 kubeovn

### Use case

由于需要在一些CI场景中使用Kubeovn，请问目前版本支持在kind创建的k8s集群中部署吗？

我用最新版本的 kubeovn 手动部署 YAML 到集群中，部分kubeovn容器无法启动。

**Comment by zhangzujian** [comment]
支持在 kind 中部署。

如果是通过 yaml 手动部署，需要替换 ovn.yaml 中的 `$addresses`。详情参考本项目 Wiki 中的手动安装部分，或者代码库中的英文文档。
