### ISSUE TITLE
kube-ovn support link local address?

### ISSUE THREAD

**Issue by liyibo-tech** [kubeovn/kube-ovn#999]
### Feature request

we use kube-ovn for user network，we supply a server that hope our user app can connect the sever. and the server use link local addess. we want to know if kube-ovn can support this ?

**Comment by ikandars** [comment]
+1

**Comment by oilbeater** [comment]
@liyibo-tech @ikandars can you give a more specific description about your usecases?

**Comment by ikandars** [comment]
@oilbeater in my case, I deployed Kube-OVN on top of Bare metal where it has 2 NEC eno1 for public connection and eno2 and for private connection. So Kube-OVN run in eno2. So, from within a pod, I need to access other http service within the same server where the request coming to eno1. unfortunately, my pod an able to route to public IP attached to eno1.

**Comment by oilbeater** [comment]
@ikandars Can you attach your subnet yaml, if using default subnet pod should access eno1 by distributed gateway

**Comment by ikandars** [comment]
@oilbeater just testing with other Bare meal and works as expected. So it seem there is other problem in my previous machine.
